### ISSUE TITLE
tailwindCSS.emmetCompletions set not work

### ISSUE THREAD

**Issue by CooLNuanfeng** [tailwindlabs/tailwindcss-intellisense#1019]
![image](https://github.com/user-attachments/assets/a3f5fc43-dea6-4d68-8b4d-c558b6272537)
![image](https://github.com/user-attachments/assets/9fbc09d6-19a2-48cc-9559-747ff66880d2)

**Comment by thecrypticace** [comment]
Hey! This appears to be working fine for me:

<img width="442" alt="Screenshot 2024-07-15 at 11 39 24" src="https://github.com/user-attachments/assets/93d1c2eb-f56e-4a8b-8cda-9f17a6a09a7a">

Your first screenshot shows the available settings, descriptions for each, and their default value. It's not updated when you change the setting via user settings or workspace settings.

Note that the setting says "Also modified in Workspace" which means it _may_ be disabled in the folder / workspace you're working in. Check the settings in `.vscode/settings.json` or the settings in your `*.code-workspace` file.
