### ISSUE TITLE
Failed to read configuration (d:\xxx\xxx\tailwind.config.js)

### ISSUE THREAD

**Issue by dlpmmk** [tailwindlabs/tailwindcss-intellisense#1020]
I use this in win10 vscode, but show this error when I open vscode window.

**Comment by thecrypticace** [comment]
Can you provide more details please? And possibly a screenshot of the error?

**Comment by dlpmmk** [comment]
Just now, I created a new next project, on the window, and still report which error, this is the project link: https://github.com/dlpmmk/temp/tree/main/vscode/tailwindcss-issue-1020

**Comment by dlpmmk** [comment]
![image](https://github.com/user-attachments/assets/d08ec9c0-08ed-4a5b-b36d-311f1060e181)

**Comment by dlpmmk** [comment]
error: 
Failed to read configuration
d:\tailwindcss-issue-1020\node_modules\tailwindcss\stubs\tailwind.config.js

**Comment by thecrypticace** [comment]
1. What version of VSCode you're using?
2. Can you provide your VSCode settings?

I don't think we have any error that says "Failed to read configuration" so a screenshot here would be super useful because I suspect the error is coming from something else.

**Comment by dlpmmk** [comment]
Oh, I'm sorry, 
![image](https://github.com/user-attachments/assets/811cdcf7-d61f-4d95-8922-09c2a917e5e1)

**Comment by dlpmmk** [comment]
It don't your error
