### ISSUE TITLE
bun runtime support

### ISSUE THREAD

**Issue by rootfebri** [tailwindlabs/tailwindcss-intellisense#1021]
I kept getting this error for WEBStorm IDE with bun runtime, Where should I report this? JetBrains?

Tailwind CSS: Unhandled exception: undefined is not an object (evaluating 'Object.keys(q3.default._pathCache)') TypeError: undefined is not an object (evaluating 'Object.keys(q3.default._pathCache)') at keys (native) at K3 (/home/febri/.local/share/JetBrains/Toolbox/apps/webstorm/plugins/tailwindcss/server/tailwindcss-language-server:2950:1957) at   (/home/febri/.local/share/JetBrains/Toolbox/apps/webstorm/plugins/tailwindcss/server/tailwindcss-language-server:2952:7887) at _init (/home/febri/.local/share/JetBrains/Toolbox/apps/webstorm/plugins/tailwindcss/server/tailwindcss-language-server:2952:7885) at   (/home/febri/.local/share/JetBrains/Toolbox/apps/webstorm/plugins/tailwindcss/server/tailwindcss-language-server:2952:7856) at init (/home/febri/.local/share/JetBrains/Toolbox/apps/webstorm/plugins/tailwindcss/server/tailwindcss-language-server:2952:7800) at   (/home/febri/.local/share/JetBrains/Toolbox/apps/webstorm/plugins/tailwindcss/server/tailwindcss-language-server:2954:1171) at   (/home/febri/.local/share/JetBrains/Toolbox/apps/webstorm/plugins/tailwindcss/server/tailwindcss-language-server:2954:1169) at Le (/home/febri/.local/share/JetBrains/Toolbox/apps/webstorm/plugins/tailwindcss/server/tailwindcss-language-server:138:1599) at V (/home/febri/.local/share/JetBrains/Toolbox/apps/webstorm/plugins/tailwindcss/server/tailwindcss-language-server:137:6882)

**Comment by rootfebri** [comment]
![image](https://github.com/user-attachments/assets/9c4c663a-ff5f-4a5e-a5f6-1b6a2f66cdb0)

**Comment by thecrypticace** [comment]
This is a bug in bun because it does not implement `Module._pathCache` (it's undefined rather than being an object).

**Comment by thecrypticace** [comment]
We could skip over the code that uses it if undefined but this seems like an indication that other things _may_ not work. I'll set aside some time to test out language server in bun probably next week b/c it would be good to know if there are any other bugs / unimplemented things in Bun that we need.

Given that this is a bug in bun though I'm gonna close this one.

**Comment by lizhongyue248** [comment]
Is there any follow-up on this issue?

**Comment by jakubdonovan** [comment]
> We could skip over the code that uses it if undefined but this seems like an indication that other things _may_ not work. I'll set aside some time to test out language server in bun probably next week b/c it would be good to know if there are any other bugs / unimplemented things in Bun that we need.
> 
> Given that this is a bug in bun though I'm gonna close this one.

Hey, have you had a chance to look into it yet?

**Comment by rootfebri** [comment]
> Any news?

take a look https://github.com/oven-sh/bun/issues/13627#issuecomment-2594404674
