### ISSUE TITLE
False cssConflict Issue

### ISSUE THREAD

**Issue by cpolanish** [tailwindlabs/tailwindcss-intellisense#1022]
I have my project set up with a cn function, and have configured the classRegex setting with the following:

{ "tailwindCSS.experimental.classRegex": [["cn\\(([^)]*)\\)", "(?:'|\"|`)([^']*)(?:'|\"|`)"]] }

I've noticed when I have the following:

![image](https://github.com/user-attachments/assets/aea965a3-7c98-4e15-a3aa-a59a2c8b8dea)

everything checks out and there are no errors. However, if I flip the two lines within the cn function:

![image](https://github.com/user-attachments/assets/61770d15-8498-4cdf-9094-7d3bbb0bb655)

I get a cssConflict error on the two stroke classes. I'm hoping I'm just overlooking something dumb...

Thanks in advance!

PS: I realize I can just change it to the following and get around this, but figured I'd mention it anyway.

![image](https://github.com/user-attachments/assets/b0c93e22-ce4e-4716-8529-82c33c11d7c8)

**Comment by adamwathan** [comment]
Hey! This warning looks correct to me, in your first example both the `stroke-[#2e75ff]` and `stroke-[#bfbfbf]` classes would be present at the same time if `selected` is true.

Your last example where you are using a ternary and making sure to only apply one of those classes is the right thing to do 👍 

Hope that helps!
