### ISSUE TITLE
v0.12.7 broken

### ISSUE THREAD

**Issue by spacecat** [tailwindlabs/tailwindcss-intellisense#1033]
Installed it just now and I'm not getting any intellisense suggestions and the console complains about the following:

[GLOBAL] No matching project for document

I closed all VS Code windows and terminated the VS Code by "Quitting" my app in my Mac app bar at the bottom.

I reverted back to v0.12.6 and now the extension works again.

Edit: For those that don't know; right click the extension in VS Code Extensions Marketplace and select "Install Specific Version..." and select v0.12.6 to get it working again.

**Comment by jxjj** [comment]
Same.

**Comment by jaaymes** [comment]
me too, downgrade v0.12.6

**Comment by OliverGrimsley** [comment]
same here, not working inside vue templates, tried a few other suggestions in other issues, not fixed, downgrade to 12.6 restores functionality

**Comment by gurenGithub** [comment]
me too, downgrade v0.12.6

**Comment by josh-dastmalchi** [comment]
fwiw deleting the comments in my angular project's styles.scss file and restarting the extension fixed it. but I just rolled back the extension instead.

**Comment by lbtoha** [comment]
I also facing this issue. Downgrade v0.12.6 is working fine.

**Comment by Koyamie** [comment]
Same here, if it helps v0.12.7 started erroring when scanning my SCSS files with the following error:
```
[Error - 2:12:25 PM] Failed to initialize workspace folder .../website e [CssSyntaxError] : .../website/src/styles/bulma.scss:66:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
```

**Comment by EPaulGR** [comment]
i had the same problem `[Info  - 12:38:48] [GLOBAL] No matching project for document {
  fsPath: '/Users/erickpaulgarciaramirez/Proyectos/front-el-cipres/server.ts',
  normalPath: '/Users/erickpaulgarciaramirez/Proyectos/front-el-cipres/server.ts'
}`

**Comment by lougreenwood** [comment]
👍  - but I get it in the Zed editor from the plain `tailwind-language-server`

**Comment by craxrev** [comment]
Like the comment above suggested, deleting inline comments (`//`) in scss files fixes the issue, you can check logs to see which files have errors

**Comment by OliverGrimsley** [comment]
@craxrev - problem (at least for me) is that many scss files that have comments are in my vendor folder, so not mine, and will get re-written on an update and fail.  Whatever parser they are using is apparently not detecting // or /* comments.

**Comment by rodrigo-mahamud** [comment]
OMG, all morning wasted trying to figure this one out 🤬.

**Comment by Yunlongzzj** [comment]
me too, downgrade v0.12.6

**Comment by EnettyTech** [comment]
Me too, downgrade v0.12.6

**Comment by gktac** [comment]
Me too, downgrade v0.12.6

**Comment by DadvDadv** [comment]
same => downgrade v0.12.6

**Comment by Rennola** [comment]
Wasted a couple of hours on this, reverted the version

**Comment by gugatxr** [comment]
Same problem here. downgrade works

**Comment by philipp-spiess** [comment]
Hey all! Thanks for reporting this and sorry for the troubles! We just released v0.12.8 of the VS Code extension with a fix that resolves this issue. If you still have issues, please let us know!

**Comment by EmmanuelOga** [comment]
I got the exact same error when using this version: `v0.13.38 (pre-release)`

I suspect the way to replicate this issue is to put TW config, input.css and some TSX file in mismatching locations. My repo uses a `packages` folder on the root of the repository.

* `packages/frontend/components/my-component.tsx`
* `packages/server/src/input.css`
* `packages/server/tailwind.config.js` (with `content: ["../.../**/*.{ts,tsx}"]`, or something like that)

... Now open `my-component.tsx` on VS Code with the TW extension installed, the "No matching project" error appears.

**I "fixed it" by moving both `tailwind.config.js` and `input.css` to the root folder of the repository.**

**Comment by vdiaz1130** [comment]
This is happening again in a Nrwl Nx Angular monorepo project. Seems the problem started with Tailwind 4 and Intellisense plugin version 0.14.2. Version 0.14.1 works as expected while newer versions beyond that failw with the following message:

```
Searching for Tailwind CSS projects in the workspace's folders.
{"tailwind":{"version":"4.0.8","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false},"path":"/Users/userName/Documents/projects/my-project/tailwind.config.js"}
{"tailwind":{"version":"4.0.8","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false},"path":"/Users/userName/Documents/projects/my-project/apps/admin/src/styles.scss"}
[Warn  - 2:12:23 PM] The config /Users/userName/Documents/projects/my-project/apps/admin/src/styles.scss requires a preprocessor and is not supported by Tailwind CSS v4.0.
[Global] Creating projects: []
[Global] Preparing projects...

Note the preprocessor warning "...requires a preprocessor and is not supported by Tailwind CSS v4.0"
[Global] Initializing projects...
[Info  - 2:12:23 PM] [GLOBAL] No matching project for document {
  fsPath: '/Users/userName/Documents/projects/my-project/apps/admin/src/app/app.component.html',
  normalPath: '/Users/userName/Documents/projects/my-project/apps/admin/src/app/app.component.html'
}
[Global] Initialized 0 projects
[Info  - 2:12:23 PM] [GLOBAL] No matching project for document {
  fsPath: '/Users/userName/Documents/projects/my-project/apps/admin/src/app/app.component.html',
  normalPath: '/Users/userName/Documents/projects/my-project/apps/admin/src/app/app.component.html'
}
```

**Comment by tientq64** [comment]
The problem still occurs in tailwindcss v4

**Comment by Goldbeener** [comment]
same => downgrade v0.14.11

**Comment by sxlwar** [comment]
For me, create a new css file under the project root floder, e.g src/style.css, copy this `@import "tailwindcss"` into the file, the plugin works.

**Comment by YYsuni** [comment]
I found that changing the SCSS file to a CSS file resolved the issue.

**Comment by MarufZak** [comment]
for me that was because i used postcss.config.mjs instead of postcss.config.js with cjs export

**Comment by mojtaba-shahverdi** [comment]
`[Info  - 6:47:06 PM] [GLOBAL] No matching project for document {
  fsPath: 'D:\\code\\Projects\\granipan\\src\\app\\(granipan)\\page.jsx',
  normalPath: '/d:/code/Projects/granipan/src/app/(granipan)/page.jsx'
}`

adding "tailwindCSS.experimental.configFile": "src/app/globals.scss" to settings.json file resolved the error but i still don't get any suggestions or auto-complete suggestions

**Comment by mlarabi** [comment]
I started facing this issue today randomly. When I remove from the settings `classFunctions` the value `twMerge` it starts working again. I have nothing in the output that shows an error.

**Comment by hdkhanh462** [comment]
This is happening again in v0.14.29

**Comment by RobinMalfait** [comment]
@hdkhanh462 can you open a new issue with a minimal reproduction repo attached that reproduces this issue?

It will also be useful if you can share the information from the `Tailwind CSS: Show Output`:
<img width="309" height="97" alt="Image" src="https://github.com/user-attachments/assets/8a500fe8-2154-4971-94b0-58de0a1f0f69" />

With the v0.14.29 version you mention it looks like this on my end:
<img width="696" height="341" alt="Image" src="https://github.com/user-attachments/assets/ee7f886e-58cf-4a63-8dc2-f39e5a7cc712" />

Can you also test the pre-release version (at the time of writing this, v0.15.2), and see if that makes a difference for you?
<img width="295" height="163" alt="Image" src="https://github.com/user-attachments/assets/491c3a5c-064b-4e61-b400-7fda97eda382" />

**Comment by hdkhanh462** [comment]
@RobinMalfait The issue occurred on my setup about 4 months ago. However, after re-testing with v0.14.29 today, everything seems to be working correctly
