### ISSUE TITLE
 while  Hover the html class style properties not showing

### ISSUE THREAD

**Issue by HariharanInstadata** [tailwindlabs/tailwindcss-intellisense#1037]

**Comment by PTiCA1** [comment]
I have the same problem. My previews stopped showing and it doesn't tell me the class names

**Comment by PTiCA1** [comment]
fix: in file: `./vscode/settings.json`
`"tailwindCSS.experimental.configFile": "./tailwind.config.js",`

**Comment by philipp-spiess** [comment]
Hey @Amir0234-afk! Thanks for reporting this and sorry for the troubles! We just release v0.12.8 of the VS Code extension [with a fix](https://github.com/tailwindlabs/tailwindcss-intellisense/pull/1043) that resolves this issue. If you still have issues, please let us know!

**Comment by HariharanInstadata** [comment]
Now its Working
