### ISSUE TITLE
Autocomplete not working, after update 0.12.7 version

### ISSUE THREAD

**Issue by Mu-jun** [tailwindlabs/tailwindcss-intellisense#1039]
**What version of VS Code are you using?**

For example: v1.92.2

**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.12.7

**What version of Tailwind CSS are you using?**

For example: v3.4.1

**What package manager are you using?**

For example: npm

**What operating system are you using?**

For example: Windows

**Tailwind config**

```js
{
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
```

**VS Code settings**

```json
default setting
```

**Describe your issue**
Autocomplete not working, after update 0.12.7 version
It is working in 0.12.6 version

**Comment by parker2808** [comment]
Yes, I have the same issue. doesn't any suggestion 👎

**Comment by alex-jitbit** [comment]
> @Mu-jun how can you install the 0.12.6 version? I can't find it

In VSCode cextension settings lick dropdown next to "Uninstall" and select "Install specific version"

**Comment by brenopolanski** [comment]
> > @Mu-jun how can you install the 0.12.6 version? I can't find it
> 
> In VSCode cextension settings lick dropdown next to "Uninstall" and select "Install specific version"

Thanks, works for me too!

**Comment by Su0515** [comment]
Yes, I am invalidated in version 27, and it is better to replace it with version 26

**Comment by u3u** [comment]
In a certain project, it found the wrong configuration file.
I fixed it by specifying `"tailwindCSS.experimental.configFile": "tailwind.config.js"`

```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Searching for Tailwind CSS projects in the workspace's folders.
[Error - 2:29:09 PM] Failed to initialize workspace folder /xxx e [CssSyntaxError]: /xxx/public/admin/vendors/bootstrap/less/bootstrap.less:7:1: Unknown word
You tried to parse Less with the standard CSS parser; try again with the postcss-less parser
    at qd.error (/Users/qwq/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.7/dist/tailwindServer.js:195:35103)
    at jw.unknownWord (/Users/qwq/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.7/dist/tailwindServer.js:201:7868)
    at jw.other (/Users/qwq/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.7/dist/tailwindServer.js:201:6274)
```

**Comment by Ali-ovo** [comment]
> In a certain project, it found the wrong configuration file. I fixed it by specifying `"tailwindCSS.experimental.configFile": "tailwind.config.js"`
> 
> ```
> Locating server…
> Booting server...
> Setting up server…
> Listening for messages…
> Searching for Tailwind CSS projects in the workspace's folders.
> [Error - 2:29:09 PM] Failed to initialize workspace folder /xxx e [CssSyntaxError]: /xxx/public/admin/vendors/bootstrap/less/bootstrap.less:7:1: Unknown word
> You tried to parse Less with the standard CSS parser; try again with the postcss-less parser
>     at qd.error (/Users/qwq/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.7/dist/tailwindServer.js:195:35103)
>     at jw.unknownWord (/Users/qwq/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.7/dist/tailwindServer.js:201:7868)
>     at jw.other (/Users/qwq/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.7/dist/tailwindServer.js:201:6274)
> ```

I have the same error

> In a certain project, it found the wrong configuration file. I fixed it by specifying `"tailwindCSS.experimental.configFile": "tailwind.config.js"`
> 
> ```
> Locating server…
> Booting server...
> Setting up server…
> Listening for messages…
> Searching for Tailwind CSS projects in the workspace's folders.
> [Error - 2:29:09 PM] Failed to initialize workspace folder /xxx e [CssSyntaxError]: /xxx/public/admin/vendors/bootstrap/less/bootstrap.less:7:1: Unknown word
> You tried to parse Less with the standard CSS parser; try again with the postcss-less parser
>     at qd.error (/Users/qwq/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.7/dist/tailwindServer.js:195:35103)
>     at jw.unknownWord (/Users/qwq/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.7/dist/tailwindServer.js:201:7868)
>     at jw.other (/Users/qwq/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.7/dist/tailwindServer.js:201:6274)
> ```

I have the same error

**Comment by philipp-spiess** [comment]
Hey @Amir0234-afk! Thanks for reporting this and sorry for the troubles! We just release v0.12.8 of the VS Code extension [with a fix](https://github.com/tailwindlabs/tailwindcss-intellisense/pull/1043) that resolves this issue. If you still have issues, please let us know!
