### ISSUE TITLE
Stopped working 0.12.7 reverting to 0.12.6 fixes the issues

### ISSUE THREAD

**Issue by alex-jitbit** [tailwindlabs/tailwindcss-intellisense#1040]
EDIT: Possibly duplicate of #1039

**What version of VS Code are you using?**

v1.92.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.12.7

**What version of Tailwind CSS are you using?**

v3.4.6

**What package manager are you using?**

npm

**What operating system are you using?**

Windows

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./Views/**/*.cshtml"],
	theme: {
		extend: {
			fontFamily: {
				sans: ['InterVariable, sans-serif'],
			},
			colors: {
				'new-color': 'rgb(var(--new-color) / <alpha-value>)',
				'new-color-dark': 'rgb(var(--new-color-dark) / <alpha-value>)',
				'tech-color': 'rgb(var(--tech-color) / <alpha-value>)',
				'tech-color-dark': 'rgb(var(--tech-color-dark) / <alpha-value>)',
				'cust-color': 'rgb(var(--cust-color) / <alpha-value>)',
				'cust-color-dark': 'rgb(var(--cust-color-dark) / <alpha-value>)',
				'fortech-color': 'rgb(var(--fortech-color) / <alpha-value>)',
				'fortech-color-dark': 'rgb(var(--fortech-color-dark) / <alpha-value>)',
				'error-color': 'rgb(var(--error-color) / <alpha-value>)',
			}
		}
	},
	darkMode: 'selector',
	plugins: [],
	safelist: ["rotate-90"] //do not purge this class from CSS (used in js)
}
```

**VS Code settings**

```json
// Paste your VS Code settings in JSON format here
```

**Describe your issue**

The classes are not suggested, reverting to 0.12.6 fixes the issue.

Message form the extension in the "output": 

```
[Info  - 12:04:03 PM] [GLOBAL] No matching project for document {
  fsPath: 'C:\\jitbit\\helpdesk\\HelpDesk\\wwwroot\\fblogin.html',
  normalPath: '/c:/jitbit/helpdesk/HelpDesk/wwwroot/fblogin.html'
}
```

**Comment by stefanMeanpug** [comment]
Same problem

**Comment by smultar** [comment]
I have also experienced this problem and can confirm reverting the version fixes the issue.

**Comment by Ruler1020730** [comment]
Me too.

**Comment by ritikanand123** [comment]
@smultar same

**Comment by squelix** [comment]
Same problem, reverting version fix the problem

**Comment by thekc66** [comment]
Yes same issue for me and also my team members. We have switched back to 0.12.6

**Comment by philipp-spiess** [comment]
Hey @Amir0234-afk! Thanks for reporting this and sorry for the troubles! We just release v0.12.8 of the VS Code extension [with a fix](https://github.com/tailwindlabs/tailwindcss-intellisense/pull/1043) that resolves this issue. If you still have issues, please let us know!
