### ISSUE TITLE
No autocomplete for classname 

### ISSUE THREAD

**Issue by ChuanyuanLiu** [tailwindlabs/tailwindcss-intellisense#1063]
**What version of VS Code are you using?**

1.94.0

**What version of Tailwind CSS IntelliSense are you using?**

v0.12.11

**What version of Tailwind CSS are you using?**

3.4.13

**What package manager are you using?**

bun

**What operating system are you using?**

macOS

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Reproduction URL**

https://github.com/ChuanyuanLiu/tailwind-autocomplete-test

**Describe your issue**

No autocomplete for classname defined in app.css

![image](https://github.com/user-attachments/assets/d3d1852e-d9e4-46fd-a20d-2109b2f578ad)
 
![image](https://github.com/user-attachments/assets/4ea89062-9bdc-4f24-bd6f-e6684ae250b4)

**Comment by thecrypticace** [comment]
Hey! Sorry for getting to this one late but this isn't a bug in Tailwind CSS IntelliSense. Our extension only concerns itself with utilities that are generated by Tailwind CSS. The `.test` class in your app.css file isn't a Tailwind utility and is therefore not suggested by the extension. I think you might be looking for a general CSS-class autocomplete which is not something that our extension provides.

I found this one on the VSCode Marketplace which might be what you're looking for: https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion

Note also that in v3 we don't read from `@layer utilities { … }` either but this has been addressed when using v4 where configuration is generally in CSS and you use `@utility` to define custom utilities.
