### ISSUE TITLE
Hover Preview Not Woring

### ISSUE THREAD

**Issue by beierzhijin** [tailwindlabs/tailwindcss-intellisense#1071]
**What version of VS Code are you using?**

`v1.94.2`

**What version of Tailwind CSS IntelliSense are you using?**

`v0.12.11`

**What version of Tailwind CSS are you using?**

` "@nuxtjs/tailwindcss": "^6.12.2"`

**What package manager are you using?**

` pnpm`

**What operating system are you using?**

`Windows`

**Tailwind config**

```ts
module.exports = {
  // The selector strategy replaced the class strategy in Tailwind CSS v3.4.1.
  // darkMode: 'class'
  darkMode: 'selector',
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
```

**VS Code settings**

```json
{
  "editor.fontFamily": "SauceCodePro NFM, Consolas, 'Courier New', monospace",
  "editor.fontSize": 16,
  "terminal.integrated.fontFamily": "SauceCodePro NFM",
  "terminal.integrated.fontSize": 16,
  "workbench.colorTheme": "Monokai",
  "workbench.editor.enablePreview": false,
  "editor.tabSize": 2,
  "git.autofetch": true,
  "editor.quickSuggestions": {
    "strings": "on"
  },
  "[vue]": {
    "editor.defaultFormatter": "Vue.volar"
  }
}
```

**Reproduction URL**
https://github.com/beierzhijin/fullstack-nuxt3

**Describe your issue**

Mouse over class has no effect.

**Comment by thecrypticace** [comment]
Hey! I'm testing your project on Windows and I am not seeing the problem. However, something I did notice is that you're using pnpm and don't have `tailwindcss` directly in your package.json. You're relying on it being around implicitly though `@nuxtjs/tailwindcss`. Unfortunately, because of the way pnpm works, this means that we can't find your local `tailwindcss` install and the extension has to fallback to the built-in version. I recommend adding it explicitly to your package.json and seeing if that resolves the issue you are seeing.

A few notes:
- Can you please grab the log details from VSCode in your projects current state? Open the command palette and run "Tailwind CSS: Show Output" and paste that info in a comment here. It would be super helpful.
- Is your project located on a network share? Or are you just using the C drive?

**Comment by beierzhijin** [comment]
> Hey! I'm testing your project on Windows and I am not seeing the problem. However, something I did notice is that you're using pnpm and don't have `tailwindcss` directly in your package.json. You're relying on it being around implicitly though `@nuxtjs/tailwindcss`. Unfortunately, because of the way pnpm works, this means that we can't find your local `tailwindcss` install and the extension has to fallback to the built-in version. I recommend adding it explicitly to your package.json and seeing if that resolves the issue you are seeing.
> 
> A few notes:
> 
> * Can you please grab the log details from VSCode in your projects current state? Open the command palette and run "Tailwind CSS: Show Output" and paste that info in a comment here. It would be super helpful.
> * Is your project located on a network share? Or are you just using the C drive?

When I create a new nuxt project using the `https://tailwindcss.com/docs/guides/nuxtjs` tutorial, everything works fine. 
So it's most likely that something is wrong with my own project, and I added the '@nuxtjs/tailwindcss' module according to the official nuxt tutorial.

1. grab the log details from VSCode:
`[Info  - 11:58:59 AM] [GLOBAL] No matching project for document {
  fsPath: 'C:\\A\\DATA\\frontend\\my-project\\pnpm-lock.yaml',
  normalPath: '/c:/A/DATA/frontend/my-project/pnpm-lock.yaml'
}`

2. I just using the C drive

3. I have added `tailwindcss` explicitly to my package.json, but Hover Preview still not working
```package.json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@nuxt/content": "^2.13.2",
    "nuxt": "^3.13.0",
    "vue": "^3.4.38"
  },
  "packageManager": "pnpm@9.9.0",
  "devDependencies": {
    "@nuxtjs/color-mode": "^3.4.4",
    "@tailwindcss/typography": "^0.5.15",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.47",
    "tailwindcss": "^3.4.14"
  }
}
```

```nuxt.confg.ts
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  modules: [
    '@nuxtjs/color-mode',
    '@nuxt/content'
  ],
})
```

```tailwind.config.ts
/** @type {import('tailwindcss').Config} */
module.exports = {
  // The selector strategy replaced the class strategy in Tailwind CSS v3.4.1.
  // darkMode: 'class'
  darkMode: 'selector',
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
```
Let me try to fix it again. Thank u.

**Comment by beierzhijin** [comment]
Finally, it worked, adding tailwindcss explicitly  or just using @nuxtjs/tailwindcss directly all worked, I don't even know what was done. It seems like I just opened tsconfig. json and clicked `"extends": "./.nuxt/tsconfig.json"`
```tsconfig.json
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
```
but I deleted tsconfig.json and it still works...
