### ISSUE TITLE
Ignore paths

### ISSUE THREAD

**Issue by rellafella** [tailwindlabs/tailwindcss-intellisense#139]
I am getting an error traced back to a file in a vendor folder, it would be good if there was an option to ignore certain folder paths from linting.

![Screen Shot 2020-07-01 at 9 02 44 am](https://user-images.githubusercontent.com/36829732/86186934-a3194280-bb79-11ea-8345-c1dea6b5926e.png)

**Comment by bradlc** [comment]
I think this is a good idea! Just dropping a note here to say that we should also have a way to exclude paths from file searches as well (e.g. when looking for a config file)

**Comment by bradlc** [comment]
You can now use the [`tailwindCSS.files.exclude` setting](https://github.com/tailwindlabs/tailwindcss-intellisense#tailwindcssfilesexclude) to exclude files from IntelliSense features 👍
