### ISSUE TITLE
[Request] Jetbrains Port

### ISSUE THREAD

**Issue by tance77** [tailwindlabs/tailwindcss-intellisense#140]
It would be amazing to have a port of this in Jetbrains: PHPStorm Webstorm ... ect. 

Love the project.

**Comment by bradlc** [comment]
Hey @tance77. Thanks for the suggestion. I think a JetBrains port is outside the scope of this project right now, but I'd like to provide a proper LSP-based language server eventually which could help facilitate a third-party implementation.

I am not a JetBrains user personally so I haven't tried it, but there is now a Tailwind CSS plugin, created by JetBrains themselves: https://plugins.jetbrains.com/plugin/15321-tailwind-css
