### ISSUE TITLE
Feature Request: Publish npm package

### ISSUE THREAD

**Issue by rodrigore** [tailwindlabs/tailwindcss-intellisense#141]
Hi!

It would be possible to publish the entire repo as a npm package or only the server code?

I just created a [port of the client to use it inside vim/neovim with coc.nvim](https://github.com/rodrigore/coc-tailwind-intellisense) and I'm using submodule of this repo.  

It would be great if I can use the intellisense as a dependency.

Thank you!

**Comment by predragnikolic** [comment]
There is already a npm package published by the author of this repo :) - https://www.npmjs.com/package/tailwindcss-language-server 
The npm package now points to a non existent repo and it hasn't been updated over a year.

Is there any way to update the npm pacakge, so other editors could benefit from it? :)

**Comment by bradlc** [comment]
Duplicate of #188
