### ISSUE TITLE
Suggesting as an object property

### ISSUE THREAD

**Issue by Akumzy** [tailwindlabs/tailwindcss-intellisense#146]
I kept on getting tailwind suggestions as an object property
![image](https://user-images.githubusercontent.com/25849232/87152947-8a620880-c2ae-11ea-8dca-e87a9c3e1bca.png)

Does anyone know why it's happening?

**Comment by bradlc** [comment]
Hey @Akumzy. The emmet completions feature has been tweaked a bit in `v0.5.6` of the extension and should now be less eager 👍
