### ISSUE TITLE
Request: Visual Studio extension

### ISSUE THREAD

**Issue by skttl** [tailwindlabs/tailwindcss-intellisense#147]
As much as I like VS Code, it doesn't offer complete Intellisense for Razor views. I don't know how much difference there is between VS Code and Visual Studio extensionwise. But a Visual Studio extension for TailwindCSS Intellisense would be sweet.

I would happily pay for a license too!

**Comment by bradlc** [comment]
Hey @skttl. Thanks for the suggestion. I think a Visual Studio extension is outside the scope of this project, but I'd like to provide a proper LSP-based language server eventually which could help facilitate a third-party implementation.

**Comment by juho-hanhimaki** [comment]
+1 for this, I do web development mostly in Visual Studio.

**Comment by marshalhayes** [comment]
I'm curious as well about the Visual Studio extension. 

How much work would be involved to provide the LSP your talking about?
