### ISSUE TITLE
Support for straight up JS virtual dom templating

### ISSUE THREAD

**Issue by Siilwyn** [tailwindlabs/tailwindcss-intellisense#149]
Wonder if this should work or if it is missing support, I do have a `tailwind.config.js` file in the root of my project and `tailwindcss` as a dependency in my package.json.

Writing in a JS file like so does not trigger any completions:
```js
import { h } from 'preact';

return h('h1', { class: 'expect completions here' }, 'Hello world!');
```

**Comment by bradlc** [comment]
I reckon this is covered by #129
