### ISSUE TITLE
Intellisense not working for '.hbs' extensions

### ISSUE THREAD

**Issue by icarthik** [tailwindlabs/tailwindcss-intellisense#152]
As per the Github source code, hbs and handlebars are in the list for default languages for html. I haven't changes any settings in the vs code tailwindcss intellisense. 

Is the .hbs file not supported by default? If yes, then how to extend the intellisense support for .hbs files?

Kindly help.

**Comment by belgoros** [comment]
Same here with `0.4.1` IntelliSense version. I added the following keys/values to User's `settings.json`:
```json
...
  "tailwindCSS.includeLanguages": {
    "HTML (Eex)": "html",
    "HTML (EEx)": "html",
    "plaintext": "html",
    "Handlebars": "html"
  },
 "tailwindCSS.emmetCompletions": true,
...
```
Still no autocomplete for styles in `*.hbs` templates(files). What am I missing?

**Comment by icarthik** [comment]
The "tailwind.confg.js" file if placed at the root of the project and using ctrl/cmd + space key enables the intellisense..

But still I am unable to relocate the tailwind.config.js file to a sub-folder. If I do that then the intellisense stops working.

**Comment by belgoros** [comment]
@icarthik Sure, I put the `tailwind.config.js` file at the root of an Ember app as follows:
```js
module.exports = {
    purge: [],
    theme: {
      extend: {},
    },
    variants: {},
    plugins: [],
  }
 ```
And here is how `settings.json` looks like:
```json
{
    "gitlens.hovers.currentLine.over": "line",
    "workbench.startupEditor": "newUntitledFile",
    "workbench.colorTheme": "One Dark Pro",
    "workbench.iconTheme": "vscode-icons",
    "emmet.triggerExpansionOnTab": true,
    "editor.fontSize": 13,
    "tailwindCSS.emmetCompletions": true,
    "emmet.includeLanguages": {
        "html-eex": "html",
        "Handlebars": "html"
      },
      "files.associations": {
        "*.eex": "html-eex",
        "*.leex": "html-eex"
      },
      "editor.minimap.enabled": false
}
```

**Comment by bradlc** [comment]
Are you still having issues @icarthik? The extension should work fine with the config file in a sub-folder.

**Comment by icarthik** [comment]
Thank you @brad, works smooth like butter...

**Comment by OmkarK45** [comment]
How to make it work for `ejs` files ?
