### ISSUE TITLE
Support for Fable & Feliz

### ISSUE THREAD

**Issue by aspnetde** [tailwindlabs/tailwindcss-intellisense#154]
Hi there,

I am trying to set the plugin up for [Fable](https://fable.io/) and [Feliz](https://github.com/Zaid-Ajaj/Feliz).

The setting seems to work:

```json
"tailwindCSS.includeLanguages": {
  "fsharp": "html"
}
```

<img width="693" alt="image" src="https://user-images.githubusercontent.com/1322584/88076102-f4fe2880-cb79-11ea-9a83-e072ac326383.png">

However, instead of having the completion "after the dot", I would need it to work inside of `prop.className ""`.

Is there a way to make this work?

**Comment by CallumVass** [comment]
Provided fix #155

**Comment by aspnetde** [comment]
Thank you @CallumVass!

**Comment by bradlc** [comment]
Hey, I think this is best covered by #129, and the new `tailwindCSS.experimental.classRegex` setting. Taking a quick look at the Feliz docs I reckon these patterns are a decent start:

```json
{
  "tailwindCSS.experimental.classRegex": [
    "\\.className\\s+\"([^\"]*)\"",
    ["\\.className\\s+\\[([^\\]]*)\\]", "\"([^\"]*)\""]
  ]
}
```

These will match `prop.className "|"` and `prop.className [ "|"; "|" ]`

Take a look at [my comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) on #129 for more info, thanks!
