### ISSUE TITLE
The extension silently crashes if there's an error with the tailwind.config.js

### ISSUE THREAD

**Issue by paulpopus** [tailwindlabs/tailwindcss-intellisense#156]
If I do something that errors out the tailwind.config.js the extension silently stops working until I restart vscode again.

To replicate you can do something like adding an invalid variant to a utility

```js
transitionDuration: ['responsive', 'hover', 'focus', 'invalid-variant'],
```
Then if you remove it, the extension is still dead and doesn't autocomplete until it's restarted.

**Comment by bradlc** [comment]
`v0.4.3` is out now with better error handling 👍

**Comment by paulpopus** [comment]
Thanks a lot @bradlc , this was such an annoying issue when writing lots of plugins.
