### ISSUE TITLE
Doesn't work with erb files

### ISSUE THREAD

**Issue by drkelly58** [tailwindlabs/tailwindcss-intellisense#158]
I've finally gotten the extension to work, but it still doesn't work with erb files. I can only get it to work if I change editor setting to html.

**Comment by karinajf** [comment]
Worked for me by adding:
```
"tailwindCSS.includeLanguages": {
    "erb": "html"
}
```

**Comment by janklimo** [comment]
HTML tags within ERB are working fine for me (e.g. appending more class names after `p-5` in the example below). The issue I'm seeing is that there is no autocomplete for dynamically rendered content:

```erb
<div class="p-5">
  <%= image_tag product.featured_image.cloudimage_url(w: 400),
      srcset: product.featured_image.cloudimage_srcset,
      sizes: "(min-width: 768px) and (max-width: 1024px) 50vw, (min-width: 1024px) 430px, 100vw",
      class: 'w-full',
      alt: product.title %>
</div>
```

Taken from a Rails project. Trying to add more classes after `w-full` won't trigger intellisense.

**Comment by bradlc** [comment]
Did you manage to get it working in the end @drkelly58? Take a look at the [troubleshooting section of the readme](https://github.com/tailwindlabs/tailwindcss-intellisense#troubleshooting) if you're still having issues.

**Comment by drkelly58** [comment]
I did finally get it to work. I think I had to add html.erb to the extensions mapping, Adding just .erb didn't work

**Comment by alexon1234** [comment]
In order to make the autocomplete work add this:

https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-764760030
