### ISSUE TITLE
Yarn Plug'n'Play support

### ISSUE THREAD

**Issue by izznatsir** [tailwindlabs/tailwindcss-intellisense#160]
This extension is really awesome! But, not yet supported by Yarn VS Code SDK. Please make it works with Yarn 2 Plug'n'Play. Thanks!

**Comment by nliapis** [comment]
hello, as @izznatsir mentioned above, is there any plan to support Yarn PnP?

**Comment by rizkyramadhan** [comment]
I just compiled DanSnow's version, https://drive.google.com/file/d/1YvK2XpG8cgF4VJZR27NcSskCwSSyv0cO/view?usp=sharing
It's working on my machine.

**Comment by FuJuntao** [comment]
> I just compiled DanSnow's version, [Download it at my gdrive](https://drive.google.com/u/0/uc?id=1YvK2XpG8cgF4VJZR27NcSskCwSSyv0cO&export=download)
> It's working on my machine.

I download the file and installed, but still not working.

```
"typescript": "^4.1.0-beta",
"tailwindcss": "^1.9.6",
```

**Comment by rizkyramadhan** [comment]
Well, make sure you have tailwind.config.js on **root** project and installed tailwindcss module on root project. 

I'm puzzled too when my compiled extension does not work in my workspace, and then after tinkering for a while it does work only if I added it on root. 

Even my root project does not need tailwend, so currently I have duplicate dependencies both on root and on my workspace...

**Comment by rizkyramadhan** [comment]
just in case, this is my tailwind.config.js

```
module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  purge: ['./**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [],
}

```

make sure the `purge` properties are like above, because when tsx / jsx is not included, the extension will refuse to load....

**Comment by FuJuntao** [comment]
Thank you for the replies, @rizkyramadhan. I added `tailwindcss` to root dependencies, and it worked. It seems that `tailwind.config.js` dosen't have to be at root level.

**Comment by rizkyramadhan** [comment]
It's weird, sometime it works, sometime it doesn't... So for peace of mind, i put it tailwind.config.js at root :)

**Comment by FuJuntao** [comment]
I run into this problem `Error: Cannot find module 'tailwindcss/defaultTheme'`, when I try to require `'tailwindcss/defaultTheme'` in `tailwind.config.js`

**Comment by jon301** [comment]
> I just compiled DanSnow's version, [Download it at my gdrive](https://drive.google.com/u/0/uc?id=1YvK2XpG8cgF4VJZR27NcSskCwSSyv0cO&export=download)
> It's working on my machine™.

I confirm this version also worked for me.
I don't have any root `tailwind.config.js` as my project is monorepo, but still had to install `tailwindcss` in the root package to make it work.

**Comment by jon301** [comment]
Intellisense does not work anymore - even with DanSnow's version - with Tailwind v2 :/

**Comment by rizkyramadhan** [comment]
maybe stick to tailwind v1 ? 

as tailwind v2 are too different in their internal mechanics
