### ISSUE TITLE
node_modules directory location for Phoenix (Elixir) apps

### ISSUE THREAD

**Issue by ptinsley** [tailwindlabs/tailwindcss-intellisense#161]
My `tailwind.config.js` file lives in `assets/` as does my `node_modules` directory and I get no love with my `*.html.eex` files.

If I create an empty `node_modules` directory in the base directory of my workspace (with nothing in it) the plugin works fine with my `*.html.eex` files.

I can obviously do that for now but am wondering if there is a way to have the plugin find the already existing `node_modules` directory that sits next to the `tailwind.config.js` file in the workspace?

**Comment by katywings** [comment]
Oof :joy:, thank you a ton for mentioning the workaround @ptinsley :100: 

Just from the looks of it it seems like this plugin already tries to import all its dependencies based on a clever tailwind config glob [starting here](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/src/class-names/index.js#L41). I couldn't find any _explicit_ logic which would require a node_modules folder in the cwd.

Question is: what implicitly expects a node_modules folder in the cwd :thinking: ? Could this be related on how node is resolving dependencies?

(cwd -> Current working dir / workspace dir)

**Comment by bradlc** [comment]
Yeah this is odd for sure. Here's a test setup I have that works fine:

![image](https://user-images.githubusercontent.com/2615508/100748024-b6effb80-33da-11eb-8470-d0cf5d315495.png)

Are you still experiencing this issue and if so which operating system and package manager are you using?

**Comment by tomsharratt** [comment]
@bradlc here is my elixir project setup and as you can see tailwind is not being detected.
![image](https://user-images.githubusercontent.com/55295995/104480677-d447e600-5592-11eb-83ba-29ad743bea2f.png)

**Comment by bradlc** [comment]
I am going to close this due to inactivity but please open a new issue if you're still having problems 👍 

@tomsharratt please open a new issue with details of your project setup, operating system, package manager etc.
