### ISSUE TITLE
[Feature request] add command to delete tailwind classes

### ISSUE THREAD

**Issue by sanscheese** [tailwindlabs/tailwindcss-intellisense#162]
Hey Brad and team Tailwind. You're doing some amazing work at the moment!

After reskinning a Tailwind project I thought it would be great if the vscode extension could have a command to delete all the tailwind classes in the file/project to start fresh.

**Comment by bradlc** [comment]
Hey @sanscheese! I think this feature is out of scope for the extension, but thank you for the suggestion

**Comment by JohnnyWalkerDesign** [comment]
Tailwind is great until you need to reskin something. Then it's hell on earth.
