### ISSUE TITLE
Auto-complete not working in laravel vue.

### ISSUE THREAD

**Issue by max-fletcher** [tailwindlabs/tailwindcss-intellisense#165]
I am using tailwind in a laravel project inside a vue file. The extension is not showing auto-completes.

**Comment by kajuberdut** [comment]
@max-fletcher have you tried adding vue to the included languages?

In your vs code settings add:

    "tailwindCSS.includeLanguages": {
        "Vue": "html"
    }

**Comment by bradlc** [comment]
Hey @max-fletcher, are you seeing completions in other files, for example HTML files? Also please check the [troubleshooting](https://github.com/tailwindlabs/tailwindcss-intellisense#troubleshooting) section of the readme if you haven't already.

**Comment by max-fletcher** [comment]
I am seeing completion in html files, but weird thing is, in some vue
files, I see its auto-completing (e.g App.vue) but others are not. I don't
understand why tho. I did include languages BTW.

**Comment by max-fletcher** [comment]
Is the v in vue supposed to be capitalized ?

**Comment by bradlc** [comment]
You do not need to use the `includeLanguages` setting as Vue support is built in. Is there any chance you can share a repository where this is happening, or even just the contents of the file?

**Comment by max-fletcher** [comment]
I believe I solved it. I used small v for vue when I included languages. I
switched to capital V then the problem was solved. Ty.

**Comment by kajuberdut** [comment]
@bradlc I had the same experience as max-fletcher so possibly if .Vue files should be handled without an "includeLanguages" setting there is a bug preventing that. Single file components were not getting any tailwind hints or completes for me upon my first install. I added the entry for includeLanguages and they started working.

`"tailwindCSS.includeLanguages": {
    "Vue": "html"
}`

**Comment by bradlc** [comment]
Going to close this as it seems like the original issue is fixed. If anyone is still having issues with Vue please open a new issue, thanks!
