### ISSUE TITLE
Why do I have to enter a space to take effect first?

### ISSUE THREAD

**Issue by joinzhu** [tailwindlabs/tailwindcss-intellisense#169]

**Comment by daniel-sudz** [comment]
having this issue as well with create-react-app

**Comment by legendaryaman** [comment]
**Same problem** here and It's very annoying...
Using ReactJS + Nextjs

![Screen-Recording-2020-09-12-at-10 08 36-AM](https://user-images.githubusercontent.com/3285444/92987572-3ad3cf00-f4e1-11ea-8b4d-42f181269627.gif)

**Comment by legendaryaman** [comment]
I somehow **fixed** it by using this setting in VSCode.

<img width="505" alt="Screenshot 2020-09-12 at 11 07 37 AM" src="https://user-images.githubusercontent.com/3285444/92988360-70c88180-f4e8-11ea-94ee-f36084d95727.png">


`"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
},`

**Comment by jethromay** [comment]
@legendaryaman I was looking for a fix for this and that worked for me, thanks! It seems it doesn't always trigger the code completion without adding this.

**Comment by bradlc** [comment]
As @legendaryaman alluded to, this is due to VS Code's behaviour regarding when to trigger completions. It's the `strings` property in the `editor.quickSuggestions` setting which tells VS Code to trigger inside class attributes 👍 I recommend enabling this, and I will add a note to the readme
