### ISSUE TITLE
Tailwind intellisense extension does not provide any suggestion while working in a react framework!

### ISSUE THREAD

**Issue by fydsa** [tailwindlabs/tailwindcss-intellisense#171]
I have a reactjs project and code in vscode. And I installed tailwind alongside my react project (a new project with create-react-app), but when I apply classes to different elements, no tailwind suggestion shows up! I even tried using ctrl-space, but still no suggestions. (btw, I use macOS)

I really appreciate any help. Many thanks in advance.

**Comment by lord007tn** [comment]
Your VS Code settings are conveniently stored in a JSON file called settings.json. To edit your settings in settings.json, start by opening the Command Palette with CMD/CTRL + SHIFT + P.
The Open Settings (JSON) command will let you directly edit the settings JSON file.
add this to your JSON config
`  
"tailwindCSS.includeLanguages": {
    "plaintext": "javascript"
  }
`

**Comment by bradlc** [comment]
Hey @fydsa. Have you taken a look at the [Troubleshooting](https://github.com/tailwindlabs/tailwindcss-intellisense#troubleshooting) section of the readme?

**Comment by gitjeff05** [comment]
I was seeing an issue where emmet abbreviations were not being expanded (e.g., I would type `div.flex` and hit `tab` and nothing happened). I saw in the documentation that you have to [enable expansion on tab](https://code.visualstudio.com/docs/editor/emmet#_using-tab-for-emmet-expansions) with the setting `emmet.triggerExpansionOnTab`, so now my settings for this plugin look like:

```json
{
  "emmet.triggerExpansionOnTab": true,
  "tailwindCSS.emmetCompletions": true
}
```

Maybe this is worth adding to the docs?

**Comment by ArkjuniorK** [comment]
Solve this problem with installing ```postcss``` and then reload the window page.

You could use
```npm i postcss --save-dev``` or  ```yarn add postcss -D```

:cheese:

**Comment by bradlc** [comment]
Going to close this due to inactivity but please open a new issue if you're still having problems 👍

**Comment by sam-cross** [comment]
@fydsa add the following to your VS Code settings:

```json
"tailwindCSS.includeLanguages": {
  "javascriptreact": "html",
  "typescriptreact": "html",
  "plaintext": "html"
}
```

I *think* the `plaintext` rule is the one that fixes this, but the others don't hurt to keep around anyway.

As others have said, ensure you have a `tailwind.config.js` file in your project directory (and of course make sure Tailwind is actually *working*).
