### ISSUE TITLE
@apply not recognized working as expected (semi-colon expectedcss(css-semicolonexpected))

### ISSUE THREAD

**Issue by frederikhors** [tailwindlabs/tailwindcss-intellisense#176]
@bradlc I have the same issue. I read all the [blog post](https://www.meidev.co/blog/visual-studio-code-css-linting-with-tailwind/) linked in the first answer [here](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/117), but I think this is something this extension should cover by itself especially with Tailwind 2.0 coming.

Is there a hope to have this included?

**Comment by frederikhors** [comment]
In some working environments it is not easy to introduce new extensions and new project files, especially if you already use alternative ones for style management, as in this case.

**Comment by bradlc** [comment]
Hey @frederikhors. The "solution" to this is to disable the built-in CSS validation, as mentioned at the end of that blog post, or use a different language mode such as [PostCSS](https://marketplace.visualstudio.com/items?itemName=csstools.postcss). Unfortunately (as far as I'm aware) there is no way for an extension to hook in to the CSS validation.
