### ISSUE TITLE
v0.4.2 breaks autocomplete in my editor

### ISSUE THREAD

**Issue by bikeshaman** [tailwindlabs/tailwindcss-intellisense#177]
I really appreciate this extension! I've noticed the upgrade to v0.4.2 has broken autocomplete of Tailwind classes in both my Vue and html files. When I roll back to v0.4.1, the autocomplete works again. The hover preview is working in both versions.

**Comment by chenershisi** [comment]
> I really appreciate this extension! I've noticed the upgrade to v0.4.2 has broken autocomplete of Tailwind classes in both my Vue and html files. When I roll back to v0.4.1, the autocomplete works again. The hover preview is working in both versions.

I met the same problem too

**Comment by michaelsmedley** [comment]
I am also getting this

This is the message I am getting in the output panel if it helps:

```
[Error - 11:26:53 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'toRgbString' of undefined
  Code: -32603 
```

Not sure if this is the same issue experienced by @bikeshaman or @chenershisi, however if I downgrade to 0.4.1 autocomplete does work fine for me

Thanks!

**Comment by bradlc** [comment]
Are any of you able to share your Tailwind config please?

@michaelsmedley thanks for sharing that error message, that one should be easy to fix 👍

**Comment by bikeshaman** [comment]
Here's my Tailwind config:

```js
const screens = {
  xs: 320,
  sm: 512,
  md: 768,
  lg: 1024,
  xl: 1280,
};

module.exports = {
  purge: ['./src/**/*.vue'],
  theme: {
    screens: {
      // Min
      xs: `${screens.xs}px`,
      sm: `${screens.sm}px`,
      md: `${screens.md}px`,
      lg: `${screens.lg}px`,
      xl: `${screens.xl}px`,

      // Only
      'only-xs': { max: `${screens.sm - 1}px` },
      'only-sm': { min: `${screens.sm}px`, max: `${screens.md - 1}px` },
      'only-md': { min: `${screens.md}px`, max: `${screens.lg - 1}px` },
      'only-lg': { min: `${screens.lg}px`, max: `${screens.xl - 1}px` },
      'only-xl': { min: `${screens.xl}px` },
    },
    spacing: {
      '0': '0',
      px: '1px',
      '1': '0.5rem',
      '2': '1rem',
      '3': '1.5rem',
      '4': '2rem',
      '5': '2.5rem',
      '6': '3rem',
      '7': '3.5rem',
      '8': '4rem',
      '9': '4.5rem',
      '10': '5rem',
      '11': '5.5rem',
      '12': '6rem',
      '14': '7rem',
      '18': '9rem',
      '22': '11rem',
      '24': '12rem',
      '32': '16rem',
      '40': '18rem',
      '48': '22rem',
      '64': '32rem',
    },
    colors: {
      white: '#FFFFFF',
      default: '#303030',
      actionable: '#0A7986',
      'actionable-hover': '#005D68',
      'core-brand-1': '#DF2A63',
      'core-brand-2': '#F2828F',
      'core-brand-3': '#15B5AC',
      'core-brand-4': '#20E1D1',
      'core-brand-5': '#022682',
      'core-brand-6': '#1E3CD6',
      'supporting-1': '#840853',
      'supporting-2': '#EFA5B1',
      'supporting-3': '#FBDDDF',
      'supporting-4': '#A3FEF3',
      'supporting-5': '#FCC751',
      'supporting-6': '#F9F1E0',
      'neutral-1': '#F9F9F9',
      'neutral-2': '#F2F2F2',
      'neutral-3': '#E6E6E6',
      'neutral-4': '#D9D9D9',
      'neutral-5': '#BFBFBF',
      'neutral-6': '#999999',
      'neutral-7': '#666666',
      'neutral-8': '#474747',
      success: '#2FA84F',
      warning: '#FCC751',
      error: '#E60A0A',
      transparent: 'rgba(0, 0, 0, 0)',
      facebook: '#4267B2',
      twitter: '#1DA1F2',
    },
    boxShadow: {
      default: '0 10px 32px rgba(59, 74, 116, 0.16)',
    },
    extend: {},
  },
  variants: {
    borderWidth: ['responsive', 'hover', 'focus'],
  },
  plugins: [],
};
```

**Comment by bradlc** [comment]
Thanks @bikeshaman! Based on that I reckon you are hitting the same error as @michaelsmedley. 906d3cf fixes an issue caused by colors with an alpha value of `0`, which you have at `theme.colors.transparent`. I haven't actually released an updated version of the extension with this fix yet, but I will get it out before the end of the day 👍

**Comment by bradlc** [comment]
@bikeshaman @michaelsmedley I have just released `v0.4.3` of the extension. Let me know if that fixes the issue

**Comment by michaelsmedley** [comment]
Hey @bradlc 

Just updated to 0.4.3 and autosuggest is working as expected for me

The response to this was super quick, really appreciate you looking into it

**Comment by bikeshaman** [comment]
@bradlc It is working for me as well, thanks so much!
