### ISSUE TITLE
Intellisense not working in Nextjs applications

### ISSUE THREAD

**Issue by cooskun** [tailwindlabs/tailwindcss-intellisense#178]
I wasvery happy with tailwind intellisense when I was using that on CRA applications. But when I tried to use it with Nextjs it stopped working. It's because Nextjs doesn't let you import global styles via typical App.js kept in src/ folder. Instead, it forces you to import global styles via pages/_app.js and it breaks the intellisense functionality since where I use the Tailwind is not the same as where global styles imported.

It would be amazing to get a solution to run away from those kinds of issues generally.

**Comment by bradlc** [comment]
Would you mind sharing your project setup @cooskun? The extension should work fine with a standard Next.js setup as long as you meet the [requirements](https://github.com/tailwindlabs/tailwindcss-intellisense#installation)

**Comment by cooskun** [comment]
@bradlc. For sure. Just want to mention one more thing that I forgot. I use the Tailwind classes with @apply directive instead of class attributes. 

And my project root looks like this
<img width="361" alt="tailwind_ with_nextjs" src="https://user-images.githubusercontent.com/14937347/91281552-8750a800-e788-11ea-8568-83929622287d.png">

And, my Tailwind config file as well.

```javascript
module.exports = {
  purge: ['./pages/**/*.js', './src/components/**/*.js'],
  theme: {
    borderRadius: {
      base: '1rem',
      lg: '3rem',
      xl: '4rem',
    },
    colors: {
      blue: {
        dark: '#3f3d56',
      },
      gray: {
        light: '#dfdede',
      },
      yellow: '#fecc01',
      white: '#fff',
    },
    fontFamily: {
      title: ['Oswald', 'sans-serif'],
      content: ['Lato', 'sans-serif'],
    },
    fontSize: {
      base: '1.6rem',
      lg: '2rem',
      xl: '2.4rem',
      '2xl': '3rem',
      '3xl': '3.6rem',
      '4xl': '4.8rem',
      '5xl': '6rem',
    },
    opacity: {
      'gallery-hover': '0.3',
    },
    zIndex: {
      navbar: 20,
      overlay: 30,
    },
    extend: {},
  },
  variants: {},
  plugins: [],
}
```

There is no any related config on my nextjs config file.

**Comment by bradlc** [comment]
That all looks fine to me! Please could you also share your VS Code info? You can get this by selecting `Help: About` from the command palette.

Also, if you open a file in your project (JS, HTML, or CSS) and go to the `Output` panel and select `tailwindcss-intellisense` from the dropdown, do you see any errors?

**Comment by cooskun** [comment]
@bradlc Intellisense is working now for some reason. Probably there was a bug on my VS Code. Now it is fine. I am closing the issue.

**Comment by marciovalim** [comment]
Try restarting vs code. Worked for me.

**Comment by Rednegniw** [comment]
Disabling and enabling the extension worked for me.

**Comment by AlwaysFocus** [comment]
@Rednegniw That worked for me too, thanks!

**Comment by robbiecren07** [comment]
I'm having this issue and I have tried all the above solutions plus others I have found online, no luck getting it to work yet. I have the Tailwind CSS: Include Languages "plaintext:javascript" as well. What info do you need from me in order to help debug the issue?

**Comment by realmichaelye** [comment]
^The hover doesn't work for me

**Comment by kelvin-ding** [comment]
because before your folder is ./pages
now you need to update to ./src/pages
hope can help u

**Comment by nahid597** [comment]
just update the taliwind.comfig.js file according to your folder structure
looks like and reload your vs code.

module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
}
