### ISSUE TITLE
Font Weight being registered as a color

### ISSUE THREAD

**Issue by phil-scott-78** [tailwindlabs/tailwindcss-intellisense#180]
Looks like fontWeight is being registered as a color.

![image](https://user-images.githubusercontent.com/2447331/91625370-d5c29a00-e974-11ea-82fd-9c8caa35c438.png)

I suspect what's happening is in [documentColorProvider.ts]( https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/src/lsp/providers/documentColorProvider.ts#L29) it's checking the variants and seeing if it's a valid color value. Because it returns a 3 digit number it looks like a valid color ( in semibold's case it returns 600 so #660000 hence the red decorator).

**Comment by bradlc** [comment]
Thanks @phil-scott-78. This has been fixed in `v0.5.1` of the extension.
