### ISSUE TITLE
PNPM support is not working

### ISSUE THREAD

**Issue by kn0wn** [tailwindlabs/tailwindcss-intellisense#183]
When I have my project built with pnpm, tailwindcss-intellisense does not recognise the installation and then doesn't display the intellisense. This is a continuation from #128

To recreate the issue, just simply clone a project and use `pnpm i`
OS: Windows 10
Node: 14.9.0

**Comment by bradlc** [comment]
Hey @kn0wn. pnpm support seems fine to me on Windows 10. Have you checked the [Troubleshooting](https://github.com/tailwindlabs/tailwindcss-intellisense#troubleshooting) section of the readme, and does the extension work for you if you use npm (or Yarn)?

**Comment by kn0wn** [comment]
Hi @bradlc, Yes I went through the troubleshooting section, are there any logs that the extension may generate?

**Comment by bradlc** [comment]
@kn0wn if you have the latest version of the extension (`v0.5.4`) you can see logs in the VS Code `Output` panel, which you can view using the `View: Toggle Output` command. Make sure to select `tailwindcss-intellisense` from the dropdown:

![image](https://user-images.githubusercontent.com/2615508/101014073-2db50200-355d-11eb-9b51-ec1544b49b49.png)

**Comment by bradlc** [comment]
Going to close this due to inactivity but please open a new issue if you're still having problems 👍
