### ISSUE TITLE
Plugin no longer works when configuring a prefix

### ISSUE THREAD

**Issue by mariusmarais** [tailwindlabs/tailwindcss-intellisense#185]
With a `tailwind.config.js` of
```js
module.exports = {
  // some of the classes and names clash with bootstrap
  important: true, 
  prefix: 'tw-',
  ...
}
```

Intellisense no longer loads, presumably because the classnames are no longer recognized.

It might be too complex to parse the `tailwind.config.js`, but could the plugin make allow a configurable prefix in its own settings?  Something like `tailwindCSS.classNamePrefix: "tw-"`.

**Comment by mariusmarais** [comment]
Or, you can wait for the language server to restart 🤦 .

Nothing to see here.

**Comment by superdc** [comment]
I met the same problem.
