### ISSUE TITLE
Support TailwindCSS 1.8.0

### ISSUE THREAD

**Issue by laymonage** [tailwindlabs/tailwindcss-intellisense#186]
Hi, thanks for the awesome extension!

I'm using the latest version (0.4.3) with TailwindCSS 1.8.6. I'm trying to use the [experimental dark mode support](https://github.com/tailwindlabs/tailwindcss/pull/2279) introduced in TailwindCSS 1.8.0, but this extension doesn't yet support it. It would be awesome if it does. Thanks!

**Comment by bradlc** [comment]
Dark mode support was improved in `v0.5.0` following the release of Tailwind v2 👍
