### ISSUE TITLE
Support Angular [ngClass] 

### ISSUE THREAD

**Issue by alexbjorlig** [tailwindlabs/tailwindcss-intellisense#187]
Angular supports adding classes based on conditions like this: 

```
<div ngClass="{
  'hover:text-blue-700 hover:underline': <some-condition>
}">
</div>
```

This makes it easy to add classes based on a condition. However, the extension does not seem to work in this case?

![Screenshot 2020-09-10 at 21 35 28](https://user-images.githubusercontent.com/9967422/92792113-8edd9700-f3ad-11ea-8a98-b04a53961319.png)

Would be awesome if it worked, because it's a fairly common way of assigning classes in Angular

**Comment by alexbjorlig** [comment]
Is this something we could maybe help add support for? Please let me know how we can help fix this, so Angular can have first class support in Tailwind

**Comment by marcjulian** [comment]
@bradlc thanks for adding ngClass support!! 👍 did you release a new extension version 0.5.2? It doesn't seem to update for me.

**Comment by bradlc** [comment]
Hey @marcjulian, it's published now! Let me know if you run into any issues, cc @alexbjorlig

**Comment by marcjulian** [comment]
![Screenshot 2020-12-01 at 12 41 33](https://user-images.githubusercontent.com/8985933/100736102-902dc700-33d2-11eb-875b-ea0003c32288.png)
Works perfect thanks!
