### ISSUE TITLE
tailwind for lsp?

### ISSUE THREAD

**Issue by steveeq1** [tailwindlabs/tailwindcss-intellisense#188]
I am going through the tutorial about tailwind and I think it's great. I would like to use the "intellisense" feature of tailwind though, but I use emacs. Are there any plans to support tailwind in some sort of lsp server so people with other editors/ides can use it?

**Comment by ahmedelgabri** [comment]
I found this issue while looking for the same thing but for vim (I know about `coc-tailwind`) but I'm using the native LSP from neovim & not coc.nvim.

**Comment by nour-dev** [comment]
hey  @steveeq1 , I am here for the same thing (tailwind intel support for emacs).
In first I thought I will find long list for object props with each key is the class name and the value is the corresponding css rule.
and I simply will add this long object to some thing like yasnippet files (after some string transformation).
 if you have any plans about this mention me.

**Comment by Strikerlulu** [comment]
Ya if this was an lsp we could add it in
https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/

**Comment by julianrubisch** [comment]
Well it does seem like it’s already there? https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/tailwindcss-intellisense/src/lsp/server.ts

Is there a way to run this standalone?

**Comment by ElArtista** [comment]
Publishing as a standalone package could open the way to make user packages on distros like arch for this too like https://aur.archlinux.org/packages/nodejs-vls/

**Comment by yassinebridi** [comment]
This could be integrated with the new NVIM lsp beautifully.

**Comment by ElArtista** [comment]
Made PR #263 towards this. With this patch extracting the prebuilt extension bundle and running `node extension/dist/server/index.js --stdio` works with vim-lsp (and I suppose with all other LSP clients)

**Comment by kabouzeid** [comment]
`node extension/dist/server/index.js --stdio` also works fine with neovim 0.5 built in language client. Having the server bin on npm would be great :)

**Comment by kabouzeid** [comment]
If you are using nvim-lspconfig, setting this handler will make hover work :)

```lua
... .setup {
    ...
    handlers = {
      ["tailwindcss/getConfiguration"] = function (_, _, params, _, bufnr, _)
        -- tailwindcss lang server waits for this repsonse before providing hover
        vim.lsp.buf_notify(bufnr, "tailwindcss/getConfigurationResponse", { _id = params._id })
      end
    },
    ...
}
```

**Comment by pedropmedina** [comment]
@ElArtista @kabouzeid  can you guys provide a step by step as to how to setup this with neovim built-in lsp? Thanks

**Comment by MindTooth** [comment]
I'm using [this](https://github.com/mattn/vim-lsp-settings/blob/master/installer/install-tailwindcss-intellisense.sh) script to download the client into `~/.bin/`.

From there I use the following snippet for [vim-lsp](https://github.com/prabirshrestha/vim-lsp):

```vim
  if executable('tailwindcss-intellisense')
    autocmd User lsp_setup call lsp#register_server({
          \ 'name': 'tailwindcss-intellisense',
          \ 'cmd': {server_info->['tailwindcss-intellisense', '--stdio']},
          \ 'allowlist': ['css', 'html', 'htmldjango'],
          \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tailwind.config.js'))},
          \ })
  endif
```

Just thought I share as I've been at this for some time and wanted to help others. 😛

**Comment by kabouzeid** [comment]
For neovim's built in LSP you can install it conveniently with https://github.com/kabouzeid/nvim-lspinstall

**Comment by Tonksthebear** [comment]
Has anyone had success getting the this working with [Coc.vim](https://github.com/neoclide/coc.nvim/wiki/Language-servers#register-custom-language-servers)? I'm new to lsp and I'm trying to map this thread to coc.vim's documentation for setting up a custom language server. 

I used the script @MindTooth provided, then I added the following config

```
tailwindcss: {
  command¦: ~/languageservers/tailwindcss/tailwindcss-intellisense,
  args¦: [--stdio],
  filetypes: [html, erb, rb],
  initializationOptions: {},
  settings: {}
}
```

I get this in the coc.vim's log

`Language server "languageserver.tailwindcss" started with 3523033`

Which makes me think it's 90% of the way there, but perhaps I'm missing an option that I need to pass for the two to actually communicate? I checked the code from [nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall/blob/main/lua/lspinstall/servers/tailwindcss.lua) and I don't see any extra parameters that is passing along to the tailwind server. I'm not having much luck from here, so I thought I'd check if anyone has experience with this

**Comment by MindTooth** [comment]
I don’t see some sort of root config.  I believe for the ls to work, it needs a `tailwind.config.json` file.

You see mine under `root_uri`.  Though, I can’t for sure say that is the reason.

**Comment by kabouzeid** [comment]
@Tonksthebear your coc config should be fine. But for tailwind to work your project already needs to be a "tailwind" project, ie you need to have tailwind.config.js, and tailwindcss in your package.json. I recommend you to open your project first with VSCode and see if tailwind completions work there, to verify your project is setup correctly for tailwind-intellisense.

There are a two coc extensions for tailwind, but they are outdated, I wouldn't use them.

Right now, if you want to get tailwind intellisense working with all the bells and whistles (preview in completion menu), you need to either use nvim-lsp + the config in nvim-lspinstall, or coc.nvim + fork tailwind-intellisense and make a coc.nvim extension from it.

**Comment by kabouzeid** [comment]
@Tonksthebear 

you also need to add something like

`"rootPatterns": ["tailwind.config.js", ".git/"],`

to your coc tailwind lsp config, so that the root dir for the server can be set. It won't work without it.

**Comment by Tonksthebear** [comment]
@kabouzeid thanks for the suggestions. I actually started this process by making sure it works with VSCode first, so it is fully working there! Must just be weird coc specific things, or not configuring the rootPattern like you suggested. Ultimately, I don't want to sink my time into this when I can just go with nvim-lsp/vim-lsp and have it work easily. And judging from the coc-tailwind plugins, they're not going to be maintained, so I don't want to run into issues whenever there is an update. So, time to swap those out!

**Comment by kabouzeid** [comment]
I actually made a coc tailwindcss plugin for myself, I just needed to change a few lines of code in the VSCode extension to make it work. Never published it though because I switched to nvim-lsp shortly after.

nvim-lsp is less "plug and play" than coc.nvim, but it's much more configurable and I prefer it that way.

With nvim-lsp it's even possible to get tailwinds color highlighting (https://www.reddit.com/r/neovim/comments/mi9wli/got_tailwindcss_color_highlighting_working/), I haven't found time to publish this yet, but probably will do so this weekend :)

**Quick guide if you want to get started with nvim-lsp:**
1. You need neovim 0.5 nightly
2. Install https://github.com/neovim/nvim-lspconfig. This is because nvim-lsp is intentionally a low level lsp implementation. The official nvim-lspconfig plugin is sort of a higher level API on top with many conveniences. Make sure to read their README and have a look at the sample config, this will get you started with most of the things you need to know.
3. (optionally) install https://github.com/kabouzeid/nvim-lspinstall so that you can conveniently install language servers, with eg `:LspInstall python`.

If you need any help setting up, feel free to let me know :)

**Comment by ElArtista** [comment]
I created an AUR package for all the Arch Linux users out there:
https://aur.archlinux.org/packages/vscode-tailwindcss-language-server-bin/

**Comment by polyzen** [comment]
> I created an AUR package for all the Arch Linux users out there:
> https://aur.archlinux.org/packages/vscode-tailwindcss-language-server-bin/

There's now also https://aur.archlinux.org/packages/tailwindcss-intellisense/ which builds from source.

**Comment by singlexyz** [comment]
Install lspinstall plugin:
`Plug 'kabouzeid/nvim-lspinstall`

Add settings:
```lua
require'lspinstall'.setup() -- important

local servers = require'lspinstall'.installed_servers()
for _, server in pairs(servers) do
  require'lspconfig'[server].setup{}
end
```

Then:
`:LspInstall tailwindcss`

It works.

<img width="714" alt="图片" src="https://user-images.githubusercontent.com/4456413/117568254-e75a6500-b0f1-11eb-8ce7-fd6075231652.png">

**Comment by kabouzeid** [comment]
@singlexyz with the config from your comment, you also need to restart neovim after `:LspInstall tailwindcss`

**Comment by kabouzeid** [comment]
You have to configure color highlighting yourself. You might be able to figure it out from my dotfiles (https://github.com/kabouzeid/dotfiles/blob/master/nvim/lua/lsp-documentcolors.lua)

I hope to find the time to release a plugin for this in future.

**Comment by MatthiasGrandl** [comment]
@kabouzeid ah got it, thanks!

**Comment by aridgupta** [comment]
I am new to neovim 0.5 and lua. I am having trouble setting up tailwindcss lsp with it. Could somebody please show me how? I don't want to use nvim-lspinstall package.

**Comment by polyzen** [comment]
@aridgupta, made a pull request to import the config:
https://github.com/neovim/nvim-lspconfig/pull/966

They intend to make the server installable with npm, but I don't think that's available yet.

If you're using Arch Linux, you can install the server with this package:
https://aur.archlinux.org/packages/tailwindcss-language-server/

**Comment by polyzen** [comment]
Merged \o/ https://github.com/neovim/nvim-lspconfig/commit/a7a93041d94a646c22af88ddbff688522ce1a01c

https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#tailwindcss

**Comment by artarf** [comment]
I assume latest `tailwindcss-intellisense` (v0.6.9) breaks things with neovim lsp because it uses internal watcher of vscode.

**Comment by polyzen** [comment]
On June 15, 2021 10:32:49 AM EDT, Arto Arffman ***@***.***> wrote:
> I assume latest `tailwindcss-intellisense` (v0.6.9) breaks things with
> neovim lsp because it uses internal watcher of vscode.

Can confirm.

--
Best,
Daniel <https://danielcapella.com>

**Comment by bradlc** [comment]
> I assume latest `tailwindcss-intellisense` (v0.6.9) breaks things with neovim lsp because it uses internal watcher of vscode.

No, it shouldn't. Tailwind CSS IntelliSense (the VS Code extension) uses VS Code's built-in watcher. The language server uses LSP events where possible and has its own watcher as a fallback. If it isn't working let me know if it's something to do with the language server and I can take a look.

To address the general LSP topic: I am going to publish the language server to npm as a standalone thing this week hopefully 👍 I will let you know when it's published

**Comment by kabouzeid** [comment]
This is the error appearing with the 0.6.9 GitHub release when running the server with `node tailwindServer.js`

```
Unhandled exception: Can't resolve '/Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/prebuilds/darwin-x64/node.napi.glibc.node' in '.'
Error: Can't resolve '/Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/prebuilds/darwin-x64/node.napi.glibc.node' in '.'
    at c (/Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:2:26545)
    at /Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:2:27232
    at /Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:2:27796
    at eval (eval at create (/Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:50:30416), <anonymous>:15:1)
    at /Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:2:27796
    at eval (eval at create (/Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:50:30416), <anonymous>:16:1)
    at /Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:2:27796
    at eval (eval at create (/Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:50:30416), <anonymous>:15:1)
    at /Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:2:27796
    at eval (eval at create (/Users/karim/.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense/extension/dist/server/tailwindServer.js:50:30416), <anonymous>:16:1)

```

**Comment by bradlc** [comment]
> This is the error appearing with the 0.6.9 GitHub release when running the server with `node tailwindServer.js`

Ah yeah that makes sense. We don't ship the watcher binaries with the VS Code extension because they are not needed. These will be included in the standalone package when I publish it 👍 

For now you can use `v0.6.8` since there's not actually any new language server features in `v0.6.9` so it's functionality equivalent outside of VS Code.

**Comment by jim-at-jibba** [comment]
Any news on the npm pacakge?

**Comment by ElArtista** [comment]
Waiting for this too!

**Comment by ElArtista** [comment]
For Vim friends on Arch Linux that use the vim-lsp plugin:

Install ​the server with this package:
https://aur.archlinux.org/packages/tailwindcss-language-server/

Use this configuration:
```
" TailwindCSS language server
if executable('tailwindcss-language-server')
   ​au User lsp_setup call lsp#register_server({
       ​\ 'name': 'tailwindcss-language-server',
       ​\ 'cmd': {server_info->[&shell, &shellcmdflag, 'tailwindcss-language-server --stdio']},
       ​\ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tailwind.config.js'))},
       ​\ 'initialization_options': {},
       ​\ 'whitelist': ['css', 'less', 'sass', 'scss', 'vue'],
       ​\ })
endif
```

Make sure that the tailwind dependencies in your project are installed using `npm install` or the completion won't work.
Also make sure that a tailwind.config.js exists in the root of your project.
Completion will work, and you can also see the analytic css classes used with the LspHover command over a tailwind class!

**Comment by rocinant3** [comment]
> Install lspinstall plugin:
> `Plug 'kabouzeid/nvim-lspinstall'`
> 
> Set it up:
> 
> ```lua
> require'lspinstall'.setup() -- important
> 
> local servers = require'lspinstall'.installed_servers()
> for _, server in pairs(servers) do
>   require'lspconfig'[server].setup{}
> end
> ```
> 
> Then execute:
> `:LspInstall tailwindcss`
> 
> and restart vim. It works.
> 
> <img alt="图片" width="714" src="https://user-images.githubusercontent.com/4456413/117568254-e75a6500-b0f1-11eb-8ce7-fd6075231652.png">

Can you share nvim config?

**Comment by rocinant3** [comment]
Class completion is very strange. What is the problem?
![nvim-tailwind](https://user-images.githubusercontent.com/42095220/126881067-f5a9e20f-3bcd-401b-9f9d-209353814ed9.gif)

tailwind lsp setup
```
 lua require('lspconfig').tailwindcss.setup{on_attach=require('completion').on_attach, cmd={'node','/home/donkyhot/.config/nvim/plugged/tailwindcss-intellisense/extension/dist/server/tailwindServer.js','--stdio'}}

```

LspInfo:
![Снимок экрана от 2021-07-25 00-08-58](https://user-images.githubusercontent.com/42095220/126881126-7a3fc05a-50af-4640-acf1-7f4b0f340db5.png)

**Comment by kabouzeid** [comment]
probably because the newest version of tailwindlabs/tailwindcss-intellisense has some problems outside of VSCode when used as is. Try if it works with version 0.6.8 for now

**Comment by rocinant3** [comment]
@kabouzeid, its 0.6.8

**Comment by kabouzeid** [comment]
hmm idk then

**Comment by rocinant3** [comment]
@kabouzeid, this is an auto-completion problem (hints are cleared as soon as you enter the "-" character) What do you use for auto-completion with tailwind?

**Comment by kabouzeid** [comment]
compe

**Comment by rocinant3** [comment]
The problem was with the nvim-lua/completion-nvim plugin. After switching to compe, everything worked as it should

![nvim-2](https://user-images.githubusercontent.com/42095220/126895560-f9cda1a3-c837-49c9-b80d-3e43f01e127d.gif)

**Comment by mcchrish** [comment]
> > This is the error appearing with the 0.6.9 GitHub release when running the server with `node tailwindServer.js`
> 
> Ah yeah that makes sense. We don't ship the watcher binaries with the VS Code extension because they are not needed. These will be included in the standalone package when I publish it 👍
> 
> For now you can use `v0.6.8` since there's not actually any new language server features in `v0.6.9` so it's functionally equivalent outside of VS Code.

Seem the standalone language-server is already published in npm and lspconfig updated the instructions as follows: https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#tailwindcss

**Comment by ElArtista** [comment]
@polyzen can you update the AUR package?

**Comment by polyzen** [comment]
That's says version `0.0.2`.

**Comment by Fghurayri** [comment]
I'm still having an issue. Maybe there's something off with my setup. 

Anyway, thank you for your kind help. 🌹

**Comment by ymarkus** [comment]
@Fghurayri did you ever manage to fix autocompletion? I'm having the same issue.

**Comment by gasacchi** [comment]
anyone know how to add new filetype?
i want to use it on my Elm file

```lua
require('lspconfig').tailwindcss.setup {
  cmd = { "tailwindcss-language-server", "--stdio" },
  filetypes = { "elm", "aspnetcorerazor", "astro", "astro-markdown", "blade", "django-html", "edge", "eelixir", "ejs", "erb", "eruby", "gohtml", "haml", "handlebars", "hbs", "html", "html-eex", "jade", "leaf", "liquid", "markdown", "mdx", "mustache", "njk", "nunjucks", "php", "razor", "slim", "twig", "css", "less", "postcss", "sass", "scss", "stylus", "sugarss", "javascript", "javascriptreact", "reason", "rescript", "typescript", "typescriptreact", "vue", "svelte" },
  init_options = {
    userLanguages = {
      eelixir = "html-eex",
      eruby = "erb"
    }
  },
  on_new_config = function(new_config)
    if not new_config.settings then
      new_config.settings = {}
    end
    if not new_config.settings.editor then
      new_config.settings.editor = {}
    end
    if not new_config.settings.editor.tabSize then
      -- set tab size for hover
      new_config.settings.editor.tabSize = vim.lsp.util.get_effective_tabstop()
    end
  end,
  root_dir = nvim_lsp.util.root_pattern('tailwind.config.cjs', 'tailwind.config.js', 'tailwind.config.ts','postcss.config.cjs', 'postcss.config.js', 'postcss.config.ts', 'package.json', 'node_modules', '.git'),
  settings = {
    tailwindCSS = {
      lint = {
        cssConflict = "warning",
        invalidApply = "error",
        invalidConfigPath = "error",
        invalidScreen = "error",
        invalidTailwindDirective = "error",
        invalidVariant = "error",
        recommendedVariantOrder = "warning"
      },
      validate = true
    }
  }
}
```
lsp is active when i open ```.elm``` file but auto-completion doesn't work

**Comment by ymarkus** [comment]
What does `:LspInfo` show?

**Comment by gasacchi** [comment]
```2 client attached to this buffer``
it show elmls and tailwindcss client.
i don't know what happen. when using svelte, auto-completion working just fine.
but not with elm

**Comment by gasacchi** [comment]
some folks can get it work on vscode as mention in here https://github.com/tailwindlabs/tailwindcss-intellisense/issues/84#issuecomment-736622127, but i don't know how to use experimental classRegex in [here](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#tailwindcss)

**Comment by TomzBench** [comment]
I found this error in nvim lsp.log

```
7   [ERROR][2022-01-06 20:21:48] ...lsp/handlers.lua:419    "Unhandled exception: Cannot read properties of undefined (reading 'filter')\nTypeError: Cannot read properties of undefined (readi    ng 'filter')\n    at matchClassAttributes (/home/thomas/.local/share/nvim/lspinstall/tailwindcss/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:57:342671)\n        at /home/thomas/.local/share/nvim/lspinstall/tailwindcss/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:57:342963\n    at Generator.next (<anonymous>)\n    at f    ulfilled (/home/thomas/.local/share/nvim/lspinstall/tailwindcss/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:57:339947)"
```

**Comment by bradlc** [comment]
Closing this as we now provide the [`@tailwindcss/language-server`](https://www.npmjs.com/package/@tailwindcss/language-server) package on npm 👍
