### ISSUE TITLE
Support css attribute in react emotions

### ISSUE THREAD

**Issue by IRediTOTO** [tailwindlabs/tailwindcss-intellisense#193]
Hi :) Thank you for made great extention. 
I have some code like bellow, but extention just work with className not this css attr.  Is there any option to add more ?
```
 <li css={tw`flex items-center`}>
                           <a href="https://themebing.com/wp/tijarah/product-category/psd-templates/">
                              PSD Templates
                           </a>
                        </li>
```

**Comment by anark** [comment]
See https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129
