### ISSUE TITLE
Intellisense does not work when inserting a class in the front of an existing classname string

### ISSUE THREAD

**Issue by cktang88** [tailwindlabs/tailwindcss-intellisense#194]
I've noticed that when I have a div and add a tailwind class in the classname string, the intellisense popup only works when I'm working on the end of the string.

Using React+JSX, latest VSCode + TailwindCSS extension at the time of writing

Example where it'll work:
```html
<div className="bg-
```

Example where it won't work (where I typed in the border classes _first_, then went back to the start of the string and inserted the `bg-` to try to get autocomplete.
```html
<div className="bg- border-2 border-solid"></div>
```

**Comment by jeffchown** [comment]
I just found that, as a temporary workaround, if you add a space first (at the beginning of the classes), then it works.
e.g. `<div class=" bg- border-2 border-solid"></div>`

**Comment by Mootook** [comment]
@jeffchown This works for me. You can also begin a class string and press ctrl + space.
`"bg-"`
then `ctrl+space`, pulls up available autocomplete suggestions

**Comment by bradlc** [comment]
This is to do with how VS Code triggers completions. Setting the `strings` property of the `editor.quickSuggestions` setting to `true` improves this a lot 👍 

```
"editor.quickSuggestions": {
  "strings": true
}
```
