### ISSUE TITLE
Support in ESM Environments with "tailwind.config.cjs"

### ISSUE THREAD

**Issue by lannonbr** [tailwindlabs/tailwindcss-intellisense#198]
As discussed in https://github.com/tailwindlabs/tailwindcss/discussions/2284, it is possible to still use Tailwind in a ESM environment by declaring the config file to have a `.cjs` file extension. That said, it breaks the activation event & sourcing of the config as it is looking for various options ending with `.js`.

I'm curious if it would be possible to add functionality for this extension to pick up tailwind config files that end with `.cjs`

**Comment by bradlc** [comment]
The extension will now look for config files with a `.cjs` extension as well as `.js`, as of `v0.5.5` 👍

**Comment by DoisKoh** [comment]
Does the extension only work with CJS? Changing tailwind.config.js to ESM results in an error - the tailwindServer.js file tries to require instead of import.
