### ISSUE TITLE
Support for scala?

### ISSUE THREAD

**Issue by hth2** [tailwindlabs/tailwindcss-intellisense#199]
I know this is somewhat unusual, but anyway decided to ask: is it possible to use this plugin with scala files? My typical code looks as follows:
```
  sb(modal)(
    doApply("fixed left-0 top-0 w-full h-full z-10")
  )
```

I read the related issues and tried to add to `tailwindCSS.includeLanguages` the following (one at a time, always restart vscode):

```
"scala": "plaintext"
"scala": "css"
"scala": "html"
"Scala": "plaintext"
"Scala": "css"
"Scala": "html"
```

I have the official scala plugin installed. I also tried to disable it, and use "plaintext" instead on "scala" in tailwindCSS.includeLanguages, but still no luck.

Any hint would be much appreciated.

**Comment by bradlc** [comment]
Hey @hth2! I think that because the syntax does not match a standard class attribute, this could be covered by #129
