### ISSUE TITLE
feat req: add rem to px preview

### ISSUE THREAD

**Issue by reslear** [tailwindlabs/tailwindcss-intellisense#200]
Sometimes, when developing, you need to use pixel equivalents, but they are not in memory)
add px preview for rems) 
like
<img width="884" alt="Снимок экрана 2020-10-07 в 13 19 34" src="https://user-images.githubusercontent.com/12596485/95319326-68255a00-08a0-11eb-99a2-34fd2d01f55c.png">

and add option for set base size like 16px

**Comment by reslear** [comment]
especially when using figma (no rem in it)
![image](https://user-images.githubusercontent.com/12596485/100139631-d221af00-2ea0-11eb-861b-79ceab0527d7.png)

please add this featurure for easy use figma users, thx)

**Comment by bradlc** [comment]
This has been added as an experimental feature which can be enabled by using the `tailwindCSS.experimental.showPixelValues` setting:

```json
{
  "tailwindCSS.experimental.showPixelValues": true
}
```

Any feedback is appreciated!

**Comment by reslear** [comment]
> This has been added as an experimental feature which can be enabled by using the `tailwindCSS.experimental.showPixelValues` setting:
> 
> ```json
> {
>   "tailwindCSS.experimental.showPixelValues": true
> }
> ```
> 
> Any feedback is appreciated!
wooow thx, I'm starting to test)

**Comment by amrnn90** [comment]
Hi @bradlc,
Tried this and it's working great, but it doesn't seem to be working with `space-x-*` and `space-y-*` utilities.

**Comment by alesso-x** [comment]
Feature req: It would also be useful to configure the px value for 1 rem. I'm working on a project that changed the root font size to 14px 😬

**Comment by bradlc** [comment]
`v0.5.9` adds two new settings: `tailwindCSS.showPixelEquivalents` (boolean, default `true`) and `tailwindCSS.rootFontSize` (number, default `16`) 🎉
