### ISSUE TITLE
Linting errors for duplicate classes while using If else conditions

### ISSUE THREAD

**Issue by sajjadalis** [tailwindlabs/tailwindcss-intellisense#201]
Hello,

I have conditional background color classes in multiple blade template files (Laravel), which gives linting errors and highlights the files in sidebar (looks uncomfortable)

Anyway to avoid that duplicate class errors when @if @endif conditions are present?

Thanks.

**Comment by bradlc** [comment]
Unfortunately this is a limitation of the class attribute parsing. If you write your conditions like this you won't get the warnings:

```html
<div class="{{ $condition ? 'bg-red-500' : 'bg-blue-500' }}">
```

Alternatively you can disable the lint rule in blade files:

```json
"[blade]": {
  "tailwindCSS.lint.cssConflict": "ignore"
}
```
