### ISSUE TITLE
Autocomplete not working with this tailwind.config.js

### ISSUE THREAD

**Issue by KazakovKirill** [tailwindlabs/tailwindcss-intellisense#203]
I'm importing some variables to get my font family in sync with my font loader:

**tailwind.config.js:**
```
const defaultTheme = require('tailwindcss/defaultTheme')
const { fontsConfig } = require('./fonts')
module.exports = {
  theme: {
    fontFamily: {
      brand: [
        fontsConfig.BRAND_FONT_TITLE,
        ...defaultTheme.fontFamily[fontsConfig.BRAND_FONT_TYPE],
      ],
    },
    extend: {
      fontFamily: {
        display: [
          fontsConfig.DISPLAY_FONT_TITLE,
          ...defaultTheme.fontFamily[fontsConfig.DISPLAY_FONT_TYPE],
        ],
        sans: [
          fontsConfig.BODY_FONT_TITLE,
          ...defaultTheme.fontFamily[fontsConfig.BODY_FONT_TYPE],
        ],
      },
    },
  },
}

```

Console output:
```
console.log({ BRAND_FONT_TITLE: fontsConfig.BRAND_FONT_TITLE })
BRAND_FONT_TITLE: 'Open Sans'
```

All fonts are working perfect, except autocomplete.
And no any error messages

**Comment by bradlc** [comment]
Are you able to share the contents of the `./fonts` file @KazakovKirill? Also make sure to check the [Troubleshooting](https://github.com/tailwindlabs/tailwindcss-intellisense#troubleshooting) section of the readme if you haven't already

**Comment by bradlc** [comment]
Also if you can, please could you check the `Output` panel for any logs? You can reveal this via the `View: Toggle Output` command:

![image](https://user-images.githubusercontent.com/2615508/101510890-60526680-3972-11eb-93dc-4561851c98c8.png)

**Comment by bradlc** [comment]
I am going to close this due to inactivity but please open a new issue if you're still having problems 👍
