### ISSUE TITLE
Update @apply complex class errors

### ISSUE THREAD

**Issue by surjithctly** [tailwindlabs/tailwindcss-intellisense#206]
While using latest version of Tailwind, it throws errors while using complex class inside @apply. 

These errors should be removed.

**Comment by tommulkins** [comment]
> While using latest version of Tailwind, it throws errors while using complex class inside @apply.
> 
> These errors should be removed.

I think you will still need to use 
```
experimental: {
  applyComplexClass: true,
}
```

**Comment by surjithctly** [comment]
When 2.0 is stable, this should not be required right?

**Comment by bradlc** [comment]
The latest extension release (`v0.5.0`) doesn't show `@apply` errors if you're on Tailwind v2 👍
