### ISSUE TITLE
Add support for @nuxtjs/tailwindcss

### ISSUE THREAD

**Issue by geabenitez** [tailwindlabs/tailwindcss-intellisense#207]
It would be great if we could use this plugin when the plugin @nuxtjs/tailwindcss is installed.

**Comment by JBetancourt1996** [comment]
Esto seria una buena idea!

**Comment by isaac5003** [comment]
Es necesario esto

**Comment by ErickPetru** [comment]
@geabenitez I'm on a Nuxt project with @nuxtjs/tailwindcss and intellisense is working as expected on Vue templates:

![image](https://user-images.githubusercontent.com/242274/99716135-82994880-2a86-11eb-8131-33d0ebc69c5b.png)

What other usage do you refer that needs to be supported?

**Comment by Divlo** [comment]
@ErickPetru Can you tell us your settings to get it working ?

**Comment by bradlc** [comment]
The extension requires a Tailwind config file in order to activate. If you want to use the default config you can create a `tailwind.config.js` file at the root of your Nuxt project with the following contents:

```js
module.exports = {}
```

**Comment by ErickPetru** [comment]
Answering to @Divlo and reinforcing what @bradlc said, in fact I always had a `tailwind.config.js` in my project, as I always need to extend its configurations.

**Comment by jjelev** [comment]
> The extension requires a Tailwind config file in order to activate. If you want to use the default config you can create a `tailwind.config.js` file at the root of your Nuxt project with the following contents:
> 
> ```js
> module.exports = {}
> ```

just copy default configuration [@nuxtjs/tailwindcss](https://github.com/nuxt-community/tailwindcss-module/blob/master/lib/files/tailwind.config.js)

**Comment by JordanMcn** [comment]
Hey guys !

Same problem for me, the thing is that with the Nuxt Tailwind module, the config file is under the `.nuxt` folder.
