### ISSUE TITLE
Dark variants generation based on existing colors.

### ISSUE THREAD

**Issue by husayt** [tailwindlabs/tailwindcss-intellisense#212]
Hi,
with dark mode going mainstream in TailwindCss 2, it would be great if this plugin could have a function to autogenerate dark variants.

Logic is surprisingly simple and would cover for most cases. Scan for all `text-` , `bg-` and other color classes and where there are no dark vairants add them. For example, where you meet `text-color-x` it would add  `text-color-${900-x}`.

This is obviously very simplified and needs to cover for edge cases, but even very simple implementation would allow for a good start and save a lot of time.

**Comment by bradlc** [comment]
Thanks for the suggestion @husayt! I think this is outside the scope of this project unfortunately. Could be a cool CLI tool though!
