### ISSUE TITLE
Supports Tailwind 2.0

### ISSUE THREAD

**Issue by ErickPetru** [tailwindlabs/tailwindcss-intellisense#213]
Tailwind 2.0 arrived yesterday with cool new features. This extension needs some changes to better handle it:

![image](https://user-images.githubusercontent.com/242274/99715617-df483380-2a85-11eb-9ccc-20ccf48979ab.png)

Mainly about the new classes, like the `ring` ones which needs to be supported.

But also there's the breaking change about how default classes are generated with uppercase `DEFAULT` properties, so the autocomplete should suggests just `bg-red` and not `bg-red-DEFAULT` for my custom red color.

**Comment by bradlc** [comment]
Are you able to share your project repo @ErickPetru? The only thing I can think of that might be causing this is that you have multiple versions of Tailwind inside the same project or something like that 🤔

**Comment by ErickPetru** [comment]
Hi @bradlc, I really don't understand how, but tested right now and it worked successfully. Maybe was there some cached Tailwind version in some deep node dependency? I really don't know. But the two points I stated are working correctly, so this issue can be closed. Thanks.
