### ISSUE TITLE
Tailwind 2.0 Issues

### ISSUE THREAD

**Issue by jneterer** [tailwindlabs/tailwindcss-intellisense#214]
Hello!

I upgraded Tailwind to 2.0 in my Angular project and I am now running into issues where tailwindcss-intellisense is not able to pick up my config options. For example, given the following extended colors:
<img width="232" alt="Screen Shot 2020-11-20 at 7 57 36 AM" src="https://user-images.githubusercontent.com/32587255/99802655-10684880-2b06-11eb-8850-12fa7cfb644e.png">
and looking at my scss:
<img width="748" alt="Screen Shot 2020-11-20 at 7 55 24 AM" src="https://user-images.githubusercontent.com/32587255/99802686-1ceca100-2b06-11eb-99a8-287940016f9c.png">
it does not seem to pick up my `text` color. This goes for any extended configs like screens, insets, etc. Maybe this is an issue with how I've set up my `tailwind.config.js` file, but wanted to bring it to your attention just in case.

Thanks!

**Comment by bradlc** [comment]
Hey @jneterer. I can't seem to reproduce this. Are you able to share your project repo at all?

**Comment by jneterer** [comment]
@bradlc Sure, the latest commit found here: https://github.com/jneterer/headache-tracker/tree/base-pages

**Comment by bradlc** [comment]
Ah so it's because your config is a function. The extension doesn't support this because it can't know what you're passing in. Perhaps instead of passing `isProd` in you could read from a environment variable instead? I'm not familiar with your setup so best to check this, but `process.env.NODE_ENV` is often already set to `"production"` when running certain tools in production mode:

```js
enabled: process.env.NODE_ENV === 'production',
```

**Comment by jneterer** [comment]
@bradlc Thank you so much for checking that out! That's what I originally had but then changed the configuration. Thanks!

**Comment by bradlc** [comment]
Actually, purge will automatically enable itself when `process.env.NODE_ENV === 'production'` so you should be able to just remove the `enabled` property completely, assuming that the environment variable is being set correctly 👍

**Comment by evanfuture** [comment]
I might add that some webpack builds don't use process.env.NODE_ENV, but instead pass the env as part of the config...  This helps have a single webpack config file instead of one for each env.  So, it would be nice if having a function could be supported 🤞
