### ISSUE TITLE
Support for Panic - Nova

### ISSUE THREAD

**Issue by justalever** [tailwindlabs/tailwindcss-intellisense#215]
Panic released a cool new editor recently called [Nova](https://nova.app/) (think Coda reinvented). There's an extension for Tailwind CSS completions the intellisense would be a sweet addition. I'm not sure if it's even possible so this is more of a  "throw it on your radar" issue.

**Comment by florianbouvot** [comment]
@justalever it's not an official extension form tailwindlabs but you can start with this one: https://github.com/jasonplatts/tailwindcss-nova-ext

**Comment by justalever** [comment]
@florianbouvot I use that one :) unfortunately it doesn't handle the intellisense component.

**Comment by bradlc** [comment]
Hey @justalever. I want to keep these issues related to the existing VS Code extension so I'm going to close this, but I appreciate the suggestion! I have played around with the Nova API in the past and the Language Server Protocol support was not great. Maybe it's something we can look at in the future.
