### ISSUE TITLE
Tailwind 2.0.1 errors relating to @apply with :hover

### ISSUE THREAD

**Issue by mosfetish** [tailwindlabs/tailwindcss-intellisense#216]
Rule:

```
.btn-blue {
  @apply bg-blue-500 hover:bg-blue-700 text-white;
}
```

Errors:

- '@apply' cannot be used with 'hover:bg-blue-700' because its definition includes a pseudo-selector (':hover')
- semi-colon expected
- at-rule or selector expected

I suspect the second two are related to the first.

Also, suggestions for :hover in that rule are not shown. All other suggestions work. :hover is suggested in other rules where it does not throw an error.

**Comment by CraigIsOnGitHub** [comment]
you can make the semi-colon and at-rule warnings go away by splitting the `@apply`'s over several lines. eg:
```
.btn-blue {
  @apply bg-blue-500; 
  @apply hover:bg-blue-700;
  @apply text-white;
}
```
but this is a pain.

**Comment by bradlc** [comment]
Hey @mosfetish. It sounds like you might have an old version of the extension. Please can you check that you're on `v0.5.0`?

@CraigIsOnGitHub those errors are from VS Code itself and can be turned off by disabling the `css.validate` setting

**Comment by mosfetish** [comment]
> Please can you check that you're on `v0.5.0`?

I'm on v0.5.0

**Comment by bradlc** [comment]
In that case are you certain that you are using Tailwind v2? (Note that if you upgraded you may need to reload the VS Code window.) If so are you able to share a project repo so I can take a look?

**Comment by mosfetish** [comment]
I'm using 2.0.1 for sure. I used the official upgrade guide It's a fresh project install.  It's a Laravel project but that shouldn't matter since the Tailwind intellisense works flawlessly otherwise, even in Blade templates.

Here's my package.json:

```
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run development -- --watch",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "@tailwindcss/forms": "^0.2.1",
    "autoprefixer": "^9.8.6",
    "axios": "^0.19",
    "cross-env": "^7.0.2",
    "laravel-mix": "^5.0.1",
    "laravel-mix-purgecss": "^5.0.0",
    "lodash": "^4.17.19",
    "postcss": "^7.0.35",
    "postcss-loader": "^3.0.0",
    "resolve-url-loader": "^3.1.0",
    "sass": "^1.28.0",
    "sass-loader": "^10.0.4",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1",
    "vue-template-compiler": "^2.6.12"
  },
  "peerDependencies": {},
  "dependencies": {}
}
```

**Comment by abhaykhillare** [comment]
I dont know how to implement newest tailwind in my project 
Please provide me the latest tailwind.css cdn link

**Comment by mhatvan** [comment]
I am also experiencing the same issue like the author.

**Comment by bradlc** [comment]
Can anyone experiencing this please take a look in the `Output` panel for any logs from `tailwindcss-intellisense`? Please make sure you are on `v0.5.4` of the extension.

![image](https://user-images.githubusercontent.com/2615508/101022402-43c8bf80-3569-11eb-944c-c9e050fcae48.png)

**Comment by mosfetish** [comment]
> Can anyone experiencing this please take a look in the `Output` panel for any logs from `tailwindcss-intellisense`? Please make sure you are on `v0.5.4` of the extension.

Output panel:

```
Found Tailwind config file: /sites/laravel.test/tailwind.config.js
Found tailwindcss v2.0.1: /sites/laravel.test/node_modules/tailwindcss
Initialised successfully. 

```

**Comment by bradlc** [comment]
Since the extension is correctly picking up that your tailwindcss version is `2.0.1` I have no idea what is going on here. The `@apply` diagnostics are disabled if you're on v2 🤔

**Comment by bradlc** [comment]
Hey @mosfetish I know it's been a while, but are you still experiencing this issue?

**Comment by dbomoto** [comment]
This is how I managed my hover states for `@apply`.

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components{
  .cmdBar-btn{
    @apply h-16 text-yellow-300 w-1/4 bg-black font-semibold rounded-lg
  }
  .cmdBar-btn:hover {
    @apply bg-blue-900 text-white border-red-500 border-4 box-border
  } 
}
```

It's a bit of a hassle to do this though, but for now this is how I do it.

**Comment by bradlc** [comment]
Going to close this as it is unclear whether the issue still exists (see https://github.com/tailwindlabs/tailwindcss-intellisense/issues/216#issuecomment-921755123)
