### ISSUE TITLE
Extension doesn't work with my setup

### ISSUE THREAD

**Issue by robdekort** [tailwindlabs/tailwindcss-intellisense#220]
Hi folks. What used to work doesn't anymore and I'm not sure why. I have the extension installed on two macs and in both cases Intellisense doesn't boot up. 

I use multiple Tailwind config files as presets. [This is my base config file](https://github.com/studio1902/statamic-peak/blob/main/tailwind.config.js).

Please let me know if you need more information. Happy to help.

**Comment by bradlc** [comment]
Hey @robdekort. Looks like you have a JS error here (`_` is not defined): https://github.com/studio1902/statamic-peak/blob/8f9e0b710bc79ed1788eec8e0c34156395346175/tailwind.config.peak.js#L73

Granted the extension could do a better job at surfacing this. We do show config errors but only if the extension has already successfully activated once.

**Comment by bradlc** [comment]
For future reference you can see this error in VS Code's `Output` panel:

![image](https://user-images.githubusercontent.com/2615508/101049510-80051b80-357b-11eb-8974-5abca6531ef1.png)

**Comment by robdekort** [comment]
Oh Wow! You are a champ. Thanks you so much for finding that. I would've never :-)
