### ISSUE TITLE
colorDecorators option is not working well with automatic line wrapping

### ISSUE THREAD

**Issue by Aferz** [tailwindlabs/tailwindcss-intellisense#221]
Hello Tw Team.

I've found that the setting `"editor.wordWrap": "on"` which autowraps the line once it reaches the end of the viewport doesn't play well with the plugin option `"tailwindCSS.colorDecorators": "on"` which render the colors inside the HTML.

It looks like the render color boxes are not being taken into account for VSCode to determine the line has reached the end and it should be wrapped.

Here one example with `colorDecorators` enabled:

![Captura de pantalla 2020-12-03 a las 19 06 52](https://user-images.githubusercontent.com/8954655/101070351-886d4e80-359b-11eb-9e5c-2f103581d477.png)

With `colorDecorators` disabled:

![Captura de pantalla 2020-12-03 a las 19 07 11](https://user-images.githubusercontent.com/8954655/101070386-9622d400-359b-11eb-9f05-3b52ae3bd942.png)

As you can see, in the second picture, the line wraps correctly.

This is a tedious bug because when your element has several classes the editor is creating a horizontal scrollbar which leaves some content hidden. The line does wrap, but only when the space that those rendered boxes are currently taking is filled.

Maybe this is not a bug in this plugin itself and is a VSCode bug, but I guess is something you should know if you didn't.

I can file a new issue in VSCode if this bug doesn't apply to this plugin.

Thank you for your work.

**Comment by bradlc** [comment]
Hey @Aferz. This is definitely a VS Code bug 👍 There is already an open issue on the VS Code repo: https://github.com/microsoft/vscode/issues/32856
