### ISSUE TITLE
Autocomplete in Twig Arrays.

### ISSUE THREAD

**Issue by christianwiedemann** [tailwindlabs/tailwindcss-intellisense#223]
Hi,

arrays are often used for classes in Twig.

```
{% set classes = [
  'flex items-center justify-center inline-flex border-0 py-2 px-5 focus:outline-none rounded transition-colors duration-500',
  expanded ? 'w-full',
] %>
```

Is there a way that IntelliSense recognize for autocomplete.

**Comment by Utkarsh-Kumar384** [comment]
I'm also looking for something similar but rather in objects. 

I seriously need IntelliSense for objects in React as the "classNames" props ais just getting bloated with 100s of classes...

 Anyone any idea?

**Comment by bradlc** [comment]
Hey @christianwiedemann. I think this is covered by #129. We recently added an [experimental `classRegex` setting](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) which can be used to trigger completions in custom contexts. For your example you could use something like this:

```json
{
  "tailwindCSS.experimental.classRegex": [
    ["\\sclasses\\s*=\\s*\\[([^\\]]*)\\]", "'([^']*)'"]
  ]
}
```
