### ISSUE TITLE
Feature request: pixel value roundup

### ISSUE THREAD

**Issue by andrewfairlie** [tailwindlabs/tailwindcss-intellisense#224]
Building on https://github.com/tailwindlabs/tailwindcss-intellisense/issues/200#issuecomment-737376603 it would be great from a rapid prototyping workflow if you could be looking at a Figma or Sketch file and look at the pixel value, and then write 

```
pt-16px
```

And have the intellisense plugin go...

1. If a key of `16px` is in the config, all is okay
2. If it's not, find the nearest Tailwind token to that pixel if possible, in this case `4` and suggest it changes to `pt-4`

**Comment by bradlc** [comment]
Hey @andrewfairlie, I don't think this is within the scope of the extension right now but I appreciate the suggestion, thank you! ❤️
