### ISSUE TITLE
Emmet Completions providing suggestion on the wrong place

### ISSUE THREAD

**Issue by claytonfaria** [tailwindlabs/tailwindcss-intellisense#228]
Hello, 

While working with Nuxt / TypeScript and Emmet Completions on, autocomplete gets messed up. 

<img width="544" alt="Screen Shot 2020-12-13 at 7 21 21 PM" src="https://user-images.githubusercontent.com/65756578/102010332-64b6bf00-3d78-11eb-8e8a-c6a5f77ddc0c.png">

with Emmet Completions Off, it works, no problems
<img width="533" alt="Screen Shot 2020-12-13 at 7 22 21 PM" src="https://user-images.githubusercontent.com/65756578/102010354-8748d800-3d78-11eb-984e-d6fa199208d7.png">

**Comment by bradlc** [comment]
Hey @claytonfaria. The emmet completions feature has been tweaked a bit in `v0.5.6` of the extension and should now be less eager 👍

**Comment by claytonfaria** [comment]
Hi @bradlc , thank your for your reply. After testing v0.5.6 (yes, reloaded vscode), unfortunately, it is still showing me the suggestions

<img width="960" alt="Screen Shot 2020-12-14 at 11 42 52 PM" src="https://user-images.githubusercontent.com/65756578/102101840-17188000-3e66-11eb-8bb3-67cc4684f76d.png">

**Comment by akomm** [comment]
This should be reopened, because its not fixed. The issue is very annoying, because whenever I write a `.` (dot) in any TS code, 100% of the time I see spam of the above suggestions. I assume the `.` (dot) is confused for the beginning of a `.class`.
