### ISSUE TITLE
IntelliSense not show suggestions for my custom class names in @layer components

### ISSUE THREAD

**Issue by dimasrakas** [tailwindlabs/tailwindcss-intellisense#230]
like https://github.com/tailwindlabs/tailwindcss-intellisense/issues/227

I have created some custom style class inside @layer components {}.  Intellisense did not show suggestions my custom class. But it still works.

here my tailwind.css
[https://pasteboard.co/JFOK9N9.png](https://pasteboard.co/JFOK9N9.png)

this how i use
[https://pasteboard.co/JFOM1hQ.png](https://pasteboard.co/JFOM1hQ.png)

**Comment by bradlc** [comment]
Duplicate of #227
