### ISSUE TITLE
Feature Request: Suggestions on Vue Transition Class props

### ISSUE THREAD

**Issue by Smuno** [tailwindlabs/tailwindcss-intellisense#231]
It would be interesting to receive class recommendations from Tailwind when using Vue Transition Classes as if it were a class attribute.
Even Adam Wathan on his twitter refers to the use of transitions: 
https://twitter.com/adamwathan/status/1118670393030537217

**Comment by bradlc** [comment]
Hey @Smuno. You could use the [`tailwindCSS.experimental.classRegex` setting](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) to enable that if you like:

```
"tailwindCSS.experimental.classRegex": [
  "(?:enter|enter-active|enter-to|leave|leave-active|leave-to)-class=\"([^\"]*)\""
]
```
