### ISSUE TITLE
Error no such file or directory open normalize.css in Tailwind 2.0 project

### ISSUE THREAD

**Issue by mjatharvest** [tailwindlabs/tailwindcss-intellisense#232]
Odd thing, starting a new project using Tailwind 2.0 and I got an error "no such file or directory open" referencing normalize.css

After installing normalize with npm intellisense worked as expected.

But why would it need normalize? 🤔

![Screen Shot 2020-12-21 at 4 21 07 PM](https://user-images.githubusercontent.com/285877/102931801-a88a8200-4464-11eb-9d49-1b5449181a26.png)

Love the extension!

**Comment by bradlc** [comment]
Do you still get this error after reloading VS Code @mjatharvest? Only thing I can think of is some sort of cache issue 🤔 Which package manager are you using?

**Comment by mjatharvest** [comment]
I'm using npm 6.14.9, I've removed normalize and run `npm prune` and can't replicate the issue at present.

Weird thing, sorry to be a bother!

**Comment by bradlc** [comment]
No problem, thanks for the follow up!
