### ISSUE TITLE
Doesn't work with M1 VSCode Insiders build

### ISSUE THREAD

**Issue by RomkaLTU** [tailwindlabs/tailwindcss-intellisense#239]
Version: 1.53.0-insider
Commit: ed6c343edb720d91ee0859e566c84b5687f5a9d5
Date: 2021-01-08T10:47:15.801Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin arm64 20.1.0

Identical extensions setup working fine on Visual Studio Code through Rosetta.

**Comment by nubpro** [comment]
I believe https://github.com/tailwindlabs/tailwindcss-intellisense/pull/226 will resolved this issue.

Awaiting for the release, can we at least have a beta version out? I miss intellisense on the M1. I need it. Help.

**Comment by bradlc** [comment]
This should be fixed in `v0.5.7` of the extension 👍

**Comment by nubpro** [comment]
> This should be fixed in `v0.5.7` of the extension 👍

Yeap it did!
