### ISSUE TITLE
space-* utilities not working

### ISSUE THREAD

**Issue by luisrudge** [tailwindlabs/tailwindcss-intellisense#241]
Hi, friends. Thanks for this amazing plugin. I'm a tailwind addict and I loved the recent `space-*` utilities, but it seems they're not being suggested by the IntelliSense. 

![image](https://user-images.githubusercontent.com/941075/104533158-9bd6f500-55f0-11eb-8a83-85d56344f264.png)

Plugin version: v0.5.6

**Comment by ozburo** [comment]
Can confirm, v0.5.6

**Comment by bradlc** [comment]
Hey @luisrudge. That's odd, the space utilities should definitely be showing up! Are you seeing suggestions for other classes? And are you able to share your Tailwind config and version number please?

**Comment by luisrudge** [comment]
@bradlc Yes, I can see suggestions for other classes.

Here's my config:

```js
module.exports = {
  purge: ["./pages/**/*.js", "./components/**/*.js"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        deposter: "Montserrat",
      },
      fontSize: {
        "10xl": ["10rem", { lineHeight: "1" }],
      },
      colors: {
        yellow: {
          default: "#F5DE4D",
          100: "#FFFFFF",
          200: "#FDF9DD",
          300: "#FAF0AD",
          400: "#F7E77D",
          500: "#F5DE4D",
          600: "#F2D51C",
          700: "#CFB50C",
          800: "#9F8B09",
          900: "#6F6106",
        },
      },
    },
  },
  variants: {},
  plugins: [],
};

```

I tested this same config in tailwind play and it works.
![image](https://user-images.githubusercontent.com/941075/104736255-71388980-5721-11eb-8f4b-5b8c179be06f.png)

tailwind version: 2.0.2

**Comment by bradlc** [comment]
Hmm yeah I'm pretty stumped 🤔 I don't suppose you could share a repo of the entire project?

**Comment by luisrudge** [comment]
I created another nextjs app and now it works 🤯  I'll close this for now until I figure out what's going on. Thanks for the help!

![image](https://user-images.githubusercontent.com/941075/104782555-28092980-5763-11eb-94ef-2891ae5b418c.png)

**Comment by luisrudge** [comment]
I updated all my packages (postcss, next) to the latest versions, deleted node_modules and yarn.lock and did everything again inside the same project: no deal. I'll try to port my nextjs code to a recently created create-next-app project and see how it goes.

![image](https://user-images.githubusercontent.com/941075/104782813-99e17300-5763-11eb-9c0f-12ac892b0c02.png)

**Comment by luisrudge** [comment]
@bradlc  Ok. got it. If I create a single project in a single folder, it always works. If I have a monorepo (my case) with multiple projects and the first project has tailwind 1.2.0 and the second 2.0+, then the plugin will use the config from directory 1:
![image](https://user-images.githubusercontent.com/941075/104790122-6c052a00-5775-11eb-91ae-fdd5d15ec596.png)

I then tried renaming to have the project with tailwind 2.0+ as the first one (alphabetically) and now the plugin shows me the space-x utils even in the project that is not supported:
![image](https://user-images.githubusercontent.com/941075/104790244-b2f31f80-5775-11eb-97e5-dc48934f3ddc.png)

Here's a repro repo: https://github.com/luisrudge/tailwind-next-repro
I'll leave this closed because this is suuuuch a niche haha, but at least it might help others 🎉
