### ISSUE TITLE
Auto-complete doesn't work in multi-root

### ISSUE THREAD

**Issue by tyler36** [tailwindlabs/tailwindcss-intellisense#242]
I'm working on a Drupal project that uses TailwindCSS in a theme.
The file structure

workspace_root
- core
- theme
  -  custom
      - awesome-tailwindcss-theme
        - node_modules
        - templates
          - front-page.html.twig
        - tailwind.config.js
    
Usage:
- Usually, I'd open VSCode at the `workspace_root`, but TailwindCSS intellisense doesn't work.
- If I open the project workspace at `awesome-tailwindcss-theme`, intellisense appears to work. This is inline with the docs saying `tailwind.config.js` must be in the root.

- If I open a multi-workspace at `workspace_root` and  `awesome-tailwindcss-theme`, intellisence doesn't work.

So,
- Can the extention support multi-root?
- Or even better, can the extension be configured to point to the `tailwind.config.js` file?
```json
"tailwindCSS.configfile": "./theme/custom/awesome-tailwind-theme/tailwind.config.js"
```
- Or even just the root, and any required node_modules dependencies would be relative to this?
```json
"tailwindCSS.root": "./theme/custom/awesome-tailwind-theme"
```

I saw there some other issues regarding the config file, but most of them seem to be about running the compiler. In VSCode, I usually open an additional `integrated terminal` and run my watcher in that.

**Comment by bradlc** [comment]
Hey @tyler36. The extension should actually be working fine in all 3 of your examples. The extension _does_ support multi-root and your config _does not_ need to be at the root.

In the cases where the extension is not working for you please could you take a look in the VS Code `Output` panel and see if there's any logs for `tailwindcss-intellisense`?

![image](https://user-images.githubusercontent.com/2615508/106268134-93063600-6222-11eb-84f0-e674ef54463d.png)

**Comment by tyler36** [comment]
Well, this is embarassing 🙄 ... you're right, it works. 

Not sure what was happening. I saw your reply and went to check it but noticed it updated to version `0.5.8`. After restarting, it worked as expected.  Must be an PICNIC error code. 😄 

Thank you for the follow up and clear directions to try. And thank for the extention.
