### ISSUE TITLE
Autocomplete not working in react app

### ISSUE THREAD

**Issue by artrn-nt** [tailwindlabs/tailwindcss-intellisense#243]
Hello,

This extension (v0.5.6) behaves like dead in my IDE (VS Code 1.52.1) for a react-app. **I strictly followed the tailwind documentation about how to setup tailwindcss in a react project.** I also made sure to check-out the 'Troubleshooting' documentation's part of the extension.

I created several react projects just to make sure but the extension is still not working. When I check the output in VS-Code the extension seems to load fine. What I'm missing? Should I modify the IDE JSON settings with something special?

**Comment by bradlc** [comment]
Hey @artrn-nt. Can you clarify that the output you are seeing is along the lines of this?

```
Found Tailwind config file: ...
Found tailwindcss vX.X.X: ...
Initialised successfully.
```

If you are seeing this then you should be good to go!

**Comment by artrn-nt** [comment]
Thank you for the reply @bradlc 

Sure I see the lines you mentioned:
<img width="996" alt="Capture d’écran 2021-01-15 à 22 34 37" src="https://user-images.githubusercontent.com/65855783/104781141-3c105380-5782-11eb-918c-3077c884eb73.png">

But I've got those problems in my index.css:
<img width="356" alt="Capture d’écran 2021-01-15 à 22 38 25" src="https://user-images.githubusercontent.com/65855783/104781375-a5906200-5782-11eb-82b6-290b1b225e67.png">

Is it possible that those problems can affect IntelliSense? I'm not sure...

**Comment by korki43** [comment]
Think this warning originates from vscode itself. Try auto completing a classname in your app. It should work. I also thougt that this was a problem with the extension but then i read this disclaimer in the readme:

> VS Code has built-in CSS validation which may display errors when using Tailwind-specific syntax, such as @apply. You can disable this with the css.validate setting:
> `"css.validate": false`

**Comment by artrn-nt** [comment]
Salut @korki43. Merci pour ta réponse.

It's now working! Thank you very much!

**Comment by SithumDilanga** [comment]
> I think this warning originates from vscode itself. Try auto completing a classname in your app. It should work. I also thougt that this was a problem with the extension but then i read this disclaimer in the readme:
> 
> > VS Code has built-in CSS validation which may display errors when using Tailwind-specific syntax, such as @apply. You can disable this with the css.validate setting:
> > `"css.validate": false`

Thanks worked for me as well
