### ISSUE TITLE
Multi-root `yarn` workspace issue?

### ISSUE THREAD

**Issue by andrewmartin** [tailwindlabs/tailwindcss-intellisense#245]
I really, really want to use this! But I can't seem to get it to resolve correctly.

I am using a multi-root project (one path is to server code, the other to client). My client code has a `tailwind.config.js` file in it that is being detected, but for some reason, I can't get around this error:

```
Found Tailwind config file: /Users/andrewmartin/code/project/client/tailwind.config.js
Failed to initialise: Error: Your application tried to access tailwindcss, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

I have it in the dependencies:

```
"tailwindcss": "^2.0.2",
```

Also tried opening `client` separately (e.g., in its own workspace, so `tailwind.config.js` is at the root)... and I'm still seeing this error. Any suggestions?

By the way, `tailwind` itself is working fine within my project etc. and is definitely installed:

```
➜  project/client master ✗ ls node_modules/tailwindcss
CHANGELOG.md     colors.js        dist             plugin.js        stubs
LICENSE          components.css   lib              resolveConfig.js tailwind.css
README.md        defaultConfig.js node_modules     screens.css      utilities.css
base.css         defaultTheme.js  package.json     scripts
```

Thanks for your work on this!

**Comment by bradlc** [comment]
Hey @andrewmartin. Is there any chance you could share a repository where you are able to reproduce this error?

**Comment by bradlc** [comment]
Going to close this for inactivity but please open a new issue with a reproduction if you're still having issues 👍
