### ISSUE TITLE
What is the vscode theme used in the README?

### ISSUE THREAD

**Issue by u3u** [tailwindlabs/tailwindcss-intellisense#246]
This theme is beautiful! What theme and font is this? 😍 Thank you!

<img src="https://raw.githubusercontent.com/bradlc/vscode-tailwindcss/master/packages/tailwindcss-intellisense/.github/autocomplete.png" alt="" />

<img src="https://raw.githubusercontent.com/bradlc/vscode-tailwindcss/master/packages/tailwindcss-intellisense/.github/linting.png" alt="" />

<img src="https://raw.githubusercontent.com/bradlc/vscode-tailwindcss/master/packages/tailwindcss-intellisense/.github/hover.png" alt="" />

**Comment by bradlc** [comment]
Hey @u3u. The theme is [Tokyo Night](https://marketplace.visualstudio.com/items?itemName=enkia.tokyo-night) 🌃 and the font is [Dank Mono](https://gumroad.com/l/dank-mono) 💅

**Comment by u3u** [comment]
Thanks!
