### ISSUE TITLE
Autocomplete not working on literal string outside className prop

### ISSUE THREAD

**Issue by VictorLandim** [tailwindlabs/tailwindcss-intellisense#248]
For organization purposes, I'd love to be able to have autocomplete on regular literal strings, outside a className prop, as addressed in `v0.3.0`.
Could that be possible or configurable?

![image](https://user-images.githubusercontent.com/5438965/105179153-b7b62b80-5b07-11eb-8d59-964f0b48ae0e.png)

**Comment by bradlc** [comment]
Hey @VictorLandim. Unfortunately in that case there isn't a good way for the extension to know that that string is a list of classes. However, there is a new `tailwindCSS.experimental.classRegex` setting which you could use to achieve this if you wanted: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659. Here's one way you could configure it for your use-case: 

```json
{
  "tailwindCSS.experimental.classRegex": [
    "[cC]lasses\\s*=\\s*`([\\s\\S]*?)`"
  ]
}
```
