### ISSUE TITLE
Pick up class names in Django template fragments. 

### ISSUE THREAD

**Issue by carltongibson** [tailwindlabs/tailwindcss-intellisense#251]
Hi! 

Thanks for the awesome work 🎁 
This is request/question. Happy to try and input to help. 

### Context

I'm using Django (and the [Django Template Language](https://docs.djangoproject.com/en/3.1/topics/templates/)). 

I'm creating partials to aid reuse.

When including a partial, one uses the DTL's `with` tag in order to set local variables for the included template. 

Something like this: 

```
         {% with color='bg-pink-600' %}
               {% include "reusable-fragment.html" %}
         {% endwith %}
```

Where inside `reusable-fragment.html` you'd use the `color` variable: 

```
<div class="{{color}} flex-shrink-0 flex items-center justify-center w-16 text-white text-sm font-medium rounded-l-md">
ABC
</div>
```

### Question/request

Could we make it so that the IntelliSense would function in fragments like this:

```
         {% with color='bg-pink-600' %}
```

? 

If it's not an immediate yes, could you give some pointers as to what the blockers are, so I can investigate? 

I hope that's sufficiently clear. If not please do say. 

Thanks again! 🙂

**Comment by bradlc** [comment]
Hey @carltongibson. There's not really a way for the extension to know that the `color` attribute contains CSS classes. However, there is an experimental setting (`tailwindCSS.experimental.classRegex`) which you can use to force the extension to trigger suggestions based on regular expressions. For example you could enable suggestions in the `color` attribute with this configuration:

```
{
  "tailwindCSS.experimental.classRegex": [
    "\\scolor=\"([^\"]*)\""
  ]
}
```

Take a look at [my comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) over at #129 for more information. Hope that helps!

**Comment by carltongibson** [comment]
Thanks for the reply! That gives me enough to get going on. Super. 🏅
