### ISSUE TITLE
The variant 'dark' does not exist. Did you mean 'last'?

### ISSUE THREAD

**Issue by meotimdihia** [tailwindlabs/tailwindcss-intellisense#256]
Vscode don't regconize `dark` variant. Do we have a fix about this? 
```css
@layer utilities {
  @variants dark {
  }
}
```
![Code_2021-01-30_11-39-40](https://user-images.githubusercontent.com/300961/106347293-ff9b3680-62ef-11eb-80d4-cfb6901d0b2e.png)

**Comment by bradlc** [comment]
Thanks for reporting! This is fixed in `v0.5.9` 👍
