### ISSUE TITLE
Smart tips do not work

### ISSUE THREAD

**Issue by webcomeon** [tailwindlabs/tailwindcss-intellisense#260]
1. I configured tailwindcss in nuxt strictly according to the documentation
2. I also installed Tailwind CSS IntelliSense in vscode and configured tailwind.config.js  as follows

![config](https://user-images.githubusercontent.com/17699267/107171690-5b577500-69fe-11eb-901b-906fd89d50a5.png)

3. I can't use autoprompt by the following actions, as shown in the image (gif)：

![123](https://user-images.githubusercontent.com/17699267/107171746-7b873400-69fe-11eb-8124-fd65717e7405.gif)
 
4. However, I can use autoprompt by **pressing the ESC key** before typing class, as shown in the image (gif)：

![1234](https://user-images.githubusercontent.com/17699267/107171779-8f329a80-69fe-11eb-9a4d-a937c82603c6.gif)

How should I configure it so that the third step above can take effect without having to press the ESC key every time before typing class?

**Comment by webcomeon** [comment]
Console output

![output](https://user-images.githubusercontent.com/17699267/107171899-dde03480-69fe-11eb-9f3b-1f262ed1fff8.png)

**Comment by bradlc** [comment]
Hey @webcomeon. This is to do with how VS Code triggers suggestions. Tweaking the `editor.quickSuggestions` setting to include `"strings": true` should fix your issue:

```
"editor.quickSuggestions": {
  "strings": true
}
```

This is mentioned in the [Recommended VS Code Settings](https://github.com/tailwindlabs/tailwindcss-intellisense#recommended-vs-code-settings) section of the extension readme.

**Comment by webcomeon** [comment]
Thanks, I've actually configured "editor.quickSuggestions" before, but it still didn't work. I guess other extensions of vscode are affecting the usage, I'll try it later.

**Comment by webcomeon** [comment]
> Hey @webcomeon. This is to do with how VS Code triggers suggestions. Tweaking the `editor.quickSuggestions` setting to include `"strings": true` should fix your issue:
> 
> ```
> "editor.quickSuggestions": {
>   "strings": true
> }
> ```
> 
> This is mentioned in the [Recommended VS Code Settings](https://github.com/tailwindlabs/tailwindcss-intellisense#recommended-vs-code-settings) section of the extension readme.

Thanks, I've actually configured "editor.quickSuggestions" before, but it still didn't work. I guess other extensions of vscode are affecting the usage, I'll try it later.
