### ISSUE TITLE
Support for remote tailwind.config.js 

### ISSUE THREAD

**Issue by danielrobertson** [tailwindlabs/tailwindcss-intellisense#267]
I'm working with a micro-frontend setup, including a dedicated repository for custom Tailwind config where the `tailwind.config.js` lives. 

I've forked the tailwindcss-intellisense code and am looking to find a path to support this remote `tailwind.config.js` setup. 

What do you all think? Perhaps an optional config parameter of a GitHub URL to a repo containing the `tailwind.config.js`?

**Comment by bradlc** [comment]
Hey @danielrobertson. I think supporting a remote config file is definitely out of scope for the project. That sounds like a super specific setup and I don't think a feature like that would be useful to many people, but would require a ton of work to get right. Appreciate the suggestion though, and sorry if that wasn't the answer you were hoping for!
