### ISSUE TITLE
Support for tailwindcss-rails

### ISSUE THREAD

**Issue by leehericks** [tailwindlabs/tailwindcss-intellisense#268]
When installing gem [tailwindcss-rails](https://github.com/rails/tailwindcss-rails) without webpacker, default generated tailwindcss is available for use in a Rails project. There is no tailwind.config.js file. Is it possible to enable intellisense when this gem is found in the gemfile?

**Comment by bradlc** [comment]
Duplicate of #247

**Comment by leehericks** [comment]
Sorry I didn't see the duplicate. I don't know well about how these extensions work, but I do know that extensions are able to enable by checking the gemfile. I'm guessing though that without the tailwind.config.js you don't know what to intellisense?
