### ISSUE TITLE
Using with standalone .html files

### ISSUE THREAD

**Issue by andgordio** [tailwindlabs/tailwindcss-intellisense#27]
Hi!

Is there a way to enable the extension for standalone .html files that use [cdn version](https://tailwindcss.com/docs/installation#cdn) of Tailwind? 

Thanks!

**Comment by Coupz** [comment]
I've already asked here and looks like it only works with the full npm package: https://github.com/bradlc/vscode-tailwindcss/issues/16

**Comment by VladimirMikulic** [comment]
That would be great since my setup doesn't include TailwindCSS config file.

**Comment by ngekoding** [comment]
Hi, any updates for this?

**Comment by HarveyB02** [comment]
Bump

**Comment by Christophvh** [comment]
Since Tailwind 3 this is possible. If you want to add the typography plugin you can append it as a 'get' parameter in the URL.

For example:
` <script src="https://cdn.tailwindcss.com?plugins=typography"></script>`

**Comment by hdahlheim** [comment]
Because I think it is related to this issue. It would be nice if the extension would support the standalone tailwindcli. Someone mentioned it in the tailwind repo already https://github.com/tailwindlabs/tailwindcss/issues/6688.

**Comment by ZackPlauche** [comment]
Bump

**Comment by abinoval** [comment]
Hope it gets resolved soon :(

**Comment by bradlc** [comment]
Tailwind CSS IntelliSense now ships with a bundled version of `tailwindcss`, so you can use the extension without a local installation of the module. For now, you can activate the extension by creating a blank `tailwind.config.js` file:

```js
module.exports = {}
```

**Comment by abinoval** [comment]
Yeayy thankssss, it works😋

**Comment by edgarasben** [comment]
Awesome! Also works with a completely empty `tailwind.config.js`

**Comment by jeetsinghb** [comment]
April 2025, it works like a charm!
