### ISSUE TITLE
Require Auto Completion on Javascript Object

### ISSUE THREAD

**Issue by Sangram1987** [tailwindlabs/tailwindcss-intellisense#270]
Currently, Tailwind Intellisense doesn't show auto completion for Javascript Object e.g.
const classes = {
    header : {
      header : 'bg-gray-300 border border-gray-900 text-left px-2',
      headerInner: 'string',
      headerName: 'string',
      sortIcon: 'string'
    }
}

Attach is the screenshot from vscode
![Screenshot 2021-02-23 at 20 17 15](https://user-images.githubusercontent.com/20522883/108860410-2bba8680-7614-11eb-9701-248bcc167fd3.png)

Can we have functionality like this?

**Comment by michaelschufi** [comment]
I'm using the following setting to do that:

```
"tailwindCSS.experimental.classRegex": [":.*?[\"`]([^\"`]*)"],
```

Since you have an extra space between the key and the colon, you might need to change the regex a bit. See #129 as well.

**Comment by bradlc** [comment]
Hey @Sangram1987. There's no way for the extension to know that a random JS string should be treated as a list of classes, but as @michaelschufi said you can use the `tailwindCSS.experimental.classRegex` setting to enable suggestions based on custom regular expressions. Check out [my comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) on #129 for more information.

**Comment by teaca-sebastian** [comment]
doesn't `"tailwindCSS.experimental.classRegex"` accept an array now? i have the same problem and the suggestion above doesn't work for me
