### ISSUE TITLE
Need help with classRegex for a PHP method

### ISSUE THREAD

**Issue by redbastie** [tailwindlabs/tailwindcss-intellisense#271]
I'm trying to figure out how I can match all single or double quoted strings inside of parenthesis. The problem is that the parenthesis may contain child parenthesis.

Here is an example of the content I'm trying to obtain matches in:

    $v->label('Name')->for('name'),
    $v->input()->id('name')->wireModelDefer('name')
        ->class(($this->error('name') ? 'border-red-500' : 'border-gray-300') . ' rounded-lg w-full'),
    $v->if($this->error('name'), fn () => $v->p($this->error('name'))->class('text-xs text-red-600'))
    
Now, I want to match all single or double quoted strings inside of the `class()` method.

So if you look at the above example, here is the context of what I need to match:

    ->class(($this->error('name') ? 'border-red-500' : 'border-gray-300') . ' rounded-lg w-full')
    ->class('text-xs text-red-600')
    
Now, given these 2 examples, as you can see, they are PHP methods which contain Tailwind class names. I want to use regex to match the Tailwind class names within this `class()` method call.

So anyways, given the above 2 lines, what should be extracted are the following:

    border-red-500 border-gray-300 rounded-lg w-full
    text-xs text-red-600
    
If `name` also happens to be matched, then so be it. I don't really care about that. Just as long as the single or double quoted strings inside the `class()` method get matched.

As for regex I've tried, here are a few examples:

    class\([\"']([^\"']*)[\"']\)
    
Which matched:

    text-xs text-red-600
    
This works great if there are no child parenthesis inside of the `class()` method arguments.

So, I tried some different things:

    class\((.*?)\)
    
This unfortunately only captured:

    ($this->error('name'
    
Then I started trying some more advanced stuff, like the recursion operator:

    class\(([^()]|(?R))*\)
    
This only matched:

    '

Trying different child parenthesis matches:

    class\('[^']*'(?=[^(']*('[^']*'[^'(]*)*\))\)

Only matches:

    class('text-xs text-red-600')
    
Trying to get more complex:

    class\((?<=\()(?:'[^']*'|[,\s]+|\d+)+(?=\))\)
    
Still, I only get the simpler match.

I feel I am getting closer with this:

    class\((?<=\().*(?=\))\)

Which matched:

    class(($this->error('name') ? 'border-red-500' : 'border-gray-300') . ' rounded-lg w-full')
    class('text-xs text-red-600'))

However, I still need to have it match the quoted strings inside, not the entire thing.

Is this possible with regex? I just want to obtain all of the single or double quoted strings inside of the `class()` method, even if it has nested parenthesis.

**Comment by bradlc** [comment]
Tricky one for sure! If you are happy that the last expression you mentioned captures the entire `class()` then you can use an array inside the `classRegex` setting:

```
"tailwindCSS.experimental.classRegex": [
  ["class\\(((?<=\\().*(?=\\)))\\)", "'([^']*)'"]
],
```

It's kind of like an outer match and an inner match. So like you said the first regex will match something like `class(($this->error('name') ? 'border-red-500' : 'border-gray-300') . ' rounded-lg w-full')`, then the inner match runs against that and will match all the strings.

**Comment by bradlc** [comment]
Going to close this but hopefully that helped, and let me know if you're still having issues 👍
