### ISSUE TITLE
Autocomplete doesn't work in some instances

### ISSUE THREAD

**Issue by dspacejs** [tailwindlabs/tailwindcss-intellisense#273]
See the following GIFs to see when it does and doesn't work:

![tailwind autocomplete](https://user-images.githubusercontent.com/9282837/109452276-5044b180-7a9f-11eb-9a1e-11327fc604b2.gif)
![tailwind autocomplete 2](https://user-images.githubusercontent.com/9282837/109452281-520e7500-7a9f-11eb-91b7-9a7506649b94.gif)

**Comment by bradlc** [comment]
Hey @dspacejs. Take a look at the ["Recommended VS Code Settings" section of our readme](https://github.com/tailwindlabs/tailwindcss-intellisense#recommended-vs-code-settings). The solution is to set the `editor.quickSuggestions.strings` setting to `true` 👍

**Comment by dspacejs** [comment]
@bradlc thanks, this worked. I didn't realise that existed, perhaps the description in the README can be a bit clearer? 

> By default VS Code will not trigger completions when editing "string" content, for example within JSX attribute values.

It was triggering completions for JSX attributes, it just only did it in some instances. So this isn't clear to users.

Additionally, if possible I think this setting should be enabled by default. I can't think of any reason users wouldn't want this to be activated by default, that'd be an exception if anything.
