### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by ElArtista** [tailwindlabs/tailwindcss-intellisense#274]
First of all providing some build instructions would be really appreciated.

Tried to clone and build the `tailwindcss-intellisense` module with:
```
npm install
cd packages/tailwindcss-intellisense/
npm run build
```

And I'm getting:
```
Error: [tsl] ERROR in /code/tailwindcss-intellisense/packages/tailwindcss-intellisense/src/lsp/server.ts(57,3)
      TS2741: Property 'showPixelValues' is missing in type '{ classRegex: undefined[]; }' but required in type '{ classRegex: string[]; showPixelValues: boolean; }'.
```

Seems that its trying to build using tailwindcss-language-service 0.0.12 and not the local version of the package

**Comment by bradlc** [comment]
Closing this because it is outdated now. Build should work with `npm run build` 👍
