### ISSUE TITLE
Feature Request: Show Autocomplete While Typing

### ISSUE THREAD

**Issue by mikebronner** [tailwindlabs/tailwindcss-intellisense#275]
Currently I am only able to get Tailwind Autocomplete to show up if I type a space and wait for the autocomplete dropdown to appear. If I start typing a tailwind class name, the autocomplete never shows up.

The other autocomplete providers do not behave this way, but instead show possible matches based on what you type as you are typing. This lets me type until my target item is at the top, then press tab to autocomplete. Currently I cannot do this using Tailwind Autocomplete.

This is one of my core VSCode plugins, thanks your all the hard work! :)

(I did got through all the settings recommendations here: https://github.com/tailwindlabs/tailwindcss-intellisense#recommended-vs-code-settings, but still can only get the autocomplete to show up if I hit space first.)

**Comment by bradlc** [comment]
Hey @mikebronner. Setting `editor.quickSuggestions.strings` to `true` is usually the fix for this 🤔 Please can you share a screen recording of what works and what doesn't, similar to #273? That usually helps to spot what the issue might be.

**Comment by bradlc** [comment]
Going to close this but please open a new issue if you're still having problems 👍

**Comment by mikebronner** [comment]
Hi @bradlc, sorry for going silent on you. I believe I implemented your suggestion, but it didn't quite alleviate the problem. I have since moved to the Nova editor, and the plugin there behaves as expected. Thanks! :)

**Comment by Sylk** [comment]
> Hey @mikebronner. Setting `editor.quickSuggestions.strings` to `true` is usually the fix for this 🤔 Please can you share a screen recording of what works and what doesn't, similar to #273? That usually helps to spot what the issue might be.

This fixed the issue that I was having. Thank you.
