### ISSUE TITLE
`space-x-2` doesn't show values when hover like `pb-4` does

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/tailwindcss-intellisense#276]
On hover, `pb-4` looks like:

![pb-4](https://user-images.githubusercontent.com/16436270/111069548-95cb9a80-84f3-11eb-910d-1aeedf1764ee.png)

However, `space-x-2` shows nothing. Would love it if it showed values as well :)

**Comment by bradlc** [comment]
Hey @deadcoder0904. `space` classes now have hovers when using recent versions of Tailwind. I'm going to close this as it's unlikely we will be back-porting this for older versions.
