### ISSUE TITLE
Clarify docs for getting tailwind config file

### ISSUE THREAD

**Issue by nrgnrg** [tailwindlabs/tailwindcss-intellisense#278]
In more custom setups the tailwind config file might not be in the project root or might be named differently to `tailwind.js` or `tailwind.config.js`.

Tailwind supports these setups by specifying the config file in `postcss.config.js`

for example

```
module.exports = {
  plugins: {
    tailwindcss: { config: "./tailwind.config.cjs" },
    autoprefixer: {},
  },
};
```

It would be good if this plugin could scan `postcss.config.js` and if the tailwind file is defined there use that.

**Comment by nrgnrg** [comment]
This actually appears to work so perhaps a clarification in the docs is needed?

**Comment by bradlc** [comment]
Yep `tailwind.config.cjs` is supported! Added a clarification to the readme, thanks!
