### ISSUE TITLE
Request: Atom.io support

### ISSUE THREAD

**Issue by yeldarby** [tailwindlabs/tailwindcss-intellisense#279]
Would love to get support for [Atom](https://atom.io) in addition to VS Code.

**Comment by bradlc** [comment]
Hey @yeldarby. Thanks for the suggestion! I don't think it's likely that we would ever support an official Atom version of the extension, but at some point I do want to provide a language server based on the language server protocol, which can then be used to power Tailwind support in other editors. You can follow #188 for that 👍
