### ISSUE TITLE
Support for windmill-react-ui

### ISSUE THREAD

**Issue by dhatGuy** [tailwindlabs/tailwindcss-intellisense#280]
The first time I used tailwindcss-IntelliSense, it worked as expected.

There's a new project I'm working on using a react UI library, [windmill-react-ui](https://github.com/estevanmaito/windmill-react-ui). I found out the extension doesn't work with the library. 
The error output
`Failed to initialise: TypeError: value.charCodeAt is not a function`

Is there any way to fix this?

**Comment by bradlc** [comment]
Hey @dhatGuy. Are you able to share a repository which reproduces the issue?

**Comment by dhatGuy** [comment]
[https://github.com/dhatGuy/PERN-Store/tree/main/client](https://github.com/dhatGuy/PERN-Store/tree/main/client)

**Comment by bradlc** [comment]
I think the root issue here is that `windmill-react-ui` uses `@tailwindcss/custom-forms`, which only supports `tailwindcss` v1, but you are using v2. I'm not sure why the `tailwindcss` CLI works, because using PostCSS CLI directly throws the same error you are seeing in VS Code.
