### ISSUE TITLE
TailwindCSS Intellisense is not working

### ISSUE THREAD

**Issue by benninkcorien** [tailwindlabs/tailwindcss-intellisense#283]
VS Code 1.54.3

I have tailwindcss installed via pnpm (globally)
I have tailwind.config.js in my workspace/project root. "pnpm run build" works with these settings.
tailwindcss intellisense is enabled globally

VSCode settings.json has

`
"tailwindCSS.emmetCompletions": true,

"tailwindCSS.includeLanguages": { "plaintext": "html" },

"tailwindCSS.colorDecorators": "on",
`

I've reinstalled VS Code, I've restarted my PC/VS Code a few times.
Absolutely nothing happens when I hover over any tailwindcss classes in my html file, or start typing them.

**Comment by benninkcorien** [comment]
Update - completely uninstalled VS Code and settings/preferences/custom keybinding etc. 
Then reinstalled it and only installed TailwindCSS Intellisense, in case it was a conflict with another extension or setting.

VS Code About:

Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042


In Tailwind CSS Intellisense settings I turned on  "Enable Emmett completions".

It's still not working, it seems to do nothing at all.

My settings.json now only has :

 
    "tailwindCSS.emmetCompletions": true,

    "editor.quickSuggestions": {"strings": true},

    "tailwindCSS.includeLanguages": {"plaintext": "html"},

    "tailwindCSS.colorDecorators": "on"

**Comment by misha** [comment]
You can debug this yourself by looking at the `tailwindcss-intellisense` extension log inside of VSCode. In the pane usually at the bottom with the terminal, etc. select "Output", then the extension from the select on the right.

If your configuration is incorrect, it'll tell you how/when it failed.

**Comment by benninkcorien** [comment]
Thank you! Didn't know that. Very useful.

I was using pnpm as my package manager and apparently that's not supported. 
Switched to yarn and everything is working now.
