### ISSUE TITLE
Not working on files .jsx

### ISSUE THREAD

**Issue by karens1494** [tailwindlabs/tailwindcss-intellisense#288]
I am trying to use autocomplete on React .jsx files and it doesn't work

**Comment by mhdalmajid** [comment]
can you show us where you try to add the classes ?

normally add this  to vscode setting
```json 
  "tailwindCSS.colorDecorators": "on",
  "tailwindCSS.emmetCompletions": true,
  "tailwindCSS.includeLanguages": {
    "javascriptreact": "html",
    "typescriptreact": "html",
    "plaintext": "html"
  },
```

or you can go farther with regex

``` json
  "tailwindCSS.experimental.classRegex": [
    ["classnames\\(([^)]*)\\)", "'([^']*)'"],
    [":(?:.|\n)*?[\"'`]([^\"'`]*).*?,"],
    ["=(?:.|\n)*?[\"'`]([^\"'`]*).*?,"],
    "tw`([^`]*)"
  ],
```

**Comment by bradlc** [comment]
@karens1494 does it work in other file types? Do you see anything in the output (`Tailwind CSS: Show Output` command)?

**Comment by bradlc** [comment]
Please open a new issue if you're still having problems 👍
