### ISSUE TITLE
[Intellisense + JIT] Classes missing for some variants

### ISSUE THREAD

**Issue by pingustar** [tailwindlabs/tailwindcss-intellisense#289]
When using Tailwind-JIT and IntelliSense for VSCode I am missing a bunch of suggestions.

**For example when trying to add `dark:border-4` IntelliSense does not offer this option:**

<img width="700" alt="Screenshot 2021-03-31 at 11 27 19" src="https://user-images.githubusercontent.com/7262066/113122680-24d6f300-9214-11eb-84fc-63cff33c675b.png">

**but without dark variant it works as expected:**

<img width="664" alt="Screenshot 2021-03-31 at 11 27 01" src="https://user-images.githubusercontent.com/7262066/113122689-26a0b680-9214-11eb-9719-2733d75144c9.png">

another example is, `md:border-4` works.

But `focus:border-4` does not work.

**Comment by estephinson** [comment]
My guess is this is caused by lack of general JIT support?

If you added the `dark` variants my guess is this would work properly.

**Comment by autumnblazey** [comment]
no idea how jit works internally and not sure how this extension works, but I think its reading the tailwind config file and then applying the default enabled variants. 

maybe what it should do is also read the postcss config file and see if jit is enabled, then enable everything?

**Comment by xiaoyu-tamu** [comment]
my workaround is to create another config for build. https://tailwindcss.com/docs/configuration#using-a-different-file-name


```
// postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: { config: "./tailwind.config.prod.js" },
  },
};

// tailwind.config.js
module.exports = {
  purge: ["./src/**/*.{jsx,tsx}"],
  plugins: [require("@tailwindcss/forms")],
};

// tailwind.config.prod.js
module.exports = {
  mode: "jit",
  purge: ["./src/**/*.{jsx,tsx}"],
  plugins: [require("@tailwindcss/forms")],
};
```

**Comment by sachaw** [comment]
Mine too is broken, It's only showing the default enabled variants, I'm running tailwind `2.1.1` and plugin `0.5.10` and have reloaded my IDE multiple times

**Comment by pingustar** [comment]
@bradlc any news on this? Can you confirm that this is a general problem? Is this something thats being worked on or going to stay this way?

I upgraded Tailwind to `2.1.1 `and Intellisense is on `0.5.10`

**Comment by bradlc** [comment]
@pingustar Hey! Yep this is a known issue, Tailwind CSS IntelliSense doesn't support JIT mode currently. I am working on it though and hoping to get something out in the next couple weeks 👀

**Comment by bradlc** [comment]
JIT mode is fully supported in `v0.6.0` 🤙
