### ISSUE TITLE
sveltekit + tailwind: semicolon or block is expected error when using variant in @apply

### ISSUE THREAD

**Issue by kavaro** [tailwindlabs/tailwindcss-intellisense#290]
When using a variant (e.g. hover:bg-red-500) inside @apply result in  semicolon or block is expected error.

To reproduce:

```bash
npm init svelte@next
npx svelte-add tailwindcss --jit
npm install
```

Open src/routes/index.svelte and add a style with variant inside @apply (see below):

```svelte
<script lang="ts">
	import Counter from '$lib/Counter.svelte';
</script>

<main>
	<h1>Hello world!</h1>

	<Counter />

	<p>Visit <a class="text-blue-600 underline" href="https://svelte.dev">svelte.dev</a> to learn how to build Svelte apps.</p>
</main>

<style style lang="postcss">
	main {
		@apply text-center;
		@apply p-4;
		@apply mx-auto;
	}

	h1 {
		@apply text-red-600;
		@apply uppercase;
		@apply text-6xl;
		@apply font-thin;
		@apply leading-tight;
		@apply my-16 mx-auto;
		@apply max-w-xs;
                 /* ADD THESE 2 LINES */
                 @apply hover:bg-red-500;
                 @apply hover:text-white;
	}

	p {
		@apply max-w-xs;
		@apply my-8 mx-auto;
		@apply leading-snug;
	}

	@screen sm {
		h1 {
			@apply max-w-none;
		}

		p {
			@apply max-w-none;
		}
	}
</style>

```

The svelte project works as expected, including the variant classes, but VSC will report semicolon or block expected
for the first variant used in an @apply statement.

I am using the latest version of tailwindcss-intellisense (0.5.9) with VSC Version: 1.54.3 on OSX.
Other enabled plugins: 
- postcss language support
- svelte for vscode
- vscode styled jsx
- yaml

**Comment by BibbyChung** [comment]
try to set up vscode setting to solve this problem.

```
svelte.plugin.css.diagnostics.enable: false 
```

**Comment by bradlc** [comment]
This error is not generated by Tailwind CSS IntelliSense and @BibbyChung's solution should work 👍
