### ISSUE TITLE
tailwindcss-intellisense not working correctly with sveltekit

### ISSUE THREAD

**Issue by Yiak** [tailwindlabs/tailwindcss-intellisense#291]
### 1. Auto suggestions don’t show up at all.
I have tried everything mentioned in #151 & #252 and still no luck.
I tried both on pc and mac and none of them worked properly.

My VSCode version info on PC and mac:
> Version: 1.55.0 (user setup)
> Commit: c185983a683d14c396952dd432459097bc7f757f
> Date: 2021-03-30T16:01:55.261Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19042

>Version: 1.55.0
>Commit: c185983a683d14c396952dd432459097bc7f757f
>Date: 2021-03-30T16:01:05.981Z
>Electron: 11.3.0
>Chrome: 87.0.4280.141
>Node.js: 12.18.3
>V8: 8.7.220.31-electron.0
>OS: Darwin x64 20.3.0

### 2. `@apply` in the comment will cause the highlighting to be inaccurate.
eg:
Before:
![1](https://user-images.githubusercontent.com/25087436/113268012-875deb00-9309-11eb-8890-87ef7c25a39b.png)
After:
![2](https://user-images.githubusercontent.com/25087436/113268040-8e84f900-9309-11eb-83fc-f98815261eee.png)

### To reproduce:
1. Disable all VSCode extensions except [Svelte for VS Code](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) and [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss)
2. Run followings in an empty directory:
``` 
npm init svelte@next
npx svelte-add tailwindcss --jit
npm install 
```

**Comment by MstrBlonde** [comment]
I'm guessing this may be caused by the absence of a **tailwind.config.js** or **tailwind.js** file, which according to the readme is required for the intellisense to work. The svelte-add package creates a tailwind.config.**cjs** file.

**Comment by Yiak** [comment]
> I'm guessing this may be caused by the absence of a **tailwind.config.js** or **tailwind.js** file, which according to the readme is required for the intellisense to work. The svelte-add package creates a tailwind.config.**cjs** file.

@MstrBlonde Thank you for your help.  According to #198 , the extension should accept cjs file since version 0.5.5 …

**Comment by MstrBlonde** [comment]
I just happened to notice a new version of the plugin was pushed yesterday, and now I've got working intellisense in my SvelteKit project! Hopefully it works for you as well. Good luck!

**Comment by jescowuester** [comment]
for me it's the other way around, 0.5.10 breaks it completely while 0.5.9 works fine

**Comment by bradlc** [comment]
Hey @Yiak. I can't reproduce the issue 🤔 Are you seeing anything in the output panel? You can view this using the `Tailwind CSS: Show Output` command.

**Comment by Yiak** [comment]
@bradlc Thank you for the command. Here's the output:
```
[Error - 7:45:22 PM] Tailwind CSS: Can't resolve 'tailwindcss' in 'c:\Users\xxx\Documents\tailwind'
Error
    at new g (c:\Users\xxx\.vscode\extensions\bradlc.vscode-tailwindcss-0.6.13\dist\server\tailwindServer.js:56:279180)
    at c:\Users\xxx\.vscode\extensions\bradlc.vscode-tailwindcss-0.6.13\dist\server\tailwindServer.js:56:346192
    at Generator.next (<anonymous>)
    at o (c:\Users\xxx\.vscode\extensions\bradlc.vscode-tailwindcss-0.6.13\dist\server\tailwindServer.js:56:339494)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
And I have uploaded a svelte-kit+tailwindcss sample [here](https://github.com/Yiak/tailwind), just in case you wanna have a look.

**Comment by JonathanLafey** [comment]
Adding the [windicss](https://windicss.org/editors/vscode.html) plugin provides all the necessary tailwind intellisense (at least that I used) without the need to install the actual windicss package.

This should be regarded as a temporary workaround though.

**Comment by bradlc** [comment]
@Yiak Is this still an issue with the latest version of the extension (`v0.7.6`)?

**Comment by Yiak** [comment]
@bradlc Everything looks good with the latest version of extension. Thank you for your effort.
