### ISSUE TITLE
Not working on MacBook Air

### ISSUE THREAD

**Issue by eugenevk** [tailwindlabs/tailwindcss-intellisense#292]
I have VS Code and TailwindCSS IntelliSense installed. On my Windows laptop it works fine, but on my MacBook Air it doesn't. The available classes are not shown when you start typing. Please help.

**Comment by bradlc** [comment]
Take a look at the [Troubleshooting](https://github.com/tailwindlabs/tailwindcss-intellisense#troubleshooting) section of the readme. If that doesn't help take a look at VS Code's `Output` panel and select `Tailwind CSS IntelliSense` – can you see any errors in there?

![image](https://user-images.githubusercontent.com/2615508/115012588-e98d2300-9ea7-11eb-89a3-ec724b7885f2.png)

**Comment by eugenevk** [comment]
It kind of works all of a sudden, i.e. I sometimes need to press Ctrl-Space to force a search for available Tailwind classes. But sometimes it seems to work correctly. No error were in the output window. Consider issue closed for now.
