### ISSUE TITLE
Missing utilities from `2.1.0`

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [tailwindlabs/tailwindcss-intellisense#294]
I miss some utilities like `filter` or `blur`at the VSCode Intellisense. Will they get supported in the future?

**Comment by pingustar** [comment]
Probably related to #289

**Comment by bradlc** [comment]
Those classes should definitely be showing up. Did you upgrade to `2.1.0` while you had VS Code open? You may need to reload VS Code if that's the case.

**Comment by HAUDRAUFHAUN** [comment]
Works since the update
