### ISSUE TITLE
Support Intellisense for Vite TailwindCSS Config

### ISSUE THREAD

**Issue by VladimirMikulic** [tailwindlabs/tailwindcss-intellisense#295]
Hi,

Thank you for this amazing extension.
Currently, it seems to work only if it encounters TailwindCSS config file in the project. (`tailwind.config.js`)

However, I am using Vite's central configuration file (`vite.config.js`) for configuring everything. (PostCSS, TailwindCSS etc.)

Here's how it looks like:

```js
export default {
  root: "src",
  build: {
    outDir: "../dist",
    emptyOutDir: true,
  },
  server: {
    open: true,
  },
  css: {
    postcss: {
      plugins: [
        require("tailwindcss")({
          purge: ["./src/**/*.html"],
          darkMode: false, // or 'media' or 'class'
          theme: {
            container: {
              screens: {
                "2xl": "1280px",
              },
            },
            extend: {},
          },
          variants: {
            extend: {},
          },
          plugins: [],
        }),
        require("autoprefixer"),
      ],
    },
  },
};
```

So, instead of looking for the TailwindCSS config file, maybe it would be better to look for `tailwindcss` package in package.json and then decide whether to provide autocomplete or not.

Thanks!

**Comment by shroudedcode** [comment]
> So, instead of looking for the TailwindCSS config file, maybe it would be better to look for tailwindcss package in package.json and then decide whether to provide autocomplete or not.

That only solves one problem (Tailwind not being detected in a project), but introduces the much bigger problem that the IntelliSense extension just no longer has access to the config, meaning that anything specified in there (like custom colors) can't be auto-completed anymore. The other option of extracting the Tailwind config from tool-specific config files like `vite.config.js` doesn't seem worth the complexity either.

What's preventing you from putting the Tailwind config into its own file? 🤔

**Comment by VladimirMikulic** [comment]
@shroudedcode that's true, it would need to extract a config from there. Nothing is preventing me from putting TailwindCSS config in a separate file, but I really dislike having 1000 config files, each for every single tool. (JS fatigue eh? :)

**Comment by shroudedcode** [comment]
> I really dislike having 1000 config files, each for every single tool. (JS fatigue eh? :)

Trust me, I get that sentiment, but think about the technical side: Extracting the Tailwind config from just the Vite config alone (which is only of many tool-specific config files that can contain a Tailwind config) is quite a difficult task as you have to:

- execute the entire file (since it's a `.js` file that can contain all sorts of expressions and conditions)
  - in a context that supports modern ES Modules (note the `export default` in the Vite config)
  - in a VS Code context (where you don't have full control of things like your Node.js version)
  - preferably in a separate process (as to not cause memory leaks through all the registered Vite plugins)
- extract the Tailwind config from the huge resulting config object

Is that really worth it? 😅

**Comment by VladimirMikulic** [comment]
Yeah, that would be required in order to have a full autocomplete - as you suggested, probably not worth it. Adding 1001 config file... :joy:

**Comment by zanminkian** [comment]
This issue is not solved. Please reopen it.
I have a suggestion. To enable this extension, we can require vite config file to export an `tailwindcssConfig`.
```js
import react from "@vitejs/plugin-react";
import autoprefixer from "autoprefixer";
import tailwindcss from "tailwindcss";
import { defineConfig } from "vite";

export const tailwindcssConfig = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
}

export default defineConfig({
  plugins: [react()],
  css: {
    postcss: {
      plugins: [
        tailwindcss(tailwindcssConfig),
        autoprefixer,
      ],
    },
  },
});

```
