### ISSUE TITLE
Feature request: add option to enable intellisense in JSX for all *ClassName props (e.g. containerClassName, buttonClassName, etc.)

### ISSUE THREAD

**Issue by electronic33** [tailwindlabs/tailwindcss-intellisense#298]
This would be very helpful for my custom components that accept such props.

If this is possible right now, then forgive me for my ignorance. :)

BTW, this extension is amazing, good job! :)

**Comment by bradlc** [comment]
Hey @electronic33. Thanks for the suggestion. Probably not going to add this as a default, but you may be able to use [the `experimental.classRegex` setting](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) to achieve this.
