### ISSUE TITLE
Class detection hover box shifted when using class regex

### ISSUE THREAD

**Issue by michaelschufi** [tailwindlabs/tailwindcss-intellisense#299]
Hi

I'm using the following class regex setting:
```json
"tailwindCSS.experimental.classRegex": [
    ":(?:\\s)*?[\"'`]([^\"'`]*).*?,",
  ],
```
Which matches everything inside the single quotes as you can see in the screenshot below.
![image](https://user-images.githubusercontent.com/2805598/114838891-71eec380-9dd5-11eb-89d1-4fba72fe471c.png)

Unfortunately, if the string literal starts on the new line the class detection hover box is shifted to the left:
![image](https://user-images.githubusercontent.com/2805598/114838418-fe4cb680-9dd4-11eb-9ea8-5e593ba0fd70.png)

This makes it very hard to read. Additionally, the autocomplete isn't working anymore, because of the offset:

Not OK:
![image](https://user-images.githubusercontent.com/2805598/114838721-466bd900-9dd5-11eb-9ca6-ab26f59ba92c.png)

OK:
![image](https://user-images.githubusercontent.com/2805598/114838621-289e7400-9dd5-11eb-9716-f711d17e5a99.png)

**Comment by bradlc** [comment]
Hey @michaelschufi. This looks like a bug relating to non-capturing groups. In your specific case the non-capturing group is redundant so you can remove it to fix the issue:

```
"tailwindCSS.experimental.classRegex": [
  ":\\s*?[\"'`]([^\"'`]*).*?,",
],
```

**Comment by michaelschufi** [comment]
Oh, thank you @bradlc! This works well. :D 

That's a good hint/workaround for simple regexps. But I remember needing the capturing group for some more complex regex, which I replaced in the meantime and forgot to remove the capturing group.

**Comment by bradlc** [comment]
I've looked into this some more and it seems like it's definitely an issue with the `multi-regexp2` library, related to using quantifiers with capture groups. For example the pattern `(\s)*` would cause an issue, whereas `(\s*)` would not. As this is an upstream issue, and an edge case, _and_ there is a workaround, it's not likely that we will be pursuing a solution and I'm going to close this issue. I hope that's understandable!
