### ISSUE TITLE
Reverse color lookup (hex to utility class name)

### ISSUE THREAD

**Issue by tordans** [tailwindlabs/tailwindcss-intellisense#300]
It would be great if intellisense could show me the corresponding tailwind color name like "green-500" when hovering a hex value.

This has two usecases:
- In situations where the hex value is used for whatever reason it is an super fast way to validate it matches a given tailwind config color
- In situations where hex values are delivered and I want to replace them with the right tailwind color class name, this saves quite a few clicks

**Comment by bradlc** [comment]
Hey @tordans. Cool idea but I don't think the case for adding this is strong enough unfortunately. Thank you for the suggestion though! 🙏
