### ISSUE TITLE
What is the expeced response for the tailwindcss/getConfiguration request?

### ISSUE THREAD

**Issue by predragnikolic** [tailwindlabs/tailwindcss-intellisense#301]
First of all, nice work!

Second,
I am using the [LSP-tailwindcss](https://github.com/sublimelsp/LSP-tailwindcss) plugin for Sublime Text,
which internally uses this language server.

When the LSP client sends the completion request to the tailwindcss server.
```
:: --> LSP-tailwindcss textDocument/completion(6): {'textDocument': {'uri': 'file:///home/predrag/Documents/sandbox/my-vue-app/src/index.css'}, 'position': {'line': 5, 'character': 0}}
```
the server never responds for the completion items request,
instead it send back a `tailwindcss/getConfiguration` request to the client:

```
:: <?  LSP-tailwindcss tailwindcss/getConfiguration: {'languageId': 'css', '_id': '2cc8994716988609ba4bc3a14d94b086'}
```
### Question:
How should a LSP client respond to the `tailwindcss/getConfiguration` request? (as I believe once the client responds back to the server for the `tailwindcss/getConfiguration`, the server would reply to the completion item request). 

Thanks!

EDIT: 
I tried to enable tracing of the sever in VS Code, to see how the client responds back to the server, but I do not see a setting to enable logging of the server.

**Comment by ElArtista** [comment]
Relevant: https://github.com/prabirshrestha/vim-lsp/issues/1136

**Comment by bradlc** [comment]
Hey @predragnikolic. I just discovered LSP-tailwindcss this week, great work! 👏 As you have noticed by now this request isn't used anymore. Please let me know if you run into any other issues with the language server. I am working on publishing the standalone server to npm which will hopefully make it easier for you to integrate it into LSP-tailwindcss.

**Comment by predragnikolic** [comment]
Thanks, but I definitely can't take all the credit. :)

> I am working on publishing the standalone server to npm which will hopefully make it easier for you to integrate it into LSP-tailwindcss.

That sounds like great news!
That would definitely ease the maintenance of the LSP-tailwindcss repo
