### ISSUE TITLE
Extension not working at all in one project

### ISSUE THREAD

**Issue by jonlambert** [tailwindlabs/tailwindcss-intellisense#304]
I've added this extension to my installation of VS Code. `tailwindcss` is installed and a valid `tailwind.config.js` is in the root of the project. Opening a `.tsx` file and typing `className="...` results in no suggestions. 

Oddly, this does work in another React Native project.

Are there any tools, logs or debug commands I can use to find out why it's not working? Some sort of debug command or, frankly, _anything_ would be better than cryptically not autocompleting.

**Comment by bradlc** [comment]
Is there anything in VS Code's `Output` panel if you select "Tailwind CSS IntelliSense" from the dropdown?

![image](https://user-images.githubusercontent.com/2615508/115224567-ecd11a80-a104-11eb-9d9e-1252f75afb89.png)

Or if you can provide a repository that reproduces the issue I would be happy to take a look.

**Comment by jonlambert** [comment]
Perfect, thanks. I didn't even think to check there. 🤦‍♂️

Turns out I had a PostCSS config file present, but the package wasn't installed.
