### ISSUE TITLE
show hex in color preview

### ISSUE THREAD

**Issue by jedy05097952** [tailwindlabs/tailwindcss-intellisense#305]
Hi

Is it possible to show hex in color preview like showcase image in read.me?

<img width="864" alt="截圖 2021-04-23 上午10 24 56" src="https://user-images.githubusercontent.com/50637947/115809736-3e3c1b00-a41f-11eb-800c-ed4917c0089f.png">

this is my preview, thanks!
<img width="478" alt="截圖 2021-04-23 上午10 07 36" src="https://user-images.githubusercontent.com/50637947/115809778-51e78180-a41f-11eb-80fd-6858720fd0b2.png">

**Comment by bradlc** [comment]
Hey @jedy05097952. The hover previews show the exact CSS associated with the class. In the example image the hex is displayed because that's what the CSS output used to look like for text color classes. Since the output no longer contains the fallback hex value it isn't shown.
