### ISSUE TITLE
Is there a way to make it work without node_modules?

### ISSUE THREAD

**Issue by WilsonNet** [tailwindlabs/tailwindcss-intellisense#307]
Sometimes I just want to create a simple HTML file and play around, I don't wanna have some huge node_modules folder, but the extensions don't work this way, I get this error:

`Error: Cannot find module 'tailwindcss/package.json`

The docs say that I need a tailwind.config.js file to make it work, but I have one created by the tailwindcss-cli.

**Comment by bradlc** [comment]
Not currently, no, but I am considering adding something like this. Going to close this as a duplicate of #27.
