### ISSUE TITLE
Not showing css errors? Is it meant to?

### ISSUE THREAD

**Issue by sunscreem** [tailwindlabs/tailwindcss-intellisense#308]
Plug is working great, except it doesn't highlight css errors:

Is it meant to? 

![image](https://user-images.githubusercontent.com/7523595/115962427-407fa180-a513-11eb-9127-b682d1d4d154.png)

I should be seeing an error there?

**Comment by bradlc** [comment]
This extension does not provide anything like that. VS Code has built-in CSS validation, but this can show errors when using `@apply`, so it's common to disable that when using Tailwind. Another option is to use something like [stylelint](https://stylelint.io/)
