### ISSUE TITLE
Tailwind CSS: variantsValue is not iterable

### ISSUE THREAD

**Issue by nashabibah** [tailwindlabs/tailwindcss-intellisense#309]
I am getting false notifications while using backgroundBlendMode variant in tailwind.config.js
background-bend-mode added in tailwindcss@2.1.0

![2021-04-25_144750](https://user-images.githubusercontent.com/33183574/115987285-44282c80-a5d6-11eb-952b-d8a515c9db89.png)

**Comment by bradlc** [comment]
Are you able to share a repository which reproduces the issue @nashabibah? Or if not, just the contents of the Tailwind config file?

**Comment by bradlc** [comment]
@thalesagapito Thanks for that! Your issue should be fixed in `v0.6.2` of the extension 👍

@nashabibah Please could you check whether your issue is resolved in `v0.6.2`?

**Comment by nashabibah** [comment]
@bradlc Thank you. I am not getting that false notification.

**Comment by dasDaniel** [comment]
Can this issue be re-opened?
