### ISSUE TITLE
"Ring Color" Colour Preview Not Showing

### ISSUE THREAD

**Issue by joeknex** [tailwindlabs/tailwindcss-intellisense#312]
Hi, As you can see, the "focus:ring-lightblue-700" is not showing the little square colour preview. This works for other "lightblue-700" classes just not this one.

![Problem](https://i.gyazo.com/d0b84d2ff75985bf23d8eb5501829756.png)

**Comment by bradlc** [comment]
Weird, can you share your Tailwind config please @joeknex?

**Comment by joeknex** [comment]
Thanks @bradlc

```
module.exports = {
    mode: "jit",
    purge: [
        "./node_modules/tippy.js/dist/tippy.css",
        "./routes/**/*.php",
        "./app/**/*.php",
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {},
        colors: {
            transparent: "transparent",
            current: "currentColor",

            lightblue: {
                100: "#e3f8ff",
                200: "#a7e5fb",
                300: "#6dd1f6",
                400: "#35c0f2",
                500: "#00aded",
                600: "#0195d4",
                700: "#027dbb",
                800: "#0367a1",
                900: "#035388",
            },

            bhsdb: "#223160",
            bhsb: "#18557f",

            red: "#ff0000",
            orange: "#ffc000",
            green: "#00b050",
            purple: "#7030a0",

            black: "#000",
            white: "#fff",
        },
        borderWidth: {
            DEFAULT: "1px",
            0: "0",
            1: "1px",
            2: "2px",
            3: "3px",
            4: "4px",
            6: "6px",
            8: "8px",
        },
    },
    variants: {
        extend: {},
    },
    plugins: [require("@tailwindcss/forms")],
};
```

**Comment by bradlc** [comment]
Thanks! I can't reproduce this at all 🤔 Which version of `tailwindcss` and the Tailwind CSS IntelliSense extension are you using? If you are able to share your project repository that may help as well.

**Comment by joeknex** [comment]
Hi @bradlc I've made a fresh example app and it gives the same problem: https://github.com/joeknex/example-app

"Tailwind CSS IntelliSense" is v0.5.10
"Visual Studio Code" is v1.55.2

Steps followed:
composer install
npm install
npm run watch
Open: resources\views\demo.blade.php

![Image of Yaktocat](https://i.gyazo.com/592045099b5ff722ad5d12256e4a25e0.png)

**Comment by joeknex** [comment]
@bradlc v0.6.0 has resolved this problem
