### ISSUE TITLE
Feature request: add tailwindcss config path to the settings

### ISSUE THREAD

**Issue by kareljan** [tailwindlabs/tailwindcss-intellisense#314]
Is it possible to add the config path to the settings in VS code? 
I sometimes work on websites with more than one layout. So I have different tailwind.config.js files in my project. It would be nice if I can change the config file the intellisense uses if I work on a different part of the site. 

So a setting like "tailwindCSS.config" that I can set to "tailwind.config.projectA.js" or "tailwind.config.projectB.js" would be nice. And if the setting is not set, that it defaults to tailwind.config.js or tailwind.js

**Comment by bradlc** [comment]
Closing in favour of #218
