### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by jpmonteagudo** [tailwindlabs/tailwindcss-intellisense#318]
When I write it does not suggest anything to autocomplete.

I have reinstalled and nothing

**Comment by CarlosRGL** [comment]
same here. no suggestions or color preview in classes

**Comment by logemann** [comment]
Same for me after upgrading to tailwind v2.1+. I dont even know how webstorm should know which css classes exist when using JIT way things.

**Comment by IgnisDa** [comment]
Autocomplete does not work for me too. I am in VSCode.

OS: Inside an Ubuntu virtual machine
Version: tailwindcss 2.1.2
Extension version: v0.6.3

There is absolutely no output in the Output panel
![image](https://user-images.githubusercontent.com/60938164/117868197-f0e0fa00-b2b6-11eb-843a-5c328b6a3dff.png)

Config file:
```js
module.exports = {
  darkMode: 'class', // or 'media' or 'class'
  mode: 'jit',
  purge: {
    content: [
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.js',
      'nuxt.config.js',
    ],
  },
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [require('tailwindcss-debug-screens')],
}
```

**Comment by hjpotter92** [comment]
Same. Using emacs-lsp, the client logs the following:

```
Unhandled exception: Cannot read property 'configuration' of null
TypeError: Cannot read property 'configuration' of null
    at /home/hjpotter92/Documents/.files/.emacs.d/.cache/lsp/tailwindcss/extension/dist/server/index.js:54:342424
    at Generator.next (<anonymous>)
    at /home/hjpotter92/Documents/.files/.emacs.d/.cache/lsp/tailwindcss/extension/dist/server/index.js:54:341977
    at new Promise (<anonymous>)
    at En (/home/hjpotter92/Documents/.files/.emacs.d/.cache/lsp/tailwindcss/extension/dist/server/index.js:54:341722)
    at Pn (/home/hjpotter92/Documents/.files/.emacs.d/.cache/lsp/tailwindcss/extension/dist/server/index.js:54:342309)
    at Object.<anonymous> (/home/hjpotter92/Documents/.files/.emacs.d/.cache/lsp/tailwindcss/extension/dist/server/index.js:54:355674)
    at Generator.next (<anonymous>)
    at /home/hjpotter92/Documents/.files/.emacs.d/.cache/lsp/tailwindcss/extension/dist/server/index.js:54:341977
    at new Promise (<anonymous>)
```

The config file for project is:

```js
module.exports = {
  mode: 'jit',
  purge: ['./pages/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  darkMode: 'media',
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by polyzen** [comment]
When I upgraded to 0.6.x, this language server did not work with [vim-lsp](https://github.com/mattn/vim-lsp-settings/blob/932b66a098873f2dd8809b203765a8ecd5e6b1a6/settings/tailwindcss-intellisense.vim), but seems to work just as well as 0.5.10 did with [nvim-lsp](https://github.com/kabouzeid/nvim-lspinstall/blob/e5492bcd7c172e48fa4122416799e06d0c2b5444/lua/lspinstall/servers/tailwindcss.lua#L13).

**Comment by AdamT** [comment]
When I activate the plugin it will work for the first class I add but then stops working. Removing the plugin will allow autocomplete to work (without recommending tailwind classes of course). I think this is a new occurrence, perhaps related to the amount of classes involved. I have another project on another computer that's on tailwind older than 2.0 and autocomplete works fine. Looking at the plugins I see tailwind requires a "Reload Required" and given this issue I'll not being doing so until the issue is resolved this failing machine.

When the plugin is active with tailwind version 2.1.4 I see this:
![image](https://user-images.githubusercontent.com/641502/120915360-232b1f00-c6de-11eb-83ec-2d82186bf66c.png)

### Broken version
>Which operating system are you using?

macOS 10.14.6
>Which package manager are you using?

npm

>Which version of Tailwind?

2.1.4

>Which version of the extension?

v0.6.8

> Are there any errors in the Output panel? You can see this by running the Tailwind CSS: Show Output command from the command palette

Is this what you mean?

```
Found Tailwind CSS config file: /Users/me/development/apps/my_app/assets/tailwind.config.js
Loaded postcss v8.3.0: /Users/me/development/apps/my_app/assets/node_modules/postcss
Loaded tailwindcss v2.1.4: /Users/me/development/apps/my_app/assets/node_modules/tailwindcss
```

> What does your Tailwind config file look like?

```
const colors = require('tailwindcss/colors');

module.exports = {
  purge: {
    enabled: process.env.NODE_ENV === "production",
    content: [
      '../lib/my_app_web/templates/**/*.html.eex',
      './vue/**/*.vue',
      './vue/*.vue',
    ]
  },
  theme: {
    extend: {
      colors: {
        "purple-200": "#F2ECFF",
      },

      spacing: {
        "72": "18rem",
        "84": "21rem",
        "96": "24rem",
      },
    },
  },
  variants: {
    borderColor: ["group-hover", "hover"],
    backgroundColor: ["group-hover", "hover"],
  },
  plugins: [],
};
```

**Comment by ElArtista** [comment]
Using latest git version with vim-lsp I can confirm I get the same stack trace:
```
Unhandled exception: Cannot read property 'configuration' of undefined
TypeError: Cannot read property 'configuration' of undefined
    at /usr/bin/tailwindcss-language-server:57:397768
    at Generator.next (<anonymous>)
    at /usr/bin/tailwindcss-language-server:57:396654
    at new Promise (<anonymous>)
    at Et (/usr/bin/tailwindcss-language-server:57:396401)
    at createProjectService (/usr/bin/tailwindcss-language-server:57:397639)
    at TW.<anonymous> (/usr/bin/tailwindcss-language-server:57:414270)
    at Generator.next (<anonymous>)
    at /usr/bin/tailwindcss-language-server:57:396654
    at new Promise (<anonymous>)
```

**Comment by heidarKadkhoda** [comment]
Which operating system are you using?
    Windows 10
    
    Which package manager are you using?
    npm

    Which version of Tailwind?
    v2.2.7 

    Which version of the extension?
    v0.6.13 

    Are there any errors in the Output panel? You can see this by running the Tailwind CSS: Show Output command from the command palette
    
    This is what I see in Tailwind CSS Intellisense Output:
    
    [Error - 12:38:55] Tailwind CSS: Can't resolve 'tailwindcss' in 'c:\Users\UserName\Desktop\...'
    Error
    at new g (c:\Users\UserName\.vscode\extensions\bradlc.vscode-tailwindcss-0.6.13\dist\server\tailwindServer.js:56:279180)
    at c:\Users\UserName\.vscode\extensions\bradlc.vscode-tailwindcss-0.6.13\dist\server\tailwindServer.js:56:346192
    at Generator.next (<anonymous>)
    at o (c:\Users\UserName\.vscode\extensions\bradlc.vscode-tailwindcss-0.6.13\dist\server\tailwindServer.js:56:339494)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


    What does your Tailwind config file look like?

```javascript
module.exports = {
  mode: 'jit',
  purge: ['./*.html'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by bradlc** [comment]
@AdamT I wasn't able to reproduce this from the config alone, are you able to share your project's repository, or a minimal one that reproduces the issue?

**Comment by rajan-kz** [comment]
I am facing this error. I am using vite
![image](https://user-images.githubusercontent.com/39906424/140437230-1664cf2d-eaec-45c8-bc81-d7a32f3395c6.png)

**Comment by zackha** [comment]
If you are working with nuxt3, you can try this.

Add the following configuration to your `.vscode/settings.json file`, so that Tailwind directives have proper autocomplete, syntax highlighting, and linting:

```
"tailwindCSS.experimental.configFile": ".nuxt/tailwind.config.cjs"
"files.associations": {
    "*.css": "tailwindcss"
}
```

detailed: [link](https://tailwindcss.nuxt.dev/tailwind/editor-support)
