### ISSUE TITLE
Elixir's EEX templates only autocomplete in HTML looking areas

### ISSUE THREAD

**Issue by justgage** [tailwindlabs/tailwindcss-intellisense#323]
So in Elixir you have a templating language syntax that looks like this:
```eex
# Allows HTML, that works
<a href="#" class="bg-red-400">
  Works
</a>

# Allows for function style, which compiles to HTML
<%= link to: "#", class: "bg-red-400" do %>
  Doesn't Work
<% end %>
```

You can see the `class: ` will turn into `class=` after it's compiled, but I think this isn't triggering tailwindcss because it's not a `class=` place.

Here's a picture:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/164033/118002741-a033c600-b2e3-11eb-9c59-da61d0f84978.png">

## Settings I've changed

```
  "editor.quickSuggestions": {
    "strings": true
  },
  "tailwindCSS.includeLanguages": {
    "html": "html",
    "elixir": "html",
    "eex": "html",
    "html-eex": "html"
  },
  ```

**Comment by bradlc** [comment]
Hey @justgage. I am reluctant to add this as built-in functionality, but if you want completions in the second case you can get pretty far with the [experimental `classRegex` setting](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659):

```
{
  "tailwindCSS.experimental.classRegex": [
    "class:\\s*\"([^\"]*)\""
  ]
}
```

**Comment by justgage** [comment]
Awesome, that works @bradlc 👍🏻

**Comment by Vagab** [comment]
does anyone know how to also make it work with sigils? I.e.
```elixir
class: ~w(text-center flex-grow)
```
