### ISSUE TITLE
Since yesterday this plugin is trying (and failing) to "fix" my PHP files

### ISSUE THREAD

**Issue by vesper8** [tailwindlabs/tailwindcss-intellisense#328]
I don't know if this is because of a new update, but since yesterday whenever I edit and save a PHP file, with no CSS contained within.. I get a popup saying 

```
Saving myfile.php: Getting code actions from "Tailwind CSS Intellisense"
```

And then it just spins and spins and never ends.. and it blocks my save action too.. I have to click the cancel button and save again and only then does it save my file

I don't have this problem when saving js/vue/css files.. only php files

**Comment by bradlc** [comment]
Is this happening consistently @vesper8? Like if you reload VS Code and straight-away save a PHP file it hangs?

**Comment by vesper8** [comment]
Hrmm.. yesterday I was prompted to reload and update and it kept happening. But just now I quit VSCode completely and started it up again and so far it's not happening.

So I will close the issue for now and re-open and if happens again

**Comment by vesper8** [comment]
@bradlc There's definitely a problem.. this is happening constantly still.. quitting completely and re-opening, if anything, only makes the problem go away for a little bit.

This continues to be only a problem with saving php files, works fine on js/vue/css files

**Comment by iKlsR** [comment]
Can reproduce this. Consistently as well, it will happen in the middle of a session, can't say why. If I had to give any clues however it might be related to when you open a large file say a .lock or so and for whatever reason some code action plugin wants to run which will show a tooltip bottom right and the file won't be saved until it's done.

**Comment by bradlc** [comment]
🤔 Are either of you able to share your project's repository?

**Comment by vesper8** [comment]
I can't.. they are closed-source repos.. but it's happening on at least two now (The only two php repos I've been editing lately). They are both Laravel-based.

Is it possible to set a setting in tailwindcss-intellisense so that it will only try to apply its magic to certain file extensions? js/vue/css only for example?

**Comment by vesper8** [comment]
It was fixed for a while and just started happening again @bradlc 

Every time I save a php file it tries to apply some Tailwind Intellisense to it and makes everything slow =/

This is a straight php file with no html or css in it.

**Comment by bradlc** [comment]
Without a reproduction I'm going to have to close this issue. Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but I just know that without a reproduction this issue will stay open forever without any updates. If you're ever able to share a reproduction please open a new issue and I'd be happy to take a look 🙏

> _Is it possible to set a setting in tailwindcss-intellisense so that it will only try to apply its magic to certain file extensions? js/vue/css only for example?_

We now have the following settings:

- `tailwindCSS.hovers`
- `tailwindCSS.suggestions`
- `tailwindCSS.codeActions`
- `tailwindCSS.colorDecorators`
- `tailwindCSS.validate`

You can use these settings to disable IntelliSense features. For example you could disable code actions in PHP files:

```
"[php]": {
  "tailwindCSS.codeActions": false
}
```

Or only enable code actions in HTML files:

```
"tailwindCSS.codeActions": false,
"[html]": {
  "tailwindCSS.codeActions": true
}
```
