### ISSUE TITLE
When extension is enabled, it is locking folders

### ISSUE THREAD

**Issue by longtimedeveloper** [tailwindlabs/tailwindcss-intellisense#329]
I started using this extension and discovered that it is locking folders (probably using the file watcher, not sure) **that are excluded in the files.watcherExclude section.**

I have the `/public` and `/resources` folders excluded in both the vscode user and workspace settings.

I'm using Tailwindcss in my **Hugo project.**

Each time Hugo builds, it outputs the build to `/public` and some working files in `/resources`.  

In order to get a clean build, it is recommended that you delete the `/public` folder before building.

Unfortunately, this extension locks the `/public` folder, making it impossible to delete the folder.

Can you please honor the files.watcherExclude settings and not look in folders that are excluded, otherwise, I can't use this great extension.

After disabling the extension and reloading, the `/public` and `/resources` can be deleted normally.  

I'm on the latest vscode, using Tailwind CSS IntelliSense v0.6.3 

Thank you,

Karl

**Comment by longtimedeveloper** [comment]
I figured out a workaround for anyone running into this.

Instead of deleting the `/public` and `/resources` folders, let Hugo do it for you.

`hugo  --cleanDestinationDir`

The above will clean out the destination folder before beginning its rebuild.  Problem solved.

For production deployments I run:

`hugo --minify --cleanDestinationDir `

Hope this helps someone.

Best regards,

Karl

**Comment by biandtlp** [comment]
Hi all, same problem here, it seems that tailwind plugin lock the process:
![image](https://user-images.githubusercontent.com/79506705/119787068-197d0c80-bed1-11eb-9c10-ec02e1421580.png)

**Comment by bradlc** [comment]
Hey @longtimedeveloper. As of `v0.6.9` the extension uses VS Code's built-in file watcher so this should be resolved. This also means that the `files.watcherExclude` setting is respected 👍
