### ISSUE TITLE
Suggestions don't show value in px anymore (hovering does)

### ISSUE THREAD

**Issue by SergiArias** [tailwindlabs/tailwindcss-intellisense#332]
I'm seeing this function disappearing and reappearing in different versions. Now it only gives the value in rems and not the equivalence into px, which was quite convenient as the specs from designers come in px normally.
I downgraded to 0.5.10 and it works, but it doesn't in last version.

**Comment by bradlc** [comment]
Thanks for reporting! Fixed in `v0.6.6` 👍
