### ISSUE TITLE
Intellisense in React strings

### ISSUE THREAD

**Issue by Shahaed** [tailwindlabs/tailwindcss-intellisense#337]
What would be the difficulty of allowing auto complete / linting outside the `className` in jsx/tsx code?

For example: 
```jsx
export const Example= () => {
  return (
    <div className="block w-full border" > <! ––  intellisense works here ––>
    </div>
  );
};
```
to

```jsx
export const Example= () => {
  const myClass = "block w-full border" // get intellisense here 
  return (
    <div className={myClass} >
    </div>
  );
};
```

**Comment by michaelschufi** [comment]
I don't know the features planned for this extension.
But you can check out some regexes shared in #129 in the meantime.

**Comment by bradlc** [comment]
As @michaelschufi said, there's no plans to add anything like this as there's no way to know which arbitrary strings contain CSS classes. You can use the [`tailwindCSS.experimental.classRegex`](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) setting to enable support for this yourself though.
