### ISSUE TITLE
Per project config

### ISSUE THREAD

**Issue by davidwebca** [tailwindlabs/tailwindcss-intellisense#338]
Hi,

I'm sorry if this is evident, but I can't find any details. I'd like to be able to configure rootFontSize per project. Is there a config file syntax that I can include in the project's files itself to override some configs?

Thanks a lot!

**Comment by bradlc** [comment]
Hey @davidwebca. You can use VS Code's "workspace" settings: https://code.visualstudio.com/docs/getstarted/settings

**Comment by davidwebca** [comment]
Thank you!
