### ISSUE TITLE
Problem: The screen 'md' does not exist in your theme config.

### ISSUE THREAD

**Issue by arekuusa** [tailwindlabs/tailwindcss-intellisense#344]
Hello.
After the upgrade version (v 0.6.8) error message appears.
And couldn't show SCSS/CSS suggestions because of @screen
Works to carry out the project. We're fine. Why?

Previous version (v 0.6.3) - there were no message errors and show suggestions.

![● _main scss - pure design - Visual Studio Code](https://user-images.githubusercontent.com/3696127/120990347-1fa0a200-c789-11eb-9f3b-398ce1d704f2.jpg)

**Comment by arekuusa** [comment]
Hi, my starter project is working. There were no errors, but there are from tailwindcss-intellisense
I'll show you my scripts.
tailwind.config.js - http://joxi.ru/4Ak0RN1SoZpgEr
_breakpoint.js - http://joxi.ru/nAyLgW5SgK0Ll2

**Comment by arekuusa** [comment]
Why didn't anyone answer or correct?

**Comment by bradlc** [comment]
Thanks for sharing your code. The issue is occurring because your `screens` config (`theme.screens`) is an array, when it should be an object. The same goes for your `minWidth` and `maxWidth` config:

```diff
  const screen = [
    ['2xl', 1536], // desktop
    ['xl', 1280],
    ['lg', 1024], // laptop
    ['md', 768], // tablet
    ['sm', 640],
    ['xs', 480], // mobile
    ['last', 320]
  ]

  const padding = 10

- let screens = []
+ let screens = {}
  screen.forEach((element, index) => { screens['+'+element[0]] = {'max': (element[1]-1)+'px'}; })
  screen.forEach((element, index) => { screens['-'+element[0]] = element[1]+'px'; })

- let maxWidths = []
+ let maxWidths = {}
  screen.forEach((element, index) => { maxWidths[element[0]] = (element[1]-(padding*2))+'px'; })

- let minWidths = []
+ let minWidths = {}
  screen.forEach((element, index) => { minWidths[element[0]] = element[1]+'px'; })

  module.exports = {
    screens: screens,
    maxWidth: maxWidths,
    minWidth: minWidths,
    padding: {
      c: padding+'px'
    },
  }
```

**Comment by arekuusa** [comment]
Thanks. I corrected. No mistakes.
Again couldn't show SCSS / CSS suggestions because of @screen  http://joxi.ru/52aND3KuE1j5zA
Works to show SCSS / CSS suggestions without @screen  http://joxi.ru/823nXDws9Rvd1m

Waiting for an answer
