### ISSUE TITLE
Expose linter as a stylelint plugin or a standalone tool

### ISSUE THREAD

**Issue by AleksaC** [tailwindlabs/tailwindcss-intellisense#346]
Hi, thanks for all the work you've been putting into making this useful extension. 

I have a suggestion that would extend the benefits of a portion of the extension to the entire team by exposing the linter as a stylelint plugin or a standalone cli tool. This way it could be ran in CI and as a pre-commit hook.  This has the added benefit of actually enforcing the rules as linting errors can often go unnoticed in the editor. 

I'm not sure how much work would it take to do this but I'd be willing to help if there's anything I can do in a reasonable amount of time. Also I'm not too familiar with stylelint so it might not make sense to go for a plugin.

**Comment by driskull** [comment]
This would be awesome. We are looking at a way to lint our css files pre-commit and ensure proper tailwind variables are being used. So far, I haven't been able to find something that we could use for this.

**Comment by bradlc** [comment]
Thanks for the suggestion @AleksaC! As this is a feature request I'm going to close this issue in favour of this existing discussion over on the tailwindcss repo: https://github.com/tailwindlabs/tailwindcss/discussions/5698 – please feel free to add any thoughts you have over there 👍
