### ISSUE TITLE
Please add license file

### ISSUE THREAD

**Issue by polyzen** [tailwindlabs/tailwindcss-intellisense#347]
MIT licenses have to be distributed along with the project.

There's also this comment that points to a license file that's not there:
https://github.com/tailwindlabs/tailwindcss-intellisense/blob/898347c4cd518211b72497b7562b93e0eb380830/packages/vscode-tailwindcss/src/extension.ts#L1-L4

**Comment by bradlc** [comment]
Do you mean in the extension package (the `.vsix` file)?

**Comment by polyzen** [comment]
I mean the repo in general, but it should probably also be distributed with the extension.

**Comment by lockhartja** [comment]
+1

**Comment by polyzen** [comment]
License files have been added since.
