### ISSUE TITLE
Custom config path or support .ts extension

### ISSUE THREAD

**Issue by seahindeniz** [tailwindlabs/tailwindcss-intellisense#348]
Hi,

Is there a way to specify a custom config file name instead of `tailwind.config.js`.
For example, I don't like to have JS files in my project, so I use `tailwind.config.ts` with vanilla ES6 syntax just for shadowing the JS file extension. But in the meantime, I'm loosing intellisense feature of the extension. So in this case, I think having a config for specifying path is kind of needed.

Alternatively, these lines can have `ts` extension just to cover the issue.
https://github.com/tailwindlabs/tailwindcss-intellisense/blob/898347c4cd518211b72497b7562b93e0eb380830/packages/vscode-tailwindcss/src/extension.ts#L40
https://github.com/tailwindlabs/tailwindcss-intellisense/blob/6e092ddf334a1c1e81e15034902ccbedea1c7602/packages/tailwindcss-language-server/src/server.ts#L75

**Comment by bradlc** [comment]
Hey @seahindeniz. I am open to this idea but I am curious: how do you use the `tailwind.config.ts` file with Tailwind itself?

**Comment by seahindeniz** [comment]
Hmm, well, I'm using Webpack and for the css loader, I'm using `postcss-loader`. Under postcss options, I simply using `tailwindcss` as a plugin and I specify file path for config file like the following

```js
rules: [
  {
    test: /\.(?:s[ac]|c)ss$/,
    use: [
      MiniCssExtractPlugin.loader,
      { loader: 'css-loader', options: { importLoaders: 1 } },
      {
        loader: 'postcss-loader',
        options: {
          postcssOptions: {
            plugins: [
              'postcss-preset-env',
              ['tailwindcss', { config: './tailwind.config.ts' }],
              'autoprefixer',
            ],
          },
        },
      },
    ],
  },
],
```

For the config file, I simply using it like the following:
```js
// tailwind.config.ts

module.exports = {
  purge: ['**/src/**/*.{[tj]s?(x),html}'],
  darkMode: 'media',
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

I know, it's not ideal however, it a tricky solution for my case.

**Comment by DianaOlympos** [comment]
as a side note, i would really appreciate this feature too. I use tailwind but as part of an elixir/phoenix framework. This means that my tailwind config is in an `assets` directory, not at the root of my workspace. Being able to specify the place the config is in would enable me to use this, instead of having it crash all the time.

**Comment by ahuggins** [comment]
I saw in the docs:

> In order for the extension to activate you must have tailwindcss installed and a Tailwind config file named tailwind.config.js in your workspace.

And my situation is this... I have a React component library package that is used on multiple applications, so each individual application won't have a `tailwind.config.js` file...but I would love to be able to use the one from the library I made in the application.

I sort of was able to get this working with creating a tailwind.config.js file in the application with contents:

`module.exports = require('./node_modules/{your}/{package}/tailwind.config.js');`

As long as in the library you include the `tailwind.config.js` file in your npm build.

Then I had to install Tailwind and any extensions in the `devDependencies` in the application and was able to get autocomplete based on the library `tailwind.config.js`.

Posting this in case it helps anyone here if they are trying something similar...or maybe it's just helpful in some way.

**Comment by alvis** [comment]
@bradlc I have the same request! In my case, I am using tailwind with gatsby in typescript.
Gatsby doesn't have any `tailwind.config.js` in the build so the hack doesn't work. ._.

**Comment by doug-shontz** [comment]
+1 on this for me as well.  We use tailwind in a monorepo setup where the master tailwind.config is not at the "project" root level...it's at the workspace root level and we just reference that during the build and it works just fine.  But we get no intellisense because the tailwind config is in the "wrong place".  Being able to specify this at a VS Code workspace level would be amazing.

My suggestion would be to make the tailwind config a variable for the extension which, if not filled out, could default to the normal glob that it does...but could be specified.  That way it could be checked in as part of VSCode's settings.json file.

**Comment by megalithic** [comment]
> as a side note, i would really appreciate this feature too. I use tailwind but as part of an elixir/phoenix framework. This means that my tailwind config is in an `assets` directory, not at the root of my workspace. Being able to specify the place the config is in would enable me to use this, instead of having it crash all the time.

having this same issue -- same scenario in an elixir phoenix app.

**Comment by dgonzalezr** [comment]
When working with `.ts` files in Typescript projects we can include types, therefore the following becomes a valid use case of setting up the configuration file for TW:

![CleanShot 2021-11-15 at 14 53 41](https://user-images.githubusercontent.com/328492/141785443-c51c095c-8134-4b04-85f6-2283f022d2d9.png)

Or even further I could split the theme object and import then from different modules, like:

![CleanShot 2021-11-15 at 15 00 03](https://user-images.githubusercontent.com/328492/141786281-18686907-53a4-45b4-ad12-18749cbf4c1a.png)

The scenario above works perfectly in all gets compiled as expected, TW does not complain about it, it is just that we lose the autocompletion feature. So yes, supporting `.ts` configuration file is one step, but also validating it. In the case above the extension will fail with a message like:

![CleanShot 2021-11-15 at 14 50 51](https://user-images.githubusercontent.com/328492/141785341-22e0e694-07ff-4614-947a-b3a939c8eb89.png)

PS: I've tested the solution provided in the PO [here](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/348#issue-917203755) and compiled the extension as a `.vsix` installable, but it fails when using ES6 modules.

**Comment by megalithic** [comment]
@DianaOlympos did you ever get past this with your elixir phoenix project? you and i have a similar issue: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/421#issuecomment-985615681

**Comment by DianaOlympos** [comment]
@megalithic no i did not. Sadly.

**Comment by megalithic** [comment]
To be clear; tailwindcss-language-server is working in css files when used with the `@apply` directive; it's just not working properly for *.heex files.

**Comment by cmitjans-at-wiris** [comment]
Hello, is there any update on this issue? I'm also looking forward to be able to set my tailwindcss config in a .ts

**Comment by mjuniper** [comment]
I've just run into this too. Would be great if it would work with my tailwind.config.ts file.

**Comment by bradlc** [comment]
Hey all. `v0.8.3` is available now with a new `tailwindCSS.experimental.configFile` setting. You can use this setting to manually specify the Tailwind config file(s) that should be used to provide IntelliSense.

If your project has a single config file:

```
"tailwindCSS.experimental.configFile": ".config/tailwind.config.js"
```

If your project has multiple config files you can use an object where each key is a config file path and the value is a glob (or array of globs) representing the files where that config applies:

```
"tailwindCSS.experimental.configFile": {
  "themes/simple/tailwind.config.js": "themes/simple/**",
  "themes/neon/tailwind.config.js": "themes/neon/**"
}
```

If anyone has any feedback feel free to ping me in a [discussion](https://github.com/tailwindlabs/tailwindcss/discussions), and for bugs please open an issue on this repo 👍 

**_Please note that this setting is experimental and may be changed or removed at any time._**

**Comment by inoas** [comment]
@bradlc thank you so much!

**Comment by sgarcia-dev** [comment]
@bradlc thanks man, you're amazing!

**Comment by dgonzalezr** [comment]
@bradlc does this change support the `.ts` config file? Because I just tested it and I get no IntelliSense for Tailwind 😞

**Comment by bradlc** [comment]
> @bradlc does this change support the `.ts` config file?

Yes, as long as you don't have any TypeScript syntax in the file.

**Comment by dgonzalezr** [comment]
> > @bradlc does this change support the `.ts` config file?
> 
> Yes, as long as you don't have any TypeScript or ESM syntax in the file.

So basically, I cannot set my config in this way?

![CleanShot 2021-11-15 at 14 53 41](https://user-images.githubusercontent.com/328492/141785443-c51c095c-8134-4b04-85f6-2283f022d2d9.png)

or like:

![CleanShot 2021-11-15 at 15 00 03](https://user-images.githubusercontent.com/328492/141786281-18686907-53a4-45b4-ad12-18749cbf4c1a.png)

right? 🤔

**Comment by magoz** [comment]
Hi, does anybody know how or where to define `"tailwindCSS.experimental.configFile": ".config/tailwind.config.js"` if using Neovim?

I tried creating the `.vscode/settings.json` file, but it doesn't seem to be picked by the LSP in Neovim. Not sure how workspaces work in Neovim.

I have a monorepo using `Turborepo` and my tailwind config is in `packages/tailwind/tailwind.config.js`.

Thanks!

**Comment by EinfachHans** [comment]
@dgonzalezr did you found a solution? I don't see this as "resolved" if i can specify a `.ts` file in th enew config path option but it does not work if it contains typescript syntax, because: well that's the point^^

**Comment by dgonzalezr** [comment]
@EinfachHans Actually yes, it is working for me with [Tailwind CSS v3](https://tailwindcss.com/blog/tailwindcss-v3-3), you can [check this repo here](https://github.com/Endava/bee-q/blob/develop/tailwind.config.ts).

**Comment by khuezy** [comment]
If anyone else is having problems, this may help:
instead of creating a second `tailwind.config.ts` for a specific package, move the config over to the `postcss.config.js`'s `plugins.tailwindcss`.
