### ISSUE TITLE
nunjucks still not working as expected. should it?

### ISSUE THREAD

**Issue by stoqe** [tailwindlabs/tailwindcss-intellisense#349]
- love this extension , thank you
- this still doesn't seem to work for nunjucks
- should it?
- nunjucks is so gooooood

**Comment by bradlc** [comment]
Yeah it should work. Which nunjucks extension are you using? Does the extension work with other file types in the same project?

**Comment by bradlc** [comment]
Going to close this as it's been a while without a response. Please open a new issue if you're still having problems 👍
