### ISSUE TITLE
tailwind plug in error msg, lot of ressource used

### ISSUE THREAD

**Issue by vince93290** [tailwindlabs/tailwindcss-intellisense#353]
Hello

I would like to report a bug with the tailwind plug in for vs code.

When the plug-in is requested for different things such as suggestions or hover information ect ... the plug-in indicates error messages and the plug-in starts to use a lot of resources which makes your code unusable.

I am posting an animated gif that shows you the errors messages.

I don't know if there is an incompatibility with another plug in.

![Animation](https://user-images.githubusercontent.com/44445302/122665754-6b9c0f80-d1a9-11eb-92ed-61bfe0baf673.gif)

**Comment by bradlc** [comment]
Thanks for reporting! The error has been fixed in `v0.6.12` 👍
