### ISSUE TITLE
need to reload vsc for custom theme adjustments to be in auto-completion

### ISSUE THREAD

**Issue by akomm** [tailwindlabs/tailwindcss-intellisense#356]
Example `tailwind.config.js`
```js
module.exports = {
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './ui/**/*.{js,ts,jsx,tsx}'],
  darkMode: false,
  theme: {
    extend: {
      colors: {
        custom: '#f00'
      }
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

The plugin won't display color helper and auto-complete bg-custom until I run `> reload window`

**Comment by kpratik2015** [comment]
You can also do `> Developer: Restart Extension Host` for time being

**Comment by bradlc** [comment]
Hey @akomm. Are you able to provide a GitHub repository which reproduces the issue? Unfortunately without that it will be impossible to debug it, thanks!

**Comment by bradlc** [comment]
Going to close this as there aren't enough details to debug the issue. Please open a new issue (and answer the questions in the new issue template) if you're still experiencing problems.
