### ISSUE TITLE
What languages does tailwindcss-intellisense support?

### ISSUE THREAD

**Issue by predragnikolic** [tailwindlabs/tailwindcss-intellisense#360]
Hello,

Question, what languages does tailwindcss-intellisense support?
I discovered that it can run in js, jsx, ts, tsx, vue, html, laravel blade files, twig. 

But I don't know the full list of languages, can you please provide them? 
Also does tailwindcss-intellisense look at the languageId when starting the ls server?

**Comment by bradlc** [comment]
Hey @predragnikolic. The language IDs supported by default are all here: https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/tailwindcss-language-service/src/util/languages.ts

You can configure additional languages using [the `includeLanguages` setting](https://github.com/tailwindlabs/tailwindcss-intellisense#tailwindcssincludelanguages).

**Comment by predragnikolic** [comment]
Thanks!
