### ISSUE TITLE
class"" suggestions not working on VSCode Vue project

### ISSUE THREAD

**Issue by moracabanas** [tailwindlabs/tailwindcss-intellisense#366]
OS: Windows 10
Vscode: 1.58
Tailwind working on the project as utility classes are rendering on save.

Tailwind CSS IntelliSense Output:
```log
Found Tailwind CSS config file: c:\Users\<user>\Documents\Github\taskbox\tailwind.config.js
Loaded postcss v7.0.36: c:\Users\<user>\Documents\Github\taskbox\node_modules\postcss
Loaded tailwindcss v2.2.4: c:\Users\<user>\Documents\Github\taskbox\node_modules\tailwindcss
```

I used the reccomended `settings.json` as it follows: 
```js
{
      "css.validate": false,
      "editor.quickSuggestions": {
          "strings": true
      },
      "tailwindCSS.includeLanguages": {
          "plaintext": "html"
      },
}
```

I can't get it working consistently. It worked sometimes but for a genera rule, you must `Ctrl+Space` on `class=""` to open suggestions or write a utility class, then  the next will be suggested as you write.

Also `"css.validate": false` works when you save, but if you restart vscode linting over `@apply` directives are showing again

**Comment by ahuggins** [comment]
Are you working in html files only? If you are in JS files, you may need to update your `includeLanguages` definition?

**Comment by moracabanas** [comment]
I am working with Vue files, i tellisense is only triggered on classes from 2th class you type

**Comment by bradlc** [comment]
Hey @moracabanas. Can you record a video of the behaviour you are seeing? I am not sure I understand what's going on.

**Comment by moracabanas** [comment]
> Hey @moracabanas. Can you record a video of the behaviour you are seeing? I am not sure I understand what's going on.

Sure here is:

To trigger autosuggestions I must type at least 1 space

[![Image from Gyazo](https://i.gyazo.com/7be68869d20452cb2d99a0a99528b4fd.gif)](https://gyazo.com/7be68869d20452cb2d99a0a99528b4fd)

**Comment by moracabanas** [comment]
I reinstalled Tailwindcss Intellisense, and I worked, then I closed VSCode to test it. 
Once I opened again the issue es still there.

**Comment by bradlc** [comment]
Thanks for the video @moracabanas. The reason the completions don't show in your video is because you are selecting the `class` attribute completion, which automatically inserts `class=""` when you select it. Completion providers in VS Code can define "trigger characters" which cause the completions to show, and we define `"` as a trigger character. But because you're not actually typing the `"` it doesn't trigger. As far as I'm aware there's no way for us to trigger suggestions in this instance.
