### ISSUE TITLE
Allow to hide tailwind.config.js

### ISSUE THREAD

**Issue by al6x** [tailwindlabs/tailwindcss-intellisense#370]
Currently if `tailwind.config.js` is hidden, the autocomplete tw classes doesn't work in VSCode

I usually hide `xxx.config.js` kind of files in the project, to avoid visual noise and distraction.

Please consider not requiring the visibility of this file. And tanks for great CSS library :)

**Comment by bradlc** [comment]
Hey @al6x. Unfortunately I don't think this is feasible. The extension uses standard VS Code APIs like `workspace.findFiles` and if a file is hidden it will not be picked up by these APIs. Sorry about that!
