### ISSUE TITLE
Class detection works only when strings begin and end with whitespace

### ISSUE THREAD

**Issue by michaelschufi** [tailwindlabs/tailwindcss-intellisense#372]
Hi

I am desperately trying to make the intellisense work with multi-line strings using the class regex setting.

**Goal**
I want to have all the strings in here "stringed together" in one class attribute context:
```js
cls(
  "relative flex-1 flex flex-col max-w-xs w-full bg-indigo-700",
  "transition bg-gray-50 ease-in-out duration-300 transform",
  sidebarIsOpen ? "translate-x-0" : "-translate-x-full",
),
```

**The problem**
Using the regex
```
"tailwindCSS.experimental.classRegex": [
    "cls\\(([^)]*)\\)",
  ],
```
it only partially works.

As you can see, the suggestions for the second class, for example, works:
![image](https://user-images.githubusercontent.com/2805598/126684906-1a1c40f9-4aec-4cdd-a067-07827fa35788.png)

But the first and last one of the first string, does not:
![image](https://user-images.githubusercontent.com/2805598/126685100-a882d95d-98a3-4c6b-87b5-f81fe4e917a8.png)

The strings with single classes in them also don't work.

**The magic trick**
If I add a space to the start and the end of each string, it magically works:

![image](https://user-images.githubusercontent.com/2805598/126685478-172f65b3-0990-44fd-b803-fd5de0143174.png)

---- 

It would be awesome if this problem could be fixed. Personally, I also don't mind the warnings, since I defined that everything inside `cls(...)` should be one group. 

This may fix some problems other people are having coming from #129.

**Comment by geekox86** [comment]
I have the same problem, though using my custom classRegex `["tw`[^`]*`?", "tw`([^`]*)`?"]` and `tw` as string template literal that simply split the string classes into array.

Autocomplete works when pressing space but not enters. Please, advise.

**Comment by chrisd08** [comment]
Same problem here

**Comment by bradlc** [comment]
Hey @michaelschufi. Here's a configuration that should fix your issue, and also prevent the incorrect warnings:

```
"tailwindCSS.experimental.classRegex": [
  ["\\bcls\\(([^)]+)\\)", "\"([^\"]*)\""]
],
```

With your existing configuration the set of classes is parsed as follows:

```
Group 1
=======
cls(
"relative
flex-1
flex
flex-col
max-w-xs
w-full
bg-indigo-700",
"transition
bg-gray-50
ease-in-out
duration-300
transform",
sidebarIsOpen
?
"translate-x-0"
:
"-translate-x-full",
),
```

With the updated configuration they are parsed like this:

```
Group 1
=======
relative
flex-1
flex
flex-col
max-w-xs
w-full
bg-indigo-700

Group 2
=======
transition
bg-gray-50
ease-in-out
duration-300
transform

Group 3
=======
translate-x-0

Group 4
=======
-translate-x-full
```

Check out [my comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659) over on #129 for more information. I hope that helps!
