### ISSUE TITLE
Auto Complete not showing if nextline.

### ISSUE THREAD

**Issue by BroJenuel** [tailwindlabs/tailwindcss-intellisense#373]
If I try to write in the next line the auto complete doesnt show up.
![image](https://user-images.githubusercontent.com/31676163/126863694-23d3f22b-c036-4eeb-8225-4a55c28a78f9.png)

**Comment by zaidpro** [comment]
> If I try to right in the next line the auto complete doesnt show up.
> ![image](https://user-images.githubusercontent.com/31676163/126863694-23d3f22b-c036-4eeb-8225-4a55c28a78f9.png)

how to make all class name in one line not on each line in vs code, when ever re-format vs-code each class will take a line?
 sorry about question

**Comment by BroJenuel** [comment]
> > If I try to right in the next line the auto complete doesnt show up.
> > ![image](https://user-images.githubusercontent.com/31676163/126863694-23d3f22b-c036-4eeb-8225-4a55c28a78f9.png)
> 
> how to make all class name in one line not on each line in vs code, when ever re-format vs-code each class will take a line?
> sorry about question

I am using prettier to autoformat my codes.

**Comment by geekox86** [comment]
I have the same problem, though using my custom classRegex `["tw`[^`]*`?", "tw`([^`]*)`?"]` and `tw` as string template literal that simply split the string classes into array.

Autocomplete works when pressing space but not enters. Please, advise.

**Comment by bradlc** [comment]
Thanks for reporting. This should be fixed in `v0.6.14` 👍

**Comment by Tazi0** [comment]
@bradlc On current version `v0.6.14` it next line still requires a space to be activated

**Comment by Tazi0** [comment]
nevermind, the editor has to have a specific quick suggestion, see more: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/359#issuecomment-868906215
