### ISSUE TITLE
Support Border Color Utilities

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/tailwindcss-intellisense#375]
I thought it isn't supported as autocompletes weren't there so I searched & stumbled upon 2-3 issues which lead me to [this PR by @adamwathan](https://github.com/tailwindlabs/tailwindcss/pull/4404) which adds support for custom border colors.

Basically it should autocomplete when I type `border-t-` like:

```html
<div class="border-t-blue-500 border-b-pink-300">
```

**Comment by BennaceurHichem** [comment]
The same problem for, it doesn't work also when I use it

**Comment by bradlc** [comment]
Hey @deadcoder0904. Per-side border colour completions are supported when using `tailwindcss` v3. I'm going to close this as it's unlikely we will be back-porting this for v2's JIT mode.
