### ISSUE TITLE
The `group` class does not exist.

### ISSUE THREAD

**Issue by RyanRoberts** [tailwindlabs/tailwindcss-intellisense#376]
When using `group` within an @layer like so:

```css
@layer components {
  .example {
    @apply group;
  }
}
```

I'm seeing the following error:
```
The `group` class does not exist. If `group` is a custom class, make sure it is defined within a `@layer` directive.
```

I'd give you my details but it can be replicated over on Tailwind Play, e.g. https://play.tailwindcss.com/3b4AcIqEFT?file=css

**Comment by RyanRoberts** [comment]
Sorry wrong repo

**Comment by sunscreem** [comment]
@RyanRoberts Nice.

**Comment by deadcoder0904** [comment]
But it certainly doesn't exist in Intellisense as well. I can't get Intellisense besides `@apply`. Can you re-open?

**Comment by deadcoder0904** [comment]
Don't re-open. I guess [it's by design](https://github.com/tailwindlabs/tailwindcss/issues/2848#issuecomment-734523233) :)

**Comment by RyanRoberts** [comment]
> it's by design

Yeah I came across that too, I was going to open another issue when I saw it's by design.
