### ISSUE TITLE
Class preview on shortcut keypress instead of hover?

### ISSUE THREAD

**Issue by Nuno111** [tailwindlabs/tailwindcss-intellisense#381]
Hi all,

Any way to add a shortcut so that for example doing ctrl + j would show the preview of the class  instead of hovering over it?

I am trying to stay away from mouse as much as possible and this would really improve my workflow.

Ps: this is in vscode

Thank you!

**Comment by bradlc** [comment]
Hey @Nuno111. There is actually a built-in feature within VS Code for this. You can trigger the hover using the `Show Hover` command. This can be accessed from the command palette or you can use a keyboard shortcut, which is `cmd+k cmd+i` by default on macOS

**Comment by Nuno111** [comment]
Thank you very much Bradlc, that is exactly what I needed!
