### ISSUE TITLE
SyntaxError: Unexpected token 'export' when using external file in tailwind.config.js

### ISSUE THREAD

**Issue by maxcaplan** [tailwindlabs/tailwindcss-intellisense#382]
I'm currently working on a project where we have our breakpoints defined in the following javascript file `breakpoints.js`:
```javascript
export const screens = {
  'sm': '640px',
  'md': '768px',
  'lg': '1024px',
  'xl': '1280px',
  '2xl': '1536px',
};
```

This is then used in our `tailwind.config.js` file as follows:
```javascript
const { screens } = require("./breakpoints.js");

module.exports = {
  darkMode:
  mode: "jit",
  plugins: [],
  purge: [
    './components/**/*.{vue,js}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
  ],
  theme: {
    extend: {},
    screens,
  },
  variants: {
    extend: {},
  },
}
```
This causes the extension to fail with the output:
```bash
Tailwind CSS: Unexpected token 'export'
```
The only solution I have right now is to switch `breakpoints.js` to use `module.exports` as follows:
```javascript
module.exports = screens = {
  'sm': '640px',
  'md': '768px',
  'lg': '1024px',
  'xl': '1280px',
  '2xl': '1536px',
}
```
I'm using Node version 14.17.3

**Comment by bradlc** [comment]
Hey @maxcaplan. Hope you don't mind, I'm going to close this and use #399 for anything related to ES modules
