### ISSUE TITLE
IntelliSense is not working

### ISSUE THREAD

**Issue by sunel** [tailwindlabs/tailwindcss-intellisense#383]
Version: 1.59.0 (system setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

Name: Tailwind CSS IntelliSense
Id: bradlc.vscode-tailwindcss
Description: Intelligent Tailwind CSS tooling for VS Code
Version: 0.6.13
Publisher: Brad Cornes

Command is also not showing up

**Comment by heidarKadkhoda** [comment]
Not working for me either.
- Autocomplete wont work.
- Color box wont show up.


Firefox: 90.0.2 (64-bit)
Version: 1.59.0 (user setup)
Electron: 13.1.7
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

I also see this error.

[Error - 17:39:29] Tailwind CSS: Can't resolve 'tailwindcss' in 'c:\Users\UserName\Desktop\TailwindFolder'
Error
    at new g (c:\Users\UserName\.vscode\extensions\bradlc.vscode-tailwindcss-0.6.13\dist\server\tailwindServer.js:56:279180)
    at c:\Users\UserName\.vscode\extensions\bradlc.vscode-tailwindcss-0.6.13\dist\server\tailwindServer.js:56:346192
    at Generator.next (<anonymous>)
    at o (c:\Users\UserName\.vscode\extensions\bradlc.vscode-tailwindcss-0.6.13\dist\server\tailwindServer.js:56:339494)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by sunel** [comment]
After remaning the config file to tailwind.config.js it worked
