### ISSUE TITLE
Intellisense doesn't work with tailwind CLI

### ISSUE THREAD

**Issue by FJLendinez** [tailwindlabs/tailwindcss-intellisense#386]
Using as a reference this video:
What's New in Tailwind CSS v2.2 (Tailwind Labs)
https://www.youtube.com/watch?v=DxcJbrs6rKk

We can see how he uses `npx tailwindcss -o ./build/tailwind.css --jit -w` and intellisense doesn't show options properly. (2:30 ~ 2:48)

I tried like this and generating a valid `tailwind.config.js` in the root of the project and nothing happens.

**Comment by bradlc** [comment]
Hey @FJLendinez. I think this is covered by #27, i.e. adding support for environments where `tailwindcss` is not installed
