### ISSUE TITLE
Use intellisense with tailwind.config.js in a subfolder

### ISSUE THREAD

**Issue by kstfR** [tailwindlabs/tailwindcss-intellisense#389]
Would like to see tailwind css intellisense being able to work when the config file is put in a subfolder, e.g. ".config/tailwind.config.js"

**Comment by bradlc** [comment]
Hey @kstfR. The extension already works with the config file in a subfolder. Are you using the `files.exclude` or `files.watcherExclude` settings to hide the `.config` folder by any chance?

**Comment by kstfR** [comment]
hey @bradlc. No I'm not, it's actually the first time I'm hearing of `files.exclude` and `files.watcherExclude`. :) I am using `eleventy` though, but then again it's the same in my `electron` project.

**Comment by bradlc** [comment]
Config files inside hidden (dot) folders should now be picked up by the extension, in `v0.6.15` 👍
