### ISSUE TITLE
babel config ignored

### ISSUE THREAD

**Issue by selfagency** [tailwindlabs/tailwindcss-intellisense#395]
Hello,

I am receiving the error

```
Tailwind CSS: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
```

after switching to ES6 syntax in my Tailwind configuration. However, my `babel.config.js` specifies `sourceType: module` and is evidently being ignored by your extension.

I would appreciate your guidance.

Thank you

**Comment by selfagency** [comment]
I was able to resolve this problem by changing the extension of the `tailwind.config.js` file to `tailwind.config.mjs`.

**Comment by bradlc** [comment]
Hey @selfagency. Hope you don't mind, I'm going to close this and use #399 for anything related to ES modules. Please note however, there's no plans for the extension to honour Babel configs when reading the Tailwind config file.

**Comment by finnmerlett** [comment]
@selfagency I can't see how you managed to do that? Everywhere in the extension's code it only mentions `.js`/`.cjs` file extensions being checked. If I change `tailwind.config.js` to `tailwind.config.mjs` it is no longer recognised by the extension at all. How did you get that to work for you?

**Comment by selfagency** [comment]
wish i could remember @finnmerlett but it's been a while

**Comment by finnmerlett** [comment]
Just for posterity I solved my issues by using exclusively javascript and module.exports for the files where I wanted to store common consts to be imported elsewhere. I turned on allowJs and checkJs in the .tsconfig to ensure that the consts exported where fully typed (implicitly, or explicitly where needed using jsdoc).
