### ISSUE TITLE
Support the new JIT engine

### ISSUE THREAD

**Issue by sajedsoliman** [tailwindlabs/tailwindcss-intellisense#397]
We need an update for the new engine (JIT). It has more extra approaches such as caret for inputs, border constraints, chaining variants, etc...

**Comment by bradlc** [comment]
Hey @sajedsoliman. The extension already supports JIT mode 👍 What issue are you running into exactly?

**Comment by sajedsoliman** [comment]
I have no autocompletion for (dark) selector and all new features such as caret(for inputs' cursor color), chained variants and etc.

**Comment by bradlc** [comment]
Do you have any errors in the extension output? You can see this by running the "Tailwind CSS: Show Output" command from the command palette.

**Comment by bradlc** [comment]
Going to close this for inactivity but please open a new issue with a repository that reproduces the issue if you're still having problems 👍
