### ISSUE TITLE
Support for ClojureScript?

### ISSUE THREAD

**Issue by bigodel** [tailwindlabs/tailwindcss-intellisense#400]
is there any plans on adding support for ClojureScript? i'd be willing to help!

**Comment by WindOfMind** [comment]
Also interested in that!

**Comment by bradlc** [comment]
Hey! I am not familiar with ClojureScript. How do you use CSS classes with that?

**Comment by WindOfMind** [comment]
Basically, ClojureScript uses Hiccup (https://github.com/weavejester/hiccup).
So, you can provide classes in the next ways:

```
[:div.bg-gray-100]
```

or

```
[:div {:class "bg-gray-100"}]
```

And Tailwind Intellisense doesn't work in these cases, at least for me. If I start typing `class="bg-"`, it will work. But in ClojureScript, we don't provide classes in that way. Any advice for that?

**Comment by bradlc** [comment]
Thanks for that @WindOfMind! I am reluctant to add first-class support for syntaxes that don't resemble traditional HTML (i.e. `class=""`), but there is a solution that might work for you. There is a `tailwindCSS.experimental.classRegex` setting that you can use to define custom places where CSS classes might exist in your code. So for your second example you could configure `tailwindCSS.experimental.classRegex` like this:

```
"tailwindCSS.experimental.classRegex": [
  ":class\\s+\"([^\"]*)\""
]
```

You can read more about this here: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659. Hope that helps!

**Comment by Chase-Lambert** [comment]
This works great, thanks so much. Has anyone figured out the proper regex for the `[:h1.text-3xl.font-extrabold.mt-6 "Hello, World!"]` shortcut style of writing out the css classes?

**Comment by bigodel** [comment]
> This works great, thanks so much. Has anyone figured out the proper regex for the `[:h1.text-3xl.font-extrabold.mt-6 "Hello, World!"]` shortcut style of writing out the css classes?

i had some success in the past with [this](https://github.com/tailwindlabs/tailwindcss/issues/7553#issuecomment-984202139), hope it helps

**Comment by Chase-Lambert** [comment]
Hey, thought I would share this for those who end up here when looking for a Clojure or ClojureScript solution like I did, some nice folks on the Clojure slack helped me find this full solution that gives you autocompletion using both styles of hiccup (eg. `[:h1 {:class "text-3xl font-extrabold mt-6"}]` and `[:div.text-3xl.font-extrabold.mt-6]`): 

```
 "tailwindCSS.experimental.classRegex": [                                                       
    ":class\\s+\"([^\"]*)\"",                                                                    
    ":[\\w-.#>]+\\.([\\w-]*)"                                                                    
  ],                                                                                             
  "tailwindCSS.includeLanguages": {                                                              
    "clojure": "html"                                                                            
  }

**Comment by chase-lambert** [comment]
Does the above solution still work for everyone? For some reason the `[:div.text-3xl.font-extrabold.mt-6 "Hello, World!"]` method doesn't give me autocomplete anymore. I haven't figured out what has changed. The `:class "..."` method still works for autocompletion so it is properly detecting the clojure file for css if that makes sense. 

Probably unrelated but I noticed there is a `tailwindCSS.emmetCompletions` setting now (not sure when it was added, could be old) and that is very similar to our hiccup style (e.g. div.text-3xl.font-extrabold...) so this should be possible somehow.

Also, is anyone able to get sorting to work from this tool: https://github.com/heybourn/headwind in your clojure code? 

I am using this vim plug-in if that makes a difference in why things are different for me: https://github.com/yaegassy/coc-tailwindcss3

**Comment by milelo** [comment]
I developed these for hiccup:

```clojure
:div.c1.c2
{:class :c1.c2
{:class "c1 c2"}
{:class  ["c1" :c2]}
```
```json
  "tailwindCSS.includeLanguages": {
    "clojure": "",
    "clojurescript": ""
  },
  "tailwindCSS.experimental.classRegex": [
    [
      "\\[:[^.\\s]*((?:\\.[^.\\s\\]]*)+)[\\s\\]]",
      "\\.([^.]*)"
    ],
    [
      "\\:class\\s+(\\:[^\\s\\}]*)[\\s\\}]",
      "[\\:.]([^.]*)"
    ],
    [
      "\\:class\\s+(\"[^\\}\"]*)\"",
      "[\"\\s]([^\\s\"]*)"
    ],
    [
      "\\:class\\s+\\[(.*)\\]",
      "[\"\\:]([^\\s\"]*)[\"]?"
    ]
  ],
```

**Comment by chase-lambert** [comment]
Hi @milelo, the `:class` based approach works for me but I'm still not getting suggestions when trying the `:div.c1.c2` way. Do you have a small repo that this works on you can share?

**Comment by milelo** [comment]
> Hi @milelo, the `:class` based approach works for me (edit: well the old fashioned `:class "c1 c2"` way. I didn't even know you can do those other ways but they don't work for me here anyways) but I'm still not getting suggestions when trying the `:div.c1.c2` way. Do you have a small repo that this works on you can share?

That makes me think you could have some conflicting settings.

Look at https://github.com/milelo/biff-electric-hiccup and its HTML Styling section.

Ensure you don't have any user-settings for the plugin while you try it.

**Comment by Peluko** [comment]
@milelo thanks for your settings, they are working for me. I've updated the settings to support some multiline class vectors, by using keywords or symbols. For example, this settings work for:

```clojure
  [:div {:class [:h-4
                 :w-10
                 :bg-slate-200]}]
```

and for
```clojure
  [:div {:class '[h-4
                  w-10
                  bg-slate-200]}]
```
The only changes are on your last regex and a new added another one. Here is the full setup:

```json
    "tailwindCSS.includeLanguages": {
        "clojure": "",
        "clojurescript": ""
    },
    "tailwindCSS.experimental.classRegex": [
        [
            "\\[:[^.\\s]*((?:\\.[^.\\s\\]]*)+)[\\s\\]]",
            "\\.([^.]*)"
        ],
        [
            "\\:class\\s+(\\:[^\\s\\}]*)[\\s\\}]",
            "[\\:.]([^.]*)"
        ],
        [
            "\\:class\\s+(\"[^\\}\"]*)\"",
            "[\"\\s]([^\\s\"]*)"
        ],
        [
            "\\:class\\s+\\[([\\s\\S]*)\\]",
            "[\"\\:]([^\\s\"]*)[\"]?"
        ],
        [
            "\\:class\\s+'\\[([\\s\\S]*)\\]",
            "([^\\s]*)?"
        ]
    ],
```
 I don't know if this has another side effects, but for now it's working.

Regards.

**Comment by chase-lambert** [comment]
I tweaked the ones above to also include Fulcro's style syntax sugar `(dom/div :.c1.c2 ...` 
```
"\\:(\\.[^\\s#]+(?:\\.[^\\s#]+)*)" "\\.([^\\.\\s#]+)" 
```

And for any neovim users here is how I got this all working when I switched from `coc.nvim` to the builtin lsp capabilities:
```
  {
    "luckasRanarison/tailwind-tools.nvim",
    name = "tailwind-tools",
    build = ":UpdateRemotePlugins",
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-telescope/telescope.nvim",
      "neovim/nvim-lspconfig",
    },
    opts = {
      server = {
        override = true,
        settings = {
          emmetCompletions = true,
          includeLanguages = { clojurescript = "html" },
          experimental = {
            classRegex = {
              { "\\[:[^.\\s]*((?:\\.[^.\\s\\]]*)+)[\\s\\]]", "\\.([^.]*)" },
              { "\\:(\\.[^\\s#]+(?:\\.[^\\s#]+)*)", "\\.([^\\.\\s#]+)" },
              { "\\:class\\s+(\\:[^\\s\\}]*)[\\s\\}]", "[\\:.]([^.]*)" },
              { "\\:class\\s+(\"[^\\}\"]*)\"", "[\"\\s]([^\\s\"]*)" },
              { "\\:class\\s+\\[([\\s\\S]*)\\]", "[\"\\:]([^\\s\"]*)[\"]?" },
              { "\\:class\\s+'\\[([\\s\\S]*)\\]", "([^\\s]*)?" },
            },
          },
        },
      },
    },
  },
```

**Comment by agorgl** [comment]
Taking a hint from the actual code that uses classRegex here: https://github.com/tailwindlabs/tailwindcss-intellisense/blob/main/packages/tailwindcss-language-service/src/util/classes.ts and the examples in the tests here: https://github.com/tailwindlabs/tailwindcss-intellisense/blob/main/packages/tailwindcss-language-service/src/util/classes.test.ts,
I also came up with some regexes that might be useful for development with reagent or replicant, so I'll post them here too for future searchers:
```
    tailwindcss = {
      settings = {
        tailwindCSS = {
          experimental = {
            classRegex = {
              { ":class\\s+\\[([^\\]]*?)\\]", '[:"]([^\\s"]*)"?' },
              { ':class\\s+"([^"]*?)"', "([^\\s]*)" },
              { "\\[:[^\\.]+((\\.[^\\.]+)*)", "\\.([^\\.]*)" },
            },
          },
          includeLanguages = {
            clojure = "html",
          },
        },
      },
    },
```
