### ISSUE TITLE
How to add exclude option?

### ISSUE THREAD

**Issue by thousandsofraccoons** [tailwindlabs/tailwindcss-intellisense#401]
Hello, thank you for a great library. I've a question: how do I make it work only in `tsx` files? It analyzes every single file I edit and slows down the editing of files of any extension.

**Comment by calvo-jp** [comment]
[This](https://tailwindcss.com/docs/content-configuration) article might help. It used to be `purge`, but was changed lately to `content`

**Comment by bradlc** [comment]
The extension has the following settings that can be used to disable IntelliSense features:

- `tailwindCSS.hovers`
- `tailwindCSS.suggestions`
- `tailwindCSS.codeActions`
- `tailwindCSS.colorDecorators`
- `tailwindCSS.validate`

So if you wanted to only enable these in `tsx` files you could use a configuration like this:

```
"tailwindCSS.hovers": false,
"tailwindCSS.suggestions": false,
"tailwindCSS.codeActions": false,
"tailwindCSS.colorDecorators": false,
"tailwindCSS.validate": false,
"[typescriptreact]": {
  "tailwindCSS.hovers": true,
  "tailwindCSS.suggestions": true,
  "tailwindCSS.codeActions": true,
  "tailwindCSS.colorDecorators": true,
  "tailwindCSS.validate": true
}
```

I hope that helps!
