### ISSUE TITLE
html `style` self closing tag break intellisense

### ISSUE THREAD

**Issue by boompikachu** [tailwindlabs/tailwindcss-intellisense#402]
Having a self closing tag `style` in the file cause the tailwind intellisense to not work 

Without `<style />`
<img width="363" alt="image" src="https://user-images.githubusercontent.com/37561295/131643428-598e605c-f3ba-4d27-8e73-9d38caf6c99b.png">

With `<style />`
<img width="312" alt="image" src="https://user-images.githubusercontent.com/37561295/131643533-78a1ea7e-4208-4a44-8fad-b9c4d816f83d.png">

Notice the color preview in picture 1 indicating intellisense to be working.

It looks like the `<style />` only disabled the intellisense underneath it
<img width="301" alt="image" src="https://user-images.githubusercontent.com/37561295/131643848-12ba745c-cc71-44f7-a07e-81318e4aa280.png">

I tried other different closing tag but it still work
<img width="309" alt="image" src="https://user-images.githubusercontent.com/37561295/131643992-ad1afa1f-a60f-48dd-a0c9-6c7feac78d3a.png">

This might have to do with style-system?
```
const someStyle = style`

`
```

**Comment by bradlc** [comment]
Thanks for reporting. This is fixed in `v0.6.15` 👍
