### ISSUE TITLE
How can I build this locally to debug?

### ISSUE THREAD

**Issue by aidos** [tailwindlabs/tailwindcss-intellisense#404]
Hi, thanks for the extension. I've been using the lsp from neovim via lspinstall and lspconfig. On recent install it's stopped working (getting `tailwindcss: -32601: Unhandled method textDocument/hover` and completion isn't working).

I decided that rather than pestering you I'd build it locally so I could debug it here but that's not working for some reason.

```
cd packages/tailwindcss-language-server
npm i
npm run build
```

It looks like it's not able to resolve the libs in the node_modulles folder. I'm getting:

```
Error: [tsl] ERROR in /home/vagrant/tailwindcss-intellisense/packages/tailwindcss-language-service/src/hoverProvider.ts(2,52)
      TS2307: Cannot find module 'vscode-languageserver' or its corresponding type declarations.
```

Any idea what I'm doing wrong? Thanks!

**Comment by aidos** [comment]
Figured it out. Need to run `npm run bootstrap` in the root and setup the `tailwindcss-language-service` package.

**Comment by bnjmnt4n** [comment]
Hey @aidos just wondering if you ever managed to get to the root cause of this issue? I've also recently started experiencing the `tailwindcss: -32601: Unhandled method textDocument/hover` error using nvim-lspconfig. The language server was working fine before that though.
