### ISSUE TITLE
Improve the text open when hover class name on VS code

### ISSUE THREAD

**Issue by IRediTOTO** [tailwindlabs/tailwindcss-intellisense#405]
### What version of @tailwindcss/aspect-ratio are you using?

2.2

### What version of Node.js are you using?

14

### What browser are you using?

edge

### What operating system are you using?

win 10

### Reproduction repository

You don't need this

### Describe your issue

Hi, I think you can improve the text open when you hover the class name on the editor. It's so long and not right I think. :) 
![image](https://user-images.githubusercontent.com/15695252/131219629-b1a4847e-81ab-4024-8f42-39ff65c4b886.png)

**Comment by bradlc** [comment]
Hey @IRediTOTO. I think this is working as expected as it just shows all of the CSS rules associated with a class. If you're using recent versions of `tailwindcss` (>= `v3.0.0`) and `@tailwindcss/aspect-ratio` (>= `v0.4.0`) then the preview is a bit nicer:

<img width="854" alt="CleanShot 2022-02-25 at 13 49 27@2x" src="https://user-images.githubusercontent.com/2615508/155726341-453dc185-5d12-4a60-982d-c78669b3ff23.png">
