### ISSUE TITLE
Can't get intellisense to work with .heex files

### ISSUE THREAD

**Issue by doughsay** [tailwindlabs/tailwindcss-intellisense#406]
Using the ElixirLS extension for .heex file support, and adding

```
"tailwindCSS.includeLanguages": {
  "html-eex": "html"
}
```

... doesn't seem to work. I'm pretty sure the language identifier is `html-eex`, but I've also tried `heex` and `HTML-eex` to no avail.  Adding `plaintext` like in the example works, and I get intellisense in regular html files as well, so I know the extension is working.

Am I using the wrong language identifier?  What else can I check, what else could be wrong?

**Comment by doughsay** [comment]
Sorry, I figured it out.  VSCode really doesn't make it easy for you to figure out what the actual language identifier being used is, because it just shows the "human readable name" everywhere.  Anyway, in my case, the language identifier I was looking for is actually `phoenix-heex`...

**Comment by sergiotapia** [comment]
I needed intellisense for both heex templates and single file liveviews that end in .ex:

```
"tailwindCSS.includeLanguages": {
    "plaintext": "html",
    "phoenix-heex": "html",
    "elixir": "html",
  }
```
