### ISSUE TITLE
cssConflict when using parenthesis with twin.macro

### ISSUE THREAD

**Issue by wottpal** [tailwindlabs/tailwindcss-intellisense#408]
Hey there, when using tailwind with twin.macro I can wrap e.g. responsive properties inside parenthesis (see below). Unfortunately IntelliSense sometimes (not always) thinks that the property is doubled (even though it isn't) and creates a **cssConflict** warning.

E.g. this one creates a warning about `px`:
```
tw`px-2 sm:(pt-4 px-4)`
```

But this one works (if the according property is the first inside the parenthesis):
```
tw`px-2 sm:(px-4 pt-4)`
```

Would be nice to see this fixed :) 

FYI @ben-rogerson

**Comment by bradlc** [comment]
Hey @wottpal. While Tailwind CSS IntelliSense can (to an extent) be used with Tailwind-adjacent tools like twin, the project aims to support **Tailwind CSS only**. The syntax you are referring to does not exist in Tailwind CSS so we won't be adding first-class support for it. Sorry about that! Perhaps this is something that could be supported by the [twin extension](https://marketplace.visualstudio.com/items?itemName=lightyen.tailwindcss-intellisense-twin)?

**Comment by wottpal** [comment]
@ben-rogerson What do you think about that? Can this extra extension somehow block these warnings to be thrown.

**Comment by wottpal** [comment]
Nevermind: Everything seems to work now as expected. I had to disable this (official) TailwindCSS extension to get the Twin-TailwindCSS plugin working correctly.

 You should highlight this in the Readme of the extension @lightyen :)
