### ISSUE TITLE
Support reading config even if it is listed in files.exclude

### ISSUE THREAD

**Issue by domdomegg** [tailwindlabs/tailwindcss-intellisense#410]
I have seen the discussions which previously found that if `tailwind.config.js` is matched by a `files.exclude` path this extension cannot currently read it and so doesn't work in that scenario (#174, #277, #345).

Is there any way that this can be overcome? Ideally I'd like to be able to hide the `tailwind.config.js` from users in VS Code while still getting the amazing tailwindcss-intellisense features. I think technically it must be possible given there are many extensions that do still seem to read and function based on hidden files (e.g. the TS intellisense can read from node_modules despite us hiding it, or GitLens must be reading from the .git directory, ESLint is reading from .eslintrc which we hide).

Use case: we have a project that many non-technical people use, and it's generally simpler if we can hide things that they're not going to (and shoudn't change). To do this, we use the `files.exclude` feature which generally works great apart from this case.

Potential alternative: maybe there is some way to hide files from the sidebar in VS code without using `files.exclude`. I'm not aware of one, but would be open to switching if that's possible.

Thanks for this awesome tool!

**Comment by bradlc** [comment]
Hey @domdomegg. I think the solution to this is going to be adding a setting that allows you to explicitly set the config path, so I'm going to close this in favour of #348
