### ISSUE TITLE
unable to resolve preset from published config

### ISSUE THREAD

**Issue by JeffBeltran** [tailwindlabs/tailwindcss-intellisense#412]
I ran into the same issue as https://github.com/tailwindlabs/tailwindcss-intellisense/issues/333, However, im trying to reference a published preset (Github package). Tailwind has no issues with this, but in vscode this extension crashes

```
  presets: [require("@homevalet/bowtie/config")],
  mode: "jit",
  purge: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./node_modules/@homevalet/bowtie/**/*",
  ],
```

but the extension throws the following error
 
```
[Error - 3:04:52 PM] Tailwind CSS: Can't resolve '@homevalet/bowtie/config' in '/Users/jeffbeltran/code/vite-project'
Error: Can't resolve '@homevalet/bowtie/config' in '/Users/jeffbeltran/code/vite-project'
    at c (/Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:2:26552)
    at /Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:2:27239
    at /Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:2:27803
    at eval (eval at create (/Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:50:32334), <anonymous>:15:1)
    at /Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:2:27803
    at eval (eval at create (/Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:50:32334), <anonymous>:27:1)
    at /Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:2:13662
    at /Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:2:27803
    at eval (eval at create (/Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:50:32334), <anonymous>:15:1)
    at /Users/jeffbeltran/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.14/dist/server/tailwindServer.js:2:27803
```

this could 100% be on me with how i published the module, but at this point this extension is the only thing not working.

if it helps, i can fix the issue with the above error by directly referencing the module via 

```
 presets: [require("./node_modules/@homevalet/bowtie/dist/config")],
```

so not a blocking issue but would be nice to see if it's something i could do on my end.

Cheers and thanks for this great extension

**Comment by bradlc** [comment]
Hey @JeffBeltran. Is `@homevalet/bowtie/config` the correct path? You use `@homevalet/bowtie/dist/config` in your last example so I'm wondering if it's meant to be `require("@homevalet/bowtie/dist/config")`? Or does the `config` directory have a `package.json` file with a `main` field?

**Comment by JeffBeltran** [comment]
hey thanks @bradlc, `@homevalet/bowtie/config` is the correct path, sorry about the confusion, it was likely part of my debugging that made it's way to that comment. As for the `package.json`, this is the entry i have 
```json
"main": "./dist/bowtie.umd.js",
"module": "./dist/bowtie.es.js",
"exports": {
    ".": {
        "import": "./dist/bowtie.es.js",
        "require": "./dist/bowtie.umd.js"
    },
    "./config": "./dist/config/index.js"
},
```

and just to be more clear

```javascript
// this works for both this extension and tailwind config
presets: [require("./node_modules/@homevalet/bowtie/dist/config")]

// this only works for the tailwind config, the extension gives the above error
presets: [require("@homevalet/bowtie/config")],

// this doesn't work for any of them
presets: [require("@homevalet/bowtie/dist/config")]
```

if it would help i'll throw together a public example

**Comment by dimitrisnl** [comment]
Thank you @JeffBeltran - I have the same issue, and your `./node_modules/@..` workaround saved the day for me. Hoping for a proper fix.

**Comment by JeffBeltran** [comment]
Cheers @bradlc just tested this out and can confirm this is now resolved resolved
