### ISSUE TITLE
Color Hex Code in intellisense box

### ISSUE THREAD

**Issue by kayvaninvemo** [tailwindlabs/tailwindcss-intellisense#418]
Is it possible to add color hex code in the intellisense dialog?

![image](https://user-images.githubusercontent.com/74557546/134763675-e274ad54-8b92-4441-a13d-46506deed550.png)

I mean I wish that here I could see `#767676` beside `rgb(118, 118, 118)`.

The reason is that most of the time the developer get the hex code from the designer, with this we could speed up the development and better DX.

**Comment by polyzen** [comment]
https://github.com/tailwindlabs/tailwindcss-intellisense/pull/416

**Comment by bradlc** [comment]
Hey @kayvaninvemo, thanks for the suggestion. Unfortunately, it is not possible to show multiple versions of the colour in that location in VS Code, because that value is what VS Code uses to display the colour block, therefore it must be a single value.

**Comment by aungbobotun** [comment]
@bradlc  Can we see the original color value instead of the RGB value? Hex is easier to read.

**Comment by Swennet** [comment]
Just commenting because I would really like this feature as well. I have to keep cross-referencing my tailwind.config.js file to know which value I'm looking for, which gets really annoying.

It would be much easier if I could see the HEX value in the intellisense dialog, even if it replaces the RGBA value altogether.

**Comment by Sodj** [comment]
+1

**Comment by arnaudambro** [comment]
yes please !

**Comment by osama996** [comment]
> Just commenting because I would really like this feature as well. I have to keep cross-referencing my tailwind.config.js file to know which value I'm looking for, which gets really annoying.
> 
> It would be much easier if I could see the HEX value in the intellisense dialog, even if it replaces the RGBA value altogether.


@bradlc  it would be okay if we could just configure the colors display format somehow!

**Comment by MohammadKurjieh** [comment]
@bradlc  Any updates on this issue? It would be really nice as it will save us from cross referencing with `tailwind.config.js` as mentioned by @Swennet

**Comment by watchingon9** [comment]
+1

**Comment by davidungio** [comment]
+1

**Comment by Jibs-Jibz** [comment]
+1

**Comment by PILLOWPET** [comment]
+1

**Comment by GustavoSmith** [comment]
+1!

**Comment by matheusmb** [comment]
+1

**Comment by aliazhar-id** [comment]
+1
