### ISSUE TITLE
Jit Mode Per-side border colors auto complete suggestion not showing

### ISSUE THREAD

**Issue by mehdad-hussain** [tailwindlabs/tailwindcss-intellisense#419]
Hello,
I am using this extension. It's nice extension for tailwind CSS.
But for JIT mode border-t-red-900 or border-b-blue-900
these suggestion is not showing.
[https://tailwindcss.com/docs/just-in-time-mode#per-side-border-colors](url)
Like here mentioned in the official docs.

**Comment by bradlc** [comment]
Duplicate of #375
