### ISSUE TITLE
Feature Request: Enable extension for "plain vanilla" CDN installs?

### ISSUE THREAD

**Issue by RobJacobson** [tailwindlabs/tailwindcss-intellisense#425]
I'm just getting started with Tailwind. I did some "plain vanilla" installations using a simple HTML5 file using both of the following CDN options:

1. The min.css CDN link: `<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">`

2. The new JIT CDN link, described here:
https://beyondco.de/blog/tailwind-jit-compiler-via-cdn

I realize that nobody would ever use these approaches for production, but they're quite nice for demos/tutorials. These don't currently seem to be supported by the extension. Would there be any way of making the extension work in these types of environments?

Thanks for the hard work! 👍

**Comment by bradlc** [comment]
Hoping to explore this soon! Closing in favour of #27
