### ISSUE TITLE
Directive Highlighting Issues

### ISSUE THREAD

**Issue by bigmike36c** [tailwindlabs/tailwindcss-intellisense#428]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7

**What version of Tailwind CSS are you using?**

v2.2.16

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Describe your issue**

I'm having issues with syntax highlighting working for certain tailwind directives. This issue only happens in .scss files as shown below. I tried adding sass/scss as an included language but this made no difference.

<img width="308" alt="Screen Shot 2021-10-11 at 1 06 52 AM" src="https://user-images.githubusercontent.com/81941044/136736164-b5f8703b-df1b-4cf2-9822-17ac2ff503d6.png">

It appears to be working properly for @apply but none of the other tailwind specific directives. I've also configured stylelint to work with tailwind and disabled all vscode's default linting. I'm not sure if there is anything else to try here.

**Comment by arekuusa** [comment]
+1
