### ISSUE TITLE
Getting strange output in Tailwind CSS Intellisense 

### ISSUE THREAD

**Issue by jhirn** [tailwindlabs/tailwindcss-intellisense#430]
Hey all. FIrst off, intellisense is actually working in most cases on my machien. However on every save I'm getting concerning output in the Tailwind CSS Intellisense output window. 

```shell
Found Tailwind CSS config file: /Users/jhirn/src/imnotart/nft_gallery/tailwind.config.js
Loaded postcss v8.3.11: /Users/jhirn/src/imnotart/nft_gallery/node_modules/postcss
Loaded tailwindcss v2.2.17: /Users/jhirn/src/imnotart/nft_gallery/node_modules/tailwindcss
undefined
[35m%s[0m
[32m%s[0m
undefined
undefined
[35m%s[0m
[32m%s[0m
undefined
undefined
[35m%s[0m
[32m%s[0m
undefined
undefined
[35m%s[0m
[32m%s[0m
undefined
```

Not sure what else to do for this. I'm running tailwind exclusively though the CLI and don't have postcss configured. It could be an issue with that but not really sure. I didn't see an option to enable more verbose output from the plugin so this is all i have to go on. 

**What version of Tailwind CSS IntelliSense are you using?**

v0.7.1

**What version of Tailwind CSS are you using?**
2.2.17

**What package manager are you using?**

esbuild

**What operating system are you using?**

osx

**Comment by bradlc** [comment]
Hey @jhirn. Very strange! Is it possible that the logs are being generated by a Tailwind plugin that you're using? 🤔

**Comment by jhirn** [comment]
It's possible. I've since stoped working on this project but it's very likely the problem was a conflicting plugin. I will close this for now as it's most likely not a real problem for you to be concerned with. 

Thanks for the follow up.
