### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by andreialecu** [tailwindlabs/tailwindcss-intellisense#432]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.1

**What version of Tailwind CSS are you using?**

v2.2.17

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Reproduction URL**

none

**Describe your issue**

Getting:

```
[Error - 10:42:06 PM] Tailwind CSS: Maximum call stack size exceeded
Error
    at new y (/Users/andreialecu/.vscode-insiders/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:286819)
    at /Users/andreialecu/.vscode-insiders/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:356021
    at Generator.next (<anonymous>)
    at o (/Users/andreialecu/.vscode-insiders/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:348919)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This is an angular project.

I actually had the same `Maximum call stack size exceeded` from webpack while building the project after adding tailwind and I fixed it by updating `webpack-sources`. 

Here's the related issue: https://github.com/webpack/webpack-sources/issues/131 where this is discussed.

**Comment by bradlc** [comment]
Hey @andreialecu, thanks for investigating this! The next release of Tailwind CSS IntelliSense will use a patched version of `enhanced-resolve` that should resolve your issue 👍
