### ISSUE TITLE
Emit wrong warnings with :class object in Vue template 

### ISSUE THREAD

**Issue by mockingjet** [tailwindlabs/tailwindcss-intellisense#433]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.1

**What version of Tailwind CSS are you using?**

v2.2.7

**What package manager are you using?**

yarn

**What operating system are you using?**

Windows

**Reproduction URL**

![image](https://user-images.githubusercontent.com/32839503/139632590-e8fa625c-06d2-4e51-924b-2f4aa6ad07e0.png)

![image](https://user-images.githubusercontent.com/32839503/139633039-1e06d15b-47d5-467a-bf1a-0d20801d7135.png)

**Describe your issue**

When using tailwindcss classes with Vue, I can put the same class but different values based on conditions within the class variable. And now it emits warnings.

**Comment by bradlc** [comment]
Hey @mockingjet. Are you using the `tailwindCSS.experimental.classRegex` setting at all?

**Comment by bradlc** [comment]
Going to close this for inactivity, but my guess is that you're using `tailwindCSS.experimental.classRegex` and your regular expression(s) is capturing those classes as part of one class list, when they should be two separate lists.
