### ISSUE TITLE
Same property detection not working when properties are between template literal placeholder

### ISSUE THREAD

**Issue by rokobekavac0** [tailwindlabs/tailwindcss-intellisense#434]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.1

**What version of Tailwind CSS are you using?**

 v2.2.15

**What package manager are you using?**

yarn v1.22.5

**What operating system are you using?**

Windows 10 19042

**Reproduction URL**

Not needed.

**Describe your issue**

Intellisense doesn't detect duplicate Tailwind properties when there is template literal placeholder ( `${expr}` ) between properties, as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/55251261/139643567-0abccf4d-8a7f-4094-add5-ae65f013aec5.png)

Works when they are on the same side.
![image](https://user-images.githubusercontent.com/55251261/139643971-681d792a-0a19-4083-8309-52d4147694e2.png)

**Comment by bradlc** [comment]
Hey, thanks for reporting! This will be fixed in the next release 👍
