### ISSUE TITLE
Tailwind extension stopped working with React-typescript project after VS Code update

### ISSUE THREAD

**Issue by HartS** [tailwindlabs/tailwindcss-intellisense#439]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.2

**What version of Tailwind CSS are you using?**

    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.3",

**What package manager are you using?**

npm

**What operating system are you using?**

OSX

**Describe your issue**

Earlier today, I restarted VS code and applied an update. After restarting, my React + typescript project no longer gets any tailwind class hints

I created a new workspace with tailwind and an HTML file to verify that the tailwind plugin is still working (it is). I wonder if this could be related to the non-standard tailwind version installed in my workspace. However, none of the dependencies have changed recently.

**Comment by bradlc** [comment]
Hey @HartS. What do you see in the output panel? (Run `Tailwind CSS: Show Output` from the command palette)

**Comment by HartS** [comment]
Hey @bradlc sorry I didn't update this. The issue was that I had `*.js` files excluded in my vscode project settings.json (becuase it's a Typescript project). Of course, the extension looks for `tailwind.config.js`, but couldn't find it because it was ignored. Actually I think I kept adding/removing that rule because I would want to access the tailwind config file and then get annoyed by build assets or node_modules dependencies showing up in my project search.

Actually, if the rule *isn't* in the vscode settings.json on startup, and then added after (to ignore *.js files), the extension loads and then continues working fine after. So I experienced restarting VS code breaking the extension, but it was actually just because of that `files.exclude: *.js` setting.

Quite confusing, maybe worth noting in the docs somewhere

**Comment by bradlc** [comment]
Ah got it! Thanks for the update. The `files.exclude` thing is [mentioned](https://github.com/tailwindlabs/tailwindcss-intellisense#troubleshooting) in the readme already, and the issue with it continuing to work after changing the setting should be fixed now 👍
