### ISSUE TITLE
Need way to ignore config inside of built folder 

### ISSUE THREAD

**Issue by arpowers** [tailwindlabs/tailwindcss-intellisense#440]
**What version of Tailwind CSS IntelliSense are you using?**
Latest 

**Describe your issue**

Inside of VSCode, this plugin is finding a "built" version of tailwind.config.js that is also in ESM. It is continually throwing this notification... "Tailwind CSS: Cannot use import statement outside a module"

<img width="660" alt="Screen Shot 2021-12-08 at 8 39 22 AM" src="https://user-images.githubusercontent.com/308134/145247687-e665c8d6-e96a-4818-807c-278b4d1e5586.png">

Is there a way to prevent this plugin from trying to autoload this file?

**Comment by bradlc** [comment]
You can now use the [`tailwindCSS.files.exclude` setting](https://github.com/tailwindlabs/tailwindcss-intellisense#tailwindcssfilesexclude) to exclude files from IntelliSense features, including Tailwind config files 👍
