### ISSUE TITLE
Error using tailwind language server

### ISSUE THREAD

**Issue by joshpetit** [tailwindlabs/tailwindcss-intellisense#441]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.3-1

**What version of Tailwind CSS are you using?**

v2.0.4

**What package manager are you using?**

yarn

**What operating system are you using?**

Arch

**Reproduction URL**

Any project

**Describe your issue**

I'm using the nvim lsp with the tailwind language server, and when I try running it now I receive this error:

```
[ERROR][2021-12-09 14:24:56] ...lsp/handlers.lua:404	"Unhandled exception: Cannot read properties of undefined (reading 'filter')\nTypeError: Cannot read properties of undefined (reading 'filter')\n    at matchClassAttributes (/usr/bin/tailwindcss-language-server:57:342673)\n    at /usr/bin/tailwindcss-language-server:57:342965\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/bin/tailwindcss-language-server:57:339949)"
```

It was working perfectly before, but this happened after a recent update so I'm not sure what's causing it. I'd file this with nvim lsp, but I don't have any problems with my other lsps. Some help would be appreciated! Thanks. Also I don't know if this is pertinent but when I run tailwindcss-language-server --version a large exception is thrown.

**Comment by joshpetit** [comment]
Never mind I just need to update my lspconfig haha.

**Comment by luiskhernandez** [comment]
@joshpetit Could you share how you fixed it? I'm having the same issue.

**Comment by joshpetit** [comment]
@luiskhernandez Yea, so I just updated my nvim-lspconfig. Did that with `PackerSync`, but you can do it with any utility you have. If you have problems downloading the update you might have conflicts like I did so I `cd`ed into `.local/share/nvim/site/pack/packer/start` and reverted the `nvim-lspconfig` repo then updated.
