### ISSUE TITLE
Config separator not work

### ISSUE THREAD

**Issue by IRediTOTO** [tailwindlabs/tailwindcss-intellisense#442]
**What version of Tailwind CSS IntelliSense are you using?**

Newest

**What version of Tailwind CSS are you using?**

3.0

**What package manager are you using?**

 yarn

**What operating system are you using?**

Windows

**Describe your issue**
Hi, I am trying to set Tw config like this
![image](https://user-images.githubusercontent.com/15695252/145508809-8da44ce4-ee86-406d-824d-674db7b19552.png)

But in editor it not work 
![image](https://user-images.githubusercontent.com/15695252/145511033-c7a56d64-65d9-447c-bdf1-a8aff4255cc5.png)

**Comment by bradlc** [comment]
Hey @IRediTOTO. The `separator` option lets you customize which character should be used to separate modifiers (screen sizes, `hover`, `focus`, etc.) from utility names (`text-center`, `items-end`, etc.). Your screenshot doesn't have any modifiers in it. Try typing `hover` or `focus` and you should see your separator:

<img width="512" alt="CleanShot 2021-12-13 at 17 53 25@2x" src="https://user-images.githubusercontent.com/2615508/145863280-553b4219-4122-4976-97ee-5a406f2bb57e.png">
