### ISSUE TITLE
Warn when `border-none` & `border-2` are used together

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/tailwindcss-intellisense#445]
**What version of Tailwind CSS IntelliSense are you using?**
v0.7.4

**What version of Tailwind CSS are you using?**
v3.0.0

**What package manager are you using?**
npm

**What operating system are you using?**
macOS

**Describe your issue**

Just need a warning as usual when `border-none` & `border-2` are used in conjunction. I couldn't see why my border won't show & it was because I had used `border-none` after setting `border-2`.

I mean the CSS properties are different underneath but I still think this should warn. Idk why it shouldn't?

**Comment by bradlc** [comment]
Hey @deadcoder0904. There isn't technically a conflict with `border-none` and `border-2`, because `border-none` sets `border-style` whereas `border-2` sets `border-width`. This would be a totally reasonable thing to write I think:

```html
<div class="border-none border-2 sm:border-solid"></div>
```

**Comment by deadcoder0904** [comment]
oh cool, it does cause a confusion when only `border-none` & `border-2` are used but wasn't so sure so i asked to confirm.
