### ISSUE TITLE
Autocompletion doesn't work after installing V3 

### ISSUE THREAD

**Issue by BuffaloDebile** [tailwindlabs/tailwindcss-intellisense#448]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.4

**What version of Tailwind CSS are you using?**

v3

**What package manager are you using?**

 CDN

**What operating system are you using?**

Windows 10

**Describe your issue**

Hi, I've just installed the new Tailwind  3 CDN using the <script src="https://cdn.tailwindcss.com"></script>
Then updated the VS code extension to v0.7.4 and the autocompletion doesn't work anymore.

Does anyone have an idea of why it doesn't work anymore? 
Thanks.

**Comment by Nzent** [comment]
Same problem

**Comment by bradlc** [comment]
Hey @BuffaloDebile. Do you have the `tailwindcss` module installed, and a valid `tailwind.config.js` file?

**Comment by BuffaloDebile** [comment]
Hi @bradlc thanks for your answer.

No I have just installed the play CDN 3, I do not want to do an NPM install. 
In the previous version, it was possible to have autocompletion with CDN, is this not the case anymore?

**Comment by signheim** [comment]
I have the same problem and got his log:

Found Tailwind CSS config file: /Users/me/Documents/frontend/Tailwind-3/boilerplate/tailwind.config.js
Loaded postcss v8.4.4: /Users/me/node_modules/postcss
Loaded tailwindcss v3.0.2: /Users/me/node_modules/tailwindcss
[Error - 5:16:54 PM] Tailwind CSS: format is not a function
TypeError: format is not a function
    at /Users/me/node_modules/tailwindcss/lib/lib/setupContextUtils.js:197:47
    at /Users/me/node_modules/tailwindcss/lib/lib/setupContextUtils.js:209:25
    at /Users/me/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:360540
    at Array.forEach (<anonymous>)
    at /Users/me/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:360034
    at /Users/me/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:362119
    at Generator.next (<anonymous>)
    at o (/Users/me/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:348919)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

I installed a config and tailwind css is also installed (v 3). I am using cli-mode. Interesting that Postcss is still checked. This did not appear before updating to tailwind css 3

**Comment by adrianmak** [comment]
Im using the new standalone tailwind css cli.
Does the extension work with it ?

**Comment by onurozer** [comment]
I'm having the same problem when using Tailwind CLI that comes with [tailwindcss-rails](https://github.com/rails/tailwindcss-rails). The extension doesn't autocomplete class names. VSCode output panel displays the error: 

`[Error] Tailwind CSS: Can't resolve 'tailwindcss' in '/rails7-project-folder/config'`

**Comment by pekosong** [comment]
works well tailwind v2

when i installed tailwind@lastest not working 

as same 

 Tailwind CSS: format is not a function

**Comment by austinbutler** [comment]
- OS: Arch Linux
- Package manager: Nix
- Tailwind version: CLI `v3.0.6`
- Tailwind extension version: `v0.7.4`
- Output panel:
```
[Error - 4:45:45 PM] Tailwind CSS: Can't resolve 'tailwindcss' in '/home/austin/Documents/web'
Error
    at new y (/home/austin/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.4/dist/server/tailwindServer.js:56:288476)
    at /home/austin/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.4/dist/server/tailwindServer.js:56:357793
    at Generator.next (<anonymous>)
    at o (/home/austin/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.4/dist/server/tailwindServer.js:56:350663)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
- Tailwind config:
```javascript
module.exports = {
  content: ["./templates/**/*.html"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

Checking `process.env.PATH` in VS Code dev tools I see `tailwindcss`  is there. Looking in the extension code it seems to be looking for `tailwindcss` in the same folder as the config file, which won't work. I could be missing another lookup but seems like the extension hasn't been updated for the standalone CLI yet?

**Comment by tesar-tech** [comment]
Same.
Using Standalone CLI (but I am not sure how to tell this fact to the extension). No node.js installed.

**Comment by sprite2005** [comment]
> I'm having the same problem when using Tailwind CLI that comes with [tailwindcss-rails](https://github.com/rails/tailwindcss-rails). The extension doesn't autocomplete class names. VSCode output panel displays the error:
> 
> `[Error] Tailwind CSS: Can't resolve 'tailwindcss' in '/rails7-project-folder/config'`

Same issue. Hoping there will be a fix for this soon.

**Comment by schmidp** [comment]
I am also using Rails 7 and get the following error:

```
[Error - 11:50:48 AM] Tailwind CSS: Can't resolve 'tailwindcss' in '/Users/schmidp/Development/xxxxx/config'
Error
    at new y (/Users/schmidp/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.4/dist/server/tailwindServer.js:56:288476)
    at /Users/schmidp/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.4/dist/server/tailwindServer.js:56:357793
    at Generator.next (<anonymous>)
    at o (/Users/schmidp/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.4/dist/server/tailwindServer.js:56:350663)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

```
% which tailwindcss                                                                                                                                                             
/opt/homebrew/lib/ruby/gems/3.0.0/bin/tailwindcss
```

**Comment by RooSoft** [comment]
On MacOS 12.1, I got the `tailwindcss` standalone executable in `/usr/local/bin`, and thus in the path. It's usable in the terminal, everything seems fine.

No help from the plugin in the editor... tried to copy the executable directly in the project's folder, same result.

Now, despite not depending on `npm` at all in the project, I've decided to make a `package.json` with `tailwindcss` as a dependency... `npm install`... and eureka, the plugin works.

Is there a way to tell the plugin where the standalone executable is, in order to remove that `npm` dependency?

**Comment by loicnestler** [comment]
Getting the same error as @signheim when trying to use the Tailwind CSS IntelliSense extension in my code-server instance:

```
Found Tailwind CSS config file: /root/workspace/xxx/yyy/tailwind.config.js
Loaded postcss v8.3.11: /root/workspace/xxx/yyy/node_modules/.pnpm/postcss@8.3.11/node_modules/postcss
Loaded tailwindcss v3.0.8: /root/workspace/xxx/yyy/node_modules/.pnpm/tailwindcss@3.0.8_0c54bdadaf9d9c9c6c134cb2c6c061a3/node_modules/tailwindcss
[Error - 1:03:48 AM] Tailwind CSS: format is not a function
TypeError: format is not a function
    at /root/workspace/xxx/yyy/node_modules/.pnpm/tailwindcss@3.0.8_0c54bdadaf9d9c9c6c134cb2c6c061a3/node_modules/tailwindcss/lib/lib/setupContextUtils.js:197:47
    at /root/workspace/xxx/yyy/node_modules/.pnpm/tailwindcss@3.0.8_0c54bdadaf9d9c9c6c134cb2c6c061a3/node_modules/tailwindcss/lib/lib/setupContextUtils.js:209:25
    at /root/.local/share/code-server/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:360540
    at Array.forEach (<anonymous>)
    at /root/.local/share/code-server/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:360034
    at /root/.local/share/code-server/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:362119
    at Generator.next (<anonymous>)
    at o (/root/.local/share/code-server/extensions/bradlc.vscode-tailwindcss-0.7.1/dist/server/tailwindServer.js:56:348919)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Are there any update on this?

**Comment by ahsf** [comment]
Same issue when using phoenix/tailwind, which also relies on standalone CLI.

**Comment by bradlc** [comment]
Hey all! We just released `v0.7.5` of the extension, which ships with a built-in version of `tailwindcss`. This means that IntelliSense now works without a local `tailwindcss` installation, for example if you are using the standalone CLI. You still need a valid [`tailwind.config.js` file](https://tailwindcss.com/docs/configuration), so make sure to create one if you haven't already (if you're using Rails or Phoenix the chances are you already have one and you should be good to go once you've updated the extension!)

CDN users can also create a `tailwind.config.js` file in a workspace to activate IntelliSense, just be aware that the config file is not actually being used by the CDN in this case (check out [the docs](https://tailwindcss.com/docs/installation/play-cdn) for how to use a custom config with the CDN)

If you run into any issues please let us know 🙏

**Comment by cabgfx** [comment]
Thank you all so much! Super appreciated ❤️

On January 7, 2022, GitHub ***@***.***> wrote:
> Hey all! We just released v0.7.5 of the extension, which ships with a
> built-in version of tailwindcss. This means that IntelliSense now
> works without a local tailwindcss installation, for example if you are
> using the standalone CLI. You still need a valid tailwind.config.js
> file <https://tailwindcss.com/docs/configuration>, so make sure to
> create one if you haven't already (if you're using Rails or Phoenix
> the chances are you already have one and you should be good to go once
> you've updated the extension!)
>
> CDN users can also create a tailwind.config.js file in a workspace to
> activate IntelliSense, just be aware that the config file is not
> actually being used by the CDN in this case (check out the docs
> <https://tailwindcss.com/docs/installation/play-cdn> for how to use a
> custom config with the CDN)
>
> If you run into any issues please let us know 🙏
>

—
Reply to this email directly, view it on GitHub
<https://github.com/tailwindlabs/tailwindcss-
intellisense/issues/448#issuecomment-1007643418>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAEBT7NHPTAIFH2GEWY3RULUU4XJ7ANCNFSM5J4YELEQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you are subscribed to this thread.Message
ID: <tailwindlabs/tailwindcss-
***@***.***>

**Comment by stephenbiggs** [comment]
The update doesn't seem to work for me. Anyone else experiencing the same?

**Comment by BobWalsh** [comment]
Anyone stumbling over the same issue of tailwind completion not happening in .erb files, see [Tailwind CSS autocomplete in VSCode with Ruby on Rails](https://medium.com/@spaquet/tailwind-css-autocomplete-in-vscode-with-ruby-on-rails-63a5fc24a1a4). It was the key for me.

**Comment by gmrcp** [comment]
After following the medium article @BobWalsh mentioned, I still couldn't get it to work.
What did it for me was following the recommended VSCode settings in the extension page that I completely jumped over 😅
This was the missing piece in the `settings.json`:
```
"editor.quickSuggestions": {
  "strings": true
}
```

**Comment by zackha** [comment]
If you are working with nuxt3, you can try this.

Add the following configuration to your `.vscode/settings.json file`, so that Tailwind directives have proper autocomplete, syntax highlighting, and linting:

```
"tailwindCSS.experimental.configFile": ".nuxt/tailwind.config.cjs"
"files.associations": {
    "*.css": "tailwindcss"
}
```

detailed: [link](https://tailwindcss.nuxt.dev/tailwind/editor-support)
