### ISSUE TITLE
when I use autocompletation to input className=“” Tailwind css does not give me suggestion

### ISSUE THREAD

**Issue by lifeike** [tailwindlabs/tailwindcss-intellisense#449]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.0

**What version of Tailwind CSS are you using?**

v2.0.4

**What package manager are you using?**

npm,
**What operating system are you using?**

ubuntu
**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

when I use autocompletation to input className=“”
Tailwind css does not give me suggestion
when I type className="" manually
Tailwind css does give me suggestion

plus: I have configured tailwind.config  includeLanguage correctly

**Comment by bradlc** [comment]
Hey @lifeike. This is a limitation of VS Code. There is no API to trigger completions following insertion of a completion from a different provider. You can manually trigger completions using the `Trigger Suggest` command (`Ctrl+Space` by default).

**Comment by sshmaxime** [comment]
Hey @bradlc , do you know if there is an open issue about that on VS Code ends ?
