### ISSUE TITLE
How is the extension licensed?

### ISSUE THREAD

**Issue by BenStorey** [tailwindlabs/tailwindcss-intellisense#450]
Hello,

I want to use this extension at work, but my company requires every extension to have a license. Can you please on either your github or the marketplace note which license it falls under?

Thanks!

**Comment by bradlc** [comment]
Hey @BenStorey. It's MIT, and I have added a license file here: https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/vscode-tailwindcss/LICENSE

Thanks for the heads up!
