### ISSUE TITLE
TailwindCSS Standalone CLI Intellisence issue

### ISSUE THREAD

**Issue by TheRajatSethi** [tailwindlabs/tailwindcss-intellisense#454]
Tailwind standalone cli version : 3.0.7
Env : Windows 11
Node Installed : No
Filetype : Tailwind Standalone CLI windows. exe

VS code Intelligence does not work with standalone CLI.

The output states `Tailwind CSS: Can't resolve 'tailwindcss`

**Comment by bradlc** [comment]
Hey @TheRajatSethi and @RooSoft. We just released `v0.7.5` of the extension, which ships with a built-in version of `tailwindcss`. This means that IntelliSense should now work for you, as long as you have a valid [`tailwind.config.js` file](https://tailwindcss.com/docs/configuration). Try it out and let me know if you run into any issues 🤙

**Comment by aptinio** [comment]
I'm confirming that 6fdef8616ab565ce29c15244dd77f59bb45d7e4d fixed this for me but I'm also encountering #459 on v0.7.5.
