### ISSUE TITLE
IntelliSense not working with Styled Components

### ISSUE THREAD

**Issue by hugohutri** [tailwindlabs/tailwindcss-intellisense#456]
Tailwind CSS IntelliSense version:  v0.7.4
Tailwind CSS version: v3.0.11
Package manager: yarn
Operating system: Ubuntu

Intellisense does not work with [styled-components](https://styled-components.com/).
![image](https://user-images.githubusercontent.com/55588133/148538332-871b2abb-32af-43dd-9ab2-f3c480aa7af6.png)

The RegEx doesn't allow the use of `:`-symbol after className. E.g: `className: "abc"`.
If the `:` is replaced with `=`, the suggestions will be visible.

![image](https://user-images.githubusercontent.com/55588133/148538501-a83666d7-1698-4368-93dd-247ee8fb1217.png)

### Solution
Add `:` to the RegEx

**Comment by bradlc** [comment]
Hey @hugohutri. Please take a look at my comment on #457 for my thoughts on this one 👍
