### ISSUE TITLE
Please publish the latest version (0.0.6?) of "@tailwindcss/language-server" to npm

### ISSUE THREAD

**Issue by yaegassy** [tailwindlabs/tailwindcss-intellisense#463]
**Describe your issue**

I am using the `@tailwindcss/language-server` package in Vim/Neovim's LSP client plugin.

Recently, `v0.7.5` of vscode-tailwindcss was released.

There appears to be an update to the code in the server package, so could you please publish the latest version of `@tailwindcss/language-server` to npm? 🙇

- Current version (v0.0.5): https://www.npmjs.com/package/@tailwindcss/language-server

---

> Add bundled version of tailwindcss. The extension will use this version if tailwindcss cannot be resolved within the workspace

In particular, this feature to fall back on, mentioned in the release notes, is very attractive!

- <https://github.com/tailwindlabs/tailwindcss-intellisense/releases/tag/v0.7.5>

**What version of Tailwind CSS IntelliSense are you using?**

v0.7.5

**What version of Tailwind CSS are you using?**

v3.0.7

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Comment by bradlc** [comment]
It's published 👍 Let me know if you run into any issues

**Comment by yaegassy** [comment]
Thanks! 🙇
