### ISSUE TITLE
0.7.5 - Intellisense will not activate

### ISSUE THREAD

**Issue by mbulfair** [tailwindlabs/tailwindcss-intellisense#464]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.5

**What version of Tailwind CSS are you using?**

v3.0.12

**What package manager are you using?**

npm

**What operating system are you using?**

For example: macOS, Windows

macOS

**Reproduction URL**

**Describe your issue**

I have several projects but whatever changed from 0.7.4 to 0.7.5 broke the extension for me. In 0.7.4 everything will work, single repo and lerna mono-repos, in 0.7.5 nothing works, I don't see errors, or the extension even activating. Sadly that's all I can tell at the moment as it doesn't seem to be any one of my projects.

**Comment by MysticEarth** [comment]
Visual Studio Code 1.63.2 (MacOS)
tailwindcss: "^3.0.13"

Same here. On both existing and new projects. Using 0.7.5:
<img width="874" alt="Screenshot-2022-01-13-21 36 42@2x" src="https://user-images.githubusercontent.com/1181488/149405403-b84443ee-3c78-4283-822b-0d426144b443.png">

Downgrading to 0.7.4 fixes the issue:
<img width="904" alt="Screenshot-2022-01-13-21 35 25@2x" src="https://user-images.githubusercontent.com/1181488/149405234-99e95a05-151c-4981-96e0-e64277e518d2.png">

**Comment by bradlc** [comment]
Hey @mbulfair. Is your Tailwind config file in a folder that's covered by your `files.exclude` setting?

**Comment by mbulfair** [comment]
I have a variety of projects some where TW is in the root, others it's nested. 0.7.4 works for all cases. 0.7.5 works for none. 
Example: 
* root
* * packages
* * * core
* * * tailwind.config.js

Otherwise it's in the root

**Comment by bradlc** [comment]
Thanks for sharing @mbulfair, that helped me to track down the issue 👍 This should be fixed in `v0.7.6`

**Comment by mbulfair** [comment]
Confirmed this works as it did previously
