### ISSUE TITLE
Intellisense not working in Next JS

### ISSUE THREAD

**Issue by DD10654** [tailwindlabs/tailwindcss-intellisense#469]
Hello Everybody! I started using Tailwindcss recently in a react project, and installed the Intellisense, but when I try it with next js it gives me an error in the output, Expected a non-empty string! Along with that the Intellisense does not work I saw previous solutions on github and stackovverflow but they don't seem to work... please help!

Tailwind Intellisense Version : v0.7.6

Tailwind Verison : 3.0.15

Package I am using : NPM

Operating System : macOS

Please help!
![Screenshot 2022-01-24 at 12 11 03 PM](https://user-images.githubusercontent.com/75024070/150734241-2347554a-cffa-42c0-b34c-fd9e42b750cc.png)

**Comment by bradlc** [comment]
Hey @DD10654. Could you share your VS Code settings please?

**Comment by DD10654** [comment]
> Hey @DD10654. Could you share your VS Code settings please?

uh how do I share that @bradlc ????

**Comment by bradlc** [comment]
@DD10654, You can run the `Preferences: Open Settings (JSON)` command from the command palette (`Cmd+Shift+P`), then copy/paste the JSON from there.

**Comment by DD10654** [comment]
It was getting too long for github, now I don't know if it needs to be 5,000 lines! I think this is the correct one!

Since I could not paste it on github without breaking it I posted it on this link, you don't need to sign in you can just preview the code normally! : https://replit.com/@DD106/PrivateLawngreenFilename#settings.json

**Comment by bradlc** [comment]
@DD10654, it looks like you opened the default settings by accident (`Preferences: Open Default Settings (JSON)`), which is why it's so big. You want to select `Preferences: Open Settings (JSON)` instead

**Comment by DD10654** [comment]
thank god it's only 58 lines! And thanks for the instant reply @bradlc 

{
    "liveServer.settings.donotShowInfoMsg": true,
    "editor.acceptSuggestionOnCommitCharacter": false,
    "liveServer.settings.useLocalIp": true,
    "liveServer.settings.AdvanceCustomBrowserCmdLine": "",
    "files.autoSave": "afterDelay",
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "bracket-pair-colorizer-2.unmatchedScopeColor": "Green",
    "bracket-pair-colorizer-2.depreciation-notice": false,
    "workbench.colorTheme": "Material Theme Palenight High Contrast",
    "workbench.colorCustomizations": {
        "[Material Theme Palenight High Contrast]": {
            "activityBarBadge.background": "#C6FF00",
            "activityBar.activeBorder": "#C6FF00",
            "list.activeSelectionForeground": "#C6FF00",
            "list.inactiveSelectionForeground": "#C6FF00",
            "list.highlightForeground": "#C6FF00",
            "scrollbarSlider.activeBackground": "#C6FF0050",
            "editorSuggestWidget.highlightForeground": "#C6FF00",
            "textLink.foreground": "#C6FF00",
            "progressBar.background": "#C6FF00",
            "pickerGroup.foreground": "#C6FF00",
            "tab.activeBorder": "#C6FF00",
            "notificationLink.foreground": "#C6FF00",
            "editorWidget.resizeBorder": "#C6FF00",
            "editorWidget.border": "#C6FF00",
            "settings.modifiedItemIndicator": "#C6FF00",
            "settings.headerForeground": "#C6FF00",
            "panelTitle.activeBorder": "#C6FF00",
            "breadcrumb.activeSelectionForeground": "#C6FF00",
            "menu.selectionForeground": "#C6FF00",
            "menubar.selectionForeground": "#C6FF00",
            "editor.findMatchBorder": "#C6FF00",
            "selection.background": "#C6FF0040",
            "statusBarItem.remoteBackground": "#C6FF00"
        }
    },
    "materialTheme.accent": "Acid Lime",
    "workbench.iconTheme": "vscode-icons",
    "files.exclude": {
        "": true,
        "**/.git": false
    },
    "editor.fontLigatures": true,
    "explorer.confirmDragAndDrop": false,
    "window.zoomLevel": 3
}

**Comment by DD10654** [comment]
Thank you so much I really loved the help you gave me! Some of my friends had quit Tailwindcss because of this NextJS Issue! I will definitely tell them this solution! I am also marking this Issue sovled!
