### ISSUE TITLE
Can't get Intellisense to initialize unless I do a fresh npx tailwindcss init

### ISSUE THREAD

**Issue by PhilippeGauthier** [tailwindlabs/tailwindcss-intellisense#471]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.6

**What version of Tailwind CSS are you using?**

3.0.15

**What package manager are you using?**

npm

**What operating system are you using?**

mac

**Describe your issue**

I can't get intellisense to initialize unless I create a fresh config file. I can copy my old config file into the freshly created file and the extension runs flawlessly. When starting up VS Code the extension isn't listed in my Output panel. After creating a new config file it is.

**Comment by bradlc** [comment]
Hey @PhilippeGauthier. Is your Tailwind config file covered by your `files.exclude` setting by any chance?

**Comment by PhilippeGauthier** [comment]
It isn't but I just cleared a bunch of unused settings out and it's working as expected. Thanks!
