### ISSUE TITLE
0.7.5 and 0.7.6 complete broken - won't even initialize

### ISSUE THREAD

**Issue by lukasz-karolewski** [tailwindlabs/tailwindcss-intellisense#474]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.5, v0.7.6 

**What version of Tailwind CSS are you using?**

v3.0.18

**What package manager are you using?**

npm

**What operating system are you using?**

ubuntu 20.10

**Describe your issue**

tailwind extension won't start after upgrading to 0.7.5, 0.7.6 doesn't work as well, extension won't even initialize, as `show output tailwind css` is completely empty, I couldn't find any logs, 

i've downgraded to 0.7.4 and everything works as expected. 

I have monorepo with this structure:
-python project
-web (nextjs, react)
-- tailwind.css.js
-node project

**Comment by bradlc** [comment]
Hey @lukasz-karolewski. Is your Tailwind config file covered by your `files.exclude` setting by any chance?

**Comment by lukasz-karolewski** [comment]
It's not, my files excludes looks like this: 
```
  "files.exclude": {
    "\"**/*.pyc\": {\"when\": \"$(basename).py\"}": true,
    "**/__pycache__": true
  },
```

**Comment by lukasz-karolewski** [comment]
still broken in 0.7.7

**Comment by lukasz-karolewski** [comment]
I think ideal solution is not to inherit glob patterns from the files.exclude

**Comment by bradlc** [comment]
Hey @lukasz-karolewski. It looks like you've misconfigured `files.exclude`. Here's the change you need to make:

```diff
  "files.exclude": {
-   "\"**/*.pyc\": {\"when\": \"$(basename).py\"}": true,
+   "**/*.pyc": {"when": "$(basename).py"},
     "**/__pycache__": true
  },
```
