### ISSUE TITLE
Not working specific folder

### ISSUE THREAD

**Issue by cngznNN** [tailwindlabs/tailwindcss-intellisense#475]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.6

**What version of Tailwind CSS are you using?**

v3.0.18

**What package manager are you using?**

NPM

**What operating system are you using?**

Windows

**Describe your issue**

It not working when there is a specific folder name, for example: [ui]\src\ 
Is working when there is a specific folder name, for example: ui\src\

**NOT WORKING**
![not working](https://user-images.githubusercontent.com/40668822/152674264-4ff31f9c-2167-423f-b09c-4e15e6124fc5.png)

**WORKING**
![working](https://user-images.githubusercontent.com/40668822/152674265-e3152179-095d-42d0-b56a-748f1dd2cd4f.png)

**Comment by bradlc** [comment]
This is fixed in `v0.7.7` 👍
