### ISSUE TITLE
0.7.6 - TailwindCSS.files.exclude not working

### ISSUE THREAD

**Issue by justmadden** [tailwindlabs/tailwindcss-intellisense#478]
**What version of Tailwind CSS IntelliSense are you using?**
0.7.6

**What version of Tailwind CSS are you using?**
v3.0.22

**What package manager are you using?**
yarn

**What operating system are you using?**
mac OS(m1)

**Describe your issue**
The plugin runs with this problem. The exclude property is not working for me.  Do you have any idea what is wrong?

```
Found Tailwind CSS config file: /Users/mainuser/Documents/boilerplate/app/tailwind/tailwind.config.js
Loaded postcss v8.4.6: /Users/mainuser/Documents/boilerplate/node_modules/postcss
Loaded tailwindcss v3.0.22: /Users/mainuser/Documents/boilerplate/node_modules/tailwindcss
[Error - 3:37:45 PM] Tailwind CSS: Cannot use import statement outside a module
/Users/mainuser/Documents/boilerplate/node_modules/react-native/index.js:14
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
```

**Comment by bradlc** [comment]
Hey! Thank you for your bug report!

I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get across all of our projects. Hope that's understandable!

**Comment by fortezhuo** [comment]
I have similar issue and same error. And here the workaround if you use twrnc, please require plugin from "tailwindcss/plugin" instead of "twrnc"

```
// tailwind.config.js
const { plugin } = require('twrnc'); // DON'T 

// or, you can use tailwinds plugin function:
const plugin = require('tailwindcss/plugin'); // DO THIS

module.exports = {
  plugins: [
    ....
  ],
};
```
