### ISSUE TITLE
Intellisense not working if `settings.files.exclude` is configured

### ISSUE THREAD

**Issue by kitsunekyo** [tailwindlabs/tailwindcss-intellisense#486]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.7

**What version of Tailwind CSS are you using?**

@tailwindcss/postcss7-compat

**What package manager are you using?**

yarn

**What operating system are you using?**

windows + wsl2

**Describe your issue**

we have a monorepo configured with vscode workspace where we alias some folders like

```json
{
  "folders": [
    {
      "name": "Client",
      "path": "client-app"
    },
    {
      "name": "Root",
      "path": "."
    }
```

we also alias the project root, and then exclude the folders from displaying via

```json
"settings": {
    "files.exclude": {
      "client-app/": true,
```

tailwind intellisense works perfectly fine if the `files.exclude` setting is not set. it seems like the tailwind extension can not read the tailwind.config.js with this setting. even though it is there. only the folder aliased

I'm unsure whether this is a bug or intentional, so feel free to close if thats the case.

**Comment by bradlc** [comment]
Hey @kitsunekyo. It's hard to tell what your setup looks like exactly without a reproduction repository, but I think what you're seeing is expected. Presumably your Tailwind config file is in the `client-app` folder, but because this is excluded the config file cannot be found.

**Comment by jhubbardsf** [comment]
Could there not be a better workaround for this? We had a similar issue at my work where we have use workspaces, include the root directory as a folder, and files.exclude the other folders so they don't show up in root. Copying the tailwind.config file to the root directory fixes the issue but it feels wrong.
