### ISSUE TITLE
Intellisense stops working after `<style dangerouslySetInnerHTML={{ __html: '...' }}  />` containing `>` in `__html`

### ISSUE THREAD

**Issue by TomerAberbach** [tailwindlabs/tailwindcss-intellisense#496]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.7

**What version of Tailwind CSS are you using?**

v3.0.23

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/TomerAberbach/tailwindcss-intellisense-repro

**Describe your issue**

https://github.com/TomerAberbach/tailwindcss-intellisense-repro/blob/main/index.jsx
```jsx
// Intellisense works on this line
const a = <div className='' />

const b = <style dangerouslySetInnerHTML={{ __html: `#x > * {}` }} />

// Intellisense doesn't work on this line (delete `const b = ...` and it'll start working)
const c = <div className='flex' />
```

**Comment by bradlc** [comment]
Hey @TomerAberbach, thanks for reporting! This should be fixed in the next release 👍

**Comment by TomerAberbach** [comment]
Rad, thanks for the fix!

**Comment by TomerAberbach** [comment]
Rad, thanks for the fix!
