### ISSUE TITLE
Intellisense only given for first match to regex defined by `classRegex` in the same file

### ISSUE THREAD

**Issue by benatshippabo** [tailwindlabs/tailwindcss-intellisense#499]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.7

**What version of Tailwind CSS are you using?**

^3.0.23

**What package manager are you using?**

Yarn 3

**What operating system are you using?**

MacOS Monterey 12.2

**Reproduction URL**

https://github.com/benatshippabo/tailwind-vscode-bug

**Describe your issue**

Using the following vscode settings:

```json
{
    "tailwindCSS.experimental.classRegex": [["/\\*tw\\*/ ([^;]*);", "'([^']*)'"]],
}
```

When there are multiple matches to the regex defined by `classRegex` in the same file, the tailwind extension only provides intellisense and autocompletion for the first match.

### first match
![image](https://user-images.githubusercontent.com/66273043/155822760-1b1e8960-289e-46c8-a067-8185c2f8efb5.png)

### second match
![image](https://user-images.githubusercontent.com/66273043/155822780-cdf44f8c-0f75-4d11-a5e0-d343da3047fb.png)

### context
https://github.com/tailwindlabs/tailwindcss/issues/7553#issuecomment-735915659
https://github.com/tailwindlabs/tailwindcss/issues/7553#issuecomment-917271069
https://github.com/tailwindlabs/tailwindcss/discussions/7554

**Comment by bradlc** [comment]
Hey @benatshippabo, thanks for reporting. This will be fixed in the next release 👍

**Comment by benatshippabo** [comment]
> Hey @benatshippabo, thanks for reporting. This will be fixed in the next release 👍

Oooh that was quick @bradlc, thanks you!
