### ISSUE TITLE
This extension causes vs code suggestions to open slow 

### ISSUE THREAD

**Issue by Nisthar** [tailwindlabs/tailwindcss-intellisense#505]
**What version of Tailwind CSS IntelliSense are you using?**
v0.7.7

**What version of Tailwind CSS are you using?**
^3.0.23

**What package manager are you using?**
npm

**What operating system are you using?**
windows 10

**Describe your issue**
I think this extension is causing my vscode intellisense to show suggestions slowly. It took like 5 seconds to show suggestions using this extension in a .svelte javascript code. after disabling this extension, it shows suggestions almost instantly now.

**Comment by bradlc** [comment]
Hey @Nisthar. Please can you share a screen recording of the issue?

**Comment by Nisthar** [comment]
> Hey @Nisthar. Please can you share a screen recording of the issue?

It doesn't seem to lag now after i reinstalled it again. before it was causing huge lag when opening intellisense.
