### ISSUE TITLE
Suggestion doesn't work

### ISSUE THREAD

**Issue by smithliam** [tailwindlabs/tailwindcss-intellisense#507]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.7

**What version of Tailwind CSS are you using?**

v3.0.12

**What package manager are you using?**

PNPM

**What operating system are you using?**

Windows

**Reproduction URL**

https://user-images.githubusercontent.com/101414008/160206288-e43ca15d-47a7-45ab-b2e2-95fa24bd1422.mp4

**Describe your issue**

I'm having this issue since the extension released and I thought it will get fix eventually but I guess people didn't report it? In the video you can see that there is few problems that need to be fixed. This problems isn't specific to the project that I'm currently working with. As I said I'm using the extension for a long time and it had this problem in every single project.

That's all. Let me know if I can help to fix this bug. Thanks

(Please don't close the issue until I respond to it)

**Comment by smithliam** [comment]
Check this out too:

https://user-images.githubusercontent.com/101414008/160210182-72a68dbc-6d5f-4927-80ca-4554f2af70e1.mp4

I have these 3 plugins installed for the project on the right side:

![Screenshot 2022-03-25 151055](https://user-images.githubusercontent.com/101414008/160210363-6ef4b783-5a0e-4067-9f69-bb5e8f9f3fc8.png)

**Comment by smithliam** [comment]
https://github.com/microsoft/vscode/issues/146088

https://github.com/microsoft/vscode/issues/146088#issuecomment-1079697134

**Comment by bradlc** [comment]
Hey @smithliam. This is built-in VS Code behaviour and there's nothing we can do about it as far as I'm aware, short of setting every single character as a "trigger character" for suggestions, which I don't think would be a good idea. There are a couple of things you can do:

- Set `editor.quickSuggestions.strings` to `true` – this can improve suggestion triggering in some cases
- Set `editor.suggest.snippetsPreventQuickSuggestions` to `false` – same as above
- Use `Ctrl+Space` to manually trigger suggestions

I hope that helps!

**Comment by smithliam** [comment]
@bradlc

![Screenshot 2022-04-02 030019](https://user-images.githubusercontent.com/101414008/161378093-b61ea34b-cd20-465d-a929-6355f808a939.png)

**Comment by smithliam** [comment]
thanks
