### ISSUE TITLE
ERB classes don't show tailwind css autocompletion in form helpers

### ISSUE THREAD

**Issue by ishanray** [tailwindlabs/tailwindcss-intellisense#515]
```
<%= form.select :select_field, options, {}, 
        class: 'w-full mt-1 rounded-lg border  text-zinc-700' %>
```
When using tailwindcss in rails, the erb templates don't show any autocompletion when they are using rails form helpers.

**Comment by swanson** [comment]
This was helpful, however I needed an additional regex to work with double quotes:

```
"tailwindCSS.experimental.classRegex": [
      "\\bclass:\\s*'([^']*)'",
      "\\bclass:\\s*\"([^\"]*)\""
    ],
```

**Comment by katekostina** [comment]
I added this to my config file but it doesn't work in RubyMine.
What could be a problem?
<img width="1011" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/60067138/3b7f4c9c-9940-4549-a1fc-20f7d4cbc8b2">

**Comment by rafaeldalago** [comment]
Or simply this to consider both single and double quotes:

```
"tailwindCSS.experimental.classRegex": [
    "\\bclass:\\s*['\"]([^'\"]*)['\"]"
  ]
```

**Comment by loomchild** [comment]
Thanks a lot for sharing, it works.

For anyone using NeoVim with `nvim-lspconfig`:

```
lspconfig.tailwindcss.setup{
  ...
  settings = {
    tailwindCSS = {
      experimental = {
        classRegex = { [[\bclass:\s*'([^']*)']], [[\bclass:\s*\"([^"]*)"]] }
      }
    }
  }
}
```

**Comment by Samuelodan** [comment]
Update!  I found a fix for RubyMine @katekostina and anyone else interested.
All it took was installing Tailwind within the project via `npm install -D tailwindcss` according to the [RubyMine Tailwindcss docs](https://www.jetbrains.com/help/ruby/tailwind-css.html#ws_css_tailwind_install).

It also enabled the feature that lets you see the resulting CSS on hover.
I should mention, though, that VS Code didn't require this additional install. It just worked.
