### ISSUE TITLE
Tailwind CSS: e.setup is not a function

### ISSUE THREAD

**Issue by maxleistner** [tailwindlabs/tailwindcss-intellisense#516]
I get the following error trying to use the plugin. I got a VUEJS project combined with tailwindcss. 

```
[Error - 2:11:35 PM] Tailwind CSS: e.setup is not a function
TypeError: e.setup is not a function
    at /Users/***/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:56:355960
    at Generator.next (<anonymous>)
    at s (/Users/***/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:56:344167)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by techfort** [comment]
@maxleistner did you manage to solve this? i'm also stuck

**Comment by maxleistner** [comment]
Yes - still got the error. I used yarnv3 but switched back to npm (v8) and node 16.2. - still get the error.

**Comment by maxleistner** [comment]
@bradlc any ideas? i am on tailwind ^3.0.25

**Comment by maxleistner** [comment]
Now it is evolving. Another character joined the error. 
```
Tailwind CSS: pe.setup is not a function
```

**Comment by bradlc** [comment]
@maxleistner Do you have a `.pnp.js` or `.pnp.cjs` file in your project?

**Comment by maxleistner** [comment]
> @maxleistner Do you have a `.pnp.js` or `.pnp.cjs` file in your project?

yes, but it is empty

**Comment by bradlc** [comment]
> yes, but it is empty

Ah ok, that explains it. Deleting that file and reloading the VS Code window should fix it. I will consider adding a try/catch to avoids errors in this scenario 🤔

**Comment by maxleistner** [comment]
oh yeah!! Thanks a lot
