### ISSUE TITLE
cssConflict v0.8.0 with Django in an if statement

### ISSUE THREAD

**Issue by tightropeboy** [tailwindlabs/tailwindcss-intellisense#524]
I'm using Tailwind CSS IntelliSense v0.8.0, Tailwind CSS v3.0.23, npm on Windows.

So today I updated **Tailwind CSS Intellisense** to v0.8.0 and one of my HTML file had two warning about **cssConflict**,
I'm Using **Django**, the **cssConflict** is risen in a conditional statement as it is shown in the attachments.
these warnings were not risen when having Tailwind CSS IntelliSense v0.7.7
![Problems Panel](https://user-images.githubusercontent.com/41797221/163266148-db267035-4fc9-4f1b-8bac-e1b9e65015a3.png)
![Code](https://user-images.githubusercontent.com/41797221/163266323-62a47df0-e6b3-4ec5-bfab-4c30e57165ba.png)

**Comment by bradlc** [comment]
Hey @tightropeboy, thanks for reporting. This was a regression introduced in `v0.8.0` via #503. That PR has been reverted for now and upgrading to `v0.8.1` should fix the issue 👍
