### ISSUE TITLE
Intelisence does not work after <template #slotName>

### ISSUE THREAD

**Issue by mreduar** [tailwindlabs/tailwindcss-intellisense#528]
**What version of Tailwind CSS IntelliSense are you using?**
v0.8.1

**What version of Tailwind CSS are you using?**

^v3.0.18

**What package manager are you using?**

npm

**What operating system are you using?**

Windows

**Reproduction URL**

https://github.com/mreduar/tailwind-intellisence-bug (a Laravel skeleton with jetstream and inertia.)
file `resources\js\Pages\Dashboard.vue` 

**Describe your issue**

If you enter the file described above you may notice that the extension does not work after the `<template #header>.` [on line 8](https://github.com/mreduar/tailwind-intellisence-bug/blob/master/resources/js/Pages/Dashboard.vue#L8)

If you delete the template then the rest works.

with `<template #header>.`
![image](https://user-images.githubusercontent.com/22550119/163504155-d8878054-dc05-4e80-9229-716334472b4b.png)

without `<template #header>.`
![image](https://user-images.githubusercontent.com/22550119/163504215-e12b2ad7-583a-4397-b662-cb08b064655b.png)

**Comment by vanling** [comment]
Same issue here and switching back to 0.7.7 "fixes" this for now:)

**Comment by mreduar** [comment]
Thank you @bradlc!
