### ISSUE TITLE
Color decorators shifts text in Diff view so it becomes less comparable

### ISSUE THREAD

**Issue by DrJume** [tailwindlabs/tailwindcss-intellisense#533]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.1

**What version of Tailwind CSS are you using?**

v3.0.24

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Reproduction URL**

**Describe your issue**

When using Git and opening a change inside a HTML-like file with Tailwind classes, the color decorators of the Tailwind IntelliSense extension only show on the 'right side'. When using the 'Inline View' (enable with Command Palette: 'Compare: Toggle Inline View') the problem becomes even more annoying, because the color indicators are only present on the green/added lines and not on the ones which are red/removed.

This leads to the color decorators shifting the text differently.

![image](https://user-images.githubusercontent.com/12785972/164030162-32392ebc-d91e-432e-a8e5-6cf7fa0e4f15.png)

The solution would be to add a (default) option, which hides the color indicators inside the VSCode Diff view.

**Comment by bradlc** [comment]
Hey @DrJume. This is standard VS Code behaviour. The same thing happens with CSS files:

<img width="304" alt="CleanShot 2022-04-19 at 15 46 22@2x" src="https://user-images.githubusercontent.com/2615508/164031319-98e1dccf-997c-4671-8980-9e0dc982da54.png">

I don't think there's any way to change this.
