### ISSUE TITLE
Please publish the latest version (0.0.8?) of "@tailwindcss/language-server" to npm

### ISSUE THREAD

**Issue by yaegassy** [tailwindlabs/tailwindcss-intellisense#536]
**Describe your issue**:

I am using the `@tailwindcss/language-server` package in Vim/Neovim's LSP client plugin.

Recently, "v0.8.2" of "vscode-tailwindcss" was released.

There appears to be an update to the code in the server package, so could you please publish the latest version of `@tailwindcss/language-server` to npm? 🙇

Current version (v0.0.7): https://www.npmjs.com/package/@tailwindcss/language-server

---

**What version of Tailwind CSS IntelliSense are you using?**:

v0.8.2

**What version of Tailwind CSS are you using?**:

v3.0.7

**What package manager are you using?**:

yarn

**What operating system are you using?**:

macOS

**Comment by bradlc** [comment]
I'll publish it today 👍

**Comment by yaegassy** [comment]
@bradlc ping

**Comment by yaegassy** [comment]
@bradlc Hi, it seems that the latest version of `@tailwindcss/language-server` has not been published to npm yet. If possible, please publish it. 🙇
