### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by osman-c** [tailwindlabs/tailwindcss-intellisense#540]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.2

**What version of Tailwind CSS are you using?**

v3.0.24

**What package manager are you using?**

npm

**What operating system are you using?**

Windows 11

**Reproduction URL**

https://github.com/osman-c/svelte-vite-tailwind-template

**Describe your issue**

The extension doesn't work even on html files.

When I open VSCode:

![image](https://user-images.githubusercontent.com/56242266/164942633-fb8748d3-9ebc-4b29-8c6f-eb0a11ed78d3.png)

After clicked:

`Found Tailwind CSS config file: c:\Users\fukgo\OneDrive\Desktop\Codes\svelte vite tailwind template\svelte-vite-tailwind-template\tailwind.config.js
Loaded postcss v8.4.12: c:\Users\fukgo\OneDrive\Desktop\Codes\svelte vite tailwind template\svelte-vite-tailwind-template\node_modules\postcss
Loaded tailwindcss v3.0.24: c:\Users\fukgo\OneDrive\Desktop\Codes\svelte vite tailwind template\svelte-vite-tailwind-template\node_modules\tailwindcss
[Error - 9:57:41 PM] Tailwind CSS: require() of ES Module c:\Users\fukgo\OneDrive\Desktop\Codes\svelte vite tailwind template\svelte-vite-tailwind-template\tailwind.config.js from c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js not supported.
Instead change the require of tailwind.config.js in c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js to a dynamic import() which is available in all CommonJS modules.
Error [ERR_REQUIRE_ESM]: require() of ES Module c:\Users\fukgo\OneDrive\Desktop\Codes\svelte vite tailwind template\svelte-vite-tailwind-template\tailwind.config.js from c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js not supported.
Instead change the require of tailwind.config.js in c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js to a dynamic import() which is available in all CommonJS modules.
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.Xd._require.Vi.default.require (c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:179:63908)
    at c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:690:10498
    at Generator.next (<anonymous>)
    at c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:1:1201
    at new Promise (<anonymous>)
    at Wt (c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:1:1021)
    at v (c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:690:9407)
    at c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:690:4208
    at Generator.next (<anonymous>)
    at c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:1:1201
    at new Promise (<anonymous>)
    at Wt (c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:1:1021)
    at x (c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:690:4173)
    at c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:690:9381
    at Generator.next (<anonymous>)
    at i (c:\Users\fukgo\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.2\dist\tailwindServer.js:1:1059)`

My VSCode settings:

`{
  "workbench.colorTheme": "Default Dark+",
  "editor.formatOnSave": true,
  "tailwindCSS.includeLanguages": {
    "html": "html",
    "javascript": "javascript",
    "css": "css",
    "svelte": "html"
  },
  "editor.quickSuggestions": {
    "strings": true
  },
  "svelte.enable-ts-plugin": true
}
`

**Comment by adamwathan** [comment]
Hey! Your config file can’t be ESM, has to be CJS. Not only will the extension not work, Tailwind itself won’t work at all either.

**Comment by osman-c** [comment]
Thanks for the input. I finally solved it. For anyone who is also struggling with this issue:

Change `tailwind.config.js` filename:

![image](https://user-images.githubusercontent.com/56242266/164966972-8ee94f11-22bc-473c-a5f3-b595c412df58.png)

In tailwind.config.cjs, instead of using `export default`:

![image](https://user-images.githubusercontent.com/56242266/164967035-f4e6a43c-4fc2-4701-baf0-015cbe400e13.png)
