### ISSUE TITLE
Intellisense is not working inside custom web component tags with `style` in the name

### ISSUE THREAD

**Issue by luizventurote** [tailwindlabs/tailwindcss-intellisense#542]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.3

**What version of Tailwind CSS are you using?**

v3.0.23

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Describe your issue**

I have created a web component called `styleguide-ui`, then I noticed that the autocomplete feature is not working for any tag inside this component. I think the extension is reading the custom tag `styleguide-ui` as a `style` tag.

Look this screen shoot:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/4708788/165589759-fa0d86b1-14e3-4d28-863e-506b513ea723.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/4708788/165589900-ed7a4ab3-56eb-4e08-a501-1955168850ff.png">

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4708788/165589846-3a10d44e-0925-48f3-956b-80c1aa3c9e76.png">

Then, if I use another name for my custom tag, it works:

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/4708788/165590183-774ce34d-c76d-4a81-bbe3-1b4056a2551d.png">

**Comment by bradlc** [comment]
Thanks for reporting! This will be fixed in the next release 👍
