### ISSUE TITLE
Where to include setting ? In tailwind.config.js or ... ?? Im confuse

### ISSUE THREAD

**Issue by AdiCahyaSaputra** [tailwindlabs/tailwindcss-intellisense#545]
**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.7.0

**What version of Tailwind CSS are you using?**

v3*

**What package manager are you using?**

 npm

**What operating system are you using?**

 windows

Im confuse where to add the setting, i try to add in tailwind.config.js but it doesnt work

**Comment by adamwathan** [comment]
Hey! Settings should be added to your VS Code settings:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/4323180/167278962-bd7e2bbf-a66a-4de0-8424-2fb855d1007a.png">
