### ISSUE TITLE
Feature Request: Add Intellisense compatibility to rust (Yew)

### ISSUE THREAD

**Issue by wildcant** [tailwindlabs/tailwindcss-intellisense#546]
Hey guys, thank you all for this cool extension.

Today I've being playing around with [Yew](https://yew.rs/),  I added tailwind and works nice but I would like to have intellisense as well. I was taking a look at the source code and testing it locally, and it doesn't seems so hard to add compatibility to rust, as far as I can see we could add a new util function like `isRustContext` or `isYewHtmlContext` and add it to the [provideClassNameCompletions](https://github.com/wildcant/tailwindcss-intellisense/blob/bc2e5edd45f5f0e87632e6d9490b132c1d759f47/packages/tailwindcss-language-service/src/completionProvider.ts#L514) function.

<img width="771" alt="Screen Shot 2022-05-07 at 8 32 15 PM" src="https://user-images.githubusercontent.com/48843517/167278034-0126b989-cc3d-43cb-b8c2-2f1b2d620f97.png">

I'm happy to open a PR for this 😃
What do you think, am I missing something?

**Comment by devgony** [comment]
@bradlc What you suggested worked to recognize each class name but does not automatically show hover popup 😢.
Whenever i write className i should press "opt + `" manually..
Do you know any way to solve?
