### ISSUE TITLE
Aspect ratio bug

### ISSUE THREAD

**Issue by Tazi0** [tailwindlabs/tailwindcss-intellisense#549]
**What version of Tailwind CSS IntelliSense are you using?**
v0.8.3

**What version of Tailwind CSS are you using?**
"@nuxtjs/tailwindcss": "^5.0.4"

**What package manager are you using?**
npm

**What operating system are you using?**
MacOS

**Reproduction URL**
Upgrade your (nuxt) Tailwind from v2 to v3

**Describe your issue**
I am upgrading to v3 but sadly the intellisense doesn't see the upgrade so doesn't show me any popup for aspect ratio unlike width etc.
Normal popup for width:
<img width="278" alt="Screenshot 2022-05-12 at 14 10 31" src="https://user-images.githubusercontent.com/45716542/168072063-9f7525cd-575b-439b-8f6f-40e0b31defe1.png">
Aspect ratio:
(no screenshot because there is no info)

**Comment by bradlc** [comment]
Hey please can you share a GitHub repository that I can clone and open in VS Code to reproduce the issue?

**Comment by Tazi0** [comment]
Heya, this is a private repository, but I will add you to the repo

**Comment by bradlc** [comment]
Thanks @Tazi0. Your project uses ES module syntax in the `tailwind.config.js` file, and this is not currently supported by the extension, since this is not supported natively by Tailwind CSS itself. Using common JS modules instead may fix your issue, i.e.

```diff
- export default {
+ module.exports = {
```

I hope that helps!
