### ISSUE TITLE
The extension does not work in typescript files

### ISSUE THREAD

**Issue by StefanGhiban** [tailwindlabs/tailwindcss-intellisense#564]
**What version of Tailwind CSS IntelliSense are you using?**

0.8.6

**What version of Tailwind CSS are you using?**

^3.0.23

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Describe your issue**

I have a vue project that runs on vite. I have added the extension in vs code and everything works fine in .vue components in the template sections and also in css files. The problem that I am encountering is related to typescript files and js files. I am using a form framework(formkit) that has a ts config file for the theme where I can use some tailwind. The problem is that I dont get any features from the vs code extension in .ts files. I have added the settings: true to the settings.json and also included typescript in the included languages for tailwindcss. I have even deleted the tailwind config and recreated it hoping that it might work, but it still does not.

**Comment by StefanGhiban** [comment]
Solved this by adding:
```
"tailwindCSS.experimental.classRegex": [
  "/\\*\\s*tw\\s*\\*/\\s*'([^']*)'",
  "/\\*\\s*tw\\s*\\*/\\s*\"([^\"]*)\"",
]
``` 
to the settings.json of vscode.
Then adding /*tw*/ in front of strings would enable tailwind intelisense for those variables like in the following example:
```
file: {
        label: /*tw*/ "block mb-1 font-bold text-sm",
        inner: /*tw*/ "max-w-md cursor-pointer",
        input: /*tw*/ "text-gray-600 text-sm mb-1 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:bg-blue-500 file:text-white hover:file:bg-blue-600",
        noFiles: /*tw*/ "block text-gray-800 text-sm mb-1",
        fileItem: /*tw*/ "block text-gray-800 text-sm mb-1",
        removeFiles: /*tw*/ "ml-auto text-blue-500 text-sm",
    },
   ```

**Comment by everythinginjs** [comment]
that does not work if you have prefixed tailwind classes
