### ISSUE TITLE
Cannot find module 'bradlc.vscode-tailwindcss'

### ISSUE THREAD

**Issue by X-Equals-Zero** [tailwindlabs/tailwindcss-intellisense#568]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.6 

**What version of Tailwind CSS are you using?**

v3.1.4

**What package manager are you using?**

NPM

**What operating system are you using?**

Windows 10

**Reproduction URL**
Irrelevant. The same issue across multiple projects and tailwind versions.

**Describe your issue**

Autocomplete completely fails to work. 
In the output console of the extension host process, 
`[exthost] [error] Activating extension bradlc.vscode-tailwindcss failed due to an error:
[2022-06-22 15:19:32.613] [exthost] [error] Error: Cannot find module 'c:\Users\root\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.6\dist\extension.js'`

I checked and it seems that file does not exist at the given directory.  Tried reinstalling the plugin, tried restarting vscode, I don't know what else to do.

**Comment by X-Equals-Zero** [comment]
I removed the extension and installed the latest version through a .VSIX file, which fixed the problem. Before, I also tried installing it through elevated VS Code in the Extensions tab, which didn't work either, so I do not think it's a permissions issue.

**Comment by bradlc** [comment]
No idea what's going on here but it sounds like a VS Code issue to me. Are you still not able to install the extension from the marketplace?

**Comment by bradlc** [comment]
Closing this as not received a response in a while, but also this doesn't seem like an issue with the extension to me. Maybe some gremlins in your VS Code setup? You could try reinstalling VS Code completely.
