### ISSUE TITLE
Neovim is broken with tailwindcss

### ISSUE THREAD

**Issue by login6** [tailwindlabs/tailwindcss-intellisense#569]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.0

**What version of Tailwind CSS are you using?**
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.0

**What version of Tailwind CSS are you using?**
v2.0.4

**What package manager are you using?**

 npm

**What operating system are you using?**

Debian 11

**Reproduction URL**

https://github.com/neovim/neovim/issues/19118

**Describe your issue**

Neovim is very popular editor but tailwindcss not working properly with it. All other LSP working fine. Probably some problems in tailwindcss implementaion. When i use completion menu - memory growing and growing slowly beyound 1GB, some documentation, cache - don't know. Any idea what's going on?

https://user-images.githubusercontent.com/96973293/176535055-a70a4059-a25f-4961-b169-2c2a275ebeb2.mp4

**Comment by toto1384** [comment]
Same problem here

**Comment by tomchart** [comment]
ditto

**Comment by jones-sam** [comment]
I have the same issue. I had it working before with coc, but now with nvim lsp tailwind is taking a bunch of ram and making neovim run laggy

**Comment by luiscassih** [comment]
Having the same issue, tried a few older versions and only 0.0.5 seems a bit faster and less memory usage, but still, using 300mb+ is not a good experience :/

**Comment by siblanco** [comment]
Yup can also confirm. Memory usage goes to the moon and neovim gets laggy.
Happens only when the tailwind lsp is attached and actually suggesting classes...just being attached does not affect the memory usage.

**Comment by hamooo-d** [comment]
did you guys find any solution? even if it's a temporary, tailwind LSP is starting to get annoying to work with.

**Comment by siblanco** [comment]
@hamooo-d unfortunately no, nothing new. Here are more details: https://github.com/neovim/neovim/issues/19118#issuecomment-1221522853

To me it looks like an issue with nvim-cmp. I have no problems when using the lsp without nvim-cmp.

**Comment by Shougo** [comment]
It seems `nvim-cmp` problem instead of `nvim-lsp`.

**Comment by username664** [comment]
Some explonations:
https://github.com/hrsh7th/nvim-cmp/issues/1009#issuecomment-1257179645

**Comment by login6** [comment]
https://github.com/hrsh7th/nvim-cmp/issues/1009#issuecomment-1257179645

**Comment by login6** [comment]
> [hrsh7th/nvim-cmp#1009 (comment)](https://github.com/hrsh7th/nvim-cmp/issues/1009#issuecomment-1257179645)

@hrsh7th @bradlc any idea why tailwindcss server always returns the 9k items?

**Comment by bradlc** [comment]
It returns ~9,000 items because that's how many Tailwind classes are available. We actually just did a lot of work to reduce the total size of the completion response and it's about 90% smaller than it was (assuming your client supports `itemDefaults`), so hopefully you will see a difference 👍

**Comment by folke** [comment]
This has been fixed in nvim-cmp in the meantime

**Comment by login6** [comment]
> This has been fixed in nvim-cmp in the meantime

any plans for async implementation in the future?)

**Comment by folke** [comment]
My PR also improved performance and tbh it's good enough for me for now :)
