### ISSUE TITLE
The language service doesn’t extract colors from arbritary strings (Tailwind CLI does)

### ISSUE THREAD

**Issue by remcohaszing** [tailwindlabs/tailwindcss-intellisense#574]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.6

**What version of Tailwind CSS are you using?**

v3.1.5

**What package manager are you using?**

npm

**What operating system are you using?**

Pop!_OS 22.04

**Reproduction URL**

Just run `npm install tailwindcss`, then create the following: `tailwind.config.js`:

```js
module.exports = {
  content: ['*.js']
};

const className = 'text-red-500'
const foo = 'text-green-500'
```

**Describe your issue**

The Tailwind CLI will extract both `text-red-500` and `text-green-500`. However, when the project is opened in VS Code with the Tailwind CSS IntelliSense plugin active, it will only show a color decoration for `text-red-500`.

**Comment by bradlc** [comment]
Hey @remcohaszing. There's no way for the extension to know that `foo` is a string containing CSS classes. If you really want to enable IntelliSense features for all strings you may have some success with the `tailwindCSS.experimental.classRegex` setting:

```
"tailwindCSS.experimental.classRegex": [
  "'([^']*)'"
]
```

More info here: https://github.com/tailwindlabs/tailwindcss/issues/7553#issuecomment-735915659
