### ISSUE TITLE
typescript-require breaks VSCode extension

### ISSUE THREAD

**Issue by AndyOGo** [tailwindlabs/tailwindcss-intellisense#577]
**What version of Tailwind CSS IntelliSense are you using?**

`v0.8.6`

**What version of Tailwind CSS are you using?**

`v3.1.2`

**What package manager are you using?**

```sh
$ node -v
v16.13.0
$ npm -v
8.1.0
```

**What operating system are you using?**

Redhat Linux

**Describe your issue**

I'm using [`typescript-require`](https://www.npmjs.com/package/typescript-require) to load configurations in my `tailwind.config.js` file, like:

```js
// Initialize
require('typescript-require');

const { colors } = require("./colors");

/** @type {import("tailwindcss/tailwind-config").TailwindConfig} */
module.exports = {
  content: ["./src/**/*.{html,ts,tsx}"],
  theme: {
    colors,
  },
};
```
`colors.ts`
```js
export const colors = {
  transparent: "transparent",
  current: "currentColor",
  white: "#FFF",
  black: "#000",
```

**Comment by bradlc** [comment]
Hey @AndyOGo. I can't reproduce the issue, are you able to share your project?

**Comment by AndyOGo** [comment]
Hey @bradlc.

I clarified the issue with a colleague.

The problem only arises when we omit the `.ts` extension - also within TS files.

**Comment by AndyOGo** [comment]
Seems to be a limitation of node itself according to that issue
https://github.com/TypeStrong/ts-node/issues/116

**Comment by AndyOGo** [comment]
Alright, now I got it working with [`experimentalResolver`](https://typestrong.org/ts-node/api/interfaces/RegisterOptions.html#experimentalResolver)

```js
require("ts-node").register({
  preferTsExts: true,
  experimentalResolver: true,
});

const { colors } = require("./colors");
```

**Comment by bradlc** [comment]
Found a fix for this so your original version should work in the next release 👍
