### ISSUE TITLE
Licensing mismatch

### ISSUE THREAD

**Issue by hyandell** [tailwindlabs/tailwindcss-intellisense#589]
**What version of Tailwind CSS IntelliSense are you using?**

0.0.7

**What version of Tailwind CSS are you using?**

n/a

**What package manager are you using?**

npm

**What operating system are you using?**

n/a

**Reproduction URL**

n/a

**Describe your issue**

Looking at the licensing of the https://registry.npmjs.org/@tailwindcss/language-server/-/language-server-0.0.7.tgz the GPL-3.0 license for multi-regexp2@1.0.3 seems out of sorts with the overall licensing of the rest of your package. It seems to be tightly used in this https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/tailwindcss-language-service/src/util/createMultiRegexp.ts file. Digging into the https://www.npmjs.com/package/multi-regexp2/v/1.0.3 package it lacks metadata declaring the license, but does have a LICENSE file that includes GPL-3.0.

I wanted to flag this to you in case it hadn't flagged for you previously and is a concern for your licensing intents.

**Comment by bradlc** [comment]
Hey @hyandell. Thank you for flagging this. I was aware that `multi-regexp2` was GPL but I misunderstood the license terms originally. After reviewing I have replaced this module with a different one that is MIT licensed. Thanks again!
