### ISSUE TITLE
TailwindCSS CPU issues... using whole or half of CPU.

### ISSUE THREAD

**Issue by temrb** [tailwindlabs/tailwindcss-intellisense#593]
**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.7.0

**What version of Tailwind CSS are you using?**

For example: v2.0.4

**What package manager are you using?**

For example: npm, yarn

**What operating system are you using?**

For example: macOS, Windows

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

Tailwind is using whole or half of CPU when idle
![Screenshot 2022-08-10 at 3 50 54 PM](https://user-images.githubusercontent.com/22056864/184017738-3eb0d294-e749-4ceb-a162-048b3b10e542.png)
![Screenshot 2022-08-10 at 3 51 15 PM](https://user-images.githubusercontent.com/22056864/184017740-452bf53a-ac35-4517-8786-27ec992d6205.png)
...

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by bradlc** [comment]
Hey @temrb. Unfortunately there's not much I can do with so little information. What editor are you using and how is the language server configured? What does your project look like? If you can share it even better 🙏

**Comment by temrb** [comment]
@bradlc  just saw there's another issue open regarding CPU issues similar to my environment-- vscode dating back to December. #444 saw it has yet to be fixed.

**Comment by thecrypticace** [comment]
Closing in favor of #444 

If you can provide a project that consistently exhibits / reproduces this problem that would be very helpful. If you can please add a comment and link it in #444.
