### ISSUE TITLE
Support for Astro `class:list`

### ISSUE THREAD

**Issue by surjithctly** [tailwindlabs/tailwindcss-intellisense#595]
**Describe your issue**

TailwindCSS auto-complete is not working on `.astro` projects with `class:list` property. 

```html
Example *.astro project. 

// it works
<div class="text-">

// not working
<div class:list={["text-"]}
```

**Related:**
Astro also supports javascript inside `---` frontmatter. So we could also write:

```astro
---
const color = {
	blue: "from-blue-600 to-blue-700",
	red: "from-red-500 to-red-600",
};
---
```

it would be great if IntelliSense also worked on this. 

**What version of Tailwind CSS IntelliSense are you using?**

0.8.6

**What version of Tailwind CSS are you using?**

3.1

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Comment by bradlc** [comment]
Hey @surjithctly.

> TailwindCSS auto-complete is not working on .astro projects with class:list property.

You can use the `tailwindCSS.classAttributes` setting to enable autocomplete for additional attributes:

```
"tailwindCSS.classAttributes": ["class", "className", "ngClass", "class:list"]
```

> **Related:**
> Astro also supports javascript inside `---` frontmatter. So we could also write:
> 
> ```astro
> ---
> const color = {
> 	blue: "from-blue-600 to-blue-700",
> 	red: "from-red-500 to-red-600",
> };
> ---
> ```
> 
> it would be great if IntelliSense also worked on this.

It's not possible for the extension to know that those strings contain CSS classes. However, you can use the `tailwindCSS.experimental.classRegex` setting to enable autocomplete in custom places. For example if you always suffix variable names containing classes with `classes` you could enable autocomplete for these with something like this:

```
"tailwindCSS.experimental.classRegex": [
  ["[cC]lasses\\s*=\\s*{([^}]+)}", "\"([^\"]*)\""]
]
```

This would enable autocomplete in these cases:

```js
let classes = {
  blue: "_",
}

let buttonClasses = {
  blue: "_",
}
```

I hope that helps!
