### ISSUE TITLE
`undefined` doesn't remove the class

### ISSUE THREAD

**Issue by babakfp** [tailwindlabs/tailwindcss-intellisense#609]
**What version of Tailwind CSS are you using?**

v3.1.8

**Reproduction URL**

https://play.tailwindcss.com/3kRy1GbH6z

**Describe your issue**

For example, I want to remove `black: #000` from the colors object, So, I do this:

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        black: undefined,
      },
    },
  },
}

```

 The issue is that the color `black` will still be suggested.

Maybe it's something related to tailwind itself because the key `black` still does exist in the colors object. Maybe tailwind can remove the item if the value is equal to `undefined`.

Thanks

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Going to leave it open and let @bradlc decide what to do with this. However, one thing you can do is set the value to `null` instead of `undefined` which doesn't suggest `bg-black` anymore.

https://play.tailwindcss.com/eHCuHrnxdL

**Comment by bradlc** [comment]
@RobinMalfait, I believe this is a bug in `tailwindcss` itself, in the `getClassList` function. I think we need to check for `undefined` values (and other falsy values?) in this loop? https://github.com/tailwindlabs/tailwindcss/blob/master/src/lib/setupContextUtils.js#L840-L845

**Comment by RobinMalfait** [comment]
Ah yep, good catch. I'll fix that!
