### ISSUE TITLE
bradlc-vscode-tailwindcss not compatible with VS Code 1.59.0

### ISSUE THREAD

**Issue by AbubakarImam** [tailwindlabs/tailwindcss-intellisense#610]
IntelliSence: v0.8.7
**What version of Tailwind CSS are you using?**

v: 6.14.15

**What package manager are you using?**

npm

**What operating system are you using?**

Windows

**Describe your issue**

The extension stop working after I installed a update of my VS-CODE to v:1.59.0. I tried reinstalling but I am having an error that the extension is not compatible with the version of VS-CODE

**Comment by bradlc** [comment]
Hey @AbubakarImam. The extension is compatible with VS Code version `1.65` or newer. I recommend you upgrade to the latest version (currently `1.71`) 👍
