### ISSUE TITLE
Extension does not load in a multi-root workspace if the project folder is excluded in a different root

### ISSUE THREAD

**Issue by michaelschufi** [tailwindlabs/tailwindcss-intellisense#615]
**What version of Tailwind CSS IntelliSense are you using?**

0.8.7

**What version of Tailwind CSS are you using?**

3.1.7

**What package manager are you using?**

pnpm

**What operating system are you using?**

Linux Ubuntu 20.04 in WSL2 on Windows 10

**Reproduction URL**

https://github.com/michaelschufi/temp-twcss

**Describe your issue**

1. Clone the repo.
2. Open the VS Code workspace using the `temp-twcss.code-workspace` in the root of the repo.
3. Go to  `website/pages/index.tsx:16` and try to get suggestions from TailwindCSS Intellisense. It will not work.
4. Comment out the file exclusion rule (`"website/**": true`) at `temp-twcss/.vscode/settings.json:4`.
5. Go to  `website/pages/index.tsx:16` and try to get suggestions from TailwindCSS Intellisense. It will work.

I expect the extension to work, since I open a file in the root `website` and not in the `temp-twcss`.

I also tried with `tailwindCSS.experimental.configFile` but this setting does not work at all in multi-root workspaces.

Note: Opening the folder `website` as a new VS Code window works.

**Comment by bradlc** [comment]
Hey @michaelschufi, thanks for reporting this! Should be fixed in the next release (`v0.9.2`) 🤙

**Comment by dumbasPL** [comment]
> Should be fixed in the next release 

About that... It's been 27 days and no release. I'm facing the same issue btw
