### ISSUE TITLE
tailwindCSS.experimental.configFile only accepts a relative path

### ISSUE THREAD

**Issue by skattabrain** [tailwindlabs/tailwindcss-intellisense#616]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.7

**What version of Tailwind CSS are you using?**

v3.1.6

**What package manager are you using?**

PNPM

**What operating system are you using?**

MacOS

**Reproduction URL**

--

**Describe your issue**

Looks like you can only use a relative path, even a complete path like "/Users/me/my/really/large/mono/repo/project/tailwind.config.js" will not work. This is a large mono-repo that contains several projects, both front and backend. A frontend dev might open the repo in VS Code in different places, often opening where the project resides to save on memory/performance issues. Several projects reference our 1 config file.

Error output becomes - 
```
Tailwind CSS: ENOENT: no such file or directory, open '/Users/me/project/~/my/really/large/mono/repo/project/tailwind.config.js'
```

We would like to add some VS Code settings to our source control in order to point to our 1 tailwind.config.js.

**Comment by skattabrain** [comment]
Correction, I forgot we actually have 2 configs (2 different themes) - Still a problem if deleting 1 though... would really like to use an absolute path.

**Comment by bradlc** [comment]
Hey @skattabrain, thanks for reporting this! Will be fixed in the next release 👍
