### ISSUE TITLE
Individual packages within monorepo don't work in isolated multi-root workspace

### ISSUE THREAD

**Issue by agusterodin** [tailwindlabs/tailwindcss-intellisense#619]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.7

**What version of Tailwind CSS are you using?**

v3.1.8

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Reproduction URL**

Not repository specific. This is strictly about the behavior of VS code. Folder structure alone is enough to convey context.

**Describe your issue**

My organization uses a UI monorepo to house code for multiple products (along with a common UI library).

Here is the structure of my monorepo:

- ui-monorepo
   - product1
   - product2
   - ...
   - common (tailwind.config.js lives inside here)

****

I am attempting to create separate workspaces for each of our company's projects.

I want to create individual workspaces for each product so that I can do ui, common ui, and server work together without being overwhelmed with so many files/folders (and cluttered project cmd+f search).

For example, this workspace file is called Product1.workspace. It is a multi-root workspace.

- product1 (this points product1 folder inside monorepo)
- common (this points to common folder inside monorepo)
- product1-server (this points to a folder somewhere else on my machine that contains backend code)

The IntelliSense suggestions do not show up when working with html/jsx inside the product1 folder. They DO however show up when working with html/jsx inside the common folder.

I have searched through other GitHub issues in this repository relating to monorepo multi-root workspaces and have tried to find a solution there to no avail. 

I also tried adding the `tailwindCSS.experimental.configFile` property to my workspace configuration with a value of `../common/tailwind.config.js` so that the extension would look backward a folder when working with files inside of product1. I also tried playing adding the `watcherInclude` property with a value of `../common/tailwind.config.js` in hopes that it would allow VSCode to "see" the file. Unfortunately this didn't work either.

**Comment by bradlc** [comment]
Hey @agusterodin, thanks for reporting this. I've made some [improvements](https://github.com/tailwindlabs/tailwindcss-intellisense/pull/640) to how the `experimental.configFile` setting is handled so that a workspace config like below should work for your use-case:

```
{
  "folders": [
    {
      "path": "common"
    },
    {
      "path": "product1"
    }
  ],
  "settings": {
    "tailwindCSS.experimental.configFile": "common/tailwind.config.js"
  }
}

```

This will be available in the next release (`v0.9.2`). Let me know if you run into any issues with it 👍
