### ISSUE TITLE
Suggestions break when separator starts with `-`

### ISSUE THREAD

**Issue by peritpatrio** [tailwindlabs/tailwindcss-intellisense#625]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.7

**What version of Tailwind CSS are you using?**

v3.0.23

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Describe your issue**

I am trying to use `md--w-full` instead of  `md:w-full` in my project. However, when setting a custom separator that _begins_ with `-` the plugin stops suggesting class names. If the separator is set to `_-` everything works fine. 

**tailwind.config.js**
```js
module.exports = {
  separator: '--'
};
```

**Comment by bradlc** [comment]
Hey @peritpatrio, thanks for reporting this. Should be fixed in the next release 👍
