### ISSUE TITLE
Suggestions only show color classes

### ISSUE THREAD

**Issue by itsnotpolza** [tailwindlabs/tailwindcss-intellisense#643]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

v3.2.0

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Describe your issue**

Using tailwind in vs code shows only color (?) suggestions for classnames so like in examples below if i want to use a text-lg class or a flex it does not suggest the relevant classes. 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/52533333/197201103-83ddd818-a9b2-48a4-a566-04f5aabfab3f.png">
<img width="593" alt="image" src="https://user-images.githubusercontent.com/52533333/197201347-25389f77-2676-42cf-a5e9-14774f0ef3c2.png">

**Comment by bradlc** [comment]
Please can you share a GitHub repo that I can open to reproduce the issue?

**Comment by bradlc** [comment]
Sorry, I am not able to reproduce the issue. Please could you share a screen recording of the issue so I can better understand what's going on?

Please could you share your VS Code settings in JSON format as well?

**Comment by bradlc** [comment]
Ah yep, it's the `"editor.suggest.showConstants": false` specifically. Glad you figured it out!
