### ISSUE TITLE
Unhandled exception in latest commits

### ISSUE THREAD

**Issue by agorgl** [tailwindlabs/tailwindcss-intellisense#646]
Up until commit 68750d859bb3cdce33afb9e650bbcc97f12f3bca everything works as it should,
after commit b26e122fac4da99238e38dd5ca837a76e87c54cc I now get an exception in lsp logs:
```
Unhandled exception: tu(...).subscribe is not a function
TypeError: tu(...).subscribe is not a function
    at Object.<anonymous> (/usr/bin/tailwindcss-language-server:224:29339)
    at Generator.next (<anonymous>)
    at /usr/bin/tailwindcss-language-server:2:1219
    at new Promise (<anonymous>)
    at Ft (/usr/bin/tailwindcss-language-server:2:1039)
    at Hu.subscribe (/usr/bin/tailwindcss-language-server:224:29272)
    at tHe.<anonymous> (/usr/bin/tailwindcss-language-server:715:11557)
    at Generator.next (<anonymous>)
    at i (/usr/bin/tailwindcss-language-server:2:1077)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
tested by bisecting and building the AUR package on a fresh project that used tailwindcss

**Comment by bradlc** [comment]
Hey @agorgl. I don't know what an "AUR package" is, how exactly are you acquiring and using the language server? We provide the [`@tailwindcss/language-server` npm package](https://npm.im/@tailwindcss/language-server) for use outside of VS Code. This package includes the server in the `bin` folder, along with additional `.node` files that are required.

**Comment by agorgl** [comment]
Ah thanks for the update! It seems that the package definition file (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tailwindcss-language-server) does not copy the required `.node` file when installing the `tailwindcss-language-server` to `/usr/bin`

**Comment by agorgl** [comment]
Resolved by replacing the `package()` step from:
```
package() {
  cd tailwindcss-intellisense/packages/$pkgname
  install -Dt "$pkgdir"/usr/bin bin/$pkgname
  install -Dm644 -t "$pkgdir"/usr/share/licenses/$pkgname LICENSE
}
```
to
```
package() {
  cd tailwindcss-intellisense/packages/$pkgname
  local node_file=$(find bin/ -name *.glibc-*.node -exec hexdump -n 4 -e '4/1 "%2x" " {}\n"' {} \; | awk '/^7f454c46/{print $2}')
  sed -r -i "s/.\/($(basename $node_file))/\/usr\/lib\/$pkgname\/\1/g" bin/$pkgname
  install -Dt "$pkgdir"/usr/bin bin/$pkgname
  install -Dt "$pkgdir"/usr/lib/tailwindcss-language-server $node_file
  install -Dm644 -t "$pkgdir"/usr/share/licenses/$pkgname LICENSE
}
```
(ultimately by installing also the .node file and patching its path to `tailwindcss-language-server` bin :)

**Comment by agorgl** [comment]
Sorry for the wrong update, it seems that this did not resolve the issue, I'm investigating further

**Comment by bradlc** [comment]
Hey @agorgl. I'm going to close this because it isn't really an issue with Tailwind CSS IntelliSense or the language server, and instead seems to be an integration issue. As mentioned above we don't support or recommend extracting the language server from the VS Code extension. Please use the `@tailwindcss/language-server` package instead. If you're still having issues though feel free to ping me on a new [discussion](https://github.com/tailwindlabs/tailwindcss/discussions) and I'll see if I can help 👍
