### ISSUE TITLE
Question about autocomplete 

### ISSUE THREAD

**Issue by bmarvinb** [tailwindlabs/tailwindcss-intellisense#649]
It is possible to run autocomplete in regular variables or functions? For example I have objects with tailwind classes, but autocomplete not working
```typescript
const baseClasses =
  'inline-flex items-center border border-transparent font-medium rounded-md shadow-sm focus:outline-none focus:ring-2';

const sizes: Record<ButtonSize, string> = {
  xs: 'px-2.5 py-1.5 text-xs',
  sm: 'px-3 py-2 text-sm',
  md: 'px-4 py-2 text-base',
  lg: 'px-4 py-2 text-base',
  xl: 'px-6 py-3 text-base',
};
```

**Comment by bradlc** [comment]
Hey @bmarvinb. This is possible using the `tailwindCSS.experimental.classRegex` setting. Check out [my comment](https://github.com/tailwindlabs/tailwindcss/issues/7553#issuecomment-735915659) for more information and the discussion here for some examples: https://github.com/tailwindlabs/tailwindcss/discussions/7554

Hope that helps!

**Comment by bmarvinb** [comment]
@bradlc thanks a lot, looks like it's what I need
