### ISSUE TITLE
Helper functions in CSS lose color decoration if wrapped in another function

### ISSUE THREAD

**Issue by phelipetls** [tailwindlabs/tailwindcss-intellisense#653]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

3.2.1

**What package manager are you using?**

npm

**What operating system are you using?**

Linux

**Tailwind config**

I don't believe it'll be necessary, but glad to share on request.

**VS Code settings**

I don't believe it'll be necessary, but glad to share on request.

**Describe your issue**

Here's the bug:

![image](https://user-images.githubusercontent.com/39670535/200074107-be8c2d26-e731-47ad-aff2-339004b8f41c.png)

It works fine without the extra wrapper function:

![image](https://user-images.githubusercontent.com/39670535/200074367-7e22e68d-8707-4c91-af61-330b764c0890.png)

To reproduce, paste the below line in a CSS file.

```css
--myvar: fn(theme(colors.fuchsia.600));
```

I'd expect color decoration to not be affected by this change.

**Comment by bradlc** [comment]
Thanks for reporting this, it will be fixed in the next release 👍
