### ISSUE TITLE
Double-slash in script attribute breaks intellisense for the rest of the file

### ISSUE THREAD

**Issue by jacobwgillespie** [tailwindlabs/tailwindcss-intellisense#661]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

v3.2.1

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Tailwind config**

```js
module.exports = {}
```

**VS Code settings**

```json
{
  "tailwindCSS.includeLanguages": {
    "typescriptreact": "javascript"
  },
  "tailwindCSS.classAttributes": ["class", "className", "activeClassName", "inactiveClassName"]
}
```

**Reproduction URL**

This code snippet:

```jsx
export function Example() {
  return (
    <div>
      <div className="bg-red-100" />
      <script src="//" />
      <div className="bg-red-100" />
    </div>
  )
}
```

<img width="353" alt="image" src="https://user-images.githubusercontent.com/130874/201426996-df49355d-af8f-4e68-8a1e-a2f46ad818f0.png">

**Describe your issue**

If there are two slashes (`//`) contained in a `<script>` element attribute, all the intellisense is broken / does not exist for the rest of the file. This is most noticeable when there is a full URL in a script src:

```javascript
export function Example() {
  return (
    <div>
      // this class will have hover intellisense and a color preview
      <div className="bg-red-100" />
      <script src="//" />
      // from this point onward, hovering over classnames and color previews are broken

      <div className="bg-red-100" />
    </div>
  )
}
```

(see the screenshot above)

Note that it doesn't need to be the `src` attribute, it can be anything inside the `<script>`, e.g. this causes the issue as well:

```jsx
// intellisense works above
<script {...{example: '    //  '}} />
// intellisense is broken below
```

It does need to be the `<script>` tag, `<img src="//">` does not trigger the issue.

**Comment by bradlc** [comment]
Thanks for reporting this, the issue is fixed in the latest release (`v0.9.8`) 👍
