### ISSUE TITLE
 Tailwind CSS: input.split is not a function

### ISSUE THREAD

**Issue by alikomijani** [tailwindlabs/tailwindcss-intellisense#670]
Tailwind CSS IntelliSense v0.9.1
 Tailwind CSS: v3.1.8

**What package manager are you using?**

yarn

**What operating system are you using?**

windows

**Tailwind config**

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  plugins: [require("@tailwindcss/line-clamp")],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      black: "#000000",
      gray: "#D7D7D7",
      green: "#41C78E",
      blue: "#75B9F2",
      red: "#F35453",
      orange: "#FFB656",
      purple: "#B67BF8",
      pink: "#FF6CFD",
      fuchsia: "#AF14A0",
      yellow: "#FFD400",
      primary: {
        light: "#FFB656",
        DEFAULT: "#FB743E",
      },
      text: {
        light: "#9F9F9F",
        DEFAULT: "#313030",
        dark: "#222222",
      },
    },
    boxShadow: {
      sm: "0px 3px 10px #00000016",
    },
    screens: {
      xs: "320px",
      sm: "425px",
      md: "768px",
      lg: "1200px",
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "5px",
      },
      screens: {
        md: "768px",
        lg: "1200px",
      },
    },
    fontSize: {
      xs: "1.2rem",
      sm: "1.4rem",
      md: "1.6rem",
      lg: "1.8rem",
      xl: "2rem",
      "2xl": "2.2rem",
      "3xl": "2.4rem",
      "4xl": "2.6rem",
      "5xl": "2.8rem",
      "6xl": "3rem",
      "7xl": "3.2rem",
    },
    extend: {
      animation: {
        shimmer: "shimmer 2s infinite",
        keyframes: {
          shimmer: {
            from: {
              transform: "translateX(-100%)",
            },
            to: {
              transform: "translateX(100%)",
            },
          },
        },
      },
      cursor: {
        default: "url(/assets/images/main-cursor.png), default",
        pointer: "url(/assets/images/pointer-cursor.png), pointer",
        disable: "url(/assets/images/disable-cursor.png), auto",
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "42px",
        11: "44px",
        12: "46px",
        13: "48px",
        14: "50px",
        15: "52px",
        16: "54px",
        17: "56px",
        18: "58px",
        19: "60px",
        20: "62px",
      },
    },
  },
};

```

**VS Code settings**

```json
{
  "cSpell.words": ["clsx"],
  "tailwindCSS.includeLanguages": {
    "plaintext": "html"
  },
  "files.associations": {
    "*.css": "tailwindcss"
  },
  "editor.quickSuggestions": {
    "strings": true
  },
  "tailwindCSS.suggestions": true,
  "tailwindCSS.experimental.configFile": "./tailwind.config.js"
}

```

**Describe your issue**

suddenly my tailwind extension doesn't work 

[tailwind.config.js] Initializing...
[tailwind.config.js] Loaded Tailwind CSS config file: c:\Users\Mohammad\Documents\projects\LoheSama\tailwind.config.js
[tailwind.config.js] Loaded postcss v8.4.17: c:\Users\Mohammad\Documents\projects\LoheSama\node_modules\postcss
[tailwind.config.js] Loaded tailwindcss v3.1.8: c:\Users\Mohammad\Documents\projects\LoheSama\node_modules\tailwindcss
[tailwind.config.js] Building...
[Error - 1:04:36 PM] Tailwind CSS: input.split is not a function
TypeError: input.split is not a function
    at parseAnimationValue (c:\Users\Mohammad\Documents\projects\LoheSama\node_modules\tailwindcss\lib\util\parseAnimationValue.js:48:28)
    at animate (c:\Users\Mohammad\Documents\projects\LoheSama\node_modules\tailwindcss\lib\corePlugins.js:1068:67)
    at wrapped (c:\Users\Mohammad\Documents\projects\LoheSama\node_modules\tailwindcss\lib\lib\setupContextUtils.js:397:46)
    at resolveMatches (c:\Users\Mohammad\Documents\projects\LoheSama\node_modules\tailwindcss\lib\lib\generateRules.js:545:47)
    at resolveMatches.next (<anonymous>)
    at Function.from (<anonymous>)
    at Object.generateRules [as module] (c:\Users\Mohammad\Documents\projects\LoheSama\node_modules\tailwindcss\lib\lib\generateRules.js:678:29)
    at hn (c:\Users\Mohammad\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.1\dist\tailwindServer.js:210:7139)
    at Ya (c:\Users\Mohammad\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.1\dist\tailwindServer.js:211:52393)
    at c:\Users\Mohammad\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.1\dist\tailwindServer.js:712:10577

**Comment by bradlc** [comment]
Hey @alikomijani. This is because you have some syntax errors in your config, including a missing closing brace for your `animation` config:

```diff
- /** @type {import('tailwindcss').Config} /
+ /** @type {import('tailwindcss').Config} */
  module.exports = {
    content: ['./pages/**/.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
    plugins: [require('@tailwindcss/line-clamp')],
    theme: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        white: '#ffffff',
        black: '#000000',
        gray: '#D7D7D7',
        green: '#41C78E',
        blue: '#75B9F2',
        red: '#F35453',
        orange: '#FFB656',
        purple: '#B67BF8',
        pink: '#FF6CFD',
        fuchsia: '#AF14A0',
        yellow: '#FFD400',
        primary: {
          light: '#FFB656',
          DEFAULT: '#FB743E',
        },
        text: {
          light: '#9F9F9F',
          DEFAULT: '#313030',
          dark: '#222222',
        },
      },
      boxShadow: {
        sm: '0px 3px 10px #16',
      },
      screens: {
        xs: '320px',
        sm: '425px',
        md: '768px',
        lg: '1200px',
      },
      container: {
        center: true,
        padding: {
          DEFAULT: '5px',
        },
        screens: {
          md: '768px',
          lg: '1200px',
        },
      },
      fontSize: {
        xs: '1.2rem',
        sm: '1.4rem',
        md: '1.6rem',
        lg: '1.8rem',
        xl: '2rem',
        '2xl': '2.2rem',
        '3xl': '2.4rem',
        '4xl': '2.6rem',
        '5xl': '2.8rem',
        '6xl': '3rem',
        '7xl': '3.2rem',
      },
      extend: {
        animation: {
          shimmer: 'shimmer 2s infinite',
+       },
        keyframes: {
          shimmer: {
            from: {
              transform: 'translateX(-100%)',
            },
            to: {
              transform: 'translateX(100%)',
            },
          },
        },
      },
      cursor: {
        default: 'url(/assets/images/main-cursor.png), default',
        pointer: 'url(/assets/images/pointer-cursor.png), pointer',
        disable: 'url(/assets/images/disable-cursor.png), auto',
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '42px',
        11: '44px',
        12: '46px',
        13: '48px',
        14: '50px',
        15: '52px',
        16: '54px',
        17: '56px',
        18: '58px',
        19: '60px',
        20: '62px',
      },
    },
  }
- }
```

If you fix those you should be good to go. I hope that helps!
