### ISSUE TITLE
intellisense "pt-20" not coming up at "pt-2" but at "pt2"

### ISSUE THREAD

**Issue by Brentably** [tailwindlabs/tailwindcss-intellisense#677]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

v3.2.4

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**VS Code settings**

```json
{
  // "terminal.integrated.shell.osx": "/bin/zsh",
  "files.autoSave": "afterDelay",
  "css.validate": false,
  "editor.wordWrap": "on",
  "prettier.semi": false,
  "editor.formatOnSave": true,
  "editor.tabSize": 2,
  // "prettier.jsxBracketSameLine": true,
  "prettier.jsxSingleQuote": true,
  "prettier.singleQuote": true,
  "prettier.printWidth": 130,
  "liveServer.settings.donotShowInfoMsg": true,
  "hardhat.telemetry": true,
  "[solidity]": {
    "editor.defaultFormatter": "NomicFoundation.hardhat-solidity"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "python.defaultInterpreterPath": "/usr/local/bin/python3",
  "python.languageServer": "Pylance"
}
```

**Reproduction URL**

Very simple issue, so I'm not sure this is necessary, but will happily do so if you guys validate that you need it.
Here's a loom instead: [https://www.loom.com/share/e6640421adc84d81a52d531794d069c1](https://www.loom.com/share/e6640421adc84d81a52d531794d069c1)

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.
Say I'm trying to do "pt-20". When I type in "p", "pt", and "pt-", intellisense comes up. As soon as I hit "pt-2" it stops coming up. Alternatively, if I hit "pt2" pt-20, does come up.

**Comment by Brentably** [comment]
Dang I just realized it's happening elsewhere too:
Intellisense only works in the specific context that I showed in that loom. 
Check this one out:
https://www.loom.com/share/ee4f087d858642329a88c9f25e094094

If I use normal intellisense to autocomplete className='' for me, then it doesn't work... This is the core of the issue.

**Comment by bradlc** [comment]
Hey @Brentably. No idea what's causing the issue in your first video 🤔 Please could you share a list of extensions you have enabled? If you have the VS Code CLI installed you can use `code --list-extensions --show-versions`

For the second video, we [recommend](https://github.com/tailwindlabs/tailwindcss-intellisense#recommended-vs-code-settings) configuring the `editor.quickSuggestions` setting which should help with this:

```
"editor.quickSuggestions": {
  "strings": true
}
```

**Comment by Brentably** [comment]
Thanks Brad! Here are my extensions:

bradlc.vscode-tailwindcss@0.9.1
dbaeumer.vscode-eslint@2.3.0
esbenp.prettier-vscode@9.10.3
jpoissonnier.vscode-styled-components@0.0.31
ms-python.isort@2022.8.0
ms-python.python@2022.20.1
ms-python.vscode-pylance@2022.12.20
ms-toolsai.jupyter@2022.11.1003412109
ms-toolsai.jupyter-keymap@1.0.0
ms-toolsai.jupyter-renderers@1.0.12
ms-toolsai.vscode-jupyter-cell-tags@0.1.6
ms-toolsai.vscode-jupyter-slideshow@0.1.5
NomicFoundation.hardhat-solidity@0.6.3
ritwickdey.LiveServer@5.7.9
stylelint.vscode-stylelint@1.2.3


As far as the second video goes, adding that config helped with part of it, but intellisense still doesn't come up in this case:
[https://www.loom.com/share/d774434860634284b5a699ae25d797eb](https://www.loom.com/share/d774434860634284b5a699ae25d797eb) 

When I'm making a new element and I write `<div cla` and intellisense detects I'm typing classname, so I hit tab, and it jumps me to `<div className="|"`

**Comment by bradlc** [comment]
Thanks @Brentably

> _intellisense still doesn't come up in this case_

Unfortunately it's not possible for us to trigger suggestions in the case where the `className` prop is autocompleted like that. In this case you can use Ctrl+Space to manually trigger suggestions.

Regarding your original "pt-20" issue, I can reproduce this now after updating VS Code to the latest version. So I pretty sure this is a VS Code bug. I'm going to have a look through their issues to see if I can find anything

**Comment by bradlc** [comment]
Closing this in favour of microsoft/vscode#169390
