### ISSUE TITLE
Tailwind VSCode extension not showing color preview

### ISSUE THREAD

**Issue by drewboardman** [tailwindlabs/tailwindcss-intellisense#679]
**What version of Tailwind CSS IntelliSense are you using?**

0.9.1

**What version of Tailwind CSS are you using?**

3.2.4

**What package manager are you using?**

Installed plugin via VSCode. Installed tailwind with `npm install -D tailwindcss && npx tailwindcss init`

**What operating system are you using?**

macOS

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**VS Code settings**
![Screen Shot 2022-12-14 at 9 07 51 AM](https://user-images.githubusercontent.com/8429384/207619143-47aa297f-6ff4-48c3-b6bf-860025a84c8c.png)

**Describe your issue**

TailwindCSS Intellisense plugin is not displaying color previews, either on hover or beside the color declaration.

The setting is selected to enable this, and the installation instructions don't include an additional required step to get this to work.

![Screen Shot 2022-12-14 at 9 08 11 AM](https://user-images.githubusercontent.com/8429384/207619160-b4946329-8c49-4b7a-8d60-c40e6e6b7008.png)

**Comment by bradlc** [comment]
Hey @drewboardman. Tailwind CSS IntelliSense only shows color decorators for Tailwind classes in `class`/`className` attributes, and CSS helper functions, like below:

<img width="323" alt="CleanShot 2022-12-14 at 14 23 08@2x" src="https://user-images.githubusercontent.com/2615508/207620983-8ff74654-e0af-4b94-9454-f961c5053cba.png">

I hope that helps!
