### ISSUE TITLE
Extension loads on VSCode startup

### ISSUE THREAD

**Issue by DestroyerXyz** [tailwindlabs/tailwindcss-intellisense#683]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

NA

**What package manager are you using?**

NA

**What operating system are you using?**

macOS

**Tailwind config**

NA

**VS Code settings**

NA

**Reproduction URL**

NA

**Describe your issue**

The Tailwind Intellisense VSCode extension loads on VSCode startup.
Is this required for some reason?
If not, `onLanguage` could be added to `activationEvents` in `package.json` which will load the extension on opening files of specific languages or file extensions.

**Comment by bradlc** [comment]
Hey @DestroyerXyz. The current `activationEvents` configuration is required so that we can start the language server when for example a new Tailwind config file is created, and to support certain settings such as `tailwindCSS.includeLanguages`
