### ISSUE TITLE
No autocomplete of classnames in multi-folder workspace

### ISSUE THREAD

**Issue by ronaldtveen** [tailwindlabs/tailwindcss-intellisense#692]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.3

**What version of Tailwind CSS are you using?**

v3.2.4

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Describe your issue**

The following used to work until yesterday so I _think_ it broke in `v0.9.2`.

I'm working on a Vue project with Laravel as a PHP backend. Because I mostly work in Vue and not the PHP side of the project I use VSCode workspaces to split the project in parts; the root `/` as well as `/resources/js/` for example. 

My `example.test.code-workspace` is as follows:
```
{
  "folders": [
        { "path": "../Sites/example.test" },
        { "path": "../Sites/example.test/resources" },
        { "path": "../Sites/example.test/resources/js/Components" }
    ],
    "settings": {
        "tailwindCSS.experimental.configFile": "../Sites/example.test/tailwind.config.js"
    }
}
```

When I open the project folder `example.test` in VScode then the autocomplete intellisense works perfectly fine. But when I open the workspace it does no longer autocomplete any classnames. 

PS Is there a way to rollback to a previous version?

**Comment by bradlc** [comment]
Hey @ronaldtveen. Please can you share a reproduction? Ideally a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue.

> _PS Is there a way to rollback to a previous version?_

Yes, you can click the cog icon on the extension and select "Install Another Version...":

![CleanShot 2023-01-05 at 14 05 17@2x](https://user-images.githubusercontent.com/2615508/210798932-f2ac47f5-4420-4a83-87df-46e28ce46bcc.png)

**Comment by ronaldtveen** [comment]
I wish I could, it's a closed internal project which I cannot share. Let me see if I can spin up a new repro to reproduce it. 

I rolled back to `v0.9.1` and then it works again, but installing `v0.9.2` breaks it.

**Comment by bradlc** [comment]
Thank you! Should be fixed in `v0.9.4` via #693 but let me know if you're still having issues 👍

**Comment by ronaldtveen** [comment]
Just installed `v0.9.4` and reloaded VSCode but no such luck for me it seems?

**Comment by bradlc** [comment]
What do you see in the output panel? (you can run the `Tailwind CSS: Show Output` command to reveal)

**Comment by ronaldtveen** [comment]
Ahh, just edited my previous post haha. Thanks again!
