### ISSUE TITLE
Tailwind CSS: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by to-my-learning-path** [tailwindlabs/tailwindcss-intellisense#703]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.5

**What version of Tailwind CSS are you using?**

v3.2.4

**What package manager are you using?**

npm

**What operating system are you using?**

Windows

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      moderateCyan: "hsl(176, 50%, 47%)",
      darkCyan: "hsl(176, 72%, 28%)",
      black: "hsl(0, 0%, 0%)",
      darkGray: "hsl(0, 0%, 48%)",
    },
    fontFamily: {
      commissioner: ["Commissioner", "sans-serif"],
    },
    fontWeight: {
      400: "400",
      500: "500",
      700: "700",
    },
    extend: {},
  },
  plugins: [],
};
```

**VS Code settings**

```
Can't find it.
```

**Reproduction URL**

https://github.com/to-my-learning-path/crowdfunding-product-page

**Describe your issue**

Everything was working fine before three weeks. Today, the Tailwind CSS IntelliSence was not working (No suggestions or hover). 
I looked at the Tailwind CSS IntelliSence Output and I saw this:

```
[Global] Creating projects: [{"folder":"c:\\Users\\laptop\\Desktop\\React\\crowdfunding-product-page","configPath":"c:\\Users\\laptop\\Desktop\\React\\crowdfunding-product-page\\tailwind.config.js","documentSelector":[{"priority":0,"pattern":"c:\\Users\\laptop\\Desktop\\React\\crowdfunding-product-page\\**"}],"isUserConfigured":true}]
[Global] Adding watch patterns: c:\Users\laptop\Desktop\React\crowdfunding-product-page\tailwind.config.js, c:\Users\laptop\Desktop\React\crowdfunding-product-page, c:\Users\laptop\Desktop\React, c:\Users\laptop\Desktop, c:\Users\laptop, c:\Users, c:\
[tailwind.config.js] Initializing...
[Error - 6:55:06 PM] Tailwind CSS: ENOENT: no such file or directory, open 'c:\Users\laptop\Desktop\React\crowdfunding-product-page\tailwind.config.js'
Error: ENOENT: no such file or directory, open 'c:\Users\laptop\Desktop\React\crowdfunding-product-page\tailwind.config.js'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at readFileSync (node:fs:453:35)
    at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at require.readFileSync (eval at <anonymous> (c:\Users\laptop\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.2\dist\tailwindServer.js:713:35475), <anonymous>:9:14)
    at MG (c:\Users\laptop\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.2\dist\tailwindServer.js:272:27756)
    at rwe (c:\Users\laptop\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.2\dist\tailwindServer.js:272:27849)
    at AA (c:\Users\laptop\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.2\dist\tailwindServer.js:272:27681)
    at c:\Users\laptop\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.2\dist\tailwindServer.js:721:4837
    at Generator.next (<anonymous>)
```

After couple hours, I found that changing the extension in  `"tailwindCSS.experimental.configFile": "./tailwind.config.js"` from .js to .cjs fixed the problem. Was there an update that cause this?

**Comment by bradlc** [comment]
Hey @to-my-learning-path 

> _I found that changing the extension in `"tailwindCSS.experimental.configFile": "./tailwind.config.js"` from .js to .cjs fixed the problem._

The config file in your project is named `tailwind.config.cjs`, so it is correct that you were getting an error with `tailwindCSS.experimental.configFile` set to `./tailwind.config.js`. It's not clear to me why it _was_ working, but I suspect this is a configuration problem so I'm going to close this issue.

As a side note I would recommend removing your `tailwindCSS.experimental.configFile` configuration unless you absolutely need it. In your project the extension should be able to automatically find the config file 👍 Hope that helps!
