### ISSUE TITLE
Tailwind CSS path quick suggestions not working

### ISSUE THREAD

**Issue by AayushMehta** [tailwindlabs/tailwindcss-intellisense#715]
I am trying to updating the VS code settings as per the docs to enable quick suggestions in content property for path.

But after doing the following snippets as mentioned in docs: 
"editor.quickSuggestions": {
  "strings": true
}

My auto completion of path is not triggered automatically! Any suggestions on how to fix that

**Comment by bradlc** [comment]
Hey @AayushMehta. The extension does not provide path completions for the `content` property in a Tailwind config file, so this is expected. That's an interesting idea though! 💡
