### ISSUE TITLE
`experimental.classRegex` bugs

### ISSUE THREAD

**Issue by bwong365** [tailwindlabs/tailwindcss-intellisense#716]
**What version of Tailwind CSS IntelliSense are you using?**: v0.9.7

**What version of Tailwind CSS are you using?**: v3.2.6

**What package manager are you using?**: npm

**What operating system are you using?**: macOS Ventura 13.1

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};

```

**VS Code settings**

```json
{
  "tailwindCSS.experimental.classRegex": ["[a-zA-Z]*ClassName=\"([^']+)\""]
}
```

**Reproduction URL**: https://github.com/bwong365/tailwind-regex-bugs

**Describe your issue**

1. Regex appears to match only the first instance. In this example, `secondButtonClassName`'s classes receive no intellisense.
![image](https://user-images.githubusercontent.com/42486090/218250636-f155d23b-0f9c-4940-9f31-eedc64d7c4f0.png)

2. Class names appearing more than once in the same file end up flagged as duplicates/conflicts, even when the line is not correctly matched
![image](https://user-images.githubusercontent.com/42486090/218251098-6719f59c-ec0f-4c30-a977-6282c6c04092.png)

3. Classes that appear after a duplicate was detected do not receive intellisense. In this case, the `m-3` is ignored by the extension. The `m-1` does get detection in this example, since it's included in the normally matched `className`.
![image](https://user-images.githubusercontent.com/42486090/218250782-a911f945-9c06-4481-8811-b4adc262ebbc.png)

**Comment by bradlc** [comment]
Hey @bwong365. This is because your regular expression is matching too much. Check out what it matches in your example: https://regex101.com/r/uf0KO5/1

I recommend changing it to something like this:

```
"tailwindCSS.experimental.classRegex": [
  "[a-zA-Z]+ClassName=\"([^\"]*)\""
]
```

Here's what it matches now: https://regex101.com/r/88RaN9/1 – I hope that helps!

**Comment by sgalcheung** [comment]
Since upgrading to tailwindcss v4, it will load your CSS file. Write a directive(@import "tailwindcss";), and reload your project. It worked!
