### ISSUE TITLE
"css-ruleorselectorexpected" when combine "apply" with "important" in .vue style tag

### ISSUE THREAD

**Issue by horans** [tailwindlabs/tailwindcss-intellisense#718]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.7

**What version of Tailwind CSS are you using?**

v3.2.7

**What package manager are you using?**

npm

**What operating system are you using?**

Windows10

**Tailwind config**

**Describe your issue**

I am running TailwindCSS with Vue/Vite and SASS. When I trying to employ `#{!important}` along with `@apply` in my .vue component's style tag, VScode is showing "at-rule or selector expectedscss(css-ruleorselectorexpected)" error at the end. However it's ok to run/compile, so I guess it has something to do with VScode displaying.

```scss
/* ✔ works just fine */
<style lang="scss">
.test-ok {
  @apply m-0;
}
</style>
```

```scss
/* ❌ showing error but ok to run */
<style lang="scss">
.test-error {
  @apply m-0 #{!important};
} //at-rule or selector expectedscss(css-ruleorselectorexpected)
</style>
```

possible related issues:
- <https://github.com/vuejs/language-tools/issues/791>
- <https://github.com/microsoft/vscode-css-languageservice/issues/269>

**Comment by bradlc** [comment]
Hey @horans. Unfortunately this is not something we can control. The only way that I'm aware of to suppress the message is to disable SCSS validation using the `scss.validate` setting:

```
"scss.validate": false
```

I hope that helps!

**Comment by relliv** [comment]
@bradlc hi, thanks for the suggestion. when I added this to the `.vscode/settings.json` file and then the error was suppressed.

**Comment by av1v3k** [comment]
it was NOT resolved in vscode.
