### ISSUE TITLE
Auto-complete not working in MDX files

### ISSUE THREAD

**Issue by cglacet** [tailwindlabs/tailwindcss-intellisense#720]
**What version of Tailwind CSS IntelliSense are you using?**
v0.9.7

**What version of Tailwind CSS are you using?**
v3.2.7

**What package manager are you using?**
yarn

**What operating system are you using?**
Windows

**Tailwind config**
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
    prefix: "nx-",
    darkMode: "class",
    content: [
        "./components/**/*.js",
        "./pages/**/*.{md,mdx}",
        "./theme.config.tsx",
    ],
};

```

**VS Code settings**
```json
{
  "tailwindCSS.includeLanguages": {
    "html": "html",
    "javascript": "javascript",
    "javascriptreact": "javascriptreact",
    "typescript": "typescript",
    "typescriptreact": "typescriptreact",
    "css": "css",
    "mdx": "mdx",
    "markdown": "markdown"
  },
  "editor.quickSuggestions": {
    "strings": "on"
  }
}
```

**Describe your issue**
Auto-completion works in `.tsx` files but doesn't in `.mdx` files. I only get what I suppose is the default "string" output (fields with the `abc` icon).

```mdx
# Example of auto-completion not working

<h2 className="nx-font-bold nx-underline">Hello world!</h2>
```

The output from Tailwind CSS Intelisense isn't helping much in my case as it seems totally silent : 

```bash
[Global] Creating projects: []
```

You can reproduce this simply by using the default nextra [documentation theme](https://github.com/shuding/nextra-docs-template):

[![](https://vercel.com/button)](https://vercel.com/new/clone?s=https%3A%2F%2Fgithub.com%2Fshuding%2Fnextra-docs-template&showOptionalTeamCreation=false)

**Comment by bradlc** [comment]
Hey @cglacet. I was not able to reproduce the issue in nextra. Please share a reproduction – a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand. Unfortunately without this we're not going to be able to diagnose the issue. Thanks!

**Comment by cglacet** [comment]
[Here you have a reproduction](https://github.com/cglacet/tailwind-issue-autocomplete)

**Comment by cglacet** [comment]
By the way, I also don't see color codes as the documentation shows, but I guess I need to install another plugin for that to work.

**Comment by cglacet** [comment]
Yes I use WSL.

<details>
  <summary>Here is the list of extensions I have installed</summary>
<pre>
  aaron-bond.better-comments@3.0.2
  ahmadawais.shades-of-purple@7.1.5
  akamud.vscode-theme-onedark@2.3.0
  alefragnani.jenkins-status@4.4.1
  alefragnani.project-manager@12.7.0
  alexcvzz.vscode-sqlite@0.14.1
  alexdima.copy-relative-path@0.0.2
  angelomollame.batch-replacer@1.2.1
  apollographql.vscode-apollo@1.19.11
  arkademy.arkademy-training@0.111.0
  artlaman.chalice-icon-theme@1.2.21
  atomiks.moonlight@0.10.6
  azemoh.one-monokai@0.5.0
  balazs4.gitlab-pipeline-monitor@2.0.0
  barrsan.reui@1.2.5
  bierner.folder-source-actions@0.2.1
  bierner.markdown-preview-github-styles@1.0.1
  bradlc.vscode-tailwindcss@0.9.7
  bungcip.better-toml@0.3.2
  christian-kohler.npm-intellisense@1.4.4
  christian-kohler.path-intellisense@2.8.4
  ckolkman.vscode-postgres@1.4.0
  dnicolson.binary-plist@0.11.0
  donjayamanne.githistory@0.6.19
  DotJoshJohnson.xml@2.5.1
  dracula-theme.theme-dracula@2.24.2
  dsznajder.es7-react-js-snippets@4.4.3
  ecmel.vscode-html-css@1.13.1
  esbenp.prettier-vscode@9.10.4
  formulahendry.auto-close-tag@0.5.14
  formulahendry.auto-complete-tag@0.1.0
  formulahendry.auto-rename-tag@0.1.10
  formulahendry.code-runner@0.12.0
  gerane.Theme-Earthsong@0.0.5
  GitLab.gitlab-workflow@3.60.0
  gogocrow.jsx-beautify@0.0.5
  GraphQL.vscode-graphql@0.8.5
  GraphQL.vscode-graphql-syntax@1.0.6
  guyskk.language-cython@0.0.7
  HookyQR.beautify@1.5.0
  huacnlee.theme-macos-classic@1.5.0
  iocave.customize-ui@0.1.65
  iocave.monkey-patch@0.1.23
  jasonn-porch.gitlab-mr@1.4.3
  jasonnutter.search-node-modules@1.3.0
  jprestidge.theme-material-theme@1.0.1
  juanmnl.vscode-theme-1984@0.3.4
  kuscamara.electron@0.2.6
  leveluptutorials.theme-levelup@0.3.0
  liviuschera.noctis@10.40.0
  Luxcium.pop-n-lock-theme-vscode@3.32.188
  MarioQueiros.CamelCase@1.0.5
  mechatroner.rainbow-csv@3.5.0
  mgmcdermott.vscode-language-babel@0.0.36
  mhutchie.git-graph@1.30.0
  mkaufman.HTMLHint@0.10.0
  monokai.theme-monokai-pro-vscode@1.2.0
  ms-azuretools.vscode-docker@1.24.0
  MS-CEINTL.vscode-language-pack-fr@1.75.2023021509
  ms-kubernetes-tools.vscode-kubernetes-tools@1.3.11
  ms-ossdata.vscode-postgresql@0.3.0
  ms-toolsai.jupyter@2023.1.2010391206
  ms-toolsai.jupyter-keymap@1.1.0
  ms-toolsai.jupyter-renderers@1.0.14
  ms-toolsai.vscode-jupyter-cell-tags@0.1.6
  ms-vscode.atom-keybindings@3.3.0
  ms-vscode.makefile-tools@0.6.0
  ms-vscode.node-debug2@1.43.0
  ms-vscode.sublime-keybindings@4.0.10
  ms-vscode.Theme-MarkdownKit@0.1.4
  ms-vscode.vscode-typescript-next@5.1.20230227
  msjsdiag.debugger-for-chrome@4.13.0
  msjsdiag.vscode-react-native@1.10.0
  naumovs.color-highlight@2.5.0
  naumovs.theme-oceanicnext@0.0.4
  PKief.material-icon-theme@4.24.0
  pnp.polacode@0.3.4
  Poorchop.theme-darktooth@0.0.2
  ProMyze.promyze-vs-code@7.0.0
  quicktype.quicktype@12.0.46
  radiolevity.search-lights@1.10.3
  rastikerdar.vscode-seedling-icon-theme@0.10.0
  redhat.vscode-commons@0.0.6
  ritwickdey.LiveServer@5.7.9
  selfrefactor.niketa-dark-theme@2.94.0
  Shan.code-settings-sync@3.4.3
  shd101wyy.markdown-preview-enhanced@0.6.7
  shidhincr.theme-dracula-italics@1.0.1
  shirishpatil.mapbox-gl-js-snippets@0.0.4
  shuworks.vscode-table-formatter@1.2.1
  skyran.js-jsx-snippets@11.0.1
  streetsidesoftware.code-spell-checker@2.18.0
  streetsidesoftware.code-spell-checker-french@0.2.7
  svelte.svelte-vscode@107.1.2
  teabyii.ayu@1.0.5
  thenikso.github-plus-theme@1.4.3
  tombonnike.vscode-status-bar-format-toggle@3.1.1
  unifiedjs.vscode-mdx@1.2.3
  VisualStudioExptTeam.vscodeintellicode@1.2.30
  vscjava.vscode-java-debug@0.49.0
  waderyan.gitblame@10.1.0
  whizkydee.material-palenight-theme@2.0.2
  wmaurer.change-case@1.0.0
  yomed.theme-dracula-soft@1.0.4
  yzhang.markdown-all-in-one@3.5.0
  Zeplin.zeplin@2.2.0
  zhuangtongfa.material-theme@3.15.6
  Zignd.html-css-class-completion@1.20.0
</pre>
</details>

**Comment by bradlc** [comment]
Thanks for sharing, I think I see the issue. If you're using WSL you need to install the [WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl), and **ensure that you install Tailwind CSS IntelliSense in your WSL distribution rather than locally**. Check out these guides for using VS Code with WSL:

- https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode
- https://code.visualstudio.com/docs/remote/wsl

I hope that helps!

**Comment by cglacet** [comment]
@bradlc thank, it works now.
