### ISSUE TITLE
can intellisense work in javascript function outside of html scope

### ISSUE THREAD

**Issue by or2008** [tailwindlabs/tailwindcss-intellisense#729]
**What version of Tailwind CSS IntelliSense are you using?**
v0.9.7

**What version of Tailwind CSS are you using?**
v3.2.4

Hi can the intellisense work in javascript function outside of html scope?

for example I am using tailwind in React with tailwind-merge library, and sometimes I write the classnames in a get function with `twMerge` outside of the html part:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/3414979/224491846-3e3dfb22-6c22-4824-a9da-79b4748a56ed.png">

is it possible to change the config so it works it these places? maybe using 'tailwindCSS.experimental.classRegex' option?

**Comment by bradlc** [comment]
Hey @or2008. The [`tailwindCSS.experimental.classRegex` setting](https://github.com/tailwindlabs/tailwindcss/issues/7553#issuecomment-735915659) can be used to provide IntelliSense in functions with specific names. A simple configuration supporting template strings in `twMerge` calls would look like this:

```
"tailwindCSS.experimental.classRegex": [
  ["twMerge\\(([\\S\\s]*?)\\)", "`([^`]*)`"]
]
```

I hope that helps!

**Comment by or2008** [comment]
Works! thank you very much
