### ISSUE TITLE
[Feature Suggestion] Use auto complete in js string

### ISSUE THREAD

**Issue by phmngocnghia** [tailwindlabs/tailwindcss-intellisense#73]
**Problem**
Hi, I want to use this plugin to autocomplete in a javascript string.
Are there configurations allow me to that?

**My usecase**
Since `babel-plugin-taillwind-component` package seemed to be broken (I have created an issue describe the bug). I have to write a HOC component that allows me to pass tailwind className into @emotion component.
```
export const withEmotionTailwind = (
  Component: StyledComponent<any, any, any>,
  className = ""
) => {
  const hocComponent = () => <Component className={className} />;
  return hocComponent;
};
```

```
export const RoundButton = withEmotionTailwind(styled.b``, "rounded-full");
```

**Comment by mayeths** [comment]
I want this feature with styled string too... Your method is great but autocomplete is still missing for me :(

---

```javascript
import styled from "styled-components";
const Button = styled.button.attrs({className: "bg-red"})`
  color: blue;
`
```
It's convenient if intellisense trigger with `bg-red`.

**Comment by bradlc** [comment]
Please see #129
