### ISSUE TITLE
Intellisense does not show pixel equivalents for `screens`

### ISSUE THREAD

**Issue by pm0u** [tailwindlabs/tailwindcss-intellisense#759]
**What version of Tailwind CSS IntelliSense are you using?**

0.9.11

**What version of Tailwind CSS are you using?**

3.3.1

**What package manager are you using?**

yarn

**What operating system are you using?**

macos

**Tailwind config**

```ts
// screens
export const screens: Record<string, string> = {
  xxs: "21em", // 336px
  xs: "24em", // 384px
  sm: "36em", // 576px
  md: "48em", // 768px
  lg: "62em", // 992px
  xl: "75em", // 1200px
  "2xl": "90em", // 1440px
  "3xl": "120em", // 1920px
}
```

**VS Code settings**

```js
// Paste your VS Code settings in JSON format here
{
  ...
  // This isn't necessary, but I did try setting it explicitly...
  "tailwindCSS.showPixelEquivalents": true
}
```

**Describe your issue**

When set to show pixel equivalents (or no setting provided, as this is the default) pixel equivalents are not presented for media queries if they are in non-pixel values.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/410558/231201550-49b57974-746b-4747-8ec7-ee8600842cbe.png">

I would expect that when pixel equivalents are to be shown, they would be shown for any value that can be configured.

**Comment by bradlc** [comment]
Hey @pm0u, pixel equivalents will be shown for media queries in the next release 👍
