### ISSUE TITLE
Word wrap + color decorators truncates line

### ISSUE THREAD

**Issue by fturmel** [tailwindlabs/tailwindcss-intellisense#762]
Using v0.9.11 of the plugin.

It seems like the color decorators are not calculated as part of the line width in the editor and that causes lines to be truncated when word wrap is enabled. Lines without a color decorator wrap correctly.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/4009209/233078409-00cf67c7-1d8d-4646-8d6a-3b425f21b512.png">

**Comment by bradlc** [comment]
Hey @fturmel. This is a VS Code issue so I'm going to close this in favour of https://github.com/microsoft/vscode/issues/32856

**Comment by fturmel** [comment]
I find that Tailwind with word wrap is a much better experience, but this little detail is so annoying. Doesn't seem like VS Code will fix it any time soon.

Would you consider having a setting in the plugin to toggle this color preview feature between the color decorators and something that doesn't alter the line width? Maybe white text on color background (like the [Colorize](https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize) plugin)?
