### ISSUE TITLE
tailwind config location

### ISSUE THREAD

**Issue by jrock2004** [tailwindlabs/tailwindcss-intellisense#77]
So it seems like the plugin will only work if you have `tailwind.config.js` in the root of your project. I have mine in `app/tailwind/tailwind.config.js` but it does not work. Is there a way to set the path where tailwind is located?

**Comment by cwgabel** [comment]
Oh you are so right about that file. I didn't have one at all and the extension is totally dead without it. Maybe look at [https://tailwindcss.com/docs/configuration#using-a-different-file-name]( https://tailwindcss.com/docs/configuration#using-a-different-file-name)

**Comment by bradlc** [comment]
The config file does not need to be in the project root. It should work where you've got it. Please can you try updating to v0.3.0 and see if that fixes the issue?

**Comment by bradlc** [comment]
Going to close this but feel free to open a new issue if you're still having problems 👍
