### ISSUE TITLE
Not getting tailwind style suggestions popup in astro 

### ISSUE THREAD

**Issue by karannakra** [tailwindlabs/tailwindcss-intellisense#774]
**What version of Tailwind CSS IntelliSense are you using?**

0.9.11

**What version of Tailwind CSS are you using?**

3.2.1

**What package manager are you using?**

yarn

**What operating system are you using?**

MacOS

**Tailwind config**

![download](https://user-images.githubusercontent.com/47587853/235322358-c3ac2af1-aae2-47df-b41b-1d23954bcb81.png)

**Describe your issue**

When I am trying to get auto-suggestion in Astro using `class` syntax it is working fine and I am getting such results

![image](https://user-images.githubusercontent.com/47587853/235322421-4114e5cb-59e6-41d4-9eab-e535bbd37441.png)

while if I use `class:list` syntax I am not getting any suggestions

![image](https://user-images.githubusercontent.com/47587853/235322463-6da2c07e-db93-4077-92b0-353a8005a378.png)

**Comment by reinink** [comment]
Hey!

You can use the `tailwindCSS.classAttributes` setting to enable autocomplete for additional attributes:

```js
"tailwindCSS.classAttributes": ["class", "className", "ngClass", "class:list"]
```

<img width="703" alt="image" src="https://user-images.githubusercontent.com/882133/235448428-7729e3e0-a35d-4387-bbac-47273dcab413.png">


I just gave this a try in an Astro file and it started working after making this adjustment:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/882133/235448296-30058122-f5fc-47e3-aedf-9fcd63810e38.png">

Give that a try! 💪

**Comment by yoiang** [comment]
This works great for simple `class:list={["XXXXXX YYYYYY ZZZZZZZ", "AAAAAA BBBBB CCCCC"]}`, thank you!
However this does not seem to work for me with:
`class:list={[ { "XXXXXX YYYYYY ZZZZZZZ" : <CONDITION> } ]}`,
such as ` class:list={[ { 'underline underline-offset-2 decoration-1': isActive} ]}`
