### ISSUE TITLE
Custom components using @layer from imported css file is not listed by intellisense

### ISSUE THREAD

**Issue by TechAkayy** [tailwindlabs/tailwindcss-intellisense#776]
**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.9.1

**What version of Tailwind CSS are you using?**

For example: v3.3.1

**What package manager are you using?**

For example: npm

**What operating system are you using?**

For example: macOS

**Reproduction URL**
https://github.com/Pinegrow/natures-delight-with-iles-tailwindcss

**Describe your issue**

I'm importing my custom components (using the @layer directive) from colors.css following the "[Build-time imports](https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports)" tailwind documentation. 

/* main.css */
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import './colors.css';
@import 'tailwindcss/utilities';

/* colors.css */
```
@layer components {
  .pg-primary {
    @apply bg-primary-600 dark:bg-primary-200;
  }
  .pg-primary-text {
    @apply text-primary-600 dark:text-primary-200;
  }
  .pg-on-primary {
    @apply bg-white dark:bg-primary-800;
  }
  .pg-on-primary-text {
    @apply text-white dark:text-primary-800;
  }
}
```

These custom components from the imported file is not getting listed by intellisense. But if I don't import them and just have them in the main.css file itself, then these are listed correctly by intellisense. 

Does intellisense work for custom components imported from an external file? My custom components list is huge, hence keeping it outside & importing it. Thanks.

**Comment by bradlc** [comment]
Hey @TechAkayy. Currently Tailwind CSS IntelliSense does not provide IntelliSense for classes defined in CSS files. This is something that we may add in the future though!

In case it's an option for you, any classes added by a [Tailwind plugin](https://tailwindcss.com/docs/plugins) _would_ be picked up by IntelliSense.

Here's an example of how you could add your background color classes using a plugin:

```js
const plugin = require('tailwindcss/plugin')

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      // ...
    },
  },
  plugins: [
    plugin(function ({ addComponents, theme }) {
      let backgroundColors = [
        ['primary', theme('colors.primary.600'), theme('colors.primary.200')],
        ['on-primary', theme('colors.white'), theme('colors.primary.800')],
        // ...
      ]
      addComponents(
        Object.fromEntries(
          backgroundColors.map(([key, light, dark]) => [
            `.pg-${key}`,
            { backgroundColor: light, ':is(.dark &)': { backgroundColor: dark } },
          ])
        )
      )
    }),
  ],
}
```

Hope that helps!

**Comment by TechAkayy** [comment]
Thanks bunch 😃

**Comment by coderwyd** [comment]
I've also encountered this problem, and I look forward to seeing this feature released one day.
