### ISSUE TITLE
Error occurs when using `presets` field

### ISSUE THREAD

**Issue by ryu-man** [tailwindlabs/tailwindcss-intellisense#778]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.11

**What version of Tailwind CSS are you using?**

v3.3.2

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Tailwind config**

```js
import preset from 'svelte-fui/tailwindcss'

/** @type {import('tailwindcss').Config} */
export default {
  presets: [
    preset
  ],
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        background: 'whitesmoke'
      }
    },
  },
  plugins: []
}
```

**Describe your issue**

I am trying to use a custom configuration of tailwindcss, so I defined the `presets` filed and added an array containg the configuration, unfortunately the `Tailwind CSS IntelliSense` stops working and prints the following error on the consol:

```shell
[tailwind.config.cjs] Initializing...
[tailwind.config.cjs] Loaded Tailwind CSS config file: d:/projects/xshop/tailwind.config.cjs
[tailwind.config.cjs] Loaded postcss v8.4.23: D:\projects\xshop\node_modules\.pnpm\postcss@8.4.23\node_modules\postcss
[tailwind.config.cjs] Loaded tailwindcss v3.3.2: D:\projects\xshop\node_modules\.pnpm\tailwindcss@3.3.2\node_modules\tailwindcss
[tailwind.config.cjs] Building...
[Error - 10:22:34 PM] Tailwind CSS: Default condition should be last one
Error: Default condition should be last one
    at D8 (c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:134:11335)
    at c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:134:8630
    at c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:134:14282
    at pv.eval [as callAsync] (eval at create (c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:5:78), <anonymous>:22:1)
    at x0.doResolve (c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:134:340)
    at c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:134:7528
    at c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:134:3081
    at c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:134:2127
    at H (c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:134:3003)
    at c:\Users\ABDELHALIM\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:134:2591
```

Note: Removing the `presets` field make the intellisense works normally

**Comment by ryu-man** [comment]
fixed by using ESM configuration format

**Comment by hitsthings** [comment]
I'm hitting this too. Can you explain "fixed by using ESM configuration format" please? It looks like you're already using the ESM format. Did you fix it by _not_ using that format?

**Comment by ryu-man** [comment]
oh, my bad, I was not using the `ESM` format in the preset file and you probably want to double-check your preset for any syntax issue

**Comment by hitsthings** [comment]
Ah cheers! it's the dependency!

**Comment by ryu-man** [comment]
yes I have a defined the preset here `'svelte-fui/tailwindcss'`

**Comment by ryu-man** [comment]
does the `IntelliSense ` works when you remove the preset?

**Comment by hitsthings** [comment]
For me I was not using the presets. I figured it out. The intellisense either can't handle NPM workspaces or can't handle package exports. My `tailwind.config.(ts|js|mjs|cjs)` (tried a few extensions / formats) didn't like that I was importing `@mylocalorg/anotherpackage/package-export`. When I switched to instead importing `../anotherpackage/package-export` everything started working again.

**Comment by hitsthings** [comment]
I'm not sure what changed, but it unfixed itself. On deeper inspection, I think I figured out the real error.

1. The error comes from webpack when it is parsing your `package.json`.
2. If you are opening a monorepo in VS Code, it runs on _every_ subpackage, even if your tailwind stuff doesn't depend on that package.
3. Your "exports" field in package.json must always put the "default" property last. (And in Typescript, I believe you always put the "types" property first)
4. Once you've reordered all of those, you have to save the tailwind config again for it to try building.

**Comment by Lim4Mik3** [comment]
@hitsthings youre a genius, i was hitting on the same error, you really find out the source of error!!! 

Thanks my brother! 

I just moved to down the property "defaults" in my monorepo, and just works. thats it

For someone wants to see: 

Fixed version: 
"exports": {
    "import": {
      "types": "./dist/index.d.mts",
      "default": "./dist/index.mjs"
    },
    "require": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    }
  },
