### ISSUE TITLE
TailwindCSS Intellisense is not loading

### ISSUE THREAD

**Issue by claughinghouse** [tailwindlabs/tailwindcss-intellisense#784]
Type: <b>Bug</b>

Launch vscode insiders and try to add a className to a file. Tailwindcss does not display the autocomplete dropdown inline.

Extension version: 0.9.11
VS Code version: Code - Insiders 1.79.0-insider (Universal) (2946b1ee55db1d406526d3fd1df49250b2f8322d, 2023-05-18T05:30:11.573Z)
OS version: Darwin x64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 6, 7|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 1d4aac43-c7c2-48c5-9f58-fc0304063844|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
vscrpc:30624061
pythonsymbol12:30651887
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
19089226:30680468
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by thecrypticace** [comment]
@claughinghouse I just updated to VSCode insiders 1.79.0 in which the only active extension is Intellisense and it seems to be working across multiple projects.

What other extensions do you have installed on your insiders build? And, do you have a project you can provide as a GitHub repo which reproduces the problem?

**Comment by claughinghouse** [comment]
I am on 1.79.0 as well. I just switched to the insiders version to participate in the Copilot beta features. 

```
Version: 1.79.0-insider (Universal)
Commit: 2946b1ee55db1d406526d3fd1df49250b2f8322d
Date: 2023-05-18T05:30:11.573Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
```
Here is everything I have installed so far. 

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/2333441/44461769-1efc-4bb3-a20d-cd86321ff6fb)

`tailwind.config.js`

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

This is all I see when trying to use the IntelliSense that works on the non-insiders version of VSCode. I can't share the repo, but I can extract any files that would be helpful. 

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/2333441/69d2ec21-0fdb-4d04-a49e-d7f7e3db63b0)

**Comment by claughinghouse** [comment]
Resolved with latest nightly.
