### ISSUE TITLE
I always have to put a space here before the prompt box appears

### ISSUE THREAD

**Issue by weykon** [tailwindlabs/tailwindcss-intellisense#785]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.11

**What version of Tailwind CSS are you using?**

 "tailwindcss": "3.3.2",

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
```

**VS Code settings**

default config

**Describe your issue**

I am not using in **vscode**, I'm using **_cursor_** editor. I do not know if that matters.

**Comment by thecrypticace** [comment]
Hey! So the Cursor editor is based on VS Code (more specifically VSCodium) and what you are seeing is a limitation of VS Code / VSCodium. You can use Ctrl+Space to trigger suggestions in Cursor when this happens. You can find more info about the behavior you're seeing here: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/449#issuecomment-992734536
