### ISSUE TITLE
Extension should have an icon for css files 

### ISSUE THREAD

**Issue by danteissaias** [tailwindlabs/tailwindcss-intellisense#786]
<img width="279" alt="CleanShot 2023-05-22 at 15 05 20@2x" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/105590557/ab0b3095-aa6c-4477-881d-92f724567642">

Files do not have an icon when syntax mode is set to tailwindcss

**Comment by bradlc** [comment]
Hey @danteissaias, thanks for the suggestion! A default icon will be added in the next release, via #794 👍
