### ISSUE TITLE
静态html页面使用CND引入tailwindcss.js时，无法使用IntelliSense的代码提示

### ISSUE THREAD

**Issue by deajax** [tailwindlabs/tailwindcss-intellisense#790]
静态html页面使用CND引入tailwindcss.js时，无法使用IntelliSense的代码提示。
所有的方法似乎都是在使用cli的时候才能使用。

When using CND to introduce tailwindcss.js on static HTML pages, IntelliSense's code prompt cannot be used

**Comment by thecrypticace** [comment]
Hey! The Intellisense extension does need a config file to work today. I would suggest creating one in your project root to enable the extension. An empty file will work just fine for this case if the defaults suit your needs.

If you want to customize the config _and_ have those changes show up in Intellisense and work with the CDN you can import an ESM config file in the browser and tell the CDN to use it. Note that if you do this you don't get hot-reloading. The CDN is really only meant for super quick prototyping. We recommend installing from NPM and using something like Vite, Next, Astro, etc… for anything more substantial.

The following is an example config and HTML file where the config is shared between Intellisense and the CDN. In order for the config importing to work you still have to serve the files from a web server — opening them directly in the browser will not work.

Example ESM config:
```js
export default {
  theme: {
    extend: {
      //
    },
  },
};
```

Example HTML that uses the ESM config:
```html
<script src="https://cdn.tailwindcss.com/3.3.1"></script>
<script type="module">
  import cfg from "./tailwind.config.js";
  tailwind.config = cfg;
</script>

<!-- Your code here -->
<h1 class="text-3xl font-bold underline">
  Hello world!
</h1>
```

Hope that helps! ✨

**Comment by deajax** [comment]
thank you very mach!
