### ISSUE TITLE
'x' applies the same CSS properties as 'y' issue when both are object

### ISSUE THREAD

**Issue by babakfp** [tailwindlabs/tailwindcss-intellisense#791]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.11

---

Hi

I have the styles for these classes inside my `.postcss` file. Can we fix this not to show the yellow lines when the values are empty objects?

![Screenshot 2023-05-26 123414](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/44144724/b3b683ee-b2ac-48f2-b480-b26d1336bf04)

![Screenshot 2023-05-26 123445](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/44144724/c83a396d-7bde-42e3-b614-1b66e086a9fe)

Thanks

**Comment by bradlc** [comment]
Hey @babakfp, thanks for reporting this! Will be fixed in the next release 👍
