### ISSUE TITLE
Suggestion box not showing up everytime

### ISSUE THREAD

**Issue by bishalkar10** [tailwindlabs/tailwindcss-intellisense#798]
**What version of VS Code are you using?**
v1.77.2     

**What version of Tailwind CSS IntelliSense are you using?**
v0.9.11

**What version of Tailwind CSS are you using?**   
v3.3.2

**What package manager are you using?**
npm

**What operating system are you using?**
Windows

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};

```

**VS Code settings**

```json
{
  "editor.inlineSuggest.enabled": true,
  "files.exclude": {
    "**/.git": false
  },
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "github.copilot.enable": {
    "*": true,
    "plaintext": true,
    "markdown": true,
    "scminput": false
  },
  "tailwindCSS.emmetCompletions": true,
  "workbench.colorTheme": "Sublime Material Theme - Dark",
  "update.mode": "manual",
  "files.associations": {
    "*.js": "javascriptreact",
    "*.css": "postcss"
  },
  "editor.formatOnSave": true,
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "html.format.contentUnformatted": "",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "tailwind-fold.autoFold": true,
  "workbench.iconTheme": "material-icon-theme",
  "git.suggestSmartCommit": false
}

```

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead. 

// This is a React App component . This is enogh  to explain my problem .  As you can see in the first image : I have just started writting my first className but I can't see the sugestions. just after writting a correct tailwindcss classname the suggeston box shows up. To get the suggestion box again . I can just delete the '0' from the 'bg-red-500' and put the '0' back again and then the suggestion preview box will show up. I am having these inconsistencies... Please fix them.
```
function App() {
  return (
    <>
      <h1 className="bg-red-">Hello</h1>
    </>
  );
} 

export default App 
``` 

1st Image : 
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/112653391/79ed92cc-714d-4b70-9072-594acf422fb1)

2nd Image : 
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/112653391/43ed9e30-2fcd-43f1-b6d7-004b3aae1b42)

3rd Image : 
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/112653391/faf363c8-6713-4eb6-a582-6d60211d6365)

**Comment by bradlc** [comment]
Hey @bishalkar10. If you're working with JSX we [recommend](https://github.com/tailwindlabs/tailwindcss-intellisense#recommended-vs-code-settings) configuring the `editor.quickSuggestions` setting to include strings:

```
"editor.quickSuggestions": {
  "strings": true
}
```

Does this fix your issue? If not please could you provide a screen recording of the issue?

**Comment by bishalkar10** [comment]
I have initially thought of recording the issue and share, cause that would
represent the actual problem better.
But my machine is but old . It's intel i3 6th gen. I'll try my best to
record and send it.

**Comment by bishalkar10** [comment]
This is the screen recoding. Please do check.



https://github.com/tailwindlabs/tailwindcss-intellisense/assets/112653391/71398267-a6f5-4834-9542-428e98e85c7e

**Comment by bradlc** [comment]
Thanks for sharing. After watching the recording I am pretty sure this is happening because you don't have `editor.quickSuggestions` configured as recommended:

```
"editor.quickSuggestions": {
  "strings": "on"
}
```

Can you confirm that this fixes your issue?

**Comment by bishalkar10** [comment]
Yes. Thank U
