### ISSUE TITLE
The plugin does not work when using two custom breakpoints in a class

### ISSUE THREAD

**Issue by lvzhenbo** [tailwindlabs/tailwindcss-intellisense#799]
**What version of VS Code are you using?**

v1.79.0

**What version of Tailwind CSS IntelliSense are you using?**

v0.9.11

**What version of Tailwind CSS are you using?**

v3.3.2

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Tailwind config**

```js
import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {},
    fontFamily: {
      'LXGW-WenKai-Screen': ['LXGW WenKai Screen', 'sans-serif'],
    },
  },
  plugins: [],
} satisfies Config;

```

**VS Code settings**

The plugin settings have not been changed

**Reproduction URL**

https://github.com/lvzhenbo/legado-web

**Describe your issue**

I think the title and the following image can illustrate the problem
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/32427677/25272d2a-08f9-4cd6-bf3f-4b4d45633184)
To demonstrate that I have enabled the plugin, let me move the mouse to the next attribute
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/32427677/75277060-c0be-464a-b3cf-e52d9f95c90e)

**Comment by lvzhenbo** [comment]
I think I'm having an occasional problem, because today I opened it normally

**Comment by bradlc** [comment]
Hey @lvzhenbo. Please can you share a screen recording of the issue?

**Comment by bradlc** [comment]
I'm going to close this as it's been a few weeks without a response, but if you're still experiencing this issue and can share a screen recording please open a new issue, thanks!
