### ISSUE TITLE
Not displaying expected CSS class for an arbitrary screen modifier

### ISSUE THREAD

**Issue by onmax** [tailwindlabs/tailwindcss-intellisense#801]
**What version of VS Code are you using?**

Tailwind Play

**What version of Tailwind CSS IntelliSense are you using?**

Tailwind Play

**What version of Tailwind CSS are you using?**

v3.3.2

**What package manager are you using?**

Tailwind Play

**What operating system are you using?**

Any

**Tailwind config**

Default config

**VS Code settings**

Default config

**Reproduction URL**

https://play.tailwindcss.com/xRWyFwrcVu

**Describe your issue**

When I hover the mouse over the class `max-[850px]:hidden` I don't see the generated expected class. I guess this issue is with the linter

```css
@media (max-width: 850px) {
  .max-\[850px\]\:hidden {
    display: none;
  }
}
```

But I see it for other classes:

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/22072217/b1426e48-c417-4655-847c-55fda6074309)

Sorry if this issue is not related to this repo. Thank you! 🙌

**Comment by thecrypticace** [comment]
I'm seeing this in your Tailwind Play link:

<img width="532" alt="Screenshot 2023-06-15 at 08 52 53" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/614993/4fecb7d2-eca4-4a29-ba1a-7173591289a4">

This looks correct to me. What browser are you using?

**Comment by onmax** [comment]
Sorry, my bad. It works now.
