### ISSUE TITLE
Suggestions not working for CSS files in VS Code 

### ISSUE THREAD

**Issue by adamlavery** [tailwindlabs/tailwindcss-intellisense#804]
**What version of VS Code are you using?** v1.79.2
**What version of Tailwind CSS IntelliSense are you using?** v0.9.11
**What version of Tailwind CSS are you using?** v3.3.2
**What package manager are you using?** npm,
**What operating system are you using?** Windows

**Describe your issue**

When working on CSS files in VS Code there's no intellisense. Works fine on HTML/PHTML but nothing in CSS. @apply rules are all flagged as unknown. Tried adding mappings as suggested for example {"css": "css"} and {"css":"html"} but no change:

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/13659750/a631a146-24a7-40a1-9a9f-e1916be9feab)

How do I enable intellisense on CSS files so I can select and see makeup of rules?

**Comment by thecrypticace** [comment]
Hey! You can do this by selecting the Tailwind CSS language mode in VS Code.

<img width="1194" alt="Screenshot 2023-06-20 at 08 12 06" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/614993/75d7dfdc-4581-4988-9fde-f5ad4678a17c">

Once you select it the warnings you see will go away:

<img width="1194" alt="Screenshot 2023-06-20 at 08 17 55" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/614993/b9d6219d-365e-4879-9038-816f6dbae5a2">
