### ISSUE TITLE
Nuxt3 VS Code intellisense not working

### ISSUE THREAD

**Issue by NisuSan** [tailwindlabs/tailwindcss-intellisense#805]
**What version of VS Code are you using?**

v1.79.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.9.11

**What version of Tailwind CSS are you using?**

v3.3.2

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Tailwind config**

```js
const defaultFonts= ['ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Helvetica Neue', 'Arial', '"Noto Sans"', 'sans-serif', '"Apple Color Emoji"', '"Segoe UI Emoji"', '"Segoe UI Symbol"', '"Noto Color Emoji"']

export default {
  theme: {
    fontFamily: {
      sans: ['Roboto', ...defaultFonts],
    },
    extend: {
      colors: {
        main_brand: '#156EC7', //This color should be eye-catching but not harsh. It can be liberally applied to your layout as its main identity.
        light_shades: '#F3F5F5', //Use this color as the background for your dark-on-light designs, or the text color of an inverted design.
        light_accent: '#81B5D1', //Accent colors can be used to bring attention to design elements by contrasting with the rest of the palette.
        dark_accent: '#6378B2', //Another accent color to consider. Not all colors have to be used - sometimes a simple color scheme works best.
        dark_shades: '#2c355a', //Use as the text color for dark-on-light designs, or as the background for inverted designs.
        default: '#999999', //Some common things on website
        success: '#4b966d', //Success btns, alerts, etc.
        success_hover: '#438762', //Success btns, alerts, etc.
        warning: '#c88635', //Warning btns, alerts, etc.
        warning_hover: '#cd9249', //Warning btns, alerts, etc.
        danger: '#f44336', //Danger btns, alerts, etc.
        danger_hover: '#db3c30', //Danger btns, alerts, etc.
      },
      fontFamily: {
        logo: ['Rubik', ...defaultFonts]
      },
    }
  }
}
```

**VS Code settings**

```json
{
  "tailwindCSS.experimental.configFile": ".nuxt/tailwind.config.cjs",
  "files.associations": {
    "*.css": "tailwindcss"
  },
  "editor.quickSuggestions": {
    "strings": true
  }
}
```

**Describe your issue**

With Nuxt3 v3.5.3 VS Code intellisense don't provide suggestion for tw classes.
![Recording 2023-06-23 095407](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/14041642/7fc0a59c-7237-4ae4-af1b-59121f75629b)

And there is no `tailwind.config.cjs` file in the ```.nuxt``` directory

**Comment by jesspinklet** [comment]
Duo to the new version of tailwind and nuxt, the implementation has changed.
we don't have tailwindconfig inside our .nuxt folder anymore.

https://tailwindcss.nuxtjs.org/getting-started/setup

Try to install step by step with this new doc and it should fix your issue

**Comment by benjamincanac** [comment]
You can use `"tailwindCSS.experimental.configFile": "tailwind.config.ts"` in your VSCode `settings.json` if you're using a TypeScript `tailwind.config.ts`.

You can also follow this guide https://tailwindcss.nuxtjs.org/tailwind/editor-support#editor-support to write the `.nuxt/tailwind.config.cjs` yourself.

**Comment by NisuSan** [comment]
Thanks, now it's all working as expected
