### ISSUE TITLE
Problem in classes with - and number

### ISSUE THREAD

**Issue by cagan123-alt** [tailwindlabs/tailwindcss-intellisense#812]
VSCode version : v1.79.2

**What version of Tailwind CSS IntelliSense are you using?**

TailwindCss version : v0.9.11

**What version of Tailwind CSS are you using?**

TailwindCss version :v3.3.2

**What package manager are you using?**

npm

**What operating system are you using?**

Windows

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}

```

**VS Code settings**

```json
{
    "files.autoSave": "afterDelay",
    "workbench.iconTheme": "material-icon-theme",
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.wordWrap": "on",
    "liveServer.settings.donotShowInfoMsg": true,
    "workbench.colorTheme": "Tokyo Night",
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "dart.debugExternalPackageLibraries": false,
    "dart.debugSdkLibraries": false,
    "tabnine.experimentalAutoImports": true,,
    "[python]": {
        "editor.formatOnType": true
    },
    "terminal.integrated.env.windows": {},
    "editor.inlineSuggest.enabled": true,
    "tailwindCSS.emmetCompletions": true,
    "tailwindCSS.experimental.classRegex": [

    
    ],
    "javascript.format.insertSpaceAfterConstructor": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true,
    "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
    "javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,
    "javascript.format.placeOpenBraceOnNewLineForFunctions": true,
    "tailwindCSS.experimental.configFile":null,
    "editor.quickSuggestions": {
        "strings": "on"
    }
}
```

**Describe your issue**

I want show the issue with project because issue is something different normally in tailwind intellisense when you write h- it will show all height classes but when i write h-2 it doesnt show h-20 h-22 h-24 etc... it still shows all possible h- classess this bug appears just in classes with "-" and after number for example h-24 ,w-24 etc... if you write h-20 press space and then backspace it will show proper version photos of bug goes like :
Normally with error:
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/85545585/46ebfb0b-8b47-4b67-96a3-6f7ef91d33fc)
Space and backspace:
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/85545585/270901e6-318e-47f6-9ce4-3cb0b29afbe0)

What i have tried to solve this :
"tailwindCSS.experimental.classRegex": [
        "[a-zA-Z0-9\\-_:/]+",
        "[a-zA-Z0-9-_:/]+"
    
    ],
Error continued and nothing changed. Is this error cause by my end or because of extension. Vscode settings are added.

**Comment by bradlc** [comment]
Thanks for sharing @cagan123-alt! Are you seeing the same thing if you upgrade to the latest version of VS Code (`v1.80.0`)?

**Comment by cagan123-alt** [comment]
yes my version of vscode is 1.18.0 now and still have the issue 
Here is the photo of it:
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/85545585/cc12ce38-5c2a-40c0-9720-b3618b3a48a4)

**Comment by bradlc** [comment]
I think this may be a VS Code issue. I have opened an issue over on their repo: https://github.com/microsoft/vscode/issues/188162
