### ISSUE TITLE
The extension stops working when add view directory to the workspace.

### ISSUE THREAD

**Issue by anchan42** [tailwindlabs/tailwindcss-intellisense#814]
**What version of VS Code are you using?**

v1.79.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.9.11

**What version of Tailwind CSS are you using?**

^3.1.0

**What package manager are you using?**

npm

**What operating system are you using?**

 Windows

**Tailwind config**

```js
import defaultTheme from 'tailwindcss/defaultTheme';
// import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        "./node_modules/tw-elements/dist/js/**/*.js"
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    darkMode: 'class',
    plugins: [require("tw-elements/dist/plugin.cjs")],
};

```

**VS Code settings**

```json
    "tailwindCSS.includeLanguages": {
        "html": "html",
        "javascript": "javascript",
        "css": "css",
        "php": "php",
    },
    "editor.quickSuggestions": {
        "strings": true
    },
```

**Describe your issue**
It is working ok as long as the work space doesn't include the view or resource folder.
This is a Laravel project. Once the view directory is added to the workspace, it stops working completely.

**Comment by anchan42** [comment]
I managed to get it to work by copy tailwind.config.js to the view directory.
Not ideal though.

**Comment by bradlc** [comment]
Hey @anchan42, please can you share your project and instructions on how to reproduce the issue? If you can't share your actual project then a minimal project example will also be fine, thanks!

**Comment by bradlc** [comment]
I'm going to close this as it's been a couple weeks without a response, but if you're still experiencing this issue and can share a reproduction please open a new issue, thanks!
