### ISSUE TITLE
Intellisense not working while using '@tailwindcss-animate' plugin

### ISSUE THREAD

**Issue by inmess** [tailwindlabs/tailwindcss-intellisense#817]
**What version of VS Code are you using?**

For example: v1.79.2

**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.9.11

**What version of Tailwind CSS are you using?**

For example: v3.3.2

**What package manager are you using?**

For example: yarn

**What operating system are you using?**

For example: macOS

**Tailwind config**

```ts
import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ["var(--font-cal)", "system-ui", "sans-serif"],
        default: ["var(--font-inter)", "system-ui", "sans-serif"]
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    // require("@tailwindcss-animate"),
  ],
} satisfies Config;
```

**VS Code settings**

```json
{
    "editor.linkedEditing": true,
    "editor.inlineSuggest.enabled": true,
    "editor.quickSuggestions": {
        "strings": "on"
    },
    "tailwindCSS.experimental.configFile": "tailwind.config.ts"
}
```

**Describe your issue**

The thing is Intellisense does not work before I disabled plugin `@tailwindcss-animate` in my `tailwind.config.ts` file. I've been searching through this repo's issues to find a solution early today, and nothing helpful for my problem, until I disable the plugin above.

**Here's the log of tailwindcss intellisense I found**
```
[Error - 17:12:43] Tailwind CSS: Can't resolve '@tailwindcss-animate' in '/Users/XXX/Documents/front/XXX-project'
Error: Can't resolve '@tailwindcss-animate' in '/Users/XXX/Documents/front/XXX-project'
    at c (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:130:7129)
    at /Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:131:713
    at /Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:5:78), <anonymous>:27:1)
    at /Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:134:7650
    at /Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.11/dist/tailwindServer.js:134:401
```

Since this problem was "solved" after what I did, I don't really know whether it's a bug or something.

**Comment by bradlc** [comment]
Hey @inmess. I think you have a typo and you meant to require `tailwindcss-animate` instead of `@tailwindcss-animate`. `@tailwindcss-animate` is not a valid npm package name, but `tailwindcss-animate` is: https://npm.im/tailwindcss-animate

I hope that helps!

**Comment by inmess** [comment]
> Hey @inmess. I think you have a typo and you meant to require `tailwindcss-animate` instead of `@tailwindcss-animate`. `@tailwindcss-animate` is not a valid npm package name, but `tailwindcss-animate` is: https://npm.im/tailwindcss-animate
> 
> I hope that helps!

Oops! Sorry for bothering, that was unexpected😂
Thank you for pointing out that!
