### ISSUE TITLE
Intellisense not working with WSL

### ISSUE THREAD

**Issue by nicpalard** [tailwindlabs/tailwindcss-intellisense#833]
**What version of VS Code are you using?**

Version: 1.80.2 (system setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**What version of Tailwind CSS IntelliSense are you using?**

v0.9.11

**What version of Tailwind CSS are you using?**

3.3.3

**What package manager are you using?**

npm

**What operating system are you using?**

Windows with WSL2.0 emulating Ubuntu

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {},
    fontFamily: {
      'sans': 'Poppins, sans-serif',
    }
  },
  plugins: [],
}
```

**VS Code settings**

```json
{
    "files.associations": {
        "*.json5": "jsonc"
    },
    "workbench.iconTheme": "file-icons",
    "workbench.colorTheme": "Dracula",
    "security.allowedUNCHosts": [
        "wsl.localhost"
    ],
    "javascript.updateImportsOnFileMove.enabled": "always",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "editor.inlineSuggest.enabled": true,
    "editor.quickSuggestions": {
        "strings": true
    },
    "css.validate": false,
    "tailwindCSS.classAttributes": [
        "className",
        "class"
    ],
    "tailwindCSS.includeLanguages": {
        "html": "HTML",
        "javascript": "javascript",
        "javascriptreact": "javascriptreact",
        "typescriptreact": "typescriptreact",
        "typescript": "typescript",
    },
}
```

**Describe your issue**

Intellisense not working whatsoever even when pressing `ctrl` + `space` to manually triggers it. I am working in a react typescript app in tsx files and I have already tried reinstalling TailwindCSS Intellisense and re reunning `npx tailwindcss init` to regenerate a clean tailwind css config file.
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/12082794/1ce48eb3-bcbb-4cf1-9b33-255b0468a545)

**Comment by bradlc** [comment]
Hey @nicpalard. Do you have the [WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) installed, and did you install Tailwind CSS IntelliSense _inside WSL_?

**Comment by nicpalard** [comment]
Oh wow that was it. I was not aware of such specificities when using WSL, was working pretty fine previously with MacOs. Thanks a lot for taking the time to answer and solving my issue.

Have a great day !

**Comment by kgnfth** [comment]
> Hey @nicpalard. Do you have the [WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) installed, and did you install Tailwind CSS IntelliSense _inside WSL_?

I have the same issue
WSL is globally enabled
Tailwind CSS IntelliSense
v0.10.4 Extension is enabled on 'WSL: Ubuntu'
