### ISSUE TITLE
Tailwind IntelliSense disables HTML IntelliSense in .svelte files

### ISSUE THREAD

**Issue by Skyman-2** [tailwindlabs/tailwindcss-intellisense#834]
VS Code version: v1.72.1

Tailwind IntelliSense version: v0.9.11

Tailwind CSS version: v3.3.3

Package manager: npm

Operating System: Windows

**Tailwind config**
```js
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Describe your issue**
Upon installing the extension Tailwind CSS IntelliSense, my HTML IntelliSense stops working when I edit .svelte files.
For example, without the extension, if I type `header` in my .svelte file, and hit TAB, the HTML IntelliSense fills in with `<header></header>`. However, when I install the extension Tailwind CSS IntelliSense, and retype `header`, hitting TAB only indents my code instead of filling it. Furthermore, the auto-closing of HTML tags also appears to be unavailable, since upon closing a tag with a `>` symbol, no closing tag is created.

**Steps to try to solve the issue**
To solve this issue, I first tried to look it up on the Internet, and I couldn't find any reports or posts about this issue. I then tried to uninstall and reinstall the extension to no avail. I have also tried disabling the extension and reenabling it, but that didn't work either.

**More information**
My problem occurs in a Svelte + SvelteKit project. It occurred in another Svelte project on which I worked. Neither of the projects had the options Svelte proposes upon creation of a project.
An important note (I think) is that when creating an HTML file inside my Svelte project (inside the `src/routes/` folder), the HTML IntelliSense works perfectly, and so does the Tailwind CSS IntelliSense.

**Comment by bradlc** [comment]
Hey @Skyman-2. I can't reproduce this. Please can you share a GitHub repository containing a project where you are seeing this issue? Please can you also share your VS Code settings in JSON format, and a list of extensions you have installed (you can run `code --list-extensions --show-versions` if you have the Code CLI installed)

**Comment by Skyman-2** [comment]
Here's a link to the [latest project](https://github.com/Skyman-2/youtube-converter-test) on which I noticed the issue.

Here is the list of all my extensions' folder names (I can also provide the normal name, but getting those names was easier since I don't have Code CLI apparently) :
- aaron-bond.better-comments-3.0.2
- akamud.vscode-theme-onedark-2.3.0
- alexcvzz.vscode-sqlite-0.14.1
- ardenivanov.svelte-intellisense-0.7.1
- bradlc.vscode-tailwindcss-0.9.11
- burkeholland.simple-react-snippets-1.2.7
- cschlosser.doxdocgen-1.4.0
- devsense.phptools-vscode-1.33.12934-win32-x64
- eamodio.gitlens-13.5.0
- esbenp.prettier-vscode-10.1.0
- fivethree.vscode-svelte-snippets-0.5.0
- formulahendry.code-runner-0.12.0
- fwcd.kotlin-0.2.31
- icrawl.discord-vscode-5.8.0
- jeff-hykin.better-cpp-syntax-1.17.2
- markusylisiurunen.githubdarkmode-0.1.6
- mathiasfrohlich.kotlin-1.7.1
- ms-edgedevtools.vscode-edge-devtools-2.1.3
- ms-python.isort-2022.8.0
- ms-python.python-2022.16.1
- ms-python.vscode-pylance-2023.1.10
- ms-toolsai.jupyter-2022.9.1303220346
- ms-toolsai.vscode-jupyter-cell-tags-0.1.8
- ms-toolsai.vscode-jupyter-slideshow-0.1.5
- ms-vscode-remote.remote-containers-0.266.1
- ms-vscode-remote.remote-ssh-0.96.0
- ms-vscode-remote.remote-ssh-edit-0.84.0
- ms-vscode-remote.remote-wsl-0.72.0
- ms-vscode.cmake-tools-1.14.34
- ms-vscode.cpptools-1.16.3-win32-x64
- ms-vscode.cpptools-extension-pack-1.3.0
- ms-vscode.cpptools-themes-2.0.0
- ms-vscode.powershell-2023.6.0
- ms-vscode.remote-explorer-0.4.0
- ms-vsliveshare.vsliveshare-1.0.5877
- ms-vsliveshare.vsliveshare-pack-0.4.0
- pivaszbs.svelte-autoimport-1.0.4
- qwtel.sqlite-viewer-0.3.13
- ritwickdey.liveserver-5.7.9
- sdras.vue-vscode-snippets-3.1.1
- svelte.svelte-vscode-107.9.0
- teabyii.ayu-1.0.5
- teeseal.ayu-legacy-0.0.2
- tht13.html-preview-vscode-0.2.5
- twxs.cmake-0.0.17
- vscode-icons-team.vscode-icons-12.5.0
- vue.volar-1.8.8
- xdebug.php-debug-1.33.0
- xdebug.php-pack-1.0.3
- zobo.php-intellisense-1.3.2

And here are my settings:
```json
{
  "terminal.integrated.rightClickBehavior": "default",
  "code-runner.runInTerminal": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "liveServer.settings.donotVerifyTags": true,
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "security.workspace.trust.untrustedFiles": "open",
  "files.autoSave": "afterDelay",
  "editor.accessibilitySupport": "off",
  "gitlens.hovers.currentLine.over": "line",
  "phpserver.phpPath": "\"C:\\Program Files\\PHP\\php.exe\"",
  "phpserver.phpConfigPath": "\"C:\\Program Files\\PHP\\php.ini-development\"",
  "[python]": {
  },
  "window.zoomLevel": 1,
  "svelte.ask-to-enable-ts-plugin": false,
  "workbench.iconTheme": "vscode-icons",
  "settingsSync.ignoredExtensions": [
  
  ]
}
```

I am also currently updating my VS Code from version 1.72.1 to 1.81 but it's taking a while. Once it's done I will check to see if updating VS Code helped or not.

**Comment by Skyman-2** [comment]
After updating to version 1.81.0, the issue has disappeared. I also installed the System Setup instead of the User Setup (because for some reason, I couldn't update my VS Code so I just reinstalled it). Since I'm not too familiar with issues and posts like this, I'll let you see if the issue can be closed @bradlc.

**Comment by bradlc** [comment]
Thanks for the update @Skyman-2, I didn't catch that you were using VS Code v1.72! That version is pretty old so it might just have been an issue with VS Code that has since been resolved. Glad it's working now anyway! 🤙
