### ISSUE TITLE
Show Pixel Equivalents with CSS variables

### ISSUE THREAD

**Issue by viclunam** [tailwindlabs/tailwindcss-intellisense#839]
**What version of VS Code are you using?**
v1.81.1

**What version of Tailwind CSS IntelliSense are you using?**
v0.9.11

**What version of Tailwind CSS are you using?**
v3.0.24

**What package manager are you using?**
npm

**What operating system are you using?**
macOs

**Tailwind config**

```js
module.exports = {
  theme: {
    spacing: {
      1: "1rem",
      2: "var(--size-2)"
    }
  },
  plugins: [],
};
```

**VS Code settings**

```json
{
  "tailwindCSS.emmetCompletions": true
}
```

**Reproduction URL**

[https://play.tailwindcss.com/YJSM8qcRU1](https://play.tailwindcss.com/YJSM8qcRU1)

**Describe your issue**

My question is related to the "Show Pixel Equivalents" setting.

When I use fixed values in rem units, it performs the conversion without any problem.

<img width="360" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/98234382/f093f6c7-d031-4fd7-b8e5-fce23b4515bc">

However when I use CSS variables, it can't do the conversion.

<img width="377" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/98234382/4e3e210d-0354-427d-b299-c596f4228291">

**Question: Is there any way to show the px equivalents?**

**Comment by bradlc** [comment]
Hey @viclunam, I think [this comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/809#issuecomment-1660304770) does a good job of explaining some of the complexities with resolving CSS variables and why we therefore don't show colour decorators or pixel equivalents for these.

Ultimately CSS variables are just that: variable. So I'm not sure it even makes sense to resolve a CSS variable to a _single_ pixel equivalent or colour decorator.

If the value of your CSS variable _isn't_ variable then I would consider just using the values directly in your config file, i.e.

```diff
  module.exports = {
    theme: {
      spacing: {
        1: "1rem",
-       2: "var(--size-2)"
+       2: "2rem"
      }
    },
    plugins: [],
  };
```

**Comment by viclunam** [comment]
@bradlc thanks for the quick response, it was very clear to me 😁
