### ISSUE TITLE
Intellisense not working in Vue SFC script lang="ts"

### ISSUE THREAD

**Issue by filipbekic01** [tailwindlabs/tailwindcss-intellisense#843]
Intellisense not working in Vue SFC script lang="ts"

**Comment by bradlc** [comment]
Hey @filipbekic01, what specifically isn't working? If you're using JSX and want IntelliSense in the `class` prop you should use `lang="tsx"`, and make sure you're using the latest version of the extension, which is currently `0.9.13`.

**Comment by bradlc** [comment]
Going to close this because the information requested in the new issue template has not been provided and without that it's not going to be possible to track down the problem.

If you're still experiencing problems please open a new issue with the details requested, thanks!
