### ISSUE TITLE
Looks like `@tailwindcss/language-server` npmjs artifact is still with 0.0.13

### ISSUE THREAD

**Issue by chenrui333** [tailwindlabs/tailwindcss-intellisense#850]
👋 it looks like the `@tailwindcss/language-server` npmjs artifact is still with 0.0.13, but the github release is with 0.10.0 now. Did I miss anything? Thanks!

**Comment by bradlc** [comment]
Hey @chenrui333, the GitHub release you are referring to is for Tailwind CSS IntelliSense. The latest `@tailwindcss/language-server` release is here: https://github.com/tailwindlabs/tailwindcss-intellisense/releases/tag/%40tailwindcss%2Flanguage-server%40v0.0.13

We also now have an `insiders` version of the language server which is always up to date with the `master` branch here:

```
npm install @tailwindcss/language-server@insiders
```

**Comment by chenrui333** [comment]
got you, thanks @bradlc!
