### ISSUE TITLE
Blocking in [tailwind.config.js] Building...

### ISSUE THREAD

**Issue by JoyfulAndSpeedyMan** [tailwindlabs/tailwindcss-intellisense#857]
**What version of VS Code are you using?**

1.82.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.10.0

**What version of Tailwind CSS are you using?**

^6.8.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    `/components/**/*.{vue,js,ts}`,
    `/layouts/**/*.vue`,
    `/pages/**/*.vue`,
    `/composables/**/*.{js,ts}`,
    `/plugins/**/*.{js,ts}`,
    `/utils/**/*.{js,ts}`,
    `/App.{js,ts,vue}`,
    `/app.{js,ts,vue}`,
    `/Error.{js,ts,vue}`,
    `/error.{js,ts,vue}`,
    `/app.config.{js,ts}`
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**VS Code settings**

```json
{
    "security.workspace.trust.untrustedFiles": "open",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "gitlens.hovers.currentLine.over": "line",
    "gitlens.currentLine.enabled": false,
    "gitlens.codeLens.enabled": false,
    "editor.unicodeHighlight.nonBasicASCII": false,
    "git.enableSmartCommit": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "C_Cpp.updateChannel": "Insiders",
    "git.confirmSync": false,
    "workbench.iconTheme": "material-icon-theme",
    "vsicons.dontShowNewVersionMessage": true,
    "redhat.telemetry.enabled": true,
    "files.associations": {
        "*.cnf": "properties"
    },
    "Lua.diagnostics.globals": [
        "ngx"
    ],
    "openresty.luacheck.globals": [
        "ngx"
    ],
    "[python]": {
        "editor.formatOnType": true
    },
    "tailwindCSS.experimental.configFile": null
}
```

**Reproduction URL**

https://github.com/JoyfulAndSpeedyMan/tailwindcss-demo

**Describe your issue**

The project is initialized using nuxt as follows:
```
pnpm dlx nuxi@latest init tailwindcss-demo
cd tailwindcss-demo
pnpm i -D @nuxtjs/tailwindcss
npx tailwindcss init
pnpm install
```
Then I changed two configuration files: nuxt.config.ts and tailwind.config.js, which can be found in the repository above
I typed 'bg' in the class section of '<div>01</div>' in index.vue, and it didn't appear with the class name I was expecting, like bG-white.
When I tried to view it in vscode by typing: 'Tailwind CSS: Show Output', I found that blocking the '[tailwind.config.js] Building... `,
```
[tailwind.config.js] Initializing...
[tailwind.config.js] Loaded Tailwind CSS config file: d:/workspace/demo/nuxt/tailwindcss-demo/tailwind.config.js
[tailwind.config.js] Loaded postcss v8.4.29: D:\workspace\demo\nuxt\tailwindcss-demo\node_modules\.pnpm\postcss@8.4.29\node_modules\postcss
[tailwind.config.js] Loaded tailwindcss v3.3.3: D:\workspace\demo\nuxt\tailwindcss-demo\node_modules\.pnpm\tailwindcss@3.3.3\node_modules\tailwindcss
[tailwind.config.js] Building...
[tailwind.config.js] File changed: d:\workspace\demo\nuxt\tailwindcss-demo\tailwind.config.js
[tailwind.config.js] Building...
[tailwind.config.js] File changed: d:\workspace\demo\nuxt\tailwindcss-demo\tailwind.config.js
[tailwind.config.js] Building...
```

**Comment by bradlc** [comment]
Hey @JoyfulAndSpeedyMan. Can you try configuring `editor.quickSuggestions` and seeing if that resolves your issue?

```
"editor.quickSuggestions": {
  "strings": "on"
}
```

**Comment by JoyfulAndSpeedyMan** [comment]
Solved, thank you very much @bradlc

**Comment by premier213** [comment]
[tailwind.config.ts] Building...

I have this problem and 

> Hey @JoyfulAndSpeedyMan. Can you try configuring `editor.quickSuggestions` and seeing if that resolves your issue?
> 
> ```
> "editor.quickSuggestions": {
>   "strings": "on"
> }
> ```

It is not working for me

**Comment by premier213** [comment]
[tailwind.config.ts] Building...

I have this problem 
[link](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/857#issuecomment-1723100979
)
this solution does not work for me
