### ISSUE TITLE
Autocompletion won't work for css classes created in .css files

### ISSUE THREAD

**Issue by blatoo** [tailwindlabs/tailwindcss-intellisense#859]
**What version of VS Code are you using?**

Version: 1.82.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.11.9

**What version of Tailwind CSS are you using?**

3.3.3

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

**VS Code settings**

```json
  "tailwindCSS.experimental.classRegex": [],
  "tailwindCSS.experimental.configFile": null,
  "tailwindCSS.emmetCompletions": true,
  "editor.quickSuggestions": {
    "strings": "on"
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "files.associations": {
    "*.css": "tailwindcss"
  }
```

**Reproduction URL**
https://github.com/blatoo/tailwind_test

**Describe your issue**

I use vite created the react typescript project. Then added the tailwindcss and installed the tailwindcss IntelliSense plugin in vscode. ( I followed the official documentation. ) 

There are only auto suggestions for tailwind nature classes, but there are no suggestions for classes which I created in css file.

In my example, I created the two classes in `src/index.css`

```
@layer components {
  .max-container {
    max-width: 1440px;
    margin: 0 auto;
  }

  .custom-btn {
    @apply bg-black text-yellow-200 rounded-full px-4 py-1;
  }
}
```

but none of them will be suggested in `src/App.tsx`

```
      <div className="py-6 max-container">
        <button className="custom-btn">Hello</button>
      </div>
```
The `py-6` is suggested, but the `max-container` and `custom-btn` won't show.

Did I do something wrong or is it a bug?

Thanks very much for the help!

**Comment by bradlc** [comment]
Hey @blatoo. I'm going to close this in favour of https://github.com/tailwindlabs/tailwindcss/discussions/7259 because we want to use the "issues" list here for bugs only 👍
