### ISSUE TITLE
[Angular] NgClass works but conditional class doesn't

### ISSUE THREAD

**Issue by sream** [tailwindlabs/tailwindcss-intellisense#861]
**What version of VS Code are you using?**
v1.82.2

**What version of Tailwind CSS IntelliSense are you using?**
v0.10.0

**What version of Tailwind CSS are you using?**
v3.3.2

**What package manager are you using?**
npm

**What operating system are you using?**
macOS

**Describe your issue**
NgClass directive works as visible in image with the auto-complete where the conditional class attribute doesn't.

<img width="407" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/7093176/134c4f43-5603-4a0e-bcb9-ba6e176783ee">

**Comment by thecrypticace** [comment]
Hey, so we talked about this a bit internally and think that supporting this may be more complex than it seems at a glance. Additionally, this wouldn't be sortable with our Prettier plugin (and we have no plans to support this syntax there as that'd require sorting attributes themselves). I would suggest using `class` and `[ngClass]` in these cases as that already works as expected.

With that, we're going to say no to supporting / handling this syntax in Intellisense for now.
