### ISSUE TITLE
plugins stop working when null

### ISSUE THREAD

**Issue by productdevbook** [tailwindlabs/tailwindcss-intellisense#862]
```

import resolveConfig from 'tailwindcss/resolveConfig.js'

```

resolveConfig export config and vscode used.
```

    "tailwindCSS.experimental.configFile": "./tailwind.config.mjs",
    
```

this problem, if null delete problem fixed.
NULL
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/38668796/27512738-dd36-43e6-8974-659faed5811f)

IF delete fixed
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/38668796/802a5943-dd9b-4306-80ed-54f79c079b78)

**Comment by thecrypticace** [comment]
Hey! So Tailwind CSS plugins cannot be `null`. They have to be a function, an object with a `handler` key and (optionalally) a `config` key, or the return value of the `plugin()` helper. If you have plugins that are conditional I'd suggest you use something like `.filter(Boolean)` to filter out the null values — for example:

```
plugins: [
  plugin1,
  plugin2,
  // …
].filter(Boolean),
```

You can see if you try to specify a null plugin in Tailwind CSS today it will throw an error which is a good indication that it is not an expected or supported value:

<img width="817" alt="Screenshot 2023-10-02 at 09 37 46" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/614993/53f1dcd0-6d52-4d60-b096-03058109d7cf">

Hope that helps! ✨
