### ISSUE TITLE
Intellisense VsCode extension suggestions no working

### ISSUE THREAD

**Issue by DaviMarra** [tailwindlabs/tailwindcss-intellisense#875]
**What version of VS Code are you using?**
1.83.1 (Universal)

**What version of Tailwind CSS IntelliSense are you using?**

v0.10.1

**What version of Tailwind CSS are you using?**

3.3.5

**What package manager are you using?**

I've tried npx and npm neither worked. Let's say I'd use npm

**What operating system are you using?**

macOS
**Tailwind config**

tailwind.config = {
  theme: {
    extend: {
      colors: {
        clifford: '#da373d',
        primary: "#091b51"
      }
    }
  }
}

**VS Code settings**

{
    "tailwindCSS.includeLanguages": {
        "html": "html",
        "javascript": "javascript",
        "css": "css"
    },
    "editor.quickSuggestions": {
        "strings": "on"
     },
     "css.validate": false,
    "editor.inlineSuggest.enabled": true,
     
}

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

For some reason the Tailwind Intellisense VScode extension is not working for me. Any time I try to use the autocomplete or the suggestion, nothing happens, there are no suggestions for class names and anything else at all. 
 I've already followed the instructions in the [read.me](http://read.me/) and also in the extension description on vscode marketplace and still things are not working.
I'm trying to play with the CDN for now, but still, things should work right?
Here's a quick loom video showcasing the issue.
https://www.loom.com/share/46623ee93b164dcfbb46aa8d59dddbe9

**Comment by thecrypticace** [comment]
The intellisense extension requires you to have a local tailwind.config.js file for completions to work. In most cases you can create an empty file and completions will start working.

However, that it will _not_ pick up customizations set using `tailwind.config = {}` in your HTML. You must put the customizations in the config file for the Intellisense extension to pick them up.

The best way to share the configs between the config file and the CDN config is use the config file, make sure it's an ES module, and load it in the browser via `import` like so:

`tailwind.config.js`:

```
export default {
  theme: {
    extend: {
      colors: {
        clifford: '#da373d',
        primary: "#091b51"
      },
    },
  },
};
```

And in your HTML:

```html
<script type="module">
  import config from "./tailwind.config.js"
  window.tailwind.config = config
</script>
```

**Comment by DaviMarra** [comment]
Yes I know that, I already had an tailwind.config.js file and I had a
script in my html to link to it.
I've changed the script I had to this you sent:

<script type="module">
  import config from "./tailwind.config.js"
  window.tailwind.config = config
</script>

and still isn't working.

Please, open the issue again.
the issue has not been solved.

**Comment by thecrypticace** [comment]
@DaviMarra Please provide a reproduction of the repo you are using.

**Comment by DaviMarra** [comment]
[tailwind project.zip](https://github.com/tailwindlabs/tailwindcss-intellisense/files/13221604/tailwind.project.zip)
here's a zip file, it's easier since it's just a test project

**Comment by thecrypticace** [comment]
You *MUST* use the export default syntax for this to work with intellisense AND the CDN.

Replace your config file with this:
```js
export default {
  theme: {
    extend: {
      colors: {
        clifford: "#da373d",
        primary: "#091b51",
      },
    },
  },
};
```

**Comment by DaviMarra** [comment]
Ah ok, now I got it. Thank you. It worked!

**Comment by thecrypticace** [comment]
happy to help!
