### ISSUE TITLE
Tailwind config location

### ISSUE THREAD

**Issue by sebsobseb** [tailwindlabs/tailwindcss-intellisense#88]
My tailwind config comes from a dependency package, and is not located in the root of my project, but in my node_modules...

``` javascript
 postCss: [tailwindcss('node_modules/package/path/to/tailwind.config.js')],
```

How can I make Tailwind CSS IntelliSense work with this kind of set-up?

See: https://github.com/bradlc/vscode-tailwindcss/issues/77

**Comment by hacknug** [comment]
Have you tried creating `tailwind.config.js` at the root of your project to import and export your config dependency there?

**Comment by mayeths** [comment]
@hacknug It will be great if we can place `tailwind.config.js` in customized path, like detect it in `package.json` (#82) . Place it at root of project is somewhat annoy me because I have so many config there now.

**Comment by hacknug** [comment]
From what I understand, #82 is about having Tailwind's config inside `package.json`, no? That doesn't make much sense since most of Tailwind's power comes from the fact its config file is _just_ a js file that can use all kinds of dependencies and custom functions to build the final config.

I agree it would make sense to be able to provide a path to your config file using `package.json` or something else. This should probably be done by using the user-provided path here and falling back to what we have now:

https://github.com/bradlc/vscode-tailwindcss/blob/f5dfe02f74ac9bd68529f1997ae875691b819833/src/index.ts#L137-L141

```js
let files = await Workspace.findFiles( 
  ...(
    [USER_CONFIG_PATH] ||
    [CONFIG_GLOB, '**/node_modules/**']
  ), 
  1 
) 
```

**Comment by sebsobseb** [comment]
+1 for custom path to tailwind config

**Comment by dimative** [comment]
+1 for custom path to tailwind config

**Comment by Utakka** [comment]
+1 for custom path to tailwind config

**Comment by bradlc** [comment]
Not totally against adding this! I'm not sure that the `package.json` file is the correct place for it though. Perhaps the VS Code workspace settings would be better?

**Comment by atif** [comment]
+1 for custom path

**Comment by frbrz** [comment]
> Place it at root of project is somewhat annoy me because I have so many config there now.

Same reaction here.

**Comment by RobM-ADP** [comment]
in a mono-repo project it would be really useful to be able to have more than one tailwind config. For example, if I am building multiple themes, I may have multiple projects that require their own configuration.

**Comment by LeeCheneler** [comment]
Improved mono repo support would be really useful. For instance if I have 2 web apps in the mono repo and they each have different custom colors I'd like to see the intellisense for each when editing css in those packages. Currently the extension only finds your tailwind config if its in the root of the VS Code workspace, so I can open 2 VS Code instances one for each web app and it works.

Prior art of this would ESLint, their lint highlighting VS Code works, they basically walk the tree up to see where the first ESLint config is and then apply the rules so you can have different lint rules for difference packages and they'll work.

**Comment by BjoernRave** [comment]
Is this on anybodies to do? I have a monorepo, with a backend and a frontend folder and would still like to get the intellisense in my frontend project

**Comment by JonathanCallewaert** [comment]
We're also waiting on this feature, this would be really nice

**Comment by Disane87** [comment]
+1 from me. I use NX workspaced for Angular and this extension is not working

**Comment by partydrone** [comment]
The Tailwind documentation [talks about configuring a custom name/location for your configuration file](https://tailwindcss.com/docs/configuration#using-a-different-file-name) in `postcss.config.js`. I have a Rails project, using webpack, and my `postcss.config.js` file looks like this:

``javascript
module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss')('./app/javascript/packs/tailwind.config.js'),
    require('postcss-flexbugs-fixes'),
    require('postcss-preset-env')({
      autoprefixer: {
        flexbox: 'no-2009'
      },
      stage: 3
    })
  ]
}
```

What if you just derived the location of the Tailwind config file from this configuration with fallbacks to the default location?

**Comment by bradlc** [comment]
To address the original issue: You can create a `tailwind.config.js` file and re-export the config file from the npm package:

```js
// tailwind.config.js
module.exports = require('package/path/to/tailwind.config.js')
```

Then update your PostCSS config:

```js
postCss: [tailwindcss('./tailwind.config.js')],
```

**Comment by Garine519** [comment]
you can do something like this

`const jbTheme = require('./src/theme/jumbleberry-theme/tailwind.config');

// extend Theme
// variants.extend.ringOpacity = ['hover'];

module.exports = {
  prefix: jbTheme.prefix,
  purge: ['./src/**/*.{vue,js}'],
  darkMode: false, // or 'media' or 'class'
  important: '#app',
  theme: jbTheme.theme,
  variants: jbTheme.variants,
  plugins: jbTheme.plugins
};
`

**Comment by stepanjakl** [comment]
+1 for custom path to tailwind.config.js

**Comment by stepanjakl** [comment]
Sorry, apparently there is a way, I didn't read the docs properly.

Just add:
```
tailwindcss: { config: './pathbre/to/tailwind.config.js' }
```
to `postcss.config.js`

**Comment by cherrygot-personal** [comment]
What's the equivalent to specifying `config` in the new postcss package (@tailwindcss/postcss) in tailwind v4 release?
