### ISSUE TITLE
There is no inline decorator preview on Webstorm IDE

### ISSUE THREAD

**Issue by violetbee** [tailwindlabs/tailwindcss-intellisense#883]
**What version of VS Code are you using?**

I am using Jetbrains Webstorm latest version.

**What version of Tailwind CSS IntelliSense are you using?**

v0.10.2

**What version of Tailwind CSS are you using?**

v3.3.3

**What package manager are you using?**

npm

**What operating system are you using?**

Windows

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        "xxs-m": "275px",
        "xs-m": "320px",
        "sm-m": "375px",
        "md-m": "425px",
        "lg-m": "490px",
        "2.5xl": "1140px",
        "3xl": "1854px",
        "grid-sm": "640px",
        "grid-md": "1225px",
        "grid-lg": "1566px",
        "grid-xl": "1854px",
        "grid-xxl": "2450px",
      },
      colors: {
        background: "#f3f3f0",
        whitish: "#E4E4E5",
        darkBackground: "#111217",
        primary: "#32445a",
        darkPrimary: "#8AEA9C",
        secondary: "#334756",
        darkSecondary: "#17181F",
        darkHelper: "#1d1d1d",
        accent: "#295270",
        box: "#FDFCFD",
      },
      keyframes: {
        wave: {
          "0%": { transform: "rotate(0.0deg)" },
          "10%": { transform: "rotate(7deg)" },
          "20%": { transform: "rotate(-4deg)" },
          "30%": { transform: "rotate(7deg)" },
          "40%": { transform: "rotate(-2deg)" },
          "50%": { transform: "rotate(5.0deg)" },
          "60%": { transform: "rotate(0.0deg)" },
          "100%": { transform: "rotate(0.0deg)" },
        },
      },
      animation: {
        "waving-hand": "wave 3s linear infinite",
      },
    },
  },
  plugins: [],
};
```

**Describe your issue**

I want to select colors from inline color decorators in HTML, JSX, TSX etc. file but couldn't find any releated settings on Webstorm IDE. Can you please help?

I have already turn on the "tailwindCSS.colorDecorators"

Expected behavior: 
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/61601796/d1570c23-3b97-4b9e-9d7d-ecd60c9f8ba7)

problem is: 
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/61601796/bd8ce2be-1278-4299-ab2e-d03fadfd0f67)

**Comment by thecrypticace** [comment]
This feature doesn't look to be implemented in Webstorm. We support it in intellisense and the language server but it's up to JetBrains to actually implement the feature in their own editor.

It looks like you've found their issue about this given the screenshots but for any passersby here's the link: https://youtrack.jetbrains.com/issue/WEB-47817/Tailwind-css-Show-color-of-class-in-html
