### ISSUE TITLE
Color decorators don't show up in a split editor

### ISSUE THREAD

**Issue by mthierman** [tailwindlabs/tailwindcss-intellisense#885]
**What version of VS Code are you using?**

1.85.1

**What version of Tailwind CSS IntelliSense are you using?**

v0.10.3

**What version of Tailwind CSS are you using?**

3.3.6

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows 11

**Tailwind config**

```js
import type { Config } from "tailwindcss";

export default {
    plugins: [require("@tailwindcss/typography")],
    content: ["./src/**/*.{html,js,ts}"],
} satisfies Config;
```

**VS Code settings**

```json
"editor.colorDecorators": true
"tailwindCSS.colorDecorators": true
"editor.defaultColorDecorators": true
```

**Reproduction URL**

N/A

**Describe your issue**

Color decorators for Tailwind don't show up when you split an editor. This does work with regular CSS.

![Screenshot 2023-12-17 125025](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/68129072/99e0be52-7908-4dd9-9d5e-3a4db8fe4e8e)

**Comment by thecrypticace** [comment]
Confirmed. Weirdly enough the editor that the decorators appear in depends on the order in which you opened the files.

For example, if you opened a CSS file in the 2nd pane but not the first they show up in the 2nd split editor but not the first. If you swap the order then they don't appear in the second editor.

Will look into it!

**Comment by thecrypticace** [comment]
I've got a fix for this. Will get a release out sometime today or tomorrow!
