### ISSUE TITLE
No color indicator for 'dark' variants

### ISSUE THREAD

**Issue by CHE1RON** [tailwindlabs/tailwindcss-intellisense#886]
**What version of VS Code are you using?**

v1.80.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.10.2

**What version of Tailwind CSS are you using?**

v3.0.4

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Describe your issue**

`dark` variants do not hint their color:

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/122524301/52a5029c-bff1-49f3-b99d-54e2c9139315)

**Comment by thecrypticace** [comment]
Hey, I'm not seeing this issue:

<img width="721" alt="Screenshot 2023-12-19 at 08 26 58" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/614993/4f1c0cc6-c13a-48bd-a6b7-041e4af6da2f">

Can you provide a file that reproduces this issue?

Also I noticed you're on an older version of VSCode. I'd suggest updating to 1.85.1 and seeing if your problem disappears.

**Comment by CHE1RON** [comment]
Solved it .. I was missing `darkMode: 'class'` in my config file - without it, Tailwind considers `dark` to be custom / third-party class and hence no Intellisense is applied 😉
