### ISSUE TITLE
[Color previewer]: No support for oklch (DaisyUI v4)

### ISSUE THREAD

**Issue by bastiaanv** [tailwindlabs/tailwindcss-intellisense#887]
**What version of VS Code are you using?**

v1.85.1

**What version of Tailwind CSS IntelliSense are you using?**

v0.10.3

**What version of Tailwind CSS are you using?**

v3.3.6

**What package manager are you using?**

npm

**What DaisyUI version are you using?**

v4.4.19 (dev dependency)

**What operating system are you using?**

MacOS

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{html,js}"],
    plugins: [require("daisyui")],
};

```

**Describe your issue**

The color previewer in VSCode does not show the oklch-colors correctly. Actual color: https://oklch.com/#49.12,0.3096,275.75,100

<img width="545" alt="Screenshot 2023-12-19 at 16 09 58" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/3987804/2deaeb6c-81a8-4fd0-9711-af1a2a4280c2">

**Comment by thecrypticace** [comment]
Support for this is now in the pre-release version of the extension. We're now able to display color decorators for colors using lab, lch, oklab, and oklch. Given that these are wide-gamut color spaces the behaviors here are a bit different:

- Color decorators display the closest sRGB approximation of the color — until VSCode adds support for wide-gamut colors this is the best we can do
- Color equivalent hex values only appear when the color is displayable within the sRGB color space
- Color presentations / pickers are not supported. Given that VSCode does not yet support wide-gamut colors allowing modifications and interactions in this way would be lossy.
