### ISSUE TITLE
Config separator not work 

### ISSUE THREAD

**Issue by missannil** [tailwindlabs/tailwindcss-intellisense#894]
**What version of VS Code are you using?**

For example: v1.85.1

**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.10.5

**What version of Tailwind CSS are you using?**

For example: v3.4.0

**What package manager are you using?**

For example: npm

**What operating system are you using?**

 Windows 10

**Tailwind config**

```js
export default {
  content: ["**/*.html"],
  separator:'_', 
} 
```

**VS Code settings**

```json
 // all default config
```

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

Config separator not work ，hope work when  `separator:'_'`!

**Comment by thecrypticace** [comment]
This was a bug in Tailwind itself causing completions to not show up. This has been fixed and it'll be released in the next tagged Tailwind v3 release. (If it doesn't happen tomorrow then it will some time next week). Thanks for reporting this!
