### ISSUE TITLE
Conflicts with Vim?

### ISSUE THREAD

**Issue by flaugher** [tailwindlabs/tailwindcss-intellisense#90]
I just installed your extension into the Mac version of VS Code 1.41.1 and noticed right away that the Vim (vscodevim) extension stopped working immediately.  I had to uninstall vscode-tailwindcss as I'm a heavy Vim user.  Is this a known issue?

**Comment by evalexpr** [comment]
I had the same issue (almost) - but it was the opposite behaviour.

* I had vscodevim.vim installed
* I installed bradlc.vscode-tailwindcss
* None of the css classes were autocompleting
* I disabled vscodevim.vim
* The classes began autocompleting
* I reenabled vscodevim.vim
* Both things were working (vim mode, as well as the class autocompletion)

Seems strange 🤔 but this worked for me

**Comment by ncko** [comment]
I'm experiencing the same problem as described by @evalexpr

**Comment by bradlc** [comment]
Hey @flaugher. That sounds really weird 🤔 

If you get chance please could you try installing [`v0.3.0-alpha.2`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.2) and see if that fixes the problem? Instructions for installing are on the [`v0.3.0-alpha.1`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.1) notes.

**Comment by bradlc** [comment]
If you could try the newest version (`v0.3.1` right now) of the extension that would be amazing. I'm not seeing any issues with the Vim extension personally, but I might be missing something as I know nothing about Vim.

**Comment by bradlc** [comment]
Going to close this due to inactivity but please feel free to open a new issue if you're still having problems 👍
