### ISSUE TITLE
Color Decorators not appearing inside clsx() with double quotes

### ISSUE THREAD

**Issue by nwpappas** [tailwindlabs/tailwindcss-intellisense#903]
**What version of VS Code are you using?**

1.85.2

**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.10.5

**What version of Tailwind CSS are you using?**

For example: v3.4.1

**What package manager are you using?**

For example: npm

**What operating system are you using?**

For example: macOS

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.svelte',
    './src/**/*.{html,js}'
  ],
  darkMode: ['class', '[flt-theme="dark"]'],
  theme: {
    fontFamily: {
      sans: ['Metropolis', 'Avenir Next', 'sans-serif'],
      mono: ['ui-monospace', 'Consolas', 'Menlo', 'Monaco', 'monospace']
    },
    extend: {},
  },
  plugins: [],
}
```

**VS Code settings**

```json
{
  "editor.accessibilitySupport": "off",
  "terminal.integrated.fontFamily": "Fira Code",
  "terminal.external.osxExec": "iTerm.app",
  "git.autofetch": true,
  "editor.rulers": [80],
  "eslint.workingDirectories": [
    {
      "mode": "auto"
    }
  ],
  "cssVariables.lookupFiles": [
    "**/*.css",
    "**/*.scss",
    "**/*.sass",
    "**/*.less",
    "node_modules/@cds/core/styles/module.tokens.css"
  ],
  "[python]": {
    "editor.formatOnType": true
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "diffEditor.ignoreTrimWhitespace": false,
  "tailwindCSS.experimental.classRegex": [
    ["clsx\\(([^)]*)\\)", "(?:'|\"|`)([^']*)(?:'|\"|`)"]
  ],
  "svelte.enable-ts-plugin": true,
  "[svelte]": {
    "editor.defaultFormatter": "svelte.svelte-vscode"
  },
  // "editor.bracketPairColorization.enabled": true,
  // "editor.guides.bracketPairs": "active"
}
```

**Describe your issue**

When adding classes to `clsx()` the color decorator appears when using single quotes, but not when using double quotes. This is troublesome when using Prettier's default quote rules.

![Screenshot 2024-01-22 at 2 02 23 PM](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/2529208/13d24e37-a87e-44f3-b565-edf1147cf9bf)

**Comment by thecrypticace** [comment]
You should change your class regex to handle all the quotes like this:
```
{
  "tailwindCSS.experimental.classRegex": [
    ["clsx\\(([^)]*)\\)", "'([^']*)'"],
    ["clsx\\(([^)]*)\\)", "\"([^\"]*)\""],
    ["clsx\\(([^)]*)\\)", "`([^`]*)`"],
  ]
}
```

Note that I've included the specific quote type in the inner, negated character class. Because we have a constraint of a single capture group it's easiest to split it up into three regexes.

With this change you should see colors in all spots:

<img width="446" alt="Screenshot 2024-03-21 at 15 04 16" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/614993/65ea5b4f-ab58-4177-a979-b64b13e447d5">
