### ISSUE TITLE
tailwind intellisense not working after adding plugin module

### ISSUE THREAD

**Issue by devsnack** [tailwindlabs/tailwindcss-intellisense#912]
**What version of VS Code are you using?**
 v1.78.2

**What version of Tailwind CSS IntelliSense are you using?**

Latest

**What version of Tailwind CSS are you using?**

 v2.7.4

when add plugins in tailwind.config.js  intellisense stop working 

module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
    colors: colors,
  },
  variants: {
    extend: {
      flex: ["responsive", "direction"],
      margin: ["responsive", "direction"],
      padding: ["responsive", "direction"],
      justifyContent: ["responsive", "direction"],
      gap: ["responsive", "direction"],
      flexDirection: ["responsive", "direction"],
      textAlign: ["responsive", "direction"],
    },
  },
  plugins: [require("tailwindcss-dir")()],
};

**Comment by iammukeshm** [comment]
facing same issue after adding custom plugins to the tailwind config file on astro.

**Comment by thecrypticace** [comment]
@devsnack This is probably related to some error when loading the config. If you update to the pre-release version of the extension you'll likely get a bit more information about what's wrong if you run "Tailwind CSS: Show Output" from the VSCode command palette.

I noticed you're using `colors` but not requiring it. If this is the cause of error then adding the following will fix it:
```js
const colors = require("tailwindcss/colors");
```

It not, please open a new issue and provide a repository on GitHub that can be cloned that reproduces the issue.

@iammukeshm If you're still having issues please do the same, open a new issue and provide a clonable repository as a reproduction so I can look into what's happening.
