### ISSUE TITLE
Enable suggestions when using classnames library

### ISSUE THREAD

**Issue by jtiala** [tailwindlabs/tailwindcss-intellisense#92]
Would it be possible to enable intellisense suggestions when writing strings in [classNames](https://github.com/JedWatson/classnames) function call?

```ts
import React from "react";
import classNames from "classnames";

const Header: React.FC = () => {
  const classes = classNames(["flex", "items-center", "bg-gray-200"]);

  return (
    <header className={classes}>
      <h1>Title</h1>
    </header>
  );
};

export default Header;

```

**Comment by bulby97** [comment]
This is a feature I would love to see. You rarely use strings in `className` when you need to modify your styles based on props.

**Comment by mmirus** [comment]
This would be great! The function is frequently imported as `cx()` instead of `classNames()`, so maybe support for both or a config option for specifying would be helpful. Thanks for the extension, Brad, and congrats on joining the TW team!

**Comment by bradlc** [comment]
Please see #129, in particular [my recent comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129#issuecomment-735915659)
