### ISSUE TITLE
[v4] New `@theme` directive not highlighted properly

### ISSUE THREAD

**Issue by Steffan153** [tailwindlabs/tailwindcss-intellisense#920]
**What version of VS Code are you using?**

1.87.1

**What version of Tailwind CSS IntelliSense are you using?**

v0.11.47 (pre-release)

**What version of Tailwind CSS are you using?**

4.0.0-alpha.7

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Describe your issue**

The variables are not syntax highlighted under the `Tailwind CSS` language mode:

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/40404519/9f880324-c0e7-470c-aa81-8188875097a2)

**Comment by fernandortec** [comment]
I want to contribute to this issue, is anyone currently working on it?

**Comment by thecrypticace** [comment]
This is now available in the pre-release build. You might need to reload vscode for it to notice there's an update.
