### ISSUE TITLE
[v4] Order discrepancy between `prettier-plugin-tailwindcss` and `intellisense`

### ISSUE THREAD

**Issue by ryanylee** [tailwindlabs/tailwindcss-intellisense#923]
**What version of VS Code are you using?**

v1.87.1

**What version of Tailwind CSS IntelliSense are you using?**

v0.11.51

**What version of Tailwind CSS are you using?**

4.0.0-alpha.9

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Tailwind config**

```js
// Paste the contents of your Tailwind config file here
```

**VS Code settings**

```json
// Paste your VS Code settings in JSON format here
```

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

In a project, if I have the class `mt-3 mr-3` on a div, tailwindcss-intellisense switches the order to `mr-3 mt-3`, but when I run `prettier` with `prettier-plugin-tailwindcss`, it switches the order back to the original `mt-3 mr-3`

**Comment by ryanylee** [comment]
https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/253

**Comment by thecrypticace** [comment]
@ryanylee please provide a reproduction. I suspect this has something to do with Prettier not working for some reason because `mt-3 mr-3` is the correct order in v4.

**Comment by ryanylee** [comment]
Recreated I think here: https://github.com/ryanylee/inconsistent-formatting/tree/main

Apologies, it's probably not intellisense, it's `prettier` and the vscode prettier extension seemingly fighting one another.

**Comment by ryanylee** [comment]
Long story short is that I had the tailwindcss 4 alpha installed in an app in a monorepo for which I was using `pnpm`. Because packages aren't hoisted automatically with `pnpm`, the `prettier-plugin-tailwindcss` wasn't able to detect that I was using version 4 and so defaulted to version 3.
