### ISSUE TITLE
showPixelEquivalents not working with theme()

### ISSUE THREAD

**Issue by shuffgy** [tailwindlabs/tailwindcss-intellisense#927]
**What version of VS Code are you using?**

v1.87.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.10.5

**What version of Tailwind CSS are you using?**

v3.4.1

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Tailwind config**

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const plugin = require('tailwindcss/plugin');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/build/javascript/**/*.js',
    './packages/**/*.{html,tsconfig,typoscript,php}'
  ],
  theme: {
    fontFamily: {
        'barlow': ['Barlow Semi Condensed', 'sans-serif'], // base font
        'iconfont': ['iconfont'] // Iconfont
    },
    extend: {
        colors: {
            'primary': '#2A2A2A',
            'sw-gray': '#6a6a69',
            'sw-green': '#36CD5E',
            'sw-yellow': '#FAF613',
            'sw-orange': '#FF6C31',
            'sw-cyan': '#5DDFD9',
            'sw-pink': '#FA67DC',
            'sw-red': '#EE2E4A',
            'sw-blue': '#EE2E4A'
        }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
    plugin(function ({ addBase }) {
        addBase({
            ':root': { fontSize: "16px" }, // base font size = 1rem
        })
    }),
  ],
}

```

**VS Code settings**

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/17125448/f7a87e8b-7fe2-44da-ae6a-04ed7a4d9f56)
   
**Describe your issue**

tailwindCSS.showPixelEquivalents not working on theme() function in .css Files, but `@appy` works.

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/17125448/bb27ac92-9a83-44b0-8272-a685f537ca8e)

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/17125448/cdddcd2b-0904-4388-999a-70c4016ab8d8)

Same with font-size configs:   
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/17125448/1344f78b-c395-4ce2-8a44-160279669e1a)

Maybe i'm missing something?

**Comment by thecrypticace** [comment]
This has been updated and will be available in the pre-release version in a few.
