### ISSUE TITLE
scss // comments

### ISSUE THREAD

**Issue by S-p-Ace** [tailwindlabs/tailwindcss-intellisense#928]
Type: <b>Feature Request</b>

would be nice if comments at the end of a line would be supported in scss files // like this

Extension version: 0.10.5
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by adamwathan** [comment]
What do you mean by "supported"? Can you give a more specific example of the problem you're having?

**Comment by S-p-Ace** [comment]
In `.scss` files, lines containing a comment declared by double slashes `// ...` at the end will show syntax erros even though it is legal syntax.
as a workaround I have to convert the comments to block style `/* ... */`

When switching the language mode to SCSS the `//` comments will be parsed as comments (but the tailwind directives will not be recognized)

**Comment by S-p-Ace** [comment]
maybe I'm using this extension in the wrong place. in 'sass' language mode everything is fine, so I probably don't need tailwindcss specifiacally.

**Comment by thecrypticace** [comment]
Are you setting the Tailwind CSS language mode explicitly in a Sass/SCSS file?

**Comment by thecrypticace** [comment]
Gonna close this one as the Tailwind CSS language mode is intended for pure CSS and not Sass or SCSS and `// comments` are not valid in CSS.
