### ISSUE TITLE
this extension not working with out modules please solve it problem

### ISSUE THREAD

**Issue by Devazharruk** [tailwindlabs/tailwindcss-intellisense#939]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by thecrypticace** [comment]
Hi! Closing this as there's no information for me to go on. Please open a new issue and follow the issue template by providing your:

- Version of VS Code
- Version of Tailwind CSS IntelliSense
- Version of Tailwind CSS
- Package manager (and version)
- Operating system and version
- A clonable reproduction repository (preferably, on Github) if you can provide one
