### ISSUE TITLE
Extension completely loses functionality.

### ISSUE THREAD

**Issue by omariyassinee** [tailwindlabs/tailwindcss-intellisense#941]
- What version of VS Code are you using?

1.87.2

- What version of Tailwind CSS IntelliSense are you using?

v0.10.5

- What version of Tailwind CSS are you using?

3.4.3

- What package manager are you using?

npm

- What operating system are you using?

Windows

- Tailwind config

```js
/** @type {import('tailwindcss').Config} */
export default {
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	theme: {
		extend: {},
	},
	plugins: [],
};
```

- VS Code settings

```json
{
	"[javascript]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"editor.formatOnSave": true,
	"prettier.useTabs": true,
	"editor.tabSize": 3,
	"prettier.jsxSingleQuote": true,
	"prettier.singleQuote": true,
	"explorer.confirmDelete": false,
	"window.menuBarVisibility": "compact",
	"editor.fontFamily": "Consolas",
	"explorer.confirmDragAndDrop": false,
	"workbench.iconTheme": "material-icon-theme",
	"files.autoSave": "onFocusChange",
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"workbench.colorTheme": "Palenight Italic",
	"security.workspace.trust.untrustedFiles": "open",
	"editor.codeActionsOnSave": {},
	"prettier.printWidth": 70,
	"editor.tabFocusMode": false,
	"workbench.settings.applyToAllProfiles": ["editor.tabFocusMode"],
	"editor.colorDecorators": false,
	"window.zoomLevel": -0.5,
	"editor.fontSize": 17,
	"editor.cursorBlinking": "smooth",
	"editor.smoothScrolling": true,
	"editor.cursorSmoothCaretAnimation": "on",
	"terminal.integrated.smoothScrolling": true,
	"editor.linkedEditing": true,
	"javascript.updateImportsOnFileMove.enabled": "prompt",


	// ----------------------------------------- //
	"editor.hover.enabled": true,
	"tailwindCSS.hovers": true,
	"tailwindCSS.suggestions": true,
	"tailwindCSS.emmetCompletions": true,
	"tailwindCSS.includeLanguages": {
		"html": "html",
		"javascript": "javascript",
		"css": "css",
	},
	"editor.quickSuggestions": {
		"strings": true
	},
	"css.validate": false,
	"editor.inlineSuggest.enabled": true,
	"security.workspace.trust.enabled": false
}
```

- Reproduction URL
Idk what's this?

- Describe your issue

The extension loses functionality for the project directory after I close VS Code current window or project that I'm working on. Re-creating tailwind.config.js file temporarily (until I close it and reopen it again) restores the extension functionality, or I just delete the config file (tailwind.config.js) and then I press CTRL + Z which brings it back, and then everything works fine.

### Actual behavior: Suggestions disappear after reopening projects. Re-creating tailwind.config.js brings suggestions back (temporary fix).

Steps to reproduce:

- Open a project with a valid tailwind.config.js file.
- Verify Tailwind CSS IntelliSense suggestions are working.
- Close the project or VS Code window.
- Reopen the project.
- Observe that Tailwind CSS IntelliSense suggestions are no longer present.

Additional information:

Tried various troubleshooting steps including clearing VS Code cache, restarting VS Code, disabling workspace settings, reinstalling the extension, and all online solutions.
File watching settings seem to be configured correctly.

Thanks :>

**Comment by thecrypticace** [comment]
I can't figure out how to re-create this situation. The only way I can get intellisense to not show anything is to open the file outside of a workspace/project (open a file but not the folder it is in) — which is working as designed.

Any chance you could provide a video or screenshots of what you're seeing?

**Comment by thecrypticace** [comment]
I'm going to close this one — if you are able to reproduce this and provide the information above I'll take another look. Thanks!
