### ISSUE TITLE
cssConflict warning when using flex and hidden classes

### ISSUE THREAD

**Issue by oscarmrom** [tailwindlabs/tailwindcss-intellisense#959]
**What version of VS Code are you using?**
v1.88.1

**What version of Tailwind CSS IntelliSense are you using?**
v0.10.5

**What version of Tailwind CSS are you using?**
v3.4.1

**What package manager are you using?**
Rails app that uses the `tailwindcss-rails`

**What operating system are you using?**
macOS

**Describe your issue**
Similar to #136 I get a warning for hidden and flex applying the same properties
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/26697231/e6df2c74-6ad7-48f6-90bd-04134431f1ec)

`'flex' applies the same CSS properties as 'hidden'.(cssConflict)`
```
<p class="flex italic rounded-sm py-1 text-teal-700 text-xs hidden ml-2 items-center"
```

**Comment by adamwathan** [comment]
Hey! This warning is correct, you are setting `display: flex` and `display: none` at the same time by setting both of those classes. Something can't be both `flex` and `hidden` at the same time, you should conditionally apply the class you need 👍

**Comment by oscarmrom** [comment]
Thanks for the kind clarification!

**Comment by nemixbg** [comment]
I have similar issue 

![Screenshot_45](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/41578537/65fdcbec-3018-45ec-93a1-155fa0c44ce5)

`class="@error('content')
                    border-red-500 dark:border-red-500
               @enderror block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"`

The same issue when I put in different way:

![Screenshot_46](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/41578537/077d0fe2-2d23-494f-b21b-aa7dfc0ceefb)

`class="border  text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700  dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500
                    @error('title')
                    border-red-500 dark:border-red-500
                    @else
                    border-gray-300 dark:border-gray-600
                    @enderror"`

**Comment by kristian-nst** [comment]
Same with text-xxx and placeholder:text-xxx :/
