### ISSUE TITLE
Color decorators are not working for custom colors with css variables

### ISSUE THREAD

**Issue by dmagunov** [tailwindlabs/tailwindcss-intellisense#967]
**What version of VS Code are you using?**

 v1.89.1

**What version of Tailwind CSS IntelliSense are you using?**

v0.11.66

**What version of Tailwind CSS are you using?**

v3.4.3

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Tailwind config**

```js
...

theme: {
  extend: {
      colors: {
        foreground: "rgb(var(--color-foreground) / <alpha-value>)",
      }
   }
}
```

**VS Code settings**

```json
"tailwindCSS.classAttributes": [
	"class",
	"className",
	"ngClass",
	"class:list"
],
"tailwindCSS.codeActions": true,
"tailwindCSS.colorDecorators": true,
"tailwindCSS.experimental.classRegex": [],
"tailwindCSS.experimental.configFile": null,
"tailwindCSS.hovers": true,
"tailwindCSS.includeLanguages": {},
"tailwindCSS.inspectPort": null,
"tailwindCSS.rootFontSize": 16,
"tailwindCSS.showPixelEquivalents": true,
"tailwindCSS.suggestions": true,
"tailwindCSS.validate": true

```

**Describe your issue**

Color decorators (prevew) don't appear in VSCode when using custom colors with CSS variables (as described in the [Tailwindcss docs](https://tailwindcss.com/docs/customizing-colors#using-css-variables)).

<img width="1971" alt="Screenshot 2024-05-14 at 21 58 13" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/3579475/b18645ab-a91e-4ef3-824a-6ff1234461ca">

**Comment by thecrypticace** [comment]
This is intentional as there's no way for us to know what the color decorator should show given that the utility is different at runtime and potentially different based on the element being styled. We will, however, show a fallback color if one is provided in the `var(…)` for example:

```js
export default {
  content: [],
  theme: {
    extend: {
      colors: {
        // This will show a color decorator
        foreground: "rgb(var(--color-foreground, 102 51 153) / <alpha-value>)",
      },
    },
  },
  plugins: [],
};
```

<img width="498" alt="Screenshot 2024-05-17 at 15 40 06" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/614993/8198edf7-3b42-4c5a-817a-7591dfbdcb58">

**Comment by mehdi-mashayekhi** [comment]
when i change variable --color-foreground need change 102 51 153 to new value :-1:  i need to new solution!!
