### ISSUE TITLE
The extension reports wrong suggestions

### ISSUE THREAD

**Issue by brunouber** [tailwindlabs/tailwindcss-intellisense#977]
**What version of VS Code are you using?**

v1.89.1

**What version of Tailwind CSS IntelliSense are you using?**

v0.10.5

**What version of Tailwind CSS are you using?**

v3.4.3

**What package manager are you using?**

npm

**What operating system are you using?**

macOS, Sonoma 14.4.1

**Tailwind config**

```js
{
    "content": ["..."],
    "plugins": [],
    "theme": {
        "extend": {},
        "fontSize": {
            "base": "13px"
        }
    }
}
```

**VS Code settings**

```json
{
  "workbench.colorTheme": "Default Dark Modern",
  "editor.fontSize": 16,
  "editor.renderWhitespace": "all",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "git.mergeEditor": false,
  "terminal.integrated.fontSize": 14,
  "terminal.integrated.defaultProfile.osx": "zsh",
  "security.workspace.trust.untrustedFiles": "open",
  "typescript.updateImportsOnFileMove.enabled": "never",
  "javascript.updateImportsOnFileMove.enabled": "never",
  "diffEditor.hideUnchangedRegions.enabled": true,
  "files.associations": {
    "*.ejs": "plaintext"
  },
  "github.copilot.editor.enableAutoCompletions": true
}

```

**Describe your issue**

I'm trying to adopt tailwindcss in an existing project.

In this website the font-size defined on body is 13px - I can't change this at the moment.

When I use `text-base`, on hover, the extension correctly reports the corresponding value.

<img width="315" alt="immagine" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/55399398/665bcc4f-606c-4533-a122-63bde61d17d0">

But when I use other tailwindcss's utilities, such as `p-4` the extension reports the wrong value.
When I visit the page later, `p-4` is equal to `13px` as it should be.

<img width="204" alt="immagine" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/55399398/363ffbcd-06f0-41ee-a7a2-c4710758a440">

**Comment by RobinMalfait** [comment]
Hey!

This is because you set your base font size to `13px` and the extension uses `16px` by default.
You can configure this in your extension settings: https://github.com/tailwindlabs/tailwindcss-intellisense?tab=readme-ov-file#tailwindcssrootfontsize

Hope this helps!

**Comment by brunouber** [comment]
Hey @RobinMalfait ,
Thanks a lot, this solved my issue.
