### ISSUE TITLE
Releases and Changelog Not Updated

### ISSUE THREAD

**Issue by Archetipo95** [tailwindlabs/tailwindcss-intellisense#992]
I have noticed that the latest releases and the changelog for this repository are not being updated regularly. This makes it difficult for users to track changes, understand new features, and identify bug fixes or improvements. Keeping the releases and changelog updated is crucial for maintaining transparency and helping users to stay informed about the project's progress.

Expected Behavior:
The GitHub releases page should reflect the latest stable and pre-release versions of the software.
The changelog should be updated with each new release, detailing the changes, improvements, and bug fixes.

Current Behavior:
The releases page does not show the most recent versions.
The changelog is outdated and does not include information on the latest updates.

Thank you for your attention to this matter. Your efforts in maintaining this repository are greatly appreciated, and these updates will significantly enhance user experience and project transparency.

**Comment by thecrypticace** [comment]
The changelog is located here — and is definitely up to date: https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/vscode-tailwindcss/CHANGELOG.md

I'll fixup the releases today

**Comment by thecrypticace** [comment]
Releases have been updated.
