### ISSUE TITLE
Unable to find config file on network drive (v0.12 regression)

### ISSUE THREAD

**Issue by Kcko** [tailwindlabs/tailwindcss-intellisense#994]
**What version of VS Code are you using?**
1.90.2

**What version of Tailwind CSS IntelliSense are you using?**
latest -> 0.12.1

**What version of Tailwind CSS are you using?**
2.x

**What package manager are you using?**
npm

**What operating system are you using?**
Windows

**Describe your issue**
With the last installed version I get a message that my tailwind.config.js is not found. He physically exists, but the path given is wrong. I am connected to a network drive and the path is just wrong. In the previous version (not 0.12) everything worked correctly.

Is it possible to fix this or set the watcher to the file manually?

![](https://is.gd/SFg5Pr)

This is correct url
![](https://is.gd/Pv52Uc)

Thx for help.

**Comment by Kcko** [comment]
Im back on 0.10 and everything works fine ...

![](https://remotefiles.rjwebdesign.cz/i/20240626-152006.png)

**Comment by thecrypticace** [comment]
This is an interesting bug. I'm assuming it's caused by our use of `URI#fsPath` to get the path to projects in multi-root workspaces. Makes me think it might be a vscode bug but maybe it's one we can work around.

I'll have to try settings up a network share locally to see if I can reproduce.

**Comment by thecrypticace** [comment]
I can reproduce this locally! Working on figuring out a fix

**Comment by Kcko** [comment]
it's great to hear that someone solved it quickly and moreover that they solved it, great!

**Comment by thecrypticace** [comment]
Hey I've merged a fix that _should_ take care of this problem. (it seemed to in my testing) Could you test the pre-release version of the extension and report back? You can switch to the pre-release version in the extension details in VSCode:

<img width="868" alt="Screenshot 2024-06-26 at 16 52 43" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/614993/755ec11e-8067-4344-9230-a2d720b39b4d">

**Comment by thecrypticace** [comment]
The pre-release version is v0.13.1 — if after updating it says v0.13.0 you may need to wait a few minutes and then restart VSCode.

**Comment by Kcko** [comment]
Hi, I can confirm that the problem disappeared in the pre-release version, good job!
