### ISSUE TITLE
Isn't working not 

### ISSUE THREAD

**Issue by SHUBHAMRAJPUT9665** [tailwindlabs/tailwindcss-intellisense#995]
Type: <b>Bug</b>

not workiiiing proper;y not showing the suggestion while typing tailw
ind classes

Extension version: 0.12.1
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.53GB free)|
|Process Argv|--crash-reporter-id 7b04485c-8c79-4026-876e-a8154050a36e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31082724

```

</details>

**Comment by thecrypticace** [comment]
Hey. This unfortunately doesn't have any info for me to go on so I'm going to close this. However,  if you can provide details about your project structure, where it's located on your machine (file paths), and the logged output from intellisense I'll re-open this and take a look.

To get the logs from intellisense:
- Open the command palette
- Search for and click "Tailwind CSS: Show Output"
- Copy and paste the content into a GH issue

**Comment by SHUBHAMRAJPUT9665** [comment]
pm] Tailwind CSS IntelliSense client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:21:49 pm] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097  showing this

**Comment by thecrypticace** [comment]
v0.12.2 fixes this — please update 👍
