### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by BilalHamza7** [tailwindlabs/tailwindcss-intellisense#997]
- Issue Type: `Bug`
- Extension Name: `vscode-tailwindcss`
- Extension Version: `0.12.1`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 45,
		"activateCallTime": 0,
		"activateResolvedTime": 62,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "bradlc.vscode-tailwindcss",
				"_lower": "bradlc.vscode-tailwindcss"
			},
			"activationEvent": "onStartupFinished"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Pending response rejected since connection got disposed"
		},
		{
			"name": "Error",
			"message": "Client is not running and can't be stopped. It's current state is: starting"
		},
		{
			"name": "Error",
			"message": "Client is not running and can't be stopped. It's current state is: starting"
		},
		{
			"name": "Error",
			"message": "Pending response rejected since connection got disposed"
		},
		{
			"name": "Error",
			"message": "Client is not running and can't be stopped. It's current state is: starting"
		},
		{
			"name": "Error",
			"message": "Client is not running and can't be stopped. It's current state is: starting"
		}
	],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by adamwathan** [comment]
Hey! Sorry we can’t do anything with this — when you open an issue please make the effort to actually describe your issue in written words and explain the problem and expected behavior. We aren’t able to try and reverse engineer what problem you are trying to report from copy and pasted log data like this.

**Comment by thecrypticace** [comment]
I've merged the fix for this and will push out a release today. We were using an API that does not work in older versions of VSCode — v1.71 is from August 2022. I'd suggest updating VSCode though if possible 👍

**Comment by BilalHamza7** [comment]
> Hey! Sorry we can’t do anything with this — when you open an issue please make the effort to actually describe your issue in written words and explain the problem and expected behavior. We aren’t able to try and reverse engineer what problem you are trying to report from copy and pasted log data like this.

Hey Adam, I am very sorry that I didn't provide you with any info on the issue. I was redirected here from vs code, and this section was new to me so I just did what it said me to do. I'll make sure this doesn't happen again. Thank you!

**Comment by BilalHamza7** [comment]
> I've merged the fix for this and will push out a release today. We were using an API that does not work in older versions of VSCode — v1.71 is from August 2022. I'd suggest updating VSCode though if possible 👍

That's very helpful, and I'll look into it. Thank You!
